import type { Lesson } from "./lesson";

function reading(id:string,title:string,body:string,practice:string[]):Lesson{return{id:`architect-data-${id}`,title,activities:[{id:`architect-data-${id}-001`,title,estimatedMinutes:55,content:{type:"reading",body}},{id:`architect-data-${id}-002`,title:`Evaluate: ${title}`,estimatedMinutes:55,content:{type:"practical",objective:`Evaluate ${title} in Steward.`,scenario:"Use Steward's current PostgreSQL schema, domain model, APIs, tests, operational evidence and recovery constraints. Treat the existing database as evidence, not as unquestionable architecture.",instructions:practice,deliverables:["Current-state evidence","Trade-off analysis","Recommendation and consequences"],completionCriteria:["Data ownership and invariants are explicit.","Consistency assumptions are stated.","Operational and migration consequences are considered."]}}]};}

export const dataArchitectureDeepLessons:Lesson[]=[
reading("ownership","Data Ownership","Data ownership answers who is authoritative for a piece of information and who may change it. Shared storage without ownership produces hidden coupling and ambiguous invariants.",["Map major Steward data sets to owning domain capability.","Identify direct cross-boundary reads/writes.","Mark authoritative vs derived data.","Recommend ownership rules for ambiguous areas."]),
reading("schema-boundaries","Schema Boundaries","A physical database can host multiple logical ownership boundaries. Schema/table separation helps only when application access and change rules reinforce it.",["Map tables to domain/module boundaries.","Find tables used by multiple modules.","Identify joins or writes that bypass ownership.","Propose the smallest useful boundary improvement."]),
reading("transactional-consistency","Transactional Consistency","Use strong transactions where invariants require atomic change. Relaxing consistency can improve autonomy or availability, but it creates reconciliation, ordering and failure-handling obligations.",["Select a critical Steward workflow.","State its invariants and atomicity needs.","Identify what can safely be eventually consistent.","Document failure/recovery consequences."]),
reading("duplication-derived-views","Data Duplication and Derived Views","Duplication is sometimes a deliberate architecture choice for autonomy, performance or reporting. Every duplicate introduces freshness, synchronization and recovery questions.",["Identify repeated or projected data in Steward.","Classify source-of-truth and copies.","Define acceptable staleness.","Specify rebuild/reconciliation behavior."]),
reading("caching","Caching","A cache trades freshness and complexity for latency or load reduction. It is useful only when the workload and invalidation model justify it.",["Choose one Steward read path that could be cached.","Measure or state the performance driver.","Define key, TTL/invalidation and stale-data behavior.","Decide whether caching is currently justified."]),
reading("read-models","Read Models","A read model is a representation optimized for a query or audience. It can simplify complex reads without requiring that the write model adopt the same shape.",["Identify one complex Steward query/report.","Compare direct relational query vs derived read model.","Define freshness and rebuild requirements.","Evaluate whether complexity is worth the benefit."]),
reading("database-per-service","Database-per-service Trade-offs","Separate databases can strengthen ownership and deployment independence, but they remove cheap joins/transactions and add synchronization, observability, backup and recovery complexity.",["Choose a plausible future Steward service candidate.","Compare shared PostgreSQL ownership boundaries with independent database ownership.","Trace transaction/query changes.","Reject or justify separation from explicit drivers."]),
reading("migration-evolution","Data Migration and Evolution","Schema evolution must preserve service continuity, compatibility and recoverability. Safe change often requires additive-first migrations, backfills, validation and staged removal.",["Select a realistic Steward schema change.","Design expand-migrate-contract steps.","Define rollback/recovery boundaries.","Specify evidence needed before removing old structure."]),
reading("audit-history","Audit and Historical Data","Operational state answers what is true now; audit/history answers what happened and when. History must be designed around business, security and compliance needs rather than indiscriminate logging.",["Identify Steward facts whose history matters.","Define actor/time/change context required.","Separate audit evidence from mutable operational rows.","State retention, integrity and privacy implications."]),
{id:"architect-data-steward-lab",title:"Lab: Evaluate Steward Data Architecture",activities:[{id:"architect-data-steward-lab-001",title:"Establish the Data Architecture Baseline",estimatedMinutes:120,content:{type:"practical",objective:"Create an evidence-backed map of Steward data ownership, consistency and access boundaries.",scenario:"Review PostgreSQL schema, migrations, domain model, APIs, tests and recovery evidence together.",instructions:["Map domains/modules to tables and authoritative data.","Trace representative read/write flows.","Identify cross-boundary access and shared ownership.","Classify consistency requirements and critical invariants.","Record audit/history and recovery obligations."],deliverables:["Data ownership map","Schema/access map","Consistency matrix","Data risks and assumptions"],completionCriteria:["Ownership is explicit.","Cross-boundary access is evidenced.","Critical invariants are connected to transaction boundaries."]}},{id:"architect-data-steward-lab-002",title:"Challenge Data Architecture Options",estimatedMinutes:135,content:{type:"practical",objective:"Compare credible data-architecture evolutions without defaulting to more databases or caches.",scenario:"Use actual architecture drivers and earlier Reliability evidence.",instructions:["Select highest-priority data pressure.","Compare retaining current design, strengthening logical ownership, adding a derived/read model, caching, or physical separation where credible.","Evaluate consistency, query complexity, migration, observability, backup and recovery costs.","State what evidence would justify greater distribution."],deliverables:["Option matrix","Recommended decision","Rejected alternatives","Reconsideration triggers"],completionCriteria:["At least one simple option is evaluated seriously.","Distribution costs are explicit.","Recommendation follows evidence rather than pattern preference."]}},{id:"architect-data-steward-lab-003",title:"Record and Validate the Decision",estimatedMinutes:105,content:{type:"practical",objective:"Turn the selected data decision into an evolvable, testable architecture rule.",scenario:"Architecture must survive future schema and feature changes.",instructions:["Write/update ADR.","Define ownership/access rules.","Specify migration and rollback approach if change is needed.","Define tests or fitness checks for a critical invariant/boundary.","Update the Steward architecture baseline."],deliverables:["Data ADR","Migration/recovery plan","Validation or fitness-check evidence","Updated architecture baseline"],completionCriteria:["Decision has enforceable consequences.","Recovery is considered.","No speculative database split is introduced."]}}]}
];
