import type { Lesson } from "./lesson";

function lesson(id:string,title:string,body:string,practice:string[]):Lesson{return{id:`architect-integration-${id}`,title,activities:[{id:`architect-integration-${id}-001`,title,estimatedMinutes:55,content:{type:"reading",body}},{id:`architect-integration-${id}-002`,title:`Evaluate: ${title}`,estimatedMinutes:60,content:{type:"practical",objective:`Evaluate ${title} in the Steward ecosystem.`,scenario:"Use Steward's current module boundaries, APIs, PostgreSQL ownership, package ecosystem, delivery model and reliability evidence. Integration choices must be justified by explicit drivers rather than by a desire to introduce messaging technology.",instructions:practice,deliverables:["Current integration evidence","Trade-off analysis","Recommendation with failure consequences"],completionCriteria:["Interaction semantics are explicit.","Failure and recovery behavior is considered.","The simplest adequate integration style remains a valid outcome."]}}]};}

export const integrationAndMessagingDeepLessons:Lesson[]=[
lesson("styles","Integration Styles","Integration architecture coordinates independently meaningful parts of a system. In-process calls, HTTP APIs, file exchange, queues, publish-subscribe and events each create different temporal, availability, ownership and operational coupling.",["Map Steward integration points by style.","Classify temporal and availability coupling.","Identify which interactions cross true ownership boundaries.","State whether each current style matches its driver."]),
lesson("sync-apis","Synchronous APIs","Synchronous APIs are appropriate when a caller needs an immediate response and both sides can tolerate shared availability and latency. They are simple to reason about, but long call chains amplify failure and coordination costs.",["Trace one Steward synchronous workflow end to end.","Record timeout, error and retry expectations.","Identify availability coupling.","Decide whether synchronous interaction remains appropriate."]),
lesson("async","Asynchronous Messaging","Asynchronous messaging decouples execution time and can absorb bursts or temporary dependency failure, but it introduces queues, delayed outcomes, duplicates, ordering issues, observability needs and operational ownership.",["Choose a workflow that might benefit from asynchronous processing.","State the actual driver.","Model delayed success and failure.","Compare messaging with keeping the workflow synchronous."]),
lesson("queues-pubsub","Queues and Publish-Subscribe","Queues usually distribute work among consumers; publish-subscribe distributes notifications to interested consumers. The distinction matters because ownership, replay, fan-out and failure semantics differ.",["Model one work-queue candidate.","Model one event-notification candidate.","Identify consumer ownership and replay expectations.","Reject either pattern if no concrete need exists."]),
lesson("events-commands","Events and Commands","A command asks a specific owner to perform an action; an event states that something meaningful already happened. Confusing them creates hidden control flow and ambiguous ownership.",["Classify representative Steward messages as command, event or query.","Identify the authoritative owner for each action.","Rewrite ambiguous message semantics.","Document downstream assumptions."]),
lesson("delivery-semantics","Delivery Semantics","At-most-once, at-least-once and effectively-once processing describe different guarantees and costs. Distributed systems rarely provide magical exactly-once business outcomes; correctness usually depends on idempotent handling and durable state transitions.",["Choose a hypothetical Steward message flow.","State acceptable duplicate/loss behavior.","Define acknowledgement and redelivery rules.","Explain how business correctness is preserved."]),
lesson("idempotency","Idempotency","An idempotent operation can be repeated without creating a different business outcome after the first successful application. It is central to safe retries across APIs and messaging boundaries.",["Identify retryable Steward operations.","Define an idempotency key or natural business identity where appropriate.","Model duplicate delivery.","Specify persistence and expiry implications."]),
lesson("schema-contract","Schema and Contract Evolution","Integration contracts are shared architecture. Safe evolution usually favors additive changes, explicit compatibility, consumer visibility and staged removal rather than synchronized breaking releases.",["Select a Steward API or message contract.","Design a backward-compatible change.","Identify consumers and migration order.","Define evidence required before removing legacy fields/behavior."]),
lesson("failure-backpressure","Integration Failure and Backpressure","When producers can outpace consumers or dependencies fail, unbounded work becomes a reliability incident. Backpressure, bounded queues, admission control, retry policy and degradation must be designed together.",["Model a slow or unavailable Steward dependency.","Trace queued/in-flight work growth.","Define retry and backpressure behavior.","Specify alerts and recovery verification."]),
lesson("no-broker","When Not to Add a Message Broker","A broker is infrastructure with storage, networking, security, observability, backup, upgrades and failure modes. Do not add one to make architecture appear advanced; add it only when temporal decoupling, buffering, fan-out or another driver outweighs those costs.",["List credible Steward messaging drivers.","Compare broker vs in-process/synchronous alternatives.","Include operational and incident costs.","Record a no-broker decision when evidence is insufficient."]),
{id:"architect-integration-steward-lab",title:"Lab: Evaluate Steward Integration Boundaries",activities:[{id:"architect-integration-steward-lab-001",title:"Establish the Integration Baseline",estimatedMinutes:120,content:{type:"practical",objective:"Map Steward interactions, contracts and failure coupling from evidence.",scenario:"Use current architecture views, module/package boundaries, APIs, PostgreSQL access, Nexus interactions and reliability artifacts.",instructions:["Map in-process, HTTP, database and platform interactions.","Identify owner, caller/consumer, contract and consistency expectation for each.","Trace timeout, retry and failure behavior.","Rank integrations whose coupling or failure behavior creates architectural pressure."],deliverables:["Integration map","Contract/ownership matrix","Failure-coupling analysis","Priority integration risks"],completionCriteria:["Interactions reflect actual system evidence.","Ownership and semantics are explicit.","Failure chains are identified."]}},{id:"architect-integration-steward-lab-002",title:"Challenge Sync and Async Options",estimatedMinutes:135,content:{type:"practical",objective:"Compare credible integration options for one high-priority Steward interaction.",scenario:"Do not assume a broker is the target. Compare the existing design with the smallest viable alternatives.",instructions:["State the architecture driver.","Compare current interaction, improved synchronous design and asynchronous messaging only where credible.","Evaluate latency, consistency, retries, idempotency, ordering, observability, security and operations.","Model duplicate delivery and dependency failure for async options.","Choose the best-supported option."],deliverables:["Option matrix","Failure scenarios","Recommended integration decision","Rejected alternatives"],completionCriteria:["At least one simple option is evaluated seriously.","Messaging costs are explicit.","Recommendation follows evidence."]}},{id:"architect-integration-steward-lab-003",title:"Record and Govern the Integration Decision",estimatedMinutes:105,content:{type:"practical",objective:"Turn the selected integration decision into explicit contracts and architecture rules.",scenario:"Integration boundaries must remain evolvable under future change and failure.",instructions:["Write/update an ADR.","Define contract ownership and compatibility policy.","Specify timeout/retry/idempotency/backpressure rules where applicable.","Define tests or fitness checks for a critical contract or dependency rule.","Update the Steward architecture baseline and reconsideration triggers."],deliverables:["Integration ADR","Contract evolution policy","Reliability rules","Updated architecture baseline"],completionCriteria:["Decision has enforceable consequences.","Failure handling is designed, not implied.","No unnecessary broker is introduced."]}}]}
];
