import type { Lesson } from "./lesson";

function reading(id:string,title:string,body:string,practice:string[]):Lesson{return{id:`architect-resilience-${id}`,title,activities:[{id:`architect-resilience-${id}-001`,title,estimatedMinutes:55,content:{type:"reading",body}},{id:`architect-resilience-${id}-002`,title:`Evaluate: ${title}`,estimatedMinutes:55,content:{type:"practical",objective:`Evaluate ${title} in Steward.`,scenario:"Use Steward's current architecture, dependency graph, SLOs, incident evidence, reliability experiments, restore drills and integration behavior. Prefer demonstrated failure modes over imagined ones.",instructions:practice,deliverables:["Failure-path evidence","Trade-off analysis","Architecture recommendation"],completionCriteria:["Failure mode and user impact are explicit.","Mitigation cost and secondary failure modes are considered.","Recovery behavior is testable."]}}]};}

export const resilienceArchitectureDeepLessons:Lesson[]=[
reading("designing-for-failure","Designing for Failure","Resilient architecture assumes components, networks and dependencies will fail and structures the system so those failures remain bounded, observable and recoverable.",["Select a critical Steward user journey.","Map dependencies and failure points.","Identify which failures must be isolated, degraded or surfaced.","Compare current behavior with the desired failure contract."]),
reading("timeouts","Timeouts","Every remote or potentially blocking operation needs a bounded wait aligned with the user or caller's end-to-end latency budget. A timeout is an architecture policy, not merely a client setting.",["Trace one dependency call budget end to end.","Identify missing or conflicting timeout layers.","Relate timeout values to SLO evidence.","Define cancellation and timeout error behavior."]),
reading("retries","Retries and Retry Storms","Retries can turn transient failure into success, but unbounded or synchronized retries amplify load and can prolong an outage.",["Identify retried Steward operations.","Classify which are safe to retry.","Define retry budget, exponential backoff and jitter.","Model behavior when many callers retry simultaneously."]),
reading("circuit-breakers","Circuit Breakers","A circuit breaker temporarily stops calls to a failing dependency so the system can fail fast, preserve resources and probe recovery deliberately.",["Choose a dependency with a credible repeated-failure mode.","Define open/half-open/closed triggers.","Specify fallback or user-visible behavior.","State when a breaker would add unnecessary complexity."]),
reading("bulkheads","Bulkheads","Bulkheads reserve or partition capacity so one workload or dependency failure cannot consume every worker, connection or queue slot.",["Find one shared resource in Steward.","Model exhaustion by one workload.","Compare pool/queue/concurrency isolation options.","Define evidence that would justify the added partitioning."]),
reading("graceful-degradation","Graceful Degradation","A degraded service deliberately preserves the most important capabilities while making unavailable or stale behavior explicit rather than pretending full health.",["Rank Steward capabilities by criticality.","Choose a dependency outage scenario.","Define what remains available and what becomes unavailable/stale.","Specify user and operator signals for degraded mode."]),
reading("dependency-isolation","Dependency Isolation","Dependencies should not automatically share one another's latency, resource exhaustion or failure domain. Isolation may be logical, runtime, resource or deployment-based depending on the driver.",["Map critical Steward and Nexus dependencies.","Identify shared failure domains.","Evaluate isolation options and cost.","Avoid creating services solely to claim isolation."]),
reading("redundancy-failure-domains","Redundancy and Failure Domains","Redundancy improves availability only when replicas do not fail for the same reason and the failover path is itself dependable.",["Identify one component that might warrant redundancy.","Map common-mode failure risks.","Define health/failover behavior.","Compare redundancy benefit against operational complexity and data consistency cost."]),
reading("recovery-objectives","Recovery Objectives as Architecture Drivers","RPO and RTO constrain architecture: they influence data placement, backup design, redundancy, deployment topology and dependency recovery priorities.",["Take measured Steward and Nexus RPO/RTO evidence.","Compare it with desired business recovery bounds.","Identify architecture gaps rather than process-only gaps.","Recommend the smallest change that closes a material recovery gap."]),
{id:"architect-resilience-steward-lab",title:"Lab: Evolve a Steward Failure Path",activities:[{id:"architect-resilience-steward-lab-001",title:"Select and Model the Failure Path",estimatedMinutes:120,content:{type:"practical",objective:"Build an evidence-backed failure model for one critical Steward journey.",scenario:"Use a failure already observed or exercised in Reliability work where possible.",instructions:["Define normal steady state and SLO expectation.","Draw the dependency and resource path.","Identify timeout, retry, breaker, saturation and common-mode risks.","State current recovery behavior and evidence gaps."],deliverables:["Failure-path model","Current resilience controls","User-impact analysis","Evidence gaps"],completionCriteria:["The path is grounded in real dependencies.","Cascading-failure mechanisms are explicit.","Existing controls are not assumed effective without evidence."]}},{id:"architect-resilience-steward-lab-002",title:"Compare Resilience Options",estimatedMinutes:135,content:{type:"practical",objective:"Choose the smallest architecture change that materially improves the failure path.",scenario:"Compare retaining the current design with targeted timeout/retry policy, isolation, degradation, breaker, redundancy or topology changes.",instructions:["Evaluate at least three credible options including no structural change.","Quantify latency/resource/failure-domain consequences where evidence permits.","Include security, observability and operational costs.","Relate the choice to SLO and RPO/RTO drivers."],deliverables:["Option matrix","Selected resilience decision","Rejected alternatives","Reconsideration triggers"],completionCriteria:["The recommendation follows a concrete failure driver.","Mechanisms are not stacked without justification.","New failure modes are identified."]}},{id:"architect-resilience-steward-lab-003",title:"Validate and Record the Evolution",estimatedMinutes:120,content:{type:"practical",objective:"Prove the selected resilience decision improves behavior under controlled failure.",scenario:"Use learner-owned or explicitly authorized environments and reuse the Reliability experiment discipline.",instructions:["Implement or precisely specify the chosen architecture change.","Run a bounded failure experiment with abort and recovery conditions.","Verify user-visible behavior, telemetry, integrity and recovery.","Record an ADR and update the Steward architecture baseline."],deliverables:["Experiment evidence","Before/after resilience assessment","Resilience ADR","Updated architecture baseline"],completionCriteria:["Improvement is demonstrated rather than asserted.","Recovery and secondary effects are checked.","The decision remains reversible or has explicit consequences."]}}]}
];
