import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const fundamentals: LearningResource = { title: "Software Architecture in Practice — SEI", url: "https://www.sei.cmu.edu/library/software-architecture-in-practice/" };
const arc42: LearningResource = { title: "arc42 Documentation Template", url: "https://arc42.org/overview" };
const fitness: LearningResource = { title: "Thoughtworks: Evolutionary Architecture", url: "https://www.thoughtworks.com/insights/articles/fitness-function-driven-development" };

type Spec = { id: string; title: string; intro: string; principles: string[]; steward: string[]; practice: string[]; reflection: string };

function make(spec: Spec): Lesson {
  const blocks: LessonBlock[] = [
    { type: "paragraph", text: spec.intro },
    { type: "heading", id: `${spec.id}-principles`, text: "Architecture reasoning", level: 2 },
    { type: "list", items: spec.principles },
    { type: "heading", id: `${spec.id}-steward`, text: "Apply it to Steward", level: 2 },
    ...spec.steward.map((text): LessonBlock => ({ type: "paragraph", text })),
    { type: "callout", tone: "steward", title: "Architecture is a decision discipline", body: "A diagram is not architecture by itself. Architecture becomes meaningful when important structural decisions are tied to drivers, constraints, quality attributes, trade-offs and evidence about the system's behavior." },
    { type: "resources", title: "Continue learning", resources: [fundamentals, arc42, fitness] },
  ];

  return {
    id: `architecture-fundamentals-${spec.id}`,
    title: spec.title,
    activities: [
      { id: `architecture-fundamentals-${spec.id}-001`, title: spec.title, estimatedMinutes: 50, content: { type: "reading", body: spec.intro, blocks } },
      { id: `architecture-fundamentals-${spec.id}-002`, title: `Evaluate: ${spec.title}`, estimatedMinutes: 60, content: { type: "practical", objective: `Apply ${spec.title} to the mature Steward ecosystem.`, scenario: "Use the actual Steward system and evidence accumulated from development, delivery, cloud, QA, security and reliability. Do not redesign the platform to showcase a pattern; reason from present constraints and observed quality-attribute needs.", instructions: spec.practice, deliverables: ["Architecture evidence", "Driver/trade-off analysis", "Decision or explicitly justified non-change"], completionCriteria: ["The problem is stated before the solution.", "The conclusion uses explicit architecture drivers and evidence.", "Keeping the current structure is accepted when it remains the strongest option."] } },
      { id: `architecture-fundamentals-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.reflection, minimumCharacters: 200 } },
    ],
  };
}

const specs: Spec[] = [
  { id: "what-architecture-is", title: "What Software Architecture Is", intro: "Software architecture is the set of structures and significant decisions that shape how a system is organized, how its parts interact and how important qualities are achieved over time. Significance comes from cost of change and system-wide consequences, not from whether a decision sounds technical or impressive.", principles: ["Architecture includes structures, relationships and rationale.", "Significant decisions are expensive or risky to reverse.", "Architecture includes runtime, data, deployment and organizational concerns where they materially shape the system.", "Architecture should explain why the system has its current shape."], steward: ["Steward's architecture is more than the Django application: PostgreSQL, packages such as steward-common and tsa-test-core, Nexus, CI/CD, hosting, security boundaries and observability all participate in important system behavior.", "The Architect school evaluates the system that actually emerged through previous schools instead of inventing a greenfield design."], practice: ["Inventory Steward's major architectural structures: code/module, runtime, data, deployment and dependency/platform.", "For each, identify one decision that would be expensive to reverse.", "Separate architectural decisions from local implementation details.", "Write a concise current architecture definition for Steward."], reflection: "Why is choosing a variable name usually not an architecture decision, while choosing a shared internal package can become one?" },
  { id: "architecture-vs-design", title: "Architecture vs Design", intro: "Architecture and design exist on a continuum. Architecture focuses on decisions whose consequences cross important boundaries, constrain many future choices or affect key quality attributes; detailed design focuses on more local choices inside those constraints.", principles: ["Do not force a rigid architecture/design boundary based on artifact type.", "Use scope, reversibility and consequence to judge significance.", "A local design decision can become architectural as adoption spreads.", "Architects still need enough implementation understanding to evaluate consequences."], steward: ["A serializer implementation is usually local design; choosing whether domain behavior belongs inside one modular monolith or across networked services is clearly architectural.", "The status of steward-common depends on how many components rely on it and what contracts it owns, not simply because it is called a library."], practice: ["Classify ten existing Steward decisions as local design, architectural or context-dependent.", "Justify each using scope, reversibility and quality-attribute impact.", "Find one decision that started local but now has broader architectural consequence.", "Record what evidence would make you reclassify it."], reflection: "Why is architecture better understood as significant design rather than as a completely separate activity from design?" },
  { id: "architecture-drivers", title: "Architecture Drivers", intro: "Architecture drivers are the small set of business goals, quality attributes, constraints and stakeholder concerns that materially shape architecture. Without explicit drivers, architecture selection degrades into technology preference.", principles: ["Drivers include functional scope only where it materially shapes structure.", "Quality attributes need concrete scenarios to be useful.", "Constraints remove or narrow solution options.", "Drivers must be prioritized because they can conflict."], steward: ["Steward now has empirical drivers from prior schools: developer productivity, secure identity, deployability, testability, artifact availability, observability, recovery targets and maintainable package boundaries.", "Not every desirable quality should become a top architecture driver; prioritization prevents the architecture from optimizing for everything at once."], practice: ["Extract candidate Steward drivers from existing project evidence.", "Classify each as business goal, functional concern, quality attribute or constraint.", "Prioritize the top five architectural drivers and explain exclusions.", "Link each top driver to at least one observable consequence or existing artifact."], reflection: "What happens when architects list every desirable system quality as equally important?" },
  { id: "quality-attributes", title: "Quality Attributes and Architecture Characteristics", intro: "Quality attributes describe how well a system behaves under specific conditions: availability, security, modifiability, performance, deployability, testability and similar characteristics. They become architecture inputs when expressed concretely enough to evaluate structural choices.", principles: ["Avoid vague goals such as 'the system must be scalable'.", "Use scenario thinking: stimulus, environment, affected artifact, response and measurable response.", "Architecture characteristics often interact and conflict.", "Evidence from tests and operations should refine previously assumed qualities."], steward: ["Reliability work already generated SLOs, recovery evidence and capacity data that can become concrete architecture-quality scenarios.", "Security and QA evidence should also shape architecture choices rather than remain separate nonfunctional checklists."], practice: ["Write four quality-attribute scenarios for Steward using evidence from different previous schools.", "Make each response measurable or at least observable.", "Identify one conflict between two desired qualities.", "Explain which current architectural choice supports or harms each scenario."], reflection: "Why is 'Steward should be maintainable' weaker than a scenario about safely changing a module or package within a defined scope and verification effort?" },
  { id: "constraints", title: "Constraints", intro: "Constraints are conditions the architecture must respect unless explicitly renegotiated. They can be technical, organizational, regulatory, economic or temporal. Good architects distinguish true constraints from inherited preferences and challenge assumptions when the cost justifies it.", principles: ["Document the source and strength of each constraint.", "Separate hard constraints from preferences and current-state inertia.", "Constraints can change, so record assumptions and review triggers.", "Design within constraints before proposing expensive attempts to remove them."], steward: ["Examples may include the learning environment, budget-conscious hosting, current technology stack, available team skills, internal Nexus strategy and security boundaries.", "The existence of Django/PostgreSQL is not automatically a permanent constraint; the burden is to show why changing them would create enough value to justify migration."], practice: ["Build a Steward constraint register.", "Classify each as hard, negotiable or assumed.", "Identify the evidence/source behind it.", "Choose one assumed constraint and analyze the consequences of relaxing it."], reflection: "Why is 'we already use this technology' not always the same as a true architecture constraint?" },
  { id: "tradeoffs", title: "Trade-offs and Consequences", intro: "Architecture has no universally best structure. Decisions improve some outcomes while increasing cost, coupling, operational burden or risk elsewhere. The architect's job is to make those consequences explicit and acceptable in context.", principles: ["Compare credible alternatives, including no change.", "Evaluate both immediate and long-term consequences.", "Account for operational and organizational complexity, not only code elegance.", "Record uncertainty rather than disguising estimates as facts."], steward: ["Splitting Steward into services might improve independent deployment for a proven need, but would also introduce network failure, distributed data concerns, more delivery units and more operational surface.", "Keeping a shared library can reduce duplication while increasing coordinated change and compatibility risk."], practice: ["Choose one real Steward architectural tension.", "Develop at least three options including retaining the current state.", "Compare them against prioritized drivers and operational costs.", "Write the preferred decision plus consequences and uncertainty."], reflection: "Why should 'use microservices because they scale' fail an architecture review without more context?" },
  { id: "fitness-evolution", title: "Architecture Fitness and Evolution", intro: "Architecture must remain fit as requirements, scale, dependencies and team capabilities change. Evolutionary architecture uses explicit fitness criteria and evidence to determine when a structural choice is still serving its drivers or should evolve.", principles: ["Define observable fitness criteria for important architecture characteristics.", "Use automated fitness functions where they genuinely reduce regression risk.", "Not every architecture characteristic is easily automatable.", "Architecture evolution should respond to changing evidence rather than scheduled rewrites."], steward: ["Existing tests, dependency policies, SLOs, security checks, build rules and package constraints can act as architecture fitness evidence.", "A modular-monolith boundary can remain fit for years if change coupling and deployment pressure remain acceptable."], practice: ["Select three Steward architecture characteristics worth protecting.", "Define one automated or repeatable fitness check for each where feasible.", "Identify a trigger that would force reconsideration of a current architectural decision.", "Explain why another characteristic is better evaluated through review rather than automation."], reflection: "How can an automated dependency rule function as an architecture fitness function?" },
  { id: "documentation", title: "Architecture Documentation", intro: "Architecture documentation should help stakeholders understand structures, drivers, decisions and consequences without pretending one diagram can represent the entire system. Different views answer different questions, and documentation must evolve with the architecture.", principles: ["Document for specific stakeholder questions.", "Use multiple views: context, container/component, data, deployment or dependency as needed.", "Pair diagrams with rationale and significant decisions.", "Prefer versioned living documentation over polished but stale diagrams."], steward: ["Steward needs views that connect application modules, PostgreSQL, Nexus/internal packages, delivery infrastructure, runtime hosting and external actors.", "ADRs should explain major decisions while diagrams communicate structure and relationships; neither substitutes for the other."], practice: ["Identify the audiences for Steward architecture documentation.", "Create or update a context view and one deeper structural view.", "Link the views to relevant drivers/ADRs.", "Review the documentation against the current deployed system and mark any drift."], reflection: "Why can a technically accurate component diagram still be poor architecture documentation for an operations stakeholder?" },
];

const lab: Lesson = {
  id: "architecture-fundamentals-steward-baseline",
  title: "Lab: Establish the Steward Architecture Baseline",
  activities: [
    { id: "architecture-fundamentals-steward-baseline-001", title: "Reconstruct Current Architecture", estimatedMinutes: 120, content: { type: "practical", objective: "Create an evidence-backed current-state architecture model for the mature Steward ecosystem.", scenario: "Do not redesign yet. Reconstruct the system that exists after Builder, Platform, Delivery, Cloud, Quality, Security and Reliability work.", instructions: ["Map system context, major runtime/deployment units, data stores and internal/external dependencies.", "Include Nexus plus steward-common and tsa-test-core explicitly.", "Identify trust, ownership and operational boundaries.", "Link architecture elements to actual repository/configuration/operational evidence."], deliverables: ["Current-state context view", "Structural/deployment/dependency view", "Evidence index"], completionCriteria: ["Views reflect the current system rather than a target-state aspiration.", "Key dependencies and ownership boundaries are visible.", "Evidence links support the model."] } },
    { id: "architecture-fundamentals-steward-baseline-002", title: "Define Drivers and Quality Scenarios", estimatedMinutes: 120, content: { type: "practical", objective: "Turn accumulated engineering evidence into prioritized architecture drivers.", scenario: "Architecture decisions in later modules will use this driver set as their baseline, so avoid generic qualities without scenarios.", instructions: ["Create a constraint register and classify hard versus negotiable assumptions.", "Prioritize architecture drivers.", "Write measurable/observable quality-attribute scenarios from security, reliability, delivery, QA and development evidence.", "Identify explicit tensions among the scenarios."], deliverables: ["Architecture driver register", "Constraint register", "Quality-attribute scenario set", "Trade-off map"], completionCriteria: ["Drivers are prioritized.", "Quality scenarios are concrete enough to evaluate options.", "Constraints include source and negotiability."] } },
    { id: "architecture-fundamentals-steward-baseline-003", title: "Create the Architecture Baseline Record", estimatedMinutes: 90, content: { type: "practical", objective: "Publish the reference architecture baseline that later Architect modules must challenge rather than ignore.", scenario: "Summarize what is currently justified, what is uncertain and what evidence would trigger architectural change.", instructions: ["Record current significant decisions and rationale in ADR-style summaries.", "Define architecture fitness evidence and review triggers.", "List architectural risks/debt separately from stylistic preferences.", "Add a 'Do Not Change Without Evidence' section for currently successful structural choices."], deliverables: ["Steward Architecture Baseline", "Initial ADR index", "Fitness/review triggers", "Architecture risk register"], completionCriteria: ["The baseline distinguishes current fact, rationale and assumption.", "It does not pre-decide microservices or other future styles.", "Later modules can use it as a stable decision reference."] } },
  ],
};

export const architectureFundamentalsDeepLessons: Lesson[] = [...specs.map(make), lab];
