import type { Activity } from "../activities";
import type { LearningPath } from "./learning-path";
import type { Lesson } from "./lesson";
import { architectureFundamentalsDeepLessons } from "./architect-architecture-fundamentals-deep";
import { architecturalStylesDeepLessons } from "./architect-architectural-styles-deep";
import { dataArchitectureDeepLessons } from "./architect-data-architecture-deep";
import { domainModelingDeepLessons } from "./architect-domain-modeling-deep";
import { modularityDeepLessons } from "./architect-modularity-deep";

function slug(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
function lesson(pathId: string, title: string, focus?: string): Lesson {
    const lessonId = `${pathId}-${slug(title)}`;
    const practical = title.startsWith("Lab:") || title.startsWith("Milestone:");
    const activity: Activity = { id: `${lessonId}-001`, title, estimatedMinutes: title.startsWith("Milestone:") ? 420 : practical ? 75 : 12, content: practical ? {
        type: "practical", objective: focus ?? `Evaluate and evolve ${title.replace(/^(Lab|Milestone): /, "")} in the Steward ecosystem.`,
        scenario: "Treat the complete Steward ecosystem as a system with history: application code, PostgreSQL, internal packages, automation, Nexus, delivery infrastructure, cloud/VPS hosting, security controls and reliability practices. Architecture work must respond to evidence and quality attributes rather than fashion.",
        instructions: ["State the business/engineering problem and architecture drivers before proposing a structural change.", "Model the relevant current-state boundaries, dependencies, data flows and operational constraints.", "Identify at least two credible options, including retaining the current design when appropriate.", "Evaluate trade-offs against explicit architecture characteristics and evidence gathered in earlier schools.", "Record significant decisions and consequences in ADR-style form.", "Implement a change only when the evidence justifies it; otherwise document why the current architecture should remain."],
        deliverables: ["Current-state architecture evidence", "Options and trade-off analysis", "Architecture decision and validation evidence"],
        completionCriteria: ["The recommendation follows from explicit drivers rather than a preferred technology.", "Costs, coupling, failure modes and operational consequences are considered.", "Keeping a modular monolith or shared package is accepted when it remains the best-supported choice."],
    } : { type: "reading", body: focus ?? `This breadth lesson establishes ${title} as an architecture capability for the mature Steward ecosystem. Deep authoring will add researched TSA teaching, architecture cases, resources, exercises and review questions.` } };
    return { id: lessonId, title, activities: [activity] };
}
function path(id: string, title: string, titles: string[]): LearningPath { return { id, title, lessons: titles.map((title) => lesson(id, title)) }; }

export const architectureFundamentals: LearningPath = { id: "architecture-fundamentals", title: "Architecture Fundamentals", lessons: architectureFundamentalsDeepLessons };
export const modularity: LearningPath = { id: "modularity", title: "Modularity", lessons: modularityDeepLessons };
export const architecturalStyles: LearningPath = { id: "architectural-styles", title: "Architectural Styles", lessons: architecturalStylesDeepLessons };
export const domainModeling: LearningPath = { id: "domain-modeling", title: "Domain Modeling", lessons: domainModelingDeepLessons };
export const dataArchitecture: LearningPath = { id: "data-architecture", title: "Data Architecture", lessons: dataArchitectureDeepLessons };
export const integrationAndMessaging = path("integration-and-messaging", "Integration and Messaging", ["Integration Styles", "Synchronous APIs", "Asynchronous Messaging", "Queues and Publish-Subscribe", "Events and Commands", "Delivery Semantics", "Idempotency", "Schema and Contract Evolution", "Integration Failure and Backpressure", "When Not to Add a Message Broker", "Lab: Evaluate Steward Integration Boundaries"]);
export const scalabilityAndDistributedSystems = path("scalability-and-distributed-systems", "Scalability and Distributed Systems", ["Scaling Up and Scaling Out", "Stateless Services", "Load Distribution", "Caching and Contention", "Replication Concepts", "Partitioning Concepts", "Consistency and Availability Trade-offs", "Distributed Coordination", "Distributed Transactions and Sagas Concepts", "Capacity vs Architectural Complexity", "Lab: Model Steward Growth Scenarios"]);
export const resilienceArchitecture = path("resilience-architecture", "Resilience Architecture", ["Designing for Failure", "Timeouts", "Retries and Retry Storms", "Circuit Breakers", "Bulkheads", "Graceful Degradation", "Dependency Isolation", "Redundancy and Failure Domains", "Recovery Objectives as Architecture Drivers", "Lab: Evolve a Steward Failure Path"]);
export const architectureEvaluationAndGovernance: LearningPath = { id: "architecture-evaluation-and-governance", title: "Architecture Evaluation and Governance", lessons: ["Architecture Decision Records", "Architecture Reviews", "Scenario-based Architecture Evaluation", "Fitness Functions", "Evolutionary Architecture", "Standards vs Context", "Technology Selection", "Build vs Buy", "Architecture Debt", "Architecture Governance without Bottlenecks", "Dependency and Package Governance", "Evaluating steward-common as a Shared Library", "Evaluating tsa-test-core as a Shared Engineering Library"].map((title) => lesson("architecture-evaluation-and-governance", title)).concat([lesson("architecture-evaluation-and-governance", "Lab: Conduct a Steward Architecture Review", "Conduct an evidence-based review of the mature Steward ecosystem. Explicitly evaluate the modular-monolith/service question, data and integration boundaries, Nexus/internal dependency architecture, steward-common and tsa-test-core ownership/coupling, cloud and reliability constraints, and whether any proposed architectural evolution is actually justified.")]) };
export const stewardArchitectureEvolution: LearningPath = { id: "steward-architecture-evolution", title: "Architect Milestone", lessons: [lesson("steward-architecture-evolution", "Milestone: Steward Architecture Evolution", "Produce and defend an architecture evolution proposal for Steward based on accumulated evidence from development, delivery, cloud, quality, security and reliability work. Deliver current and target architecture views, architecture drivers, quality-attribute scenarios, significant ADRs, data/integration/dependency analysis, shared-package evaluation, scalability/resilience reasoning and a sequenced evolution plan. Implement at least one justified architectural improvement, but do not introduce microservices, messaging, extra databases or other distributed complexity merely to demonstrate them. A well-defended decision to retain the modular monolith or existing package boundaries is a valid architectural outcome.")] };

export const architectPaths: LearningPath[] = [architectureFundamentals, modularity, architecturalStyles, domainModeling, dataArchitecture, integrationAndMessaging, scalabilityAndDistributedSystems, resilienceArchitecture, architectureEvaluationAndGovernance, stewardArchitectureEvolution];
