import type { LearningResource } from "../activities";
import type { Lesson } from "./lesson";

const OWASP_AUTH = "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html";
const OWASP_PASSWORD = "https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html";
const OWASP_JWT = "https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html";
const DRF_AUTH = "https://www.django-rest-framework.org/api-guide/authentication/";
const DRF_PERMISSIONS = "https://www.django-rest-framework.org/api-guide/permissions/";

const passwordStorageVideo: LearningResource = { title: "Computerphile — How NOT to Store Passwords!", url: "https://www.youtube.com/watch?v=8ZtInClXe1Q", kind: "video", recommended: true, read: "Whole video", purpose: "Visually demonstrates the progression from plaintext to hashing and salting. OWASP remains authoritative for current password-storage choices." };

function richLesson(
    id: string,
    title: string,
    introduction: string,
    outcomes: string[],
    sections: { id: string; title: string; paragraphs: string[]; code?: { language: string; code: string; caption?: string } }[],
    practice: { objective: string; scenario: string; instructions: string[]; deliverables: string[]; completionCriteria: string[] },
    questions: string[],
    resources: LearningResource[],
): Lesson {
    return {
        id,
        title,
        activities: [
            {
                id: `${id}-reading`,
                title,
                estimatedMinutes: 28,
                content: {
                    type: "reading",
                    body: introduction,
                    blocks: [
                        { type: "paragraph", text: introduction },
                        { type: "heading", id: "learning-outcomes", text: "Learning outcomes", level: 2 },
                        { type: "list", items: outcomes },
                        ...sections.flatMap((section) => [
                            { type: "heading" as const, id: section.id, text: section.title, level: 2 as const },
                            ...section.paragraphs.map((text) => ({ type: "paragraph" as const, text })),
                            ...(section.code ? [{ type: "code" as const, language: section.code.language, code: section.code.code, caption: section.code.caption }] : []),
                        ]),
                        {
                            type: "callout",
                            tone: "steward",
                            title: "Steward connection",
                            body: "Security rules in Steward are domain rules as well as technical controls. Team membership, service ownership and role boundaries must be visible in code, tests and API behavior rather than implied by UI screens.",
                        },
                        { type: "resources", title: "Required and supporting reading", resources },
                    ],
                },
            },
            {
                id: `${id}-practice`,
                title: "Engineering Practice",
                estimatedMinutes: 35,
                content: { type: "practical", ...practice },
            },
            {
                id: `${id}-check`,
                title: "Knowledge Check",
                estimatedMinutes: 10,
                content: { type: "reflection", prompt: questions.map((q, i) => `${i + 1}. ${q}`).join("\n") },
            },
        ],
    };
}

export const identityAuthenticationAuthorizationDeepLessons: Lesson[] = [
    richLesson(
        "identity-authentication-authorization-identity-in-software-systems",
        "Identity in Software Systems",
        "In security, an actor or subject is the person, service or other entity attempting to interact with the system. Identity is the set of attributes or claims the system uses to distinguish and refer to that subject—for example a stable internal user or service identifier. Before Steward can decide what a caller may do, it must establish which subject the request represents and which identity claims it is prepared to trust.",
        ["Distinguish identity, account, credential and session.", "Model human and service identities separately.", "Explain why stable identifiers matter more than display names.", "Connect identity records to Steward team membership and ownership."],
        [
            { id: "identity-model", title: "Identity is a security subject", paragraphs: ["A user account is a local record. An identity is the subject the system believes it is interacting with. Credentials are evidence used to establish that belief. A session or token carries the authenticated result forward for some period of time.", "Use stable internal identifiers for authorization decisions. Email addresses, names and team labels can change. Authorization tied directly to mutable display data becomes fragile and difficult to audit."] },
            { id: "steward-subjects", title: "Identity inside Steward", paragraphs: ["Steward needs at least human users and later may need machine/service identities. A User can belong to one or more Teams through Membership records. Permissions should derive from that relationship rather than from a free-form team name copied into a token."], code: { language: "text", code: "User 42\n  └── Membership(team=platform, role=maintainer)\n        └── may modify Service owned by platform\n\nUser 42\n  └── no Membership(team=payments)\n        └── may read, but may not modify payments-owned Service", caption: "Identity becomes useful when connected to explicit domain relationships." } },
            { id: "account-lifecycle", title: "Identity has a lifecycle", paragraphs: ["Creation, activation, suspension/disablement and deletion are different states. Disabling an account should prevent new authentication without necessarily deleting audit history or ownership records. Decide how historical records continue to refer to an identity after that person can no longer sign in.", "Authentication code should check the account state that represents eligibility to authenticate. Authorization should not assume that a database row's mere existence means an active trusted actor."] },
            { id: "human-machine", title: "Human and machine identities have different credential lifecycles", paragraphs: ["A service calling another service should not impersonate a human merely to reuse the same permission path. Machine identities need their own credential issuance, rotation and ownership model. Builder only identifies this boundary; later security/platform work can implement stronger workload identity." ] },
        ],
        { objective: "Extend the existing Steward domain with durable User and Membership identity records before adding tokens or permissions.", scenario: "Steward already persists Team and Service and exposes them through Django/DRF. The missing capability is identity: the API cannot yet represent which human belongs to which Team. Add that state to the system you already built rather than designing identity in isolation.", instructions: ["Inspect the current Team and Service models and draw where User and Membership must connect.", "Choose a stable User identifier and explain why mutable display data such as email or name should not be the authorization key.", "Implement User and Membership in the existing Django project, including an explicit Team relationship and role field or equivalent.", "Create migrations, inspect them and apply them to the existing Steward database.", "Seed two users with memberships in different Teams and query the relationships from the Django shell.", "List which attributes are identity data, credential data and profile data.", "Exercise/record an inactive or disabled-account state and prove that identity history can remain while new authentication is denied.", "Identify one future machine-identity use case and explain why it should not impersonate a human, without implementing workload identity."], deliverables: ["Implemented User/Membership model", "Reviewed migration", "Two-Team identity seed/query evidence", "Identifier rationale"], completionCriteria: ["Identity is added to the existing Steward database rather than a separate demo.", "Authorization does not depend on display names.", "Credentials are not stored as ordinary profile fields.", "Membership is explicit and queryable.", "Existing Team/Service behavior still works after the migration."] },
        ["Why is an email address usually a poor primary authorization identifier?", "What is the difference between an identity and a credential?", "Why should membership be modeled explicitly in Steward?"],
        [{ title: "OWASP Authentication Cheat Sheet", url: OWASP_AUTH }],
    ),
    richLesson(
        "identity-authentication-authorization-authentication-versus-authorization",
        "Authentication versus Authorization",
        "Authentication and authorization are two separate decisions. Authentication verifies acceptable credentials to establish which principal a request represents. Authorization takes that established principal plus the requested action and relevant resource or scope, then decides whether the operation is permitted. A request can therefore authenticate successfully and still be correctly denied.",
        ["Separate authentication from authorization in request processing.", "Explain authentication failure versus permission denial.", "Design allow/deny decisions around resource and action.", "Recognize why authenticated does not mean trusted for every operation."],
        [
            { id: "two-decisions", title: "Two different decisions", paragraphs: ["Authentication verifies evidence and establishes a principal. Authorization evaluates policy using that principal, the requested action, resource state and sometimes context. A valid token can still receive 403 because identity proof does not grant ownership or role.", "In Steward, a user may be authenticated and allowed to read the service registry while still being forbidden to edit a Service owned by another Team."] },
            { id: "request-flow", title: "Make the boundary visible", paragraphs: ["A useful mental flow is: parse request → authenticate → load resource → authorize action → execute domain operation. Avoid hiding all authorization inside serializer validation or relying only on front-end buttons."], code: { language: "text", code: "request\n  ↓\nauthenticate token → principal\n  ↓\nload Service\n  ↓\ncheck team membership + required role\n  ↓\nperform update OR return 403", caption: "Authentication establishes a principal; authorization evaluates the operation." } },
            { id: "deny-default", title: "Deny by default and grant deliberately", paragraphs: ["When no policy explicitly permits an operation, the safe default is denial. This matters when a new endpoint/action is added: it should not become writable merely because nobody remembered to attach a special restriction. Central defaults plus explicit exceptions are easier to review than scattered allow-by-omission behavior."] },
            { id: "401-403", title: "401 and 403 communicate different boundaries", paragraphs: ["401 means the request lacks acceptable authentication credentials for the protected operation and commonly includes a WWW-Authenticate challenge appropriate to the scheme. 403 means the server understood the authenticated/identified request but refuses the action. Exact framework behavior can depend on the configured authentication class, so verify actual responses rather than forcing status codes cosmetically."] },
        ],
        { objective: "Define the authorization contract for the real Steward Service endpoints before implementing permission code.", scenario: "The API now has persisted Users, Memberships, Teams and Services, but those relationships do not yet enforce access. Use the endpoints and ownership data already present to specify exactly what anonymous users, Team members and cross-Team users may do.", instructions: ["Inventory the current Service list, retrieve, create, update and delete operations that actually exist.", "For each operation, define whether authentication is required and which Team membership/role permits it.", "Use the two users seeded in the previous checkpoint to write concrete same-Team and cross-Team examples.", "Add expected 401 versus 403 outcomes and explain the difference, including the authentication challenge behavior you actually observe from DRF.", "Identify one nested Environment or dependency write path that could later bypass Service ownership if permissions are applied only to the top-level endpoint.", "Keep this checkpoint as a decision table; implementation follows after authentication is wired."], deliverables: ["Endpoint authorization decision table", "Same-Team/cross-Team examples", "Potential bypass note"], completionCriteria: ["The table refers to real Steward endpoints and relationships.", "`401` and `403` are not conflated.", "Each write action includes a resource-aware rule.", "Authentication alone never grants all writes.", "At least one alternate mutation path is considered before implementation."] },
        ["Can a valid token still produce a 403? Why?", "What information does authorization need beyond identity?", "Where should resource-aware authorization happen in the request flow?"],
        [{ title: "DRF Authentication", url: DRF_AUTH }, { title: "DRF Permissions", url: DRF_PERMISSIONS }],
    ),
    richLesson(
        "identity-authentication-authorization-password-storage-and-hashing",
        "Password Storage and Hashing",
        "Passwords are verifier secrets, not data the application should be able to recover. The objective is to store enough information to verify a future attempt while making stolen credential databases expensive to crack.",
        ["Explain why passwords must be hashed rather than encrypted.", "Describe salts, work factors and adaptive password hashing.", "Use framework password APIs instead of implementing cryptography.", "Recognize dangerous logging and reset patterns."],
        [
            { id: "one-way", title: "Verification, not recovery", paragraphs: ["Encryption is reversible by design; password verification should not require recovery of the original password. Modern password hash functions include a salt and configurable computational cost so identical passwords do not produce reusable lookup values and attacks remain expensive as hardware improves.", "Django already provides mature password hashing and upgrade behavior. Calling set_password and check_password is safer than inventing a storage format or directly assigning raw password text to a model field."] },
            { id: "verification-record", title: "The database stores a verifier record, not the password", paragraphs: ["Conceptually, password storage keeps an algorithm identifier, cost/work parameters, a per-password random salt and the derived hash output. On login, the framework reads those parameters, derives a candidate hash from the supplied password using the stored salt/settings, and compares the result. The original password does not need to be decrypted because there is no encrypted original to recover.", "A salt primarily prevents identical passwords from sharing the same stored verifier and defeats useful precomputed hash tables across many accounts. The work factor makes each password guess deliberately expensive. The hash function must be designed for password storage; a fast general-purpose hash alone is not sufficient."], code: { language: "text", code: "registration:\nraw password + random salt + work parameters\n              ↓ password KDF\nalgorithm / parameters / salt / derived verifier → store\n\nlogin:\ncandidate password + stored salt/parameters\n              ↓ same KDF\ncandidate verifier ── constant-time comparison ── stored verifier", caption: "Verification reproduces a derived value; it does not recover the original password." } },
            { id: "django-passwords", title: "Use Django's password boundary", paragraphs: ["Never write user.password = raw_password. That stores unusable or dangerous data depending on the code path. Password creation and change should pass through Django's dedicated hashing API."], code: { language: "python", code: "user = User(email=\"engineer@example.com\")\nuser.set_password(raw_password)\nuser.save()\n\nif not user.check_password(candidate):\n    raise AuthenticationFailed(\"Invalid credentials\")", caption: "Delegate password hashing to Django." } },
            { id: "algorithm-upgrades", title: "Password storage must be upgradeable", paragraphs: ["Adaptive password hashing exists partly so cost can increase as hardware improves. Django stores enough algorithm/parameter information with each verifier to recognize older encodings and can upgrade hashes after successful authentication when configured hashers change. A migration strategy matters because credential databases live longer than one recommended cost setting."] },
            { id: "pepper", title: "Salt and pepper are not the same control", paragraphs: ["A salt is unique per password and can be stored alongside the verifier. A pepper, when an architecture uses one, is a separate secret kept outside the password database so stealing only that database is insufficient for offline verification. Pepper management introduces secret-rotation/recovery complexity and is not a reason to invent custom hashing; use supported framework/security architecture when it is required." ] },
            { id: "credential-abuse", title: "Correct hashing does not stop online guessing", paragraphs: ["Password hashing protects primarily against offline cracking after verifier theft. Public login endpoints still need abuse controls such as rate limiting/throttling, monitoring and deliberately non-enumerating failures. Those controls must avoid creating trivial denial-of-service against one victim account. MFA and advanced anti-abuse design belong to later security work." ] },
        ],
        { objective: "Create Steward\'s first safe password credential boundary before token authentication exists.", scenario: "The previous identity checkpoint created durable Users and Memberships, but Steward does not yet have a public authentication lifecycle. Add the minimum credential behavior that the later JWT flow can safely build on.", instructions: ["Confirm the existing User model is compatible with Django\'s password APIs; adapt the model/manager deliberately if required rather than adding a parallel password field.", "Create one controlled account-creation path appropriate to the Builder environment and route every raw password through set_password or the framework-equivalent API.", "Implement or exercise a password-change operation that verifies the required current-user/current-password precondition before replacing the verifier.", "Use check_password/authenticate through framework boundaries rather than comparing stored values.", "Create a user and prove the database stores a password verifier rather than the submitted raw password.", "Exercise correct and incorrect password verification, then document how the chosen Django hasher/cost can be upgraded without decrypting existing passwords.", "Define one bounded online-login abuse control and explain why password hashing alone does not stop online guessing.", "Inspect logs and deliberate error responses to prove raw passwords are absent.", "Record which public registration/login/token/logout endpoints still do not exist; those are introduced by later checkpoints."], deliverables: ["Safe credential creation path", "Password-change behavior", "Stored-verifier evidence", "Correct/incorrect verification evidence", "Credential logging review"], completionCriteria: ["The exercise extends the User created in the preceding identity checkpoint.", "No plaintext or reversible password storage exists.", "Raw passwords do not enter logs.", "Framework hashing APIs are used.", "The learner does not pretend JWT/login/logout endpoints exist yet."] },
        ["Why is encryption the wrong default for stored passwords?", "What purpose does a salt serve?", "Why should application developers prefer framework password APIs?"],
        [{ title: "OWASP Password Storage Cheat Sheet", url: OWASP_PASSWORD }, { title: "Django password management", url: "https://docs.djangoproject.com/en/stable/topics/auth/passwords/" }],
    ),
    richLesson(
        "identity-authentication-authorization-jwt-structure-and-lifecycle",
        "JWT Structure and Lifecycle",
        "A JSON Web Token (JWT) is a compact token format that carries claims. In the common signed form used for API authentication, it contains an encoded header and payload plus a cryptographic signature. The payload is normally readable by whoever possesses the token; the signature lets a verifier detect modification and check that an accepted signer produced it. Decoding only reads the data. Verification is the security decision that determines whether those claims can be trusted under the server's configured policy.",
        ["Describe JWT header, payload and signature.", "Distinguish signed from encrypted data.", "Identify standard lifecycle claims such as exp, iat and sub.", "Explain why token verification must constrain algorithm, issuer and audience as appropriate."],
        [
            { id: "structure", title: "Three encoded parts", paragraphs: ["A compact JWS-style JWT contains base64url-encoded header and payload plus a signature. Anyone who holds the token can usually decode the payload. Never put passwords, secrets or sensitive personal data there simply because the string looks opaque.", "The verifier must validate the signature and relevant claims. Decoding without verification is not authentication."] },
            { id: "claims", title: "Claims should be minimal and purposeful", paragraphs: ["Use stable subject identifiers in sub. exp bounds lifetime. iat helps reason about issuance. iss and aud can reduce token confusion between issuers or services. Avoid copying dynamic authorization state into long-lived tokens unless you understand the staleness trade-off."], code: { language: "json", code: "{\n  \"sub\": \"42\",\n  \"iss\": \"steward-api\",\n  \"aud\": \"steward-web\",\n  \"iat\": 1788958800,\n  \"exp\": 1788959700\n}", caption: "A small illustrative claim set; authorization still consults current Steward state." } },
            { id: "verification-policy", title: "Verification needs an explicit policy, not token-supplied trust", paragraphs: ["The verifier must restrict acceptable algorithms/keys according to server configuration and validate required claims such as expiration plus issuer/audience when the architecture uses them. Do not choose a verification algorithm merely because the token header asks for it. Key selection/rotation must remain controlled by the trusted issuer/verifier configuration.", "Allow only small, justified clock skew when validating time claims. Large leeway quietly extends credential lifetime." ] },
            { id: "jti", title: "Token identity can support revocation and replay evidence", paragraphs: ["The jti claim can uniquely identify a token. Server-side blacklist/revocation systems can persist token identifiers or related state so selected credentials can be rejected before natural expiry. This deliberately gives up some statelessness in exchange for control." ] },
            { id: "jwt-limits", title: "A valid JWT proves only what the verifier actually checked", paragraphs: ["A valid signature does not prove the current user is active, still belongs to a Team, still owns a resource, or should be authorized for an action. It proves integrity/authenticity of the signed claims under the accepted key/policy. Current application state still matters." ] },
        ],
        { objective: "Define the claims Steward actually needs in an access token.", scenario: "The team wants to place user ID, email, every role and every team membership into JWTs.", instructions: ["Separate identity claims from authorization state.", "Keep only claims required on most requests.", "Define expiry expectations.", "Explain which authorization facts should remain database-backed.", "Write an explicit JWT verification policy covering accepted algorithm/key source, required time claims, issuer/audience where applicable and bounded clock skew.", "Decide whether Steward needs jti/token identifiers for the chosen revocation model."], deliverables: ["JWT claim contract", "Staleness analysis"], completionCriteria: ["No secrets are placed in payloads.", "The subject is stable.", "Dynamic membership is not copied blindly into long-lived tokens."] },
        ["Does signing a JWT make its payload secret?", "What is the difference between decoding and verifying?", "Why can embedding team membership in long-lived tokens become dangerous?"],
        [{ title: "OWASP JWT Cheat Sheet", url: OWASP_JWT }, { title: "RFC 7519", url: "https://www.rfc-editor.org/rfc/rfc7519" }],
    ),
    richLesson(
        "identity-authentication-authorization-access-and-refresh-tokens",
        "Access and Refresh Tokens",
        "Access and refresh tokens serve different risk and usability goals. Short-lived access tokens limit exposure; refresh tokens allow a session to continue without repeatedly asking for the user's password.",
        ["Explain the roles of access and refresh tokens.", "Choose different lifetimes based on risk.", "Keep refresh endpoints narrowly scoped.", "Understand why refresh tokens deserve stronger protection than access tokens."],
        [
            { id: "two-token-model", title: "Separate frequent use from session continuation", paragraphs: ["Access tokens travel to ordinary protected endpoints and should usually be short-lived. Refresh tokens are used less frequently to obtain new access tokens and often live longer. Because a stolen refresh token can extend an attacker's access, it deserves careful storage and rotation policy.", "A refresh token should not behave like a general access token. Its audience and endpoint usage should be narrow."] },
            { id: "flow", title: "A basic lifecycle", paragraphs: ["Login verifies credentials once, returns an access/refresh pair, ordinary calls use access, and the refresh endpoint exchanges refresh state for a new access token. Logout semantics depend on whether refresh state is server-tracked or blacklistable."], code: { language: "text", code: "credentials → /token → access + refresh\naccess → /services → protected response\nrefresh → /token/refresh → new access\nexpired access → rejected even if refresh is still valid", caption: "Keep the two token purposes explicit." } },
            { id: "bearer-theft", title: "Bearer credentials are usable by whoever possesses them", paragraphs: ["A bearer access token normally does not prove which process/browser originally received it. If stolen, an attacker can use it until expiry or revocation controls stop it. TLS protects tokens in transit; storage, logs, browser script exposure and accidental copying remain separate risks." ] },
            { id: "browser-storage", title: "Browser storage changes the attack surface", paragraphs: ["A token readable by JavaScript can be exposed by XSS. An HttpOnly cookie can prevent JavaScript from reading its value, but cookies may be sent automatically by the browser and therefore require deliberate SameSite/CSRF defenses for state-changing requests. There is no magic storage location that removes both XSS and CSRF concerns; choose from the client architecture and threat model." ] },
            { id: "transport", title: "Credentials belong on protected transport and out of URLs", paragraphs: ["Send bearer credentials over HTTPS and avoid putting access/refresh tokens in query strings, where URLs may be retained in browser history, proxies, analytics or logs. Redact authentication material from application and infrastructure logging." ] },
        ],
        { objective: "Define Steward's access/refresh lifecycle and failure cases.", scenario: "Steward needs browser/API sessions without making access tokens long-lived.", instructions: ["Choose access and refresh lifetimes and justify them.", "Define what happens when access expires.", "Define what happens when refresh expires or is revoked.", "Document how clients should handle `401` from expired access.", "For a browser client, compare JavaScript-readable token storage with HttpOnly-cookie delivery and state the XSS/CSRF trade-off; do not put bearer credentials in URLs."], deliverables: ["Token lifecycle diagram", "Failure table"], completionCriteria: ["Access lifetime is shorter than refresh lifetime.", "Refresh tokens are not accepted on ordinary API endpoints.", "Expiry behavior is explicit."] },
        ["Why use a refresh token instead of a very long-lived access token?", "Which token should be sent to ordinary Steward endpoints?", "Why does refresh-token theft have high impact?"],
        [{ title: "Simple JWT documentation", url: "https://django-rest-framework-simplejwt.readthedocs.io/en/latest/" }],
    ),
    richLesson(
        "identity-authentication-authorization-expiration-and-token-rotation",
        "Expiration and Token Rotation",
        "Token expiry limits how long a credential remains useful. Rotation goes further by replacing refresh credentials as they are used, creating an opportunity to detect reuse and reduce the value of copied tokens.",
        ["Separate expiry, revocation and rotation.", "Explain replay risk for refresh tokens.", "Design logout and compromise responses deliberately.", "Identify trade-offs between stateless simplicity and server-side control."],
        [
            { id: "three-controls", title: "Expiry, revocation and rotation solve different problems", paragraphs: ["Expiration is time-based. Revocation invalidates a token before its natural expiry. Rotation replaces refresh credentials after successful use. A purely stateless design makes revocation difficult; server-side blacklists or token-family state add control but also persistence and operational complexity.", "Steward does not need to pretend these trade-offs disappear. The Builder goal is to choose and document a defensible lifecycle."] },
            { id: "reuse", title: "Refresh-token reuse is a useful signal", paragraphs: ["When rotation is enabled, presenting an already-used refresh token can indicate that a token was copied. Mature designs can revoke the token family or force reauthentication rather than silently issuing another credential."] },
            { id: "concurrent-refresh", title: "Rotation must define concurrent refresh behavior", paragraphs: ["Two legitimate client requests can race using the same refresh token. A strict single-use rotation policy may accept one and reject the other as reuse. That can be correct, but clients and servers need a deliberate concurrency/retry design so ordinary races are not mistaken for invisible success." ] },
            { id: "password-change-sessions", title: "Credential changes and existing sessions are separate decisions", paragraphs: ["Changing a password does not automatically imply every already-issued bearer credential disappears unless the implementation links those events. Decide whether password reset/change, account disablement or suspected compromise revokes refresh sessions and how quickly already-issued access tokens cease to work." ] },
        ],
        { objective: "Design a refresh rotation and logout policy for Steward.", scenario: "A user logs out on one device after suspecting credential theft.", instructions: ["Define whether refresh tokens are rotated.", "Define whether logout blacklists one token or all sessions.", "Describe behavior when an old rotated token is reused.", "Document operational state required to enforce the policy.", "Define what happens when two refresh attempts race with the same rotating refresh token.", "Define whether password change, account disablement and suspected compromise revoke existing refresh sessions and how already-issued access tokens age out."], deliverables: ["Rotation policy", "Logout/compromise response"], completionCriteria: ["Expiry and revocation are not treated as synonyms.", "Replay/reuse is considered.", "The statefulness trade-off is acknowledged."] },
        ["How is rotation different from expiration?", "Why might a server keep refresh-token state?", "What should reuse of a rotated refresh token suggest?"],
        [{ title: "Simple JWT blacklist app", url: "https://django-rest-framework-simplejwt.readthedocs.io/en/latest/blacklist_app.html" }],
    ),
    richLesson(
        "identity-authentication-authorization-authentication-flows",
        "Authentication Flows",
        "Authentication is a protocol flow, not a single login endpoint. Registration, login, refresh, logout, password change and credential failure each modify security state and need consistent contracts.",
        ["Map end-to-end authentication flows.", "Avoid account-enumeration leaks where appropriate.", "Define state transitions for password change and logout.", "Separate credential verification from token issuance."],
        [
            { id: "flow-design", title: "Design flows as state transitions", paragraphs: ["Login begins with credentials and ends with authenticated session material or a deliberately limited failure response. Refresh begins with an existing refresh credential. Password change should normally require an authenticated session and current-password or equivalent assurance depending on risk. Each flow has different preconditions.", "Do not let response wording, timing or status design accidentally reveal more identity information than necessary on public authentication endpoints."] },
            { id: "steward-flow", title: "Steward's minimum Builder flow", paragraphs: ["For this stage, Steward should support account creation through an intentional path, credential login, access/refresh issuance, refresh, logout/revocation behavior and protected API access. Recovery/MFA can remain later security work unless explicitly required."], code: { language: "text", code: "register → stored identity + password hash\nlogin → verify password → tokens\nrequest → verify access → principal\nrefresh → verify refresh → rotate/issue\nlogout → revoke refresh according to policy", caption: "Each arrow represents a security state transition worth testing." } },
        ],
        { objective: "Create a sequence map for Steward authentication flows.", scenario: "Steward already has resource endpoints, Users and safe password handling, but no public authentication endpoints yet. Design the register/login/protected-request/refresh/logout lifecycle before implementing it in the next checkpoint.", instructions: ["Map register, login, protected request, refresh and logout.", "For each step list input, state read/write and failure outcome.", "Identify which endpoints require existing authentication.", "Add at least one negative path per flow."], deliverables: ["Authentication sequence map"], completionCriteria: ["State transitions are explicit.", "Negative paths are included.", "Credential verification and token issuance are separate concepts."] },
        ["Why is logout a security-state operation rather than only a UI action?", "What are the preconditions for refresh compared with login?", "Why should authentication error messages be designed deliberately?"],
        [{ title: "OWASP Authentication Cheat Sheet", url: OWASP_AUTH }],
    ),
    richLesson(
        "identity-authentication-authorization-drf-jwt-integration",
        "Implementing JWT Authentication in DRF",
        "The token model becomes useful only when it is connected to the framework request lifecycle deliberately. In DRF with Simple JWT, configuration chooses the authentication backend and token policy, token endpoints issue or refresh credentials, and JWTAuthentication verifies an access token and establishes `request.user` before permission code runs.",
        ["Wire JWT authentication into DRF without treating the library as magic.", "Configure explicit access/refresh lifetimes and rotation policy.", "Trace login/refresh/protected-request behavior through framework components.", "Verify failures at the authentication boundary before authorization."],
        [
            { id: "install-wire", title: "Wire the authentication backend and endpoints", paragraphs: ["Install the JWT package as an application dependency, configure DRF to use JWTAuthentication for protected API requests, and expose narrowly scoped token obtain/refresh endpoints. This does not replace Django's password hashing: the login flow still verifies the user's stored password hash before credentials are issued.", "Keep token URLs separate from ordinary resource endpoints so their security purpose remains visible."], code: { language: "python", code: "# settings.py\nfrom datetime import timedelta\n\nREST_FRAMEWORK = {\n    'DEFAULT_AUTHENTICATION_CLASSES': (\n        'rest_framework_simplejwt.authentication.JWTAuthentication',\n    ),\n}\n\nSIMPLE_JWT = {\n    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),\n    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),\n    'ROTATE_REFRESH_TOKENS': True,\n    'BLACKLIST_AFTER_ROTATION': True,\n}\n\n# urls.py\nfrom rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView\n\nurlpatterns += [\n    path('auth/token/', TokenObtainPairView.as_view()),\n    path('auth/token/refresh/', TokenRefreshView.as_view()),\n]", caption: "Illustrative explicit JWT wiring; choose actual lifetimes from the documented Steward policy." } },
            { id: "request-lifecycle", title: "Trace what happens on a protected request", paragraphs: ["A client sends Authorization: Bearer <access-token>. JWTAuthentication extracts the credential, validates its signature/lifetime and token type according to configuration, resolves the user/principal, and assigns authentication state to the DRF request. Permission checks then decide whether that authenticated principal may perform the requested operation.", "This ordering explains an important diagnostic distinction: malformed/expired credentials fail authentication; a valid access token can proceed to permission evaluation and still receive 403 for a cross-team operation."] , code: { language: "text", code: "Authorization: Bearer <access>\n        ↓\nJWTAuthentication\n  extract → verify → validate claims/type → resolve principal\n        ↓\n`request.user` / request.auth\n        ↓\nDRF permission + Steward object policy\n        ↓\nallow operation OR deny", caption: "Framework mechanics preserve the authentication/authorization boundary." } },
            { id: "rotation-blacklist", title: "Rotation and blacklisting require configuration and state", paragraphs: ["If refresh rotation and blacklisting are part of the chosen policy, enable the Simple JWT blacklist application and apply its migrations. Rotation means a successful refresh can issue a replacement refresh token; blacklisting gives the server persisted state with which to reject selected refresh credentials. Verify the exact behavior in tests instead of assuming a setting name proves the policy works.", "Do not place current Team Membership authority into a long-lived token merely to avoid a database authorization query. Steward's object policy should continue to consult current membership where revocation of team authority must take effect promptly."] },
            { id: "prove-boundary", title: "Test authentication before layering authorization", paragraphs: ["First prove: valid login issues the intended token types; access works on a protected endpoint; refresh is rejected as an access credential; expired/malformed access is rejected; refresh follows the configured rotation/blacklist behavior. Then add team/object authorization tests. Separating these failures makes defects diagnosable."] },
        ],
        { objective: "Implement Steward's designed authentication lifecycle with Simple JWT and prove it before adding resource authorization.", scenario: "The token policy and authentication-flow contract have already been designed, and the password checkpoint created safe credential storage. Implement the missing HTTP lifecycle now so later permission tests are built on a real verified authentication boundary.", instructions: ["Add/configure Simple JWT and the DRF JWT authentication class.", "Implement the intentional account-creation/registration endpoint from the authentication-flow contract using the safe password boundary already created.", "Expose token obtain and refresh routes.", "Set explicit access/refresh lifetimes matching your policy.", "If using rotation/blacklisting, enable the required application/state and migrations.", "Obtain an access/refresh pair with a real Steward user.", "Call a protected endpoint with access, with refresh in the access position, with malformed access and with an expired access token.", "Exercise refresh at least once and capture whether rotation/blacklisting matches configuration.", "Implement logout/revocation according to the previously chosen policy and prove the affected refresh credential can no longer extend the session.", "Exercise one password-change flow and prove the old password no longer authenticates while the new password does.", "Record the request path from bearer credential to `request.user`."], deliverables: ["JWT framework configuration", "Registration/token/refresh/logout routes", "Authentication evidence table", "Password-change evidence", "Short request-lifecycle trace"], completionCriteria: ["The learner can identify which framework component verifies access tokens.", "Access and refresh credentials are not interchangeable.", "Lifetimes are explicit rather than library defaults nobody owns.", "Observed rotation/revocation/logout behavior matches the documented policy.", "Registration and password change preserve Django password hashing.", "Authorization has not been confused with successful authentication."] },
        ["Which component establishes `request.user` from a bearer access token?", "Why does enabling JWTAuthentication not itself authorize service modification?", "What persisted state is introduced by refresh-token blacklisting?", "Why should access and refresh credentials be tested as non-interchangeable?"],
        [{ title: "Simple JWT — Getting started", url: "https://django-rest-framework-simplejwt.readthedocs.io/en/latest/getting_started.html" }, { title: "Simple JWT — Settings", url: "https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html" }, { title: "Simple JWT — Blacklist app", url: "https://django-rest-framework-simplejwt.readthedocs.io/en/latest/blacklist_app.html" }],
    ),
    richLesson(
        "identity-authentication-authorization-roles-and-permissions",
        "Roles and Permissions",
        "Roles are useful when they compress a set of permissions, but role names alone are not a complete authorization model. The important question is which action a principal may perform within which scope.",
        ["Distinguish roles from permissions.", "Scope permissions to teams and resources.", "Avoid a single global role field when domain membership is contextual.", "Design least-privilege Steward roles."],
        [
            { id: "role-compression", title: "Roles are permission bundles", paragraphs: ["A role such as maintainer is shorthand for allowed actions. In Steward that role belongs on a Membership because the same user can be a maintainer of one Team and only a viewer or non-member of another. A global user.role field cannot represent that safely.", "Start with the smallest role set that expresses real work. Avoid creating many decorative roles before concrete permission differences exist."] },
            { id: "permission-matrix", title: "Model scope explicitly", paragraphs: ["Permission decisions should combine action with scope. For example, team maintainers may create or modify services owned by that team, while ordinary authenticated users may read the registry."], code: { language: "text", code: "viewer:     read services\nmaintainer: read + create/update services for own team\nadmin:      exceptional platform-wide administration\n\nrole is attached to Team Membership, not globally copied onto User", caption: "A small scoped role model is stronger than a large vague one." } },
            { id: "rbac-abac", title: "Roles are only one policy input", paragraphs: ["RBAC grants capabilities through roles. Attribute/context-aware rules additionally use facts about the subject, resource or environment. Steward already needs both ideas: Membership.role supplies a capability bundle, while Service.owning_team and current membership supply resource attributes/scope. You do not need an ABAC engine to reason this way." ] },
            { id: "permission-composition", title: "Policy composition must have explicit AND/OR meaning", paragraphs: ["A write might require authenticated AND active membership AND maintainer role AND ownership scope. Accidentally using OR between independent requirements can create privilege escalation. Express complex policy in named predicates/functions and test each denied component rather than compressing security logic into unreadable booleans." ] },
            { id: "admin-exception", title: "Administrative bypass is a capability that needs its own boundary", paragraphs: ["If Steward eventually needs platform-wide administration, make that authority explicit, rare and auditable. Do not scatter 'or user.is_staff' throughout business code; centralize the exceptional policy so reviewers can find where normal ownership rules are bypassed." ] },
        ],
        { objective: "Build Steward's role-permission matrix.", scenario: "The team currently has a boolean is_admin and wants to add service ownership rules.", instructions: ["Define viewer, maintainer and any truly necessary admin capability.", "Map each role to concrete actions and write each non-trivial rule as explicit AND/OR policy composition (for example authenticated AND maintainer AND own-team scope).", "Attach team-scoped roles to Membership.", "Identify actions that should remain platform-wide and exceptional."], deliverables: ["Role-permission matrix"], completionCriteria: ["Most permissions are team-scoped.", "Roles map to concrete actions.", "The design follows least privilege."] },
        ["Why is a role not the same as a permission?", "Why should maintainer usually live on Membership rather than User?", "What does least privilege mean in Steward?"],
        [{ title: "DRF Permissions", url: DRF_PERMISSIONS }],
    ),
    richLesson(
        "identity-authentication-authorization-object-level-authorization",
        "Object-Level Authorization",
        "Some permissions can be decided from the endpoint and action alone; others depend on the particular resource. A user might be allowed to update services in general but only services owned by a Team they maintain. Object-level authorization is that second decision: given the authenticated principal, requested action and actual resource, is this specific operation allowed?",
        ["Recognize object-level authorization requirements.", "Implement checks against loaded resource ownership.", "Cover list/queryset leakage as well as detail operations.", "Test negative cross-team cases."],
        [
            { id: "object-check", title: "The resource changes the answer", paragraphs: ["A maintainer may be allowed to update /services/{id}, but not every Service. Once the resource is loaded, Steward must compare its owning_team with current Membership state. The same endpoint and same HTTP method can therefore produce allow or deny depending on the object.", "Be careful with collection endpoints too. Object permission hooks on retrieve/update do not automatically prevent list endpoints from returning records the caller should never see in systems with private data."], code: { language: "python", code: "def can_modify_service(user, service) -> bool:\n    return Membership.objects.filter(\n        user=user,\n        team=service.owning_team,\n        role=Membership.Role.MAINTAINER,\n    ).exists()", caption: "Authorization derives from current domain state." } },
            { id: "drf-hooks", title: "DRF object permission hooks are not universal row filters", paragraphs: ["Generic detail flows can call check_object_permissions after get_object(), but list endpoints do not normally run object permission checks for every returned row. Creation also has no existing object to check before save. Therefore list visibility belongs in queryset/policy filtering, and create authorization must validate the requested ownership/scope before persistence." ] },
            { id: "existence-leak", title: "Authorization can leak resource existence", paragraphs: ["Returning 403 for a private object can reveal that the identifier exists, while 404 can conceal existence in some designs. There is no universal answer: define the product's visibility model and keep response behavior consistent enough that unauthorized callers cannot enumerate sensitive resources." ] },
            { id: "stale-check", title: "Check and mutation can race", paragraphs: ["Authorization based on current membership/ownership can become stale between reading policy state and committing a sensitive mutation. For ordinary Builder operations, keep checks close to the write and use database transactions/locking where an invariant truly requires atomicity. Later architecture/security work can revisit higher-contention cases." ] },
        ],
        { objective: "Implement and test object-level authorization for Steward services.", scenario: "A maintainer from Team A attempts to modify a service owned by Team B.", instructions: ["Add a reusable service-modification policy.", "Apply it to update and delete operations.", "Write positive same-team tests.", "Write negative cross-team tests.", "Verify list behavior does not leak anything the product intends to restrict; demonstrate that DRF object-permission hooks do not automatically filter a list.", "Test create separately because no persisted object exists yet for an object-permission hook.", "Decide whether an unauthorized private object should produce 403 or concealed 404 under Steward's visibility model."], deliverables: ["Authorization policy", "Positive/negative tests"], completionCriteria: ["Cross-team writes are denied.", "Same-team role behavior is proven.", "Authorization uses current database relationships."] },
        ["Why can endpoint-level authorization be insufficient?", "What makes authorization object-level?", "Why must collection/list behavior also be reviewed?"],
        [{ title: "DRF Object level permissions", url: "https://www.django-rest-framework.org/api-guide/permissions/#object-level-permissions" }],
    ),
    richLesson(
        "identity-authentication-authorization-ownership-and-access-rules",
        "Ownership and Access Rules",
        "Ownership is a domain relationship with security consequences. In Steward, services are owned by Teams, not by whichever user happened to create the record. That distinction keeps governance and authorization aligned with organizational responsibility.",
        ["Model team ownership as durable domain data.", "Separate creator/audit metadata from owner authority.", "Define transfer-of-ownership rules.", "Ensure nested resources inherit or validate ownership consistently."],
        [
            { id: "team-ownership", title: "Creator is not owner", paragraphs: ["created_by is useful audit information, but it should not become Steward's authority model. A Service belongs to an owning Team. Team membership determines who can act on behalf of that owner.", "Ownership transfer is therefore a meaningful security operation. Moving a service from Team A to Team B changes who may administer it and should require appropriate authority rather than ordinary field-edit permission."] },
            { id: "nested-resources", title: "Dependencies and environments must respect ownership", paragraphs: ["When creating an Environment or dependency relationship through a Service, ensure the caller can manage the source Service and that referenced objects obey domain rules. Nested endpoints can otherwise bypass the main Service permission model."] },
            { id: "mass-assignment", title: "Server-controlled ownership must not become mass assignment", paragraphs: ["A serializer accepting every model field can accidentally let a client set owning_team, created_by or other authority-bearing fields. Mark server-derived/security-sensitive fields read-only or validate them through an explicit ownership operation. Representation convenience must not decide authorization." ] },
            { id: "transfer", title: "Ownership transfer is a command with before-and-after authority", paragraphs: ["A transfer should validate authority to release/transfer the source ownership and authority/validity of the destination Team, then preserve an audit fact about who performed it. Because the operation changes future authorization, model it more deliberately than a generic PATCH of owning_team_id." ] },
        ],
        { objective: "Write explicit ownership invariants for Steward.", scenario: "Several endpoints can mutate Service, Environment and ServiceDependency records.", instructions: ["Define who owns each aggregate or record.", "Define who may create/update/delete each.", "Define ownership transfer separately.", "Review nested endpoints for bypass paths.", "Attempt mass assignment of owning_team/creator-like authority fields and prove the representation boundary rejects or explicitly authorizes it.", "Model ownership transfer as a distinct operation and record the before/after authority plus actor."], deliverables: ["Ownership policy", "Bypass review"], completionCriteria: ["Creator metadata is not confused with owner authority.", "Ownership transfer has a stronger rule.", "Nested writes cannot bypass service ownership checks."] },
        ["Why should created_by not determine Steward service ownership?", "Why is ownership transfer security-sensitive?", "How can nested endpoints accidentally bypass authorization?"],
        [{ title: "OWASP Authorization Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html" }],
    ),
    richLesson(
        "identity-authentication-authorization-common-authentication-and-authorization-mistakes",
        "Common Authentication and Authorization Mistakes",
        "Security defects often come from missing boundaries rather than sophisticated cryptography: trusting client-supplied ownership, checking permissions only in the UI, exposing overly long-lived tokens, leaking credentials into logs, or forgetting negative authorization tests.",
        ["Recognize common authn/authz implementation failures.", "Identify client-controlled security attributes.", "Use deny-by-default and server-derived ownership.", "Design negative tests as first-class evidence."],
        [
            { id: "mistakes", title: "Failure patterns worth hunting", paragraphs: ["Do not trust owning_team_id from a request merely because the JSON is valid. Confirm the authenticated user may act for that team. Do not expose write buttons as the primary authorization control; the API must deny unauthorized calls directly. Do not assume a valid JWT means the subject may manipulate arbitrary resource IDs.", "Avoid detailed login errors that unnecessarily distinguish unknown user from wrong password. Avoid logging `Authorization` headers, refresh tokens or raw credentials. Keep token lifetimes and CORS/transport concerns explicit rather than relying on defaults you have not inspected."] },
            { id: "negative-testing", title: "Test what must not happen", paragraphs: ["Positive tests prove functionality. Security confidence requires negative cases: expired token, malformed token, wrong team, insufficient role, changed membership, self-dependency attempt, forged ownership, revoked refresh and direct object-ID manipulation."] },
            { id: "enumeration-abuse", title: "Public authentication endpoints are abuse surfaces", paragraphs: ["Login, registration and recovery-style endpoints can reveal whether accounts exist through messages, status, response shape or large timing differences. Use deliberately limited public failures where enumeration matters, add rate/abuse controls, and keep richer diagnosis in protected operational evidence rather than client text." ] },
            { id: "idor-bola", title: "Changing an object ID is an authorization test, not input validation", paragraphs: ["If /services/41 is allowed, changing the identifier to /services/42 must trigger authorization for that specific object. Valid integer syntax and successful lookup do not grant access. This broken-object-level-authorization pattern is common enough that every object endpoint deserves cross-owner tests." ] },
            { id: "security-cache", title: "Caching authorization-sensitive data needs the same scope", paragraphs: ["If authenticated responses are cached later, the cache key/policy must preserve the same visibility boundary as the underlying endpoint. A correct database authorization check can still be undermined by serving another user's cached representation. Builder should recognize this hazard even though cache infrastructure is introduced later." ] },
        ],
        { objective: "Run a targeted authorization abuse review against Steward.", scenario: "Assume the client can send arbitrary IDs and payloads and try to cross every trust boundary.", instructions: ["Attempt cross-team service update/delete.", "Attempt to assign ownership to a team without membership.", "Replay expired/revoked token cases.", "Inspect logs for sensitive headers/tokens.", "Record each attempted abuse and observed control.", "For every object detail endpoint, mutate a valid object identifier to another Team's identifier and verify authorization is reevaluated.", "Probe login/account-facing failures for avoidable account enumeration and verify rate/abuse controls behave as documented."], deliverables: ["Abuse-case checklist", "Evidence of denials", "Any defects found"], completionCriteria: ["At least five negative cases are exercised.", "The API, not the UI, enforces denial.", "Sensitive credentials are absent from logs."] },
        ["Why is hiding a button not authorization?", "Why is client-supplied owning_team_id security-sensitive?", "What kind of evidence do negative tests provide that happy-path tests do not?"],
        [{ title: "OWASP Authorization Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html" }, { title: "OWASP API Security Top 10", url: "https://owasp.org/API-Security/" }],
    ),
    {
        id: "identity-authentication-authorization-lab-secure-steward-api",
        title: "Lab: Secure Steward API",
        activities: [
            {
                id: "identity-authentication-authorization-lab-secure-steward-api-reading",
                title: "Secure Steward as a Domain-Aware API",
                estimatedMinutes: 20,
                content: {
                    type: "reading",
                    body: "This lab integrates the identity, credential, token and authorization model into the existing PostgreSQL-backed Steward API. The goal is not merely to make endpoints require a token; it is to prove that real team ownership boundaries survive hostile requests.",
                    blocks: [
                        { type: "paragraph", text: "This lab integrates the identity, credential, token and authorization model into the existing PostgreSQL-backed Steward API. The goal is not merely to make endpoints require a token; it is to prove that real team ownership boundaries survive hostile requests." },
                        { type: "heading", id: "target", text: "Target security model", level: 2 },
                        { type: "list", items: ["Django-managed password hashing", "JWT access and refresh tokens", "short-lived access credentials", "documented refresh/rotation/logout behavior", "Team Membership roles", "object-level Service authorization", "ownership-transfer protection", "negative cross-team tests", "no credential leakage in logs"] },
                        { type: "callout", tone: "warning", title: "Do not fake authorization", body: "A test that only verifies unauthenticated requests return `401` is not enough. The important Builder evidence is authenticated-but-unauthorized behavior: valid user, valid token, wrong team or insufficient role, denied by the API." },
                        { type: "resources", title: "Implementation references", resources: [{ title: "Simple JWT", url: "https://django-rest-framework-simplejwt.readthedocs.io/en/latest/" }, { title: "DRF permissions", url: DRF_PERMISSIONS }, { title: "OWASP Authorization Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html" }] },
                    ],
                },
            },
            {
                id: "identity-authentication-authorization-lab-secure-steward-api-practice",
                title: "Secure Steward API",
                estimatedMinutes: 180,
                content: {
                    type: "practical",
                    objective: "Implement and prove authentication plus team-scoped object authorization in Steward.",
                    scenario: "Steward already has Django/DRF endpoints and PostgreSQL persistence. Add a real identity/security boundary without redesigning the product into a generic authentication demo.",
                    instructions: ["Use Django's password hashing and verify raw passwords are never persisted or logged.", "Implement JWT access and refresh endpoints with explicit lifetimes.", "Choose and document refresh rotation/revocation/logout behavior.", "Use Membership roles to represent team-scoped authority.", "Require authentication for protected write operations.", "Implement object-level rules so maintainers can modify services owned by their team but not another team.", "Protect ownership transfer as a distinct higher-risk operation.", "Apply equivalent rules to Environment and ServiceDependency mutations so nested routes cannot bypass Service authorization.", "Write tests for no-token, expired-token, insufficient-role, cross-team, revoked/invalid refresh and positive same-team cases.", "Inspect application logs and ensure credentials, `Authorization` headers and refresh tokens are not emitted.", "Update OpenAPI/authentication documentation so another engineer can exercise the flows."],
                    deliverables: ["JWT authentication implementation", "Membership/role authorization policy", "Object-level permission code", "Authentication and authorization test suite", "Token lifecycle note", "Updated API documentation"],
                    completionCriteria: ["Passwords use framework hashing.", "Expired or invalid access tokens are rejected.", "Authenticated users cannot modify another team's services without explicit authority.", "Same-team maintainers can perform allowed changes.", "Nested resource writes cannot bypass ownership checks.", "Refresh/logout behavior matches documentation.", "Negative tests prove the security boundary.", "Sensitive credentials are absent from logs."],
                },
            },
            {
                id: "identity-authentication-authorization-lab-secure-steward-api-check",
                title: "Security Defence",
                estimatedMinutes: 15,
                content: { type: "reflection", prompt: "1. Which authorization decision in your implementation depends on current database state rather than token claims?\n2. What happens if a user's Team Membership is removed while an access token is still valid?\n3. Which negative test gives you the strongest evidence that object-level authorization works?\n4. What security trade-off did you make in refresh-token handling, and what would make you revisit it?" },
            },
        ],
    },
];
