import type { LearningResource, LessonBlock } from "../activities";
import type { Lesson } from "./lesson";

const djangoDocs: LearningResource = { title: "Django documentation", url: "https://docs.djangoproject.com/en/stable/" };
const drfDocs: LearningResource = { title: "Django REST framework documentation", url: "https://www.django-rest-framework.org/" };
const openApi: LearningResource = { title: "OpenAPI Specification", url: "https://spec.openapis.org/oas/latest.html" };

function slug(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }

function richLesson(title: string, introduction: string, outcomes: string[], concepts: Array<{ heading: string; body: string; code?: { language: string; caption: string; value: string } }>, practice: string[], check: string[], resources: LearningResource[] = [djangoDocs, drfDocs]): Lesson {
  const id = `django-and-api-engineering-${slug(title)}`;
  const blocks: LessonBlock[] = [
    { type: "heading", id: "introduction", text: "Introduction" },
    { type: "paragraph", text: introduction },
    { type: "heading", id: "outcomes", text: "Learning outcomes" },
    { type: "list", items: outcomes },
  ];
  for (const concept of concepts) {
    blocks.push({ type: "heading", id: slug(concept.heading), text: concept.heading });
    blocks.push({ type: "paragraph", text: concept.body });
    if (concept.code) blocks.push({ type: "code", language: concept.code.language, caption: concept.code.caption, code: concept.code.value });
  }
  blocks.push({ type: "callout", tone: "steward", title: "Steward connection", body: "Apply this concept to Steward's engineering service registry. Framework features are valuable only when they preserve the domain rules around teams, service ownership, environments, lifecycle, criticality and service dependencies." });
  blocks.push({ type: "heading", id: "assignment", text: "Assignment" });
  blocks.push({ type: "list", ordered: true, items: practice });
  blocks.push({ type: "resources", title: "Required and supporting reading", resources });
  blocks.push({ type: "heading", id: "knowledge-check", text: "Knowledge check" });
  blocks.push({ type: "list", items: check });

  return {
    id,
    title,
    activities: [
      { id: `${id}-concepts`, title: `${title}: Concepts and Mental Model`, estimatedMinutes: 50, content: { type: "reading", body: introduction, blocks } },
      { id: `${id}-practice`, title: `${title}: Engineering Practice`, estimatedMinutes: 55, content: { type: "practical", objective: `Apply ${title} to the evolving Steward API with observable behavior and evidence.`, scenario: "Continue the same Steward codebase. Preserve useful implementation, notes and decisions for later Builder modules.", instructions: practice, deliverables: ["Working Steward implementation or focused experiment", "Evidence note describing behavior, one failure path and one design decision"], completionCriteria: ["The result is demonstrable.", "The implementation is connected to Steward rather than a disposable tutorial domain.", "At least one boundary/failure case is exercised.", "The learner can explain what Django/DRF is doing rather than only copy framework syntax."] } },
      { id: `${id}-check`, title: `${title}: Knowledge Check`, estimatedMinutes: 10, content: { type: "reflection", prompt: check.join("\n\n") } },
    ],
  };
}

export const djangoAndApiRichLessons: Lesson[] = [
  richLesson("Django Foundations", "Django is a web framework with strong conventions around configuration, request handling, persistence and application structure. The goal is not to memorize commands; it is to understand the lifecycle through which an incoming request reaches code, data and a response.", ["Explain the role of settings, URL routing, views, models and middleware.", "Trace a request through a Django project.", "Distinguish framework configuration from domain behavior."], [
    { heading: "Project lifecycle", body: "A Django project configures the process; applications group coherent functionality. HTTP requests are resolved through URL configuration to views, while middleware can act before and after the view.", code: { language: "python", caption: "Minimal route and view", value: "# urls.py\nfrom django.urls import path\nfrom .views import health\n\nurlpatterns = [path('health/', health)]\n\n# views.py\nfrom django.http import JsonResponse\n\ndef health(request):\n    return JsonResponse({'status': 'ok'})" } },
    { heading: "Framework boundary", body: "Django should host Steward's domain behavior, not redefine it accidentally. A framework-aware view can translate HTTP input into application operations while core rules remain explicit and testable." },
  ], ["Create a fresh Django project inside the Steward repository.", "Add one app for the initial service-registry capability.", "Trace a request from URL to response.", "Record which files configure infrastructure and which should hold domain behavior."], ["What is the difference between a Django project and app?", "Where does URL resolution happen?", "Why should domain rules not be scattered across settings and views?"]),

  richLesson("Django REST Framework", "Django REST Framework adds API-oriented abstractions such as Request/Response, serializers, authentication hooks, permissions, generic views and viewsets. These abstractions reduce plumbing, but they do not decide your API contract or business rules for you.", ["Explain what DRF adds on top of Django.", "Describe serializer/view/permission responsibilities.", "Return a JSON response through DRF."], [
    { heading: "API request lifecycle", body: "DRF wraps Django's request handling with content negotiation, parsing, authentication, permissions and rendering. Understanding that sequence matters when diagnosing why a request was rejected.", code: { language: "python", caption: "Simple DRF endpoint", value: "from rest_framework.decorators import api_view\nfrom rest_framework.response import Response\n\n@api_view(['GET'])\ndef service_health(request):\n    return Response({'service': 'steward', 'status': 'ok'})" } },
    { heading: "Abstractions have costs", body: "ViewSets and generic views can remove repetition. They can also hide behavior when used before the developer understands routing, serialization and authorization. Prefer the highest-level abstraction whose behavior you can still explain." },
  ], ["Install/configure DRF.", "Create one GET endpoint with DRF.", "Inspect Request and Response behavior.", "Compare the DRF endpoint with a plain Django JsonResponse endpoint."], ["What does DRF add beyond Django?", "Why is a serializer not the same thing as a model?", "What can be hidden by prematurely using ViewSets?"]),

  richLesson("Projects, Applications and Boundaries", "Django apps are packaging units, not automatically correct architectural boundaries. Steward needs boundaries derived from cohesion and domain responsibility rather than one app per database table.", ["Evaluate candidate Django app boundaries.", "Recognize low-cohesion and cyclic dependencies.", "Keep deployment configuration separate from domain modules."], [
    { heading: "Boundary by responsibility", body: "A service-registry capability may contain Services, Teams, Environments and dependencies because their behaviors change together. Splitting every model into its own app can create more coupling, not less." },
    { heading: "Dependency direction", body: "Prefer dependencies toward stable domain concepts. Avoid having every app import every other app's models, signals and utilities without an explicit contract." },
  ], ["Sketch 2–3 possible app structures for Steward.", "Choose one and document cohesion/coupling trade-offs.", "Create the initial apps without circular imports.", "Record what evidence would justify splitting them later."], ["Why is one Django app per model usually weak architecture?", "What is a circular dependency telling you?", "When should a boundary be revisited?"]),

  richLesson("Models and Domain Data", "Django models map Python objects to relational persistence, but database-shaped code should still reflect domain meaning. Fields, constraints, relationships and lifecycle values are part of Steward's behavior contract.", ["Model Steward concepts with appropriate fields and relationships.", "Distinguish database constraints from application validation.", "Use enums/choices deliberately."], [
    { heading: "Model the language of the domain", body: "Service, Team and Environment names should make the code read like the service-registry problem rather than generic Record/Item structures.", code: { language: "python", caption: "Initial Steward model", value: "from django.db import models\n\nclass Service(models.Model):\n    class Lifecycle(models.TextChoices):\n        DEVELOPMENT = 'development'\n        PRODUCTION = 'production'\n        RETIRED = 'retired'\n\n    name = models.CharField(max_length=120)\n    slug = models.SlugField(unique=True)\n    lifecycle = models.CharField(max_length=20, choices=Lifecycle.choices)" } },
    { heading: "Persistence is not all validation", body: "A unique slug belongs naturally in the database. A rule such as 'retired services cannot accept new dependencies' may require application/domain logic because it spans state and operation semantics." },
  ], ["Implement Team, Service and Environment models.", "Add at least one database-enforced constraint.", "Represent lifecycle/criticality deliberately.", "Document one rule that should not live only as a database field constraint."], ["What kinds of invariants belong in the database?", "Why are choices useful but insufficient for all domain rules?", "How can model names improve architectural clarity?"]),

  richLesson("Serializers and Representation", "Serializers sit at the representation boundary. They parse untrusted external data, validate it, translate it into application/model values and render responses. This is where the Python boundary reasoning from earlier lessons becomes concrete.", ["Explain serialization vs validation.", "Separate representation errors from domain errors.", "Control fields exposed by the API."], [
    { heading: "Input is representation", body: "A JSON string 'production' becomes a domain lifecycle only after parsing and validation. Serializers should not silently accept fields that clients must never control.", code: { language: "python", caption: "Service serializer", value: "from rest_framework import serializers\nfrom .models import Service\n\nclass ServiceSerializer(serializers.ModelSerializer):\n    class Meta:\n        model = Service\n        fields = ['id', 'name', 'slug', 'lifecycle', 'criticality', 'owner_team']\n        read_only_fields = ['id']" } },
    { heading: "Validation layers", body: "Field validation handles local shape/range rules. Object validation handles relationships among fields. Domain/application services should own rules that are broader than the representation itself." },
  ], ["Create a Service serializer.", "Reject an unsupported lifecycle.", "Make at least one server-controlled field read-only.", "Add one cross-field validation rule and explain whether it truly belongs in the serializer."], ["What is the difference between parsing and domain validation?", "Why should not every model field automatically be writable?", "When does serializer validation become misplaced business logic?"]),

  richLesson("Views, ViewSets and Routing", "Views coordinate HTTP concerns: method, authentication/authorization hooks, parsing, application calls and response translation. Routers and ViewSets can make CRUD-style APIs concise, but explicitness matters when behavior diverges from generic CRUD.", ["Choose between function views, APIView, generic views and ViewSets.", "Explain router-generated routes.", "Keep orchestration thin."], [
    { heading: "Thin orchestration", body: "A good endpoint makes the HTTP/application boundary visible. It should not accumulate persistence queries, business rules, logging, authorization and response formatting in one giant method." },
    { heading: "ViewSet example", body: "For straightforward collection/resource operations, a ModelViewSet can be appropriate when permissions and domain rules remain explicit.", code: { language: "python", caption: "Service ViewSet", value: "from rest_framework.viewsets import ModelViewSet\n\nclass ServiceViewSet(ModelViewSet):\n    queryset = Service.objects.all()\n    serializer_class = ServiceSerializer" } },
  ], ["Implement /services/ list/create and /services/{id}/ retrieve/update.", "Inspect generated routes.", "Add a custom operation only if it represents a real Steward behavior.", "Document why your chosen view abstraction is appropriate."], ["When is a ViewSet a good fit?", "Why should views remain thin?", "What is the downside of inventing action endpoints for ordinary resource updates?"]),

  richLesson("Validation and Business Rules", "Validation asks whether input can be accepted; business rules ask whether an operation is allowed in the current domain state. Steward needs both. Conflating them makes rules difficult to reuse and test.", ["Separate syntactic/representation validation from domain rules.", "Place rules where all callers can rely on them.", "Return deliberate errors for rejected operations."], [
    { heading: "Rule location", body: "A self-dependency should be rejected whether the operation comes through REST, an admin command or a future background process. That argues for a reusable application/domain rule rather than a view-only check." },
    { heading: "Example invariant", body: "ServiceDependency creation should reject source == target and duplicate source/target pairs. Database constraints can reinforce the rule, while application code returns a useful explanation." },
  ], ["Implement self-dependency rejection.", "Add duplicate-dependency protection.", "Exercise rules outside the HTTP happy path.", "Document which rules are reinforced by database constraints."], ["What is the difference between malformed input and a forbidden domain transition?", "Why duplicate critical rules at both application and database layers sometimes?", "How do you avoid view-only business logic?"]),

  richLesson("API Error Handling", "An API error is part of the contract. Clients need stable status semantics and a useful machine-readable body; operators need enough internal evidence to diagnose failures without leaking sensitive implementation detail.", ["Distinguish client, authorization, not-found, conflict and server failures.", "Design a stable error body.", "Avoid leaking stack traces or database internals."], [
    { heading: "Stable error shape", body: "Clients should not parse arbitrary framework strings. Define a predictable structure for code/message/details and preserve correlation data separately where useful.", code: { language: "json", caption: "Example domain error", value: "{\n  \"code\": \"service_dependency_self_reference\",\n  \"message\": \"A service cannot depend on itself.\",\n  \"details\": {\"target_service\": 42}\n}" } },
    { heading: "Do not confuse 4xx and 5xx", body: "A rejected client operation should not become 500 merely because Python raised an exception. Conversely, an unexpected database failure should not be disguised as validation error." },
  ], ["Define a Steward error shape.", "Map at least four failure scenarios to appropriate status codes.", "Trigger an unexpected exception locally and verify the client does not receive sensitive internals.", "Record the operator-side evidence needed for diagnosis."], ["Why is a stable error code useful?", "When is 409 more appropriate than 400?", "Why should unexpected exceptions remain distinguishable from client errors?"]),

  richLesson("Filtering, Searching and Ordering", "Collection endpoints become useful when clients can ask domain questions without downloading everything. Query parameters should reflect supported use cases and be bounded to avoid accidental performance and data-exposure problems.", ["Implement explicit filters/search/order fields.", "Distinguish exact filtering from free-text search.", "Consider query cost and information exposure."], [
    { heading: "Service-registry questions", body: "Steward should naturally answer: production services, high-criticality services, services owned by a team, or services depending on another service." },
    { heading: "Bound the interface", body: "Do not expose arbitrary model-field ordering/search simply because the framework makes it easy. Public query capabilities are part of the API contract." },
  ], ["Add lifecycle and criticality filters.", "Add owner-team filtering.", "Add a limited search over service name/slug.", "Allow ordering only on deliberate fields.", "Inspect at least one generated SQL query."], ["What is the difference between filtering and searching?", "Why can unrestricted ordering/search create performance risk?", "How does a query parameter become part of compatibility obligations?"]),

  richLesson("Pagination", "Pagination is an API behavior and a performance boundary. It limits response size, changes client navigation and creates consistency questions when underlying data changes between page requests.", ["Explain offset/page vs cursor approaches conceptually.", "Configure bounded pagination.", "Recognize unstable ordering risks."], [
    { heading: "Always define ordering", body: "Pagination without deterministic ordering can return duplicates or skip records across requests. Choose an ordering consistent with the collection semantics." },
    { heading: "Contract implications", body: "Page size, next/previous links and maximum limits affect clients and infrastructure. They should be deliberate rather than framework defaults nobody owns." },
  ], ["Enable pagination for /services/.", "Set a sensible default and maximum page size.", "Verify deterministic ordering.", "Test empty, single-page and multi-page collections."], ["Why does pagination require deterministic ordering?", "What problem does a maximum page size solve?", "When might cursor pagination be preferable?"]),

  richLesson("API Versioning", "Versioning is a compatibility strategy, not a substitute for careful evolution. Most changes should first be classified as additive, compatible, behavior-changing or breaking before choosing a version mechanism.", ["Classify API changes by compatibility impact.", "Explain URI/header/media-type versioning trade-offs.", "Prefer evolutionary compatibility where possible."], [
    { heading: "Not every change needs v2", body: "Adding an optional response field can often be compatible. Renaming lifecycle values or changing authorization semantics can break clients even if the URL version is unchanged." },
    { heading: "Versioning creates support obligations", body: "Once multiple versions exist, teams must decide ownership, deprecation timelines, documentation and testing. Versioning has ongoing cost." },
  ], ["Classify ten hypothetical Steward API changes.", "Choose a versioning strategy for Steward and justify it.", "Write a deprecation note for one breaking change.", "Identify a change you would redesign to avoid creating v2."], ["What makes an API change breaking?", "Why is versioning not free?", "What is the difference between API version and application release version?"]),

  richLesson("OpenAPI and Swagger Documentation", "An API contract should be inspectable by humans and tools. OpenAPI describes operations, parameters, schemas, responses and security. Generated docs are useful only when they accurately reflect real behavior.", ["Explain core OpenAPI concepts.", "Generate and inspect Steward's schema.", "Detect documentation/runtime drift."], [
    { heading: "Schema as contract evidence", body: "OpenAPI can support client generation, tests and review, but generated output must be checked for meaningful descriptions, status codes and error schemas." },
    { heading: "Document failure, not just success", body: "A service creation endpoint is incomplete if documentation shows only 201 and ignores validation, authorization and conflict responses." },
  ], ["Generate an OpenAPI schema.", "Inspect /services/ request/response schemas.", "Document at least two non-2xx responses.", "Compare generated documentation with a real curl exchange and fix one mismatch."], ["What can OpenAPI describe well?", "Why can generated documentation still be wrong?", "Why should error responses appear in the contract?"], [drfDocs, openApi]),

  richLesson("Configuration and Environments", "Configuration changes behavior across environments without changing application source. Settings, environment variables and secrets need clear ownership, safe defaults and startup validation.", ["Separate code from environment-specific configuration.", "Distinguish configuration from secrets.", "Fail fast on missing critical settings."], [
    { heading: "Twelve-factor idea, applied carefully", body: "Database URLs, allowed hosts, debug flags and external service addresses vary by environment. Secrets should not be committed to source control or printed in logs." },
    { heading: "Unsafe defaults", body: "DEBUG=True, permissive hosts and development credentials are acceptable locally only when the production path makes unsafe configuration difficult to carry forward accidentally." },
  ], ["Move environment-specific values out of source literals.", "Create development-safe defaults.", "Make one production-critical variable required.", "Verify secrets are not logged or committed.", "Document the configuration contract."], ["What is configuration vs a secret?", "Why are permissive development defaults dangerous?", "What should happen when a required production setting is missing?"]),

  richLesson("Application Logging", "Logs are operational evidence. Useful application logs capture events and context that help explain behavior without exposing credentials, tokens or sensitive data. Logging should be designed around diagnostic questions.", ["Use levels intentionally.", "Add contextual fields.", "Avoid sensitive/noisy logging.", "Distinguish expected domain rejection from unexpected failure."], [
    { heading: "Log events, not narration", body: "Prefer 'service_dependency_rejected source=42 target=42 reason=self_reference' over vague lines like 'something went wrong'. Structured context becomes valuable later when Reliability Engineer centralizes telemetry." },
    { heading: "Security boundary", body: "Never log passwords, authorization headers or raw tokens. Be careful with request bodies because service metadata may later contain sensitive organizational details." },
  ], ["Add structured/contextual logging around one successful and one rejected Steward operation.", "Exercise log levels.", "Verify secrets/tokens are absent.", "Use a request/correlation identifier if available.", "Write the diagnostic question each log event answers."], ["What makes a log actionable?", "Why should expected domain rejection not always be ERROR?", "What data must never be logged?"]),

  {
    id: "django-and-api-engineering-lab-steward-api-skeleton",
    title: "Lab: Steward API Skeleton",
    activities: [
      { id: "django-and-api-engineering-lab-steward-api-skeleton-brief", title: "Steward API Skeleton Brief", estimatedMinutes: 20, content: { type: "reading", body: "Turn the API contract from Web and API Foundations into the first real Django/DRF implementation. This lab is an integration checkpoint, not the final Builder milestone.", blocks: [
        { type: "heading", id: "objective", text: "Objective" },
        { type: "paragraph", text: "Produce a coherent Steward API skeleton with meaningful domain boundaries, models, serializers, endpoints, validation, errors, configuration, logging and OpenAPI documentation." },
        { type: "callout", tone: "warning", title: "Do not rush ahead", body: "PostgreSQL depth, JWT authorization and advanced query engineering belong to later Builder modules. Build enough now to create a credible API boundary without prematurely solving everything." },
        { type: "heading", id: "review", text: "What this should prove" },
        { type: "list", items: ["You can explain Django and DRF request flow.", "Your API contract matches the service-registry domain.", "Domain rules are not trapped in views.", "Failure responses are deliberate.", "Documentation and runtime behavior agree."] },
      ] } },
      { id: "django-and-api-engineering-lab-steward-api-skeleton-build", title: "Build Steward API Skeleton", estimatedMinutes: 240, content: { type: "practical", objective: "Implement the first Django/DRF Steward API skeleton from the contract designed in the previous module.", scenario: "Build the same continuing Steward engineering service registry. Do not start a new tutorial application.", instructions: ["Create the Django project/app structure and document the chosen boundaries.", "Implement initial Team, Service and Environment domain data.", "Create serializers with deliberate writable/read-only fields.", "Implement /services/ list/create and detail operations.", "Add lifecycle/criticality filtering and pagination.", "Implement at least one service-dependency rule such as self-reference rejection.", "Define a stable error shape for at least one domain rejection.", "Generate OpenAPI documentation and compare it to real HTTP behavior.", "Move environment-specific settings into configuration.", "Add useful application logging without secrets.", "Use curl/Postman to capture successful and rejected request evidence."], deliverables: ["Runnable Django/DRF Steward API skeleton", "Boundary/design note", "HTTP evidence", "OpenAPI schema/docs", "Configuration notes", "Failure/logging evidence"], completionCriteria: ["The implementation uses the locked Steward domain.", "Django/DRF abstractions can be explained.", "At least one domain rule is reusable outside a single view.", "Errors are deliberate and documented.", "The API is ready for PostgreSQL/data-depth work rather than pretending persistence is finished."] } },
      { id: "django-and-api-engineering-lab-steward-api-skeleton-review", title: "Django/API Module Review", estimatedMinutes: 20, content: { type: "reflection", prompt: "Which Django/DRF abstraction saved useful boilerplate? Which abstraction currently hides too much? Where does Steward domain logic live? What would become difficult to change if you continued without revisiting the current boundaries?" } },
    ],
  },
];
