import type { LearningResource, LessonBlock } from "../activities";
import type { Lesson } from "./lesson";

const djangoDocs: LearningResource = { title: "Django documentation", url: "https://docs.djangoproject.com/en/stable/" };
const drfDocs: LearningResource = { title: "Django REST framework documentation", url: "https://www.django-rest-framework.org/" };
const openApi: LearningResource = { title: "OpenAPI Specification", url: "https://spec.openapis.org/oas/latest.html" };
const djangoRequest: LearningResource = { title:"Django — Request and response objects", url:"https://docs.djangoproject.com/en/stable/ref/request-response/", kind:"reference" };
const djangoApps: LearningResource = { title:"Django — Applications", url:"https://docs.djangoproject.com/en/stable/ref/applications/", kind:"reference" };
const djangoModels: LearningResource = { title:"Django — Models", url:"https://docs.djangoproject.com/en/stable/topics/db/models/", kind:"reference" };
const drfSerializers: LearningResource = { title:"DRF — Serializers", url:"https://www.django-rest-framework.org/api-guide/serializers/", kind:"reference" };
const drfViews: LearningResource = { title:"DRF — Views", url:"https://www.django-rest-framework.org/api-guide/views/", kind:"reference" };
const drfValidation: LearningResource = { title:"DRF — Validators", url:"https://www.django-rest-framework.org/api-guide/validators/", kind:"reference" };
const drfExceptions: LearningResource = { title:"DRF — Exceptions", url:"https://www.django-rest-framework.org/api-guide/exceptions/", kind:"reference" };
const drfFiltering: LearningResource = { title:"DRF — Filtering", url:"https://www.django-rest-framework.org/api-guide/filtering/", kind:"reference" };
const drfPagination: LearningResource = { title:"DRF — Pagination", url:"https://www.django-rest-framework.org/api-guide/pagination/", kind:"reference" };
const djangoSettings: LearningResource = { title:"Django — Settings", url:"https://docs.djangoproject.com/en/stable/topics/settings/", kind:"reference" };
const djangoLogging: LearningResource = { title:"Django — Logging", url:"https://docs.djangoproject.com/en/stable/topics/logging/", kind:"reference" };
const resourcesByDjangoLesson: Record<string, LearningResource[]> = {
 "Django Foundations":[djangoRequest,djangoDocs],"Django REST Framework":[drfDocs],
 "Projects, Applications and Boundaries":[djangoApps],"Models and Domain Data":[djangoModels],
 "Serializers and Representation":[drfSerializers],"Views, ViewSets and Routing":[drfViews],
 "Validation and Business Rules":[drfValidation],"API Error Handling":[drfExceptions],
 "Filtering, Searching and Ordering":[drfFiltering],"Pagination":[drfPagination],
 "API Versioning":[drfDocs],"OpenAPI and Swagger Documentation":[openApi],
 "Configuration and Environments":[djangoSettings],"Application Logging":[djangoLogging],
};

function slug(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }

function richLesson(title: string, introduction: string, outcomes: string[], concepts: Array<{ heading: string; body: string; code?: { language: string; caption: string; value: string } }>, practice: string[], check: string[], resources: LearningResource[] = resourcesByDjangoLesson[title] ?? [djangoDocs, drfDocs]): Lesson {
  const id = `django-and-api-engineering-${slug(title)}`;
  const blocks: LessonBlock[] = [
    { type: "heading", id: "introduction", text: "Introduction" },
    { type: "paragraph", text: introduction },
    { type: "heading", id: "outcomes", text: "Learning outcomes" },
    { type: "list", items: outcomes },
  ];
  for (const concept of concepts) {
    blocks.push({ type: "heading", id: slug(concept.heading), text: concept.heading });
    blocks.push({ type: "paragraph", text: concept.body });
    if (concept.code) blocks.push({ type: "code", language: concept.code.language, caption: concept.code.caption, code: concept.code.value });
  }
  blocks.push({ type: "callout", tone: "steward", title: "Steward connection", body: "Apply this concept to Steward's engineering service registry. Framework features are valuable only when they preserve the domain rules around teams, service ownership, environments, lifecycle, criticality and service dependencies." });
  blocks.push({ type: "heading", id: "assignment", text: "Assignment" });
  blocks.push({ type: "list", ordered: true, items: practice });
  blocks.push({ type: "resources", title: "Required and supporting reading", resources });
  blocks.push({ type: "heading", id: "knowledge-check", text: "Knowledge check" });
  blocks.push({ type: "list", items: check });

  return {
    id,
    title,
    activities: [
      { id: `${id}-concepts`, title: `${title}: Concepts and Mental Model`, estimatedMinutes: 50, content: { type: "reading", body: introduction, blocks } },
      { id: `${id}-practice`, title: `${title}: Engineering Practice`, estimatedMinutes: 55, content: { type: "practical", objective: `Apply ${title} to the evolving Steward API with observable behavior and evidence.`, scenario: "Continue the same Steward codebase. Preserve useful implementation, notes and decisions for later Builder modules.", instructions: practice, deliverables: ["Working Steward implementation or focused experiment", "Evidence note describing behavior, one failure path and one design decision"], completionCriteria: ["The result is demonstrable.", "The implementation is connected to Steward rather than a disposable tutorial domain.", "At least one boundary/failure case is exercised.", "The learner can explain what Django/DRF is doing rather than only copy framework syntax."] } },
      { id: `${id}-check`, title: `${title}: Knowledge Check`, estimatedMinutes: 10, content: { type: "reflection", prompt: check.join("\n\n") } },
    ],
  };
}

export const djangoAndApiRichLessons: Lesson[] = [
  richLesson("Django Foundations", "Django is a web framework with strong conventions around configuration, request handling, persistence and application structure. The goal is not to memorize commands; it is to understand the lifecycle through which an incoming request reaches code, data and a response.", ["Explain the role of settings, URL routing, views, models and middleware.", "Trace a request through a Django project.", "Distinguish framework configuration from domain behavior."], [
    { heading: "Start with one request and one response", body: "Django receives an HTTP request and eventually returns an HTTP response. For a simple endpoint, URL configuration chooses the view function and the view creates the response. This is the smallest useful Django request path; middleware, models and other framework facilities add behavior around it.", code: { language: "python", caption: "Minimal route and view", value: "# urls.py\nfrom django.urls import path\nfrom .views import health\n\nurlpatterns = [path('health/', health)]\n\n# views.py\nfrom django.http import JsonResponse\n\ndef health(request):\n    return JsonResponse({'status': 'ok'})" } },
    { heading: "Project lifecycle", body: "Now expand that path: the project configures the process; middleware can act around request handling; URL configuration resolves the route to a view; the view can call application/model code; and the returned response travels back through middleware. Applications package coherent functionality inside that process." },
    { heading: "Framework boundary", body: "Django should host Steward's domain behavior, not redefine it accidentally. A framework-aware view can translate HTTP input into application operations while core rules remain explicit and testable." },
    { heading: "What startproject and startapp actually create", body: "A typical project package contains settings.py, urls.py, asgi.py and wsgi.py; manage.py is a command-line entry point that points Django at the project's settings. startapp creates an application package with conventional modules such as apps.py, models.py, views.py, migrations and tests. Generated structure is scaffolding, not architecture: you still decide responsibilities and boundaries." },
    { heading: "Settings and application registry", body: "DJANGO_SETTINGS_MODULE identifies the settings module used to configure Django. INSTALLED_APPS tells Django which application configurations participate in startup, model discovery, migrations and other framework facilities. AppConfig represents application metadata/startup configuration; avoid putting arbitrary business work in startup hooks." },
    { heading: "URL resolution is ordered matching", body: "Django evaluates URL patterns and delegates through include() until one pattern matches. Path converters such as <int:id> parse route segments before calling the view. Route order can matter when patterns overlap, so URLs are executable dispatch configuration rather than documentation alone.", code: { language: "python", caption: "Project routes delegate to an application", value: "# project/urls.py\nfrom django.urls import include, path\n\nurlpatterns = [\n    path('api/', include('registry.urls')),\n]\n\n# registry/urls.py\nurlpatterns = [\n    path('services/<int:service_id>/', service_detail),\n]" } },
    { heading: "Middleware wraps the request/response cycle", body: "Middleware is an ordered chain around views. Request processing travels inward through configured middleware; the response travels back outward. Authentication/session, security, correlation and other cross-cutting behavior may live here, but ordering dependencies matter. A middleware can also short-circuit and return a response before the view runs." },
    { heading: "HttpRequest and HttpResponse are the framework boundary", body: "Django builds an HttpRequest containing method, path, headers, query data, body and middleware-added state. A view returns an HttpResponse or subclass. This is the Django representation of the HTTP exchange you already studied; the framework does not change HTTP semantics." },
  ], ["Create a fresh Django project inside the Steward repository.", "Add one app for the initial service-registry capability.", "Trace a request from URL to response.", "Record which files configure infrastructure and which should hold domain behavior."], ["What is the difference between a Django project and app?", "Where does URL resolution happen?", "Why should domain rules not be scattered across settings and views?"]),

  richLesson("Django REST Framework", "Django REST Framework adds API-oriented abstractions such as Request/Response, serializers, authentication hooks, permissions, generic views and viewsets. These abstractions reduce plumbing, but they do not decide your API contract or business rules for you.", ["Explain what DRF adds on top of Django.", "Describe serializer/view/permission responsibilities.", "Return a JSON response through DRF."], [
    { heading: "DRF still receives a request and returns a response", body: "The basic HTTP/Django model does not disappear. DRF adds API-focused processing around it. In the smallest example, the decorator turns the Django view into a DRF-managed API view, DRF provides its Request object, and Response holds data that a renderer can turn into the negotiated response representation.", code: { language: "python", caption: "Simple DRF endpoint", value: "from rest_framework.decorators import api_view\nfrom rest_framework.response import Response\n\n@api_view(['GET'])\ndef service_health(request):\n    return Response({'service': 'steward', 'status': 'ok'})" } },
    { heading: "API request lifecycle", body: "For a managed API view, DRF performs steps such as request wrapping/parsing, authentication, permission checks and content negotiation before or around your handler, then renders the returned Response. Understanding that sequence matters when diagnosing whether rejection happened during parsing, authentication, authorization, validation or application behavior." },
    { heading: "Abstractions have costs", body: "ViewSets and generic views can remove repetition. They can also hide behavior when used before the developer understands routing, serialization and authorization. Prefer the highest-level abstraction whose behavior you can still explain." },
    { heading: "DRF Request and Response add API semantics", body: "DRF's Request wraps Django's HttpRequest and exposes parsed request.data while retaining access to method, query_params and underlying request information. DRF Response carries unrendered Python data plus status/headers; the selected renderer later turns that data into bytes for the HTTP response." },
    { heading: "Parsers consume Content-Type; renderers negotiate Accept", body: "A parser is selected from the request representation, commonly Content-Type: application/json. A renderer is selected through content negotiation using the client's Accept header and configured renderers. These are separate directions: what the client sent versus what response representation it can receive." },
    { heading: "Authentication, permissions and throttling are distinct gates", body: "Authentication establishes request identity/credentials. Permissions decide whether that request may perform an operation. Throttling limits request rates according to policy but is not an authorization mechanism. Keep these concepts separate even when DRF executes them in a common view lifecycle." },
    { heading: "APIException becomes deliberate HTTP failure", body: "DRF catches recognized API exceptions and translates them through its exception handler into Response objects. Unexpected exceptions should still surface as server failures and operator evidence; do not convert every Python exception into a generic 400." },
  ], ["Install/configure DRF.", "Create one GET endpoint with DRF.", "Inspect Request and Response behavior.", "Compare the DRF endpoint with a plain Django JsonResponse endpoint."], ["What does DRF add beyond Django?", "Why is a serializer not the same thing as a model?", "What can be hidden by prematurely using ViewSets?"]),

  richLesson("Projects, Applications and Boundaries", "Django apps are packaging units, not automatically correct architectural boundaries. Steward needs boundaries derived from cohesion and domain responsibility rather than one app per database table.", ["Evaluate candidate Django app boundaries.", "Recognize low-cohesion and cyclic dependencies.", "Keep deployment configuration separate from domain modules."], [
    { heading: "Boundary by responsibility", body: "A service-registry capability may contain Services, Teams, Environments and dependencies because their behaviors change together. Splitting every model into its own app can create more coupling, not less." },
    { heading: "Dependency direction", body: "Prefer dependencies toward stable domain concepts. Avoid having every app import every other app's models, signals and utilities without an explicit contract." },
  ], ["Sketch 2–3 possible app structures for Steward.", "Choose one and document cohesion/coupling trade-offs.", "Create the initial apps without circular imports.", "Record what evidence would justify splitting them later."], ["Why is one Django app per model usually weak architecture?", "What is a circular dependency telling you?", "When should a boundary be revisited?"]),

  richLesson("Models and Domain Data", "Django models map Python objects to relational persistence, but database-shaped code should still reflect domain meaning. Fields, constraints, relationships and lifecycle values are part of Steward's behavior contract.", ["Model Steward concepts with appropriate fields and relationships.", "Distinguish database constraints from application validation.", "Use enums/choices deliberately."], [
    { heading: "Model the language of the domain", body: "Service, Team and Environment names should make the code read like the service-registry problem rather than generic Record/Item structures.", code: { language: "python", caption: "Initial Steward model", value: "from django.db import models\n\nclass Service(models.Model):\n    class Lifecycle(models.TextChoices):\n        DEVELOPMENT = 'development'\n        PRODUCTION = 'production'\n        RETIRED = 'retired'\n\n    name = models.CharField(max_length=120)\n    slug = models.SlugField(unique=True)\n    lifecycle = models.CharField(max_length=20, choices=Lifecycle.choices)" } },
    { heading: "Model classes map to relational structure", body: "A Django model class describes persistent fields and relationships at the Python layer. Instances represent rows conceptually; ForeignKey represents a relational reference rather than an embedded Python object. This layer should map the PostgreSQL facts you already designed rather than silently invent a different data model." },
    { heading: "Migrations version schema changes", body: "Changing a model class does not directly rewrite the database. makemigrations derives a versioned migration from model-state changes; migrate applies pending migration operations. Always inspect generated migrations because the framework cannot know your production data, locking tolerance or compatibility requirements." },
    { heading: "Managers and QuerySets describe database work", body: "`Service.objects` is a model manager. Calls such as `filter()` produce `QuerySet`s: lazy descriptions of database queries that are generally executed when their results are consumed. This is why ORM fluency still requires SQL literacy—you should be able to inspect the generated query and reason about when database work happens.", code: { language: "python", caption: "Create, retrieve and inspect a QuerySet", value: "service = Service.objects.create(\n    name='Payments API',\n    slug='payments-api',\n    lifecycle=Service.Lifecycle.PRODUCTION,\n)\n\nqs = Service.objects.filter(lifecycle=Service.Lifecycle.PRODUCTION)\nprint(qs.query)       # inspect the SQL description\nfor service in qs:   # evaluation performs database work\n    print(service.slug)" } },
    { heading: "Persistence is not all validation", body: "A unique slug belongs naturally in the database. A rule such as 'retired services cannot accept new dependencies' may require application/domain logic because it spans state and operation semantics." },
    { heading: "Field classes map Python values to database representation", body: "CharField, BooleanField, DateTimeField, ForeignKey and other fields define conversion, validation metadata and schema intent. null controls database NULL for most fields; blank is primarily a validation/form concern. They are not interchangeable. Defaults may be values or callables and should represent legitimate domain defaults." },
    { heading: "Relationships have direction and deletion semantics", body: "ForeignKey models many-to-one and requires an on_delete policy such as PROTECT/RESTRICT/CASCADE/SET_NULL. OneToOneField models a unique single-valued relation. ManyToManyField uses an intermediary relation and is appropriate only when the relationship itself does not need richer domain fields—or an explicit through model can represent those fields." },
    { heading: "Meta carries model-level database intent", body: "Model Meta can declare constraints, indexes and default ordering. Prefer UniqueConstraint/CheckConstraint for durable invariants rather than relying only on serializer validation. Remember that default ordering affects every unqualified QuerySet and can add hidden sort cost." },
  ], ["Implement Team, Service and Environment models.", "Add at least one database-enforced constraint.", "Represent lifecycle/criticality deliberately.", "Document one rule that should not live only as a database field constraint."], ["What kinds of invariants belong in the database?", "Why are choices useful but insufficient for all domain rules?", "How can model names improve architectural clarity?"]),

  richLesson("ORM Query Behavior and Performance", "The ORM is a query-building interface over the relational model you already learned. Productive Django engineering means using that interface without losing sight of SQL execution, round trips or relationship cardinality.", ["Inspect generated SQL and QuerySet evaluation.", "Choose select_related versus prefetch_related from relationship shape.", "Detect and remove N+1 query patterns.", "Choose ORM versus parameterized SQL deliberately."], [
    { heading: "QuerySets are lazy descriptions", body: "Chaining filter(), exclude(), order_by() and relationship-loading methods normally builds a query description. Iteration, serialization and other evaluation operations cause database work. Inspect qs.query and query logs while learning so convenience stays connected to PostgreSQL behavior." },
    { heading: "N+1 is a round-trip pattern", body: "If one query loads 100 services and later access to service.owner_team causes another query for every service, the endpoint performs roughly 101 queries. Tiny development datasets can hide this. Measure query count instead of assuming the ORM optimized it." },
    { heading: "Load relationships intentionally", body: "`select_related` uses SQL joins for single-valued relationships such as ForeignKey/OneToOne. `prefetch_related` uses additional bounded queries and assembles multi-valued relationships in Python. Choose from cardinality and access pattern, then verify the generated behavior.", code: { language: "python", caption: "Bound query growth for service ownership", value: "qs = (\n    Service.objects\n    .filter(lifecycle='production')\n    .select_related('owner_team')\n)\n\nfor service in qs:\n    print(service.slug, service.owner_team.name)" } },
    { heading: "ORM versus SQL is a design choice", body: "Routine model operations are usually clearer in the ORM. Complex reporting, PostgreSQL-specific capabilities or carefully tuned access paths may be clearer in parameterized SQL. Do not switch to raw SQL merely because ORM syntax is unfamiliar, and never interpolate untrusted values into SQL strings." },
    { heading: "Evaluation and QuerySet caching are related but not identical", body: "Iteration, list(), len(), bool(), slicing in some forms and serialization can evaluate a QuerySet. Once a QuerySet has fetched its result set, normal reuse of that same QuerySet can use its result cache; creating another equivalent QuerySet is still another query. Methods such as iterator() deliberately change caching behavior. Measure rather than assuming a Python variable means one database call." },
    { heading: "get, first, exists and count express different database questions", body: "get() expects exactly one row and raises model-specific DoesNotExist/MultipleObjectsReturned when that contract fails. first() asks for at most one ordered result. exists() asks whether any matching row exists without materializing the full result set. count() delegates a count query rather than loading every object merely to count in Python." },
    { heading: "Transactions remain PostgreSQL transactions", body: "django.db.transaction.atomic() defines an application-visible transaction boundary; nested atomic blocks can use savepoints. Do not hold transactions open across slow network work. Database constraints/isolation still determine correctness—the ORM does not create a separate transactional universe." },
  ], ["Implement a service query with a relationship.", "Inspect its generated SQL and record when evaluation occurs.", "Create an N+1 case intentionally and capture query count.", "Fix it using select_related or prefetch_related and compare counts.", "Implement one non-trivial query in both ORM and parameterized SQL and justify which representation you would keep."], ["What does QuerySet laziness mean operationally?", "Why is N+1 a scaling pattern rather than merely one slow query?", "When should select_related be preferred to prefetch_related?", "When can raw SQL be clearer than ORM code?"]),

  richLesson("Schema Evolution with Django Migrations", "Django migrations are versioned database changes, not merely generated files to commit. The PostgreSQL schema work from the previous module established why existing data, constraints, locks and compatibility matter; Django now provides a framework mechanism for sequencing those changes.", ["Explain model state versus database state.", "Review generated migration operations.", "Plan a required-field change against populated data.", "Use expand-and-contract sequencing when compatibility requires it."], [
    { heading: "Generation is not proof of safety", body: "makemigrations compares model state and writes migration operations. migrate executes unapplied operations. A generated migration can still fail on existing rows, create long locks or break an older application version, so read it before execution." },
    { heading: "Existing rows constrain schema evolution", body: "Adding a required field to an already populated Service table may need stages: introduce nullable/new structure, deploy compatible code, backfill valid data, enforce the final constraint, and only later remove obsolete structure." },
    { heading: "Expand before contract", body: "Compatibility-sensitive changes often become safer when the database temporarily supports old and new application behavior. Expansion adds compatible structure first; migration/backfill and application rollout follow; contraction removes the old structure only after it is no longer needed." },
  ], ["Seed existing Steward services.", "Add a field that ultimately must be required.", "Inspect the generated migration.", "Implement the change in safe stages rather than assuming an empty database.", "Verify old data remains valid and document forward/rollback compatibility."], ["Why can makemigrations succeed while a production migration is unsafe?", "Why are existing rows part of schema design?", "What problem does expand-and-contract solve?"]),

  richLesson("Serializers and Representation", "Serializers sit at the representation boundary. They parse untrusted external data, validate it, translate it into application/model values and render responses. This is where the Python boundary reasoning from earlier lessons becomes concrete.", ["Explain serialization vs validation.", "Separate representation errors from domain errors.", "Control fields exposed by the API."], [
    { heading: "Input is representation", body: "A JSON string 'production' becomes a domain lifecycle only after parsing and validation. Serializers should not silently accept fields that clients must never control.", code: { language: "python", caption: "Service serializer", value: "from rest_framework import serializers\nfrom .models import Service\n\nclass ServiceSerializer(serializers.ModelSerializer):\n    class Meta:\n        model = Service\n        fields = ['id', 'name', 'slug', 'lifecycle', 'criticality', 'owner_team']\n        read_only_fields = ['id']" } },
    { heading: "Validation layers", body: "Field validation handles local shape/range rules. Object validation handles relationships among fields. Domain/application services should own rules that are broader than the representation itself." },
    { heading: "The serializer lifecycle has distinct phases", body: "Instantiate with data=... for input, call is_valid(), inspect validated_data, then create/update through save() when appropriate. For output, serializers transform instances into primitive representation exposed through .data. initial_data, validated_data and data are different stages; confusing them hides whether input has actually been validated." },
    { heading: "Field and object hooks solve different validation scopes", body: "validate_<field>() handles one field after field parsing; validate(attrs) handles relationships among fields. Serializer create()/update() control persistence mapping when defaults are insufficient. None of these hooks should become a dumping ground for reusable domain operations merely because they are convenient." },
    { heading: "Partial updates change required-field behavior", body: "A serializer instantiated with partial=True can validate a PATCH-like subset without requiring every normally required field. That does not mean omitted values become NULL or reset; the update contract must preserve the distinction between absent and explicitly supplied values." },
  ], ["Create a Service serializer.", "Reject an unsupported lifecycle.", "Make at least one server-controlled field read-only.", "Add one cross-field validation rule and explain whether it truly belongs in the serializer."], ["What is the difference between parsing and domain validation?", "Why should not every model field automatically be writable?", "When does serializer validation become misplaced business logic?"]),

  richLesson("Views, ViewSets and Routing", "Views coordinate HTTP concerns: method, authentication/authorization hooks, parsing, application calls and response translation. Routers and ViewSets can make CRUD-style APIs concise, but explicitness matters when behavior diverges from generic CRUD.", ["Choose between function views, APIView, generic views and ViewSets.", "Explain router-generated routes.", "Keep orchestration thin."], [
    { heading: "Thin orchestration", body: "A good endpoint makes the HTTP/application boundary visible. It should not accumulate persistence queries, business rules, logging, authorization and response formatting in one giant method." },
    { heading: "ViewSet example", body: "For straightforward collection/resource operations, a ModelViewSet can be appropriate when permissions and domain rules remain explicit.", code: { language: "python", caption: "Service ViewSet", value: "from rest_framework.viewsets import ModelViewSet\n\nclass ServiceViewSet(ModelViewSet):\n    queryset = Service.objects.all()\n    serializer_class = ServiceSerializer" } },
    { heading: "Choose from an abstraction ladder", body: "@api_view/function views expose mechanics directly. APIView provides class-based dispatch and DRF policy hooks. GenericAPIView plus mixins add queryset/serializer conventions for common operations. Concrete generics combine those mixins. ViewSets group related actions and routers can generate URL patterns. Moving upward reduces boilerplate but increases convention; learn what each layer supplies before inheriting it." },
    { heading: "Routers map actions to URLs", body: "A DRF router registers a ViewSet and generates collection/detail routes plus named URL patterns. list/create normally belong to the collection; retrieve/update/partial_update/destroy to a detail resource. @action can add genuine non-CRUD operations, but each custom route becomes public contract surface." },
    { heading: "Method semantics still come from HTTP", body: "Framework mixins do not redefine POST/GET/PUT/PATCH/DELETE semantics. In particular, PATCH should represent partial modification while PUT is ordinarily a complete replacement contract. If your API intentionally deviates, document it rather than inheriting accidental framework behavior." },
  ], ["Implement `/services/` list/create and /services/{id}/ retrieve/update.", "Inspect generated routes.", "Add a custom operation only if it represents a real Steward behavior.", "Document why your chosen view abstraction is appropriate."], ["When is a ViewSet a good fit?", "Why should views remain thin?", "What is the downside of inventing action endpoints for ordinary resource updates?"]),

  richLesson("Validation and Business Rules", "Validation asks whether input can be accepted; business rules ask whether an operation is allowed in the current domain state. Steward needs both. Conflating them makes rules difficult to reuse and test.", ["Separate syntactic/representation validation from domain rules.", "Place rules where all callers can rely on them.", "Return deliberate errors for rejected operations."], [
    { heading: "Rule location", body: "A self-dependency should be rejected whether the operation comes through REST, an admin command or a future background process. That argues for a reusable application/domain rule rather than a view-only check." },
    { heading: "Example invariant", body: "ServiceDependency creation should reject source == target and duplicate source/target pairs. Database constraints can reinforce the rule, while application code returns a useful explanation." },
    { heading: "Validation can occur at several boundaries", body: "Django model field validation, model clean(), database constraints, DRF field/object validators and application/domain operations have different callers and guarantees. Model save() does not automatically call full_clean(), so do not assume a model method silently enforces every validation hook." },
    { heading: "Race-sensitive invariants need database arbitration", body: "A serializer can check that a slug appears unused and still lose a race to another request. Keep the database uniqueness constraint and translate its conflict deliberately where concurrent writers can collide. Pre-checks improve messages; constraints provide the shared guarantee." },
  ], ["Implement self-dependency rejection.", "Add duplicate-dependency protection.", "Exercise rules outside the HTTP happy path.", "Document which rules are reinforced by database constraints."], ["What is the difference between malformed input and a forbidden domain transition?", "Why duplicate critical rules at both application and database layers sometimes?", "How do you avoid view-only business logic?"]),

  richLesson("API Error Handling", "An API error is part of the contract. Clients need stable status semantics and a useful machine-readable body; operators need enough internal evidence to diagnose failures without leaking sensitive implementation detail.", ["Distinguish client, authorization, not-found, conflict and server failures.", "Design a stable error body.", "Avoid leaking stack traces or database internals."], [
    { heading: "Stable error shape", body: "Clients should not parse arbitrary framework strings. Define a predictable structure for code/message/details and preserve correlation data separately where useful.", code: { language: "json", caption: "Example domain error", value: "{\n  \"code\": \"service_dependency_self_reference\",\n  \"message\": \"A service cannot depend on itself.\",\n  \"details\": {\"target_service\": 42}\n}" } },
    { heading: "Do not confuse 4xx and 5xx", body: "A rejected client operation should not become 500 merely because Python raised an exception. Conversely, an unexpected database failure should not be disguised as validation error." },
    { heading: "Central exception translation keeps the contract consistent", body: "DRF's exception handler is an appropriate boundary for normalizing known API/application exceptions into the agreed envelope. Preserve status, stable machine code, field/details and request identifier deliberately. Do not catch BaseException/Exception around entire views merely to force one shape; that can erase programming defects and operational signals." },
    { heading: "Validation errors can contain multiple field problems", body: "DRF validation errors may naturally contain field-keyed lists or nested structures. If Steward exposes a custom envelope, define how these details are represented so clients can handle more than the first failure without parsing human text." },
  ], ["Define a Steward error shape.", "Map at least four failure scenarios to appropriate status codes.", "Trigger an unexpected exception locally and verify the client does not receive sensitive internals.", "Record the operator-side evidence needed for diagnosis."], ["Why is a stable error code useful?", "When is 409 more appropriate than 400?", "Why should unexpected exceptions remain distinguishable from client errors?"]),

  richLesson("Filtering, Searching and Ordering", "Collection endpoints become useful when clients can ask domain questions without downloading everything. Query parameters should reflect supported use cases and be bounded to avoid accidental performance and data-exposure problems.", ["Implement explicit filters/search/order fields.", "Distinguish exact filtering from free-text search.", "Consider query cost and information exposure."], [
    { heading: "Service-registry questions", body: "Steward should naturally answer: production services, high-criticality services, services owned by a team, or services depending on another service." },
    { heading: "Bound the interface", body: "Do not expose arbitrary model-field ordering/search simply because the framework makes it easy. Public query capabilities are part of the API contract." },
    { heading: "Filtering usually narrows structured fields", body: "A filter backend translates supported query parameters into QuerySet predicates. Exact lifecycle/team filters are different from free-text search. If using django-filter, FilterSet can make the supported fields/operators explicit instead of exposing arbitrary model lookups." },
    { heading: "SearchFilter and OrderingFilter publish conventions", body: "DRF SearchFilter commonly uses a search query parameter over declared search_fields; OrderingFilter uses ordering over declared ordering_fields. Prefix/descending conventions and supported fields become client contract. Inspect generated SQL because convenient contains/search expressions and sorts can become expensive at scale." },
    { heading: "Never pass arbitrary query parameter names into ORM lookup construction", body: "Building filter(**request.query_params) or dynamic order_by directly from untrusted parameter names can expose fields/relationships and expensive operations you never intended. Map public parameters to an allowlisted internal query shape." },
  ], ["Add lifecycle and criticality filters.", "Add owner-team filtering.", "Add a limited search over service name/slug.", "Allow ordering only on deliberate fields.", "Inspect at least one generated SQL query."], ["What is the difference between filtering and searching?", "Why can unrestricted ordering/search create performance risk?", "How does a query parameter become part of compatibility obligations?"]),

  richLesson("Pagination", "Pagination is an API behavior and a performance boundary. It limits response size, changes client navigation and creates consistency questions when underlying data changes between page requests.", ["Explain offset/page vs cursor approaches conceptually.", "Configure bounded pagination.", "Recognize unstable ordering risks."], [
    { heading: "Always define ordering", body: "Pagination without deterministic ordering can return duplicates or skip records across requests. Choose an ordering consistent with the collection semantics." },
    { heading: "Contract implications", body: "Page size, next/previous links and maximum limits affect clients and infrastructure. They should be deliberate rather than framework defaults nobody owns." },
    { heading: "Page-number pagination is simple and user-visible", body: "PageNumberPagination exposes numbered pages and typically relies on LIMIT/OFFSET underneath. It is easy for humans/clients to understand and can expose total counts, but changing data between requests can shift rows and large offsets may become costly." },
    { heading: "Limit/offset exposes the database-style window directly", body: "LimitOffsetPagination lets clients request a limit and offset subject to configured bounds. It is flexible for integrations but inherits offset consistency/performance trade-offs and requires a maximum limit to prevent unbounded responses." },
    { heading: "Cursor pagination trades random access for stable traversal", body: "CursorPagination uses an opaque cursor tied to an ordering. With a suitable unique/stable ordering it can reduce duplicate/skip behavior as rows are inserted while traversing and avoids large offsets, but clients cannot treat the cursor as a page number or invent arbitrary positions." },
  ], ["Enable pagination for /services/.", "Set a sensible default and maximum page size.", "Verify deterministic ordering.", "Test empty, single-page and multi-page collections."], ["Why does pagination require deterministic ordering?", "What problem does a maximum page size solve?", "When might cursor pagination be preferable?"]),

  richLesson("API Versioning", "Versioning is a compatibility strategy, not a substitute for careful evolution. Most changes should first be classified as additive, compatible, behavior-changing or breaking before choosing a version mechanism.", ["Classify API changes by compatibility impact.", "Explain URI/header/media-type versioning trade-offs.", "Prefer evolutionary compatibility where possible."], [
    { heading: "Not every change needs v2", body: "Adding an optional response field can often be compatible. Renaming lifecycle values or changing authorization semantics can break clients even if the URL version is unchanged." },
    { heading: "Versioning creates support obligations", body: "Once multiple versions exist, teams must decide ownership, deprecation timelines, documentation and testing. Versioning has ongoing cost." },
    { heading: "DRF can expose versions through different schemes", body: "DRF supports approaches such as URL path/namespace, hostname and Accept-header versioning. request.version can then influence behavior. That mechanism only selects a version; it does not solve data migration, client communication, duplicate test coverage or deprecation." },
    { heading: "Compatibility is broader than JSON field shape", body: "Status codes, authorization behavior, defaults, ordering, pagination, error codes and timing/retry semantics can all affect consumers. Treat an API contract as observable behavior, not only a serializer schema." },
  ], ["Classify ten hypothetical Steward API changes.", "Choose a versioning strategy for Steward and justify it.", "Write a deprecation note for one breaking change.", "Identify a change you would redesign to avoid creating v2."], ["What makes an API change breaking?", "Why is versioning not free?", "What is the difference between API version and application release version?"]),

  richLesson("OpenAPI and Swagger Documentation", "An API contract should be inspectable by humans and tools. OpenAPI describes operations, parameters, schemas, responses and security. Generated docs are useful only when they accurately reflect real behavior.", ["Explain core OpenAPI concepts.", "Generate and inspect Steward's schema.", "Detect documentation/runtime drift."], [
    { heading: "Schema as contract evidence", body: "OpenAPI can support client generation, tests and review, but generated output must be checked for meaningful descriptions, status codes and error schemas." },
    { heading: "Document failure, not just success", body: "A service creation endpoint is incomplete if documentation shows only 201 and ignores validation, authorization and conflict responses." },
    { heading: "OpenAPI has a reusable document structure", body: "At a high level, paths contain operations such as GET/POST; operations describe parameters/requestBody/responses/security; components/schemas hold reusable representations; securitySchemes describe authentication mechanisms. $ref links reusable components so one schema can be referenced consistently across operations." },
    { heading: "Swagger UI is a consumer of the schema", body: "OpenAPI is the machine-readable contract format; Swagger UI is one interactive presentation/tooling surface. A polished UI does not prove the schema is correct. Compare generated schema with runtime requests and tests." },
    { heading: "Generated schemas need explicit help for domain behavior", body: "Framework introspection can infer serializer fields and ordinary routes, but it may not infer custom error envelopes, conditional rules, examples, auth semantics or domain-specific descriptions correctly. Treat annotations/schema customization as maintained code and test important contract elements." },
  ], ["Generate an OpenAPI schema.", "Inspect /services/ request/response schemas.", "Document at least two non-2xx responses.", "Compare generated documentation with a real curl exchange and fix one mismatch."], ["What can OpenAPI describe well?", "Why can generated documentation still be wrong?", "Why should error responses appear in the contract?"], [drfDocs, openApi]),

  richLesson("Configuration and Environments", "Configuration changes behavior across environments without changing application source. Settings, environment variables and secrets need clear ownership, safe defaults and startup validation.", ["Separate code from environment-specific configuration.", "Distinguish configuration from secrets.", "Fail fast on missing critical settings."], [
    { heading: "Twelve-factor idea, applied carefully", body: "Database URLs, allowed hosts, debug flags and external service addresses vary by environment. Secrets should not be committed to source control or printed in logs." },
    { heading: "Unsafe defaults", body: "DEBUG=True, permissive hosts and development credentials are acceptable locally only when the production path makes unsafe configuration difficult to carry forward accidentally." },
    { heading: "Django settings are Python configuration loaded at process startup", body: "Settings can import environment values and compose configuration, but application modules should not mutate global settings at runtime. Access settings through django.conf.settings where needed and keep parsing/validation centralized so malformed booleans, URLs or required values fail predictably." },
    { heading: "ALLOWED_HOSTS, DEBUG and SECRET_KEY have different security roles", body: "DEBUG controls detailed error behavior and must be false in production-like environments. ALLOWED_HOSTS constrains accepted Host headers. SECRET_KEY participates in cryptographic signing and must be unpredictable/private. Do not treat them as interchangeable 'production settings' or give them the same fallback policy." },
  ], ["Move environment-specific values out of source literals.", "Create development-safe defaults.", "Make one production-critical variable required.", "Verify secrets are not logged or committed.", "Document the configuration contract."], ["What is configuration vs a secret?", "Why are permissive development defaults dangerous?", "What should happen when a required production setting is missing?"]),

  richLesson("Application Logging", "Logs are operational evidence. Useful application logs capture events and context that help explain behavior without exposing credentials, tokens or sensitive data. Logging should be designed around diagnostic questions.", ["Use levels intentionally.", "Add contextual fields.", "Avoid sensitive/noisy logging.", "Distinguish expected domain rejection from unexpected failure."], [
    { heading: "Log events, not narration", body: "Prefer 'service_dependency_rejected source=42 target=42 reason=self_reference' over vague lines like 'something went wrong'. Structured context becomes valuable later when Reliability Engineer centralizes telemetry." },
    { heading: "Security boundary", body: "Never log passwords, authorization headers or raw tokens. Be careful with request bodies because service metadata may later contain sensitive organizational details." },
    { heading: "Django uses Python's logging hierarchy", body: "Loggers are named channels, handlers decide destinations, formatters shape records and levels filter severity. Django's LOGGING setting configures this standard logging system. Prefer module/domain logger names and structured context over print() or one global undifferentiated logger." },
    { heading: "Logger and handler levels both affect emission", body: "A record must pass the effective logger level and relevant handler/filter rules before it is emitted. Propagation can send records to ancestor loggers and accidentally duplicate output when handlers are attached at multiple levels. When a log 'disappears' or appears twice, inspect the hierarchy/configuration before changing application logic." },
    { heading: "Exceptions need traceback evidence at the right boundary", body: "logger.exception inside an exception handler records traceback context for an unexpected failure. Do not attach tracebacks to ordinary validation/domain rejections merely to make logs look detailed; severity and evidence should match operational meaning." },
  ], ["Add structured/contextual logging around one successful and one rejected Steward operation.", "Exercise log levels.", "Verify secrets/tokens are absent.", "Use a request/correlation identifier if available.", "Write the diagnostic question each log event answers."], ["What makes a log actionable?", "Why should expected domain rejection not always be ERROR?", "What data must never be logged?"]),

  {
    id: "django-and-api-engineering-lab-steward-api-skeleton",
    title: "Lab: Steward API Skeleton",
    activities: [
      { id: "django-and-api-engineering-lab-steward-api-skeleton-brief", title: "Steward API Skeleton Brief", estimatedMinutes: 20, content: { type: "reading", body: "Turn the API contract from Web and API Foundations and the PostgreSQL model from Relational Data and PostgreSQL into the first integrated Django/DRF implementation. This lab is an integration checkpoint, not the final Builder milestone.", blocks: [
        { type: "heading", id: "objective", text: "Objective" },
        { type: "paragraph", text: "Produce a coherent Steward API skeleton that deliberately maps the already-understood PostgreSQL domain into Django models, then exposes it through serializers, endpoints, validation, errors, configuration, logging and OpenAPI documentation." },
        { type: "callout", tone: "warning", title: "Do not rush ahead", body: "PostgreSQL fundamentals and query engineering were established in the previous Builder module. Reuse that model rather than redesigning it through ORM convenience. JWT authorization belongs to the following identity module; do not rush into it here." },
        { type: "heading", id: "review", text: "What this should prove" },
        { type: "list", items: ["You can explain Django and DRF request flow.", "Your API contract matches the service-registry domain.", "Domain rules are not trapped in views.", "Failure responses are deliberate.", "Documentation and runtime behavior agree."] },
      ] } },
      { id: "django-and-api-engineering-lab-steward-api-skeleton-build", title: "Build Steward API Skeleton", estimatedMinutes: 240, content: { type: "practical", objective: "Integrate the previously designed HTTP contract and PostgreSQL data model into the first Django/DRF Steward API skeleton.", scenario: "Build the same continuing Steward engineering service registry. Do not start a new tutorial application.", instructions: ["Create the Django project/app structure and document the chosen boundaries.", "Map the existing PostgreSQL Team, Service, Environment, ServiceDependency and ServiceReview design into Django models without weakening its constraints.", "Create/apply reviewed migrations against representative existing data.", "Create serializers with deliberate writable/read-only fields.", "Implement `/services/` list/create and detail operations, plus the smallest ServiceReview create/list behavior needed to preserve the review history already modeled in PostgreSQL.", "Add lifecycle/criticality filtering and pagination.", "Inspect generated SQL for representative endpoints and demonstrate that relationship loading does not introduce an N+1 query pattern.", "Implement at least one service-dependency rule such as self-reference rejection.", "Define a stable error shape for at least one domain rejection.", "Generate OpenAPI documentation and compare it to real HTTP behavior.", "Move environment-specific settings into configuration.", "Add useful application logging without secrets.", "Use curl/Postman to capture successful and rejected request evidence."], deliverables: ["Runnable Django/DRF Steward API skeleton", "ServiceReview API evidence", "Boundary/design note", "HTTP evidence", "OpenAPI schema/docs", "Configuration notes", "Failure/logging evidence"], completionCriteria: ["The implementation uses the locked Steward domain.", "Django/DRF abstractions can be explained.", "At least one domain rule is reusable outside a single view.", "Errors are deliberate and documented.", "The API preserves the PostgreSQL invariants established previously and is ready for the following identity/authorization module."] } },
      { id: "django-and-api-engineering-lab-steward-api-skeleton-review", title: "Django/API Module Review", estimatedMinutes: 20, content: { type: "reflection", prompt: "Which Django/DRF abstraction saved useful boilerplate? Which abstraction currently hides too much? Where does Steward domain logic live? What would become difficult to change if you continued without revisiting the current boundaries?" } },
    ],
  },
];
