import type { LearningResource } from "../activities";
import type { Lesson } from "./lesson";

const pythonTutorial: LearningResource = { title: "Python Tutorial", url: "https://docs.python.org/3/tutorial/" };
const pythonReference: LearningResource = { title: "Python Language Reference", url: "https://docs.python.org/3/reference/" };
const typingDocs: LearningResource = { title: "Python typing documentation", url: "https://docs.python.org/3/library/typing.html" };
const venvDocs: LearningResource = { title: "Python venv documentation", url: "https://docs.python.org/3/library/venv.html" };
const packagingGuide: LearningResource = { title: "Python Packaging User Guide", url: "https://packaging.python.org/en/latest/" };

function slug(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }

function deepLesson(title: string, body: string, objective: string, instructions: string[], reflection: string, resources: LearningResource[] = [pythonTutorial]): Lesson {
    const id = `programming-with-python-${slug(title)}`;
    return { id, title, activities: [
        { id: `${id}-concepts`, title: `${title}: Concepts and Mental Model`, estimatedMinutes: 30, content: { type: "reading", body, resources } },
        { id: `${id}-practice`, title: `${title}: Engineering Practice`, estimatedMinutes: 45, content: { type: "practical", objective, scenario: "Work in a small Python workspace that gradually becomes the domain/service core for Steward API. Keep useful code, notes and experiments instead of treating each lesson as a disposable syntax puzzle.", instructions, deliverables: ["Working Python evidence", "Short engineering note explaining behavior and one edge case"], completionCriteria: ["The result runs and can be demonstrated.", "The learner can explain the language behavior used rather than only reproduce syntax.", "At least one failure, boundary or alternative is investigated."] } },
        { id: `${id}-check`, title: `${title}: Knowledge Check`, estimatedMinutes: 10, content: { type: "reflection", prompt: reflection } },
    ] };
}

export const programmingWithPythonDeepLessons: Lesson[] = [
    deepLesson("Setting Up a Python Engineering Environment", "A Python project begins with control over the interpreter and execution environment. Learn how the shell resolves python, how interpreter versions differ from project dependencies, why `python -m pip` removes ambiguity, and why isolated environments protect one project from another. The goal is a reproducible engineering workspace, not merely seeing a prompt appear.", "Create and verify an isolated Python workspace whose interpreter and package installation location you can prove.", ["Inspect the Python executable, version and pip association before creating an environment.", "Create a project-local virtual environment and activate it.", "Prove which interpreter is executing with shell commands and Python's sys module.", "Install one small dependency, inspect where it was installed, then deactivate and prove the global interpreter cannot accidentally rely on it.", "Record the commands another engineer needs to reproduce the workspace."], "Without running commands, explain the difference between installing Python, selecting a Python interpreter, activating a virtual environment and installing a project dependency. What evidence would you collect if `pip install` succeeded but `import` failed?", [venvDocs, packagingGuide]),
    deepLesson("Python Syntax, Values and Types", "Python source is executable structure: expressions produce values, names reference objects, and types determine supported behavior. Build a mental model around objects, identity, mutability and dynamic typing rather than memorizing declarations. Pay particular attention to `None`, booleans, numbers, strings, equality versus identity, and conversions at system boundaries where text becomes domain data.", "Model a few Steward-domain values and prove how type, equality, identity, conversion and mutability affect them.", ["Create representative identifiers, names, amounts, flags and optional values.", "Inspect each value with type() and repr().", "Demonstrate a safe conversion from external text and a conversion failure.", "Compare == and `is` with examples where their meaning differs.", "Record which values should remain immutable or validated at the future API boundary."], "Why is a variable name not the same thing as an object? When should `is` be used instead of `==`? What bugs can appear when external strings are treated as already-valid domain values?"),
    deepLesson("Control Flow", "Control flow turns data into behavior. Conditions should express domain decisions clearly; loops should describe repeated work without hiding state changes. Learn truthiness, chained conditions, `for`, `while`, `break`, `continue`, early return and structural clarity. The engineering concern is not whether a branch works once, but whether every meaningful path is understandable and testable.", "Implement a small eligibility or state-transition rule with explicit branches and boundary cases.", ["Define the rule in plain language before coding it.", "Implement it with clear condition ordering.", "Exercise happy, rejected and boundary inputs.", "Refactor one nested version into guard clauses or another clearer structure.", "Explain which paths a future automated test suite must cover."], "Given a function with several conditions, how would you determine the number of meaningful behavioral paths? When does an early return improve clarity, and when can it hide important state transitions?"),
    deepLesson("Functions and Scope", "Functions create behavioral boundaries. A useful function has a clear contract: inputs, output, side effects and failure behavior. Learn parameters, return values, default arguments, keyword arguments, local/global/nonlocal scope and the LEGB name-resolution model. Prefer explicit data flow over hidden mutable state so later service and API layers remain understandable.", "Refactor procedural Steward-domain logic into small functions with explicit contracts and controlled side effects.", ["Start with a short script containing at least three responsibilities.", "Extract functions around coherent behaviors rather than arbitrary line counts.", "Use parameters and return values instead of shared global state.", "Demonstrate one scope-related bug and explain why name resolution produced it.", "Document one function's contract including invalid input behavior."], "What makes a function boundary useful? Explain LEGB using a concrete name lookup. Why are mutable default arguments dangerous, and what pattern should replace them?"),
    deepLesson("Collections and Data Structures", "Lists, tuples, dictionaries and sets encode different guarantees. Choose structures from the operations and invariants you need: ordering, uniqueness, keyed lookup, mutability and membership cost. Nested collections can model temporary data, but increasingly complex dictionary shapes are also a signal that a stronger domain model may be approaching.", "Represent a small Steward dataset with multiple built-in collections and justify each choice from required behavior.", ["Model ordered events, unique roles and keyed records using appropriate structures.", "Perform lookup, update, membership and iteration operations.", "Demonstrate aliasing/mutation behavior with a list or dictionary.", "Compare two possible structures for the same requirement and record the trade-off.", "Identify the point at which the structure would deserve a class or database model."], "Choose between list, tuple, set and dict for four different domain requirements and justify each. What does mutability change when two names reference the same collection?"),
    deepLesson("Modules and Packages", "As a program grows, file boundaries become dependency boundaries. A module is an importable Python file; packages organize modules into namespaces. Learn import resolution, `__name__`, package structure, public versus internal surfaces and circular-dependency risk. Good packaging should make dependencies easier to understand, not merely spread code across directories.", "Split the evolving service core into coherent modules and a package without creating circular dependencies.", ["Identify responsibilities currently mixed together.", "Create a package with modules whose names reflect those responsibilities.", "Use imports deliberately and run the package from a stable project entry point.", "Inspect `__name__` behavior for imported versus directly executed modules.", "Sketch the dependency direction and remove any cycle you introduce."], "What is the difference between a module, an import package and a distribution package? How can moving code into more files make architecture worse?", [pythonTutorial, packagingGuide]),
    deepLesson("Errors, Exceptions and Defensive Programming", "Failures are part of a function's contract. Exceptions separate normal return values from exceptional paths, but broad catching can destroy evidence. Learn exception propagation, targeted `try/except/else/finally`, raising domain-relevant errors, preserving context and validating at boundaries. Defensive programming means making invalid states difficult to create while keeping failures diagnosable.", "Design explicit failure behavior for a domain operation and preserve useful diagnostic context.", ["Choose an operation with at least two invalid inputs or failure conditions.", "Define which failures should be rejected before work begins and which can occur during execution.", "Raise or translate exceptions at a boundary where the abstraction changes.", "Demonstrate why `except Exception: pass` or a broad replacement message harms diagnosis.", "Record the caller-facing contract for each failure."], "When should an exception propagate unchanged, be wrapped, or become a normal domain result? What information must not be lost when translating a low-level failure?"),
    deepLesson("Object-Oriented Programming", "Objects are useful when data and behavior share invariants and lifecycle. Learn classes, instances, attributes, methods, constructors, composition, inheritance and polymorphism, but do not treat every noun as a class. Prefer the simplest model that protects domain rules. Composition is often easier to reason about than inheritance because dependencies remain explicit.", "Model one meaningful Steward concept as an object and compare it with a simpler functional/data representation.", ["Identify a concept with state plus behavior or invariants.", "Implement a small class that protects those invariants.", "Create a collaborating object using composition.", "Write an alternative representation using functions and built-in data.", "Compare both approaches and justify which one should survive."], "What problem does encapsulation solve? When is a class unnecessary? Give an example where inheritance creates coupling that composition avoids."),
    deepLesson("Comprehensions, Iterators and Pythonic Tools", "Python offers concise tools for transforming and traversing data, but concision is not automatically clarity. Learn comprehensions, generators, iterators, `enumerate`, `zip`, `any`, `all`, sorting and key functions. Understand eager versus lazy evaluation so you can reason about memory, repeated consumption and side effects.", "Transform and summarize Steward-domain data using expressive iteration while preserving readability.", ["Implement one transformation first with an explicit loop.", "Rewrite it with a comprehension and compare readability.", "Use a generator for a pipeline that need not materialize every result.", "Demonstrate that an iterator can be consumed.", "Use any/all or sorting with a key to express a domain question clearly."], "When is a comprehension worse than a loop? What is the practical difference between an iterable, iterator and generator? Why can lazy evaluation change program behavior?"),
    deepLesson("Type Hints and Static Feedback", "Python remains dynamically typed at runtime, but type annotations make interfaces and assumptions visible to humans and static tools. Learn annotations for parameters, returns, collections, unions/optionals and domain aliases. Treat static feedback as an additional engineering signal, not proof that runtime behavior is correct.", "Add useful type information to the service core and use a static checker to expose at least one real mismatch.", ["Annotate public functions before internal implementation details.", "Represent optional values explicitly rather than hiding None assumptions.", "Run a static type checker and inspect its findings.", "Introduce a deliberate mismatch, explain why it is unsafe, then fix it.", "Identify one important property type hints cannot prove."], "What does a type checker know that Python runtime may not enforce? What does it still not know? When can an annotation make an API misleading rather than safer?", [typingDocs, { title: "mypy documentation", url: "https://mypy.readthedocs.io/en/stable/" }]),
    deepLesson("Virtual Environments and Dependency Management", "Environment isolation and dependency declaration solve different problems. A virtual environment isolates installed distributions; project metadata declares what software requires. Learn direct versus transitive dependencies, version constraints, reproducibility and why dependency choices become supply-chain decisions later in TSA. This is the first step toward the internal package and Nexus lifecycle built in later schools.", "Make the Python service core reproducible from a clean environment and explain every direct dependency.", ["Create project metadata or a dependency declaration appropriate to the current project.", "Distinguish packages your code imports directly from transitive packages.", "Recreate the environment from scratch and verify the program runs.", "Change a version constraint in a controlled experiment and record the effect.", "Document what is reproducible today and what is not yet locked or controlled."], "Why is a virtual environment not a dependency specification? What is the difference between a direct and transitive dependency? How can an unconstrained dependency break a previously working build?", [venvDocs, packagingGuide]),
    deepLesson("Debugging Python Programs", "Apply the Engineering Apprentice debugging mindset inside Python. Tracebacks are structured evidence: exception type, message and call stack narrow the search space. Add debugger breakpoints, inspect state, reduce failing inputs and distinguish the line where failure surfaced from the earlier state that made failure inevitable.", "Diagnose a non-trivial Python defect from evidence rather than random edits.", ["Introduce or select a defect that crosses at least two function calls.", "Capture and annotate the traceback before changing code.", "Form at least two hypotheses about the cause.", "Use print/log inspection or the debugger to falsify one hypothesis.", "Fix the cause, rerun the reproducer and record why the change resolves it."], "A traceback points to one line. Why might that line not contain the root cause? Describe the evidence you would collect before editing code when a function receives an impossible value.", [{ title: "Python pdb documentation", url: "https://docs.python.org/3/library/pdb.html" }, pythonTutorial]),
    { id: "programming-with-python-lab-build-a-small-python-service-core", title: "Lab: Build a Small Python Service Core", activities: [
        { id: "programming-with-python-lab-build-a-small-python-service-core-brief", title: "Service Core Design Brief", estimatedMinutes: 20, content: { type: "reading", body: "This lab is the first real construction step toward Steward API. Build a framework-free Python core with enough domain behavior to expose decisions about validation, state, errors, modules and interfaces. Do not anticipate Django models or HTTP yet. The point is to prove that domain behavior can exist independently of the delivery framework." } },
        { id: "programming-with-python-lab-build-a-small-python-service-core-build", title: "Build the Service Core", estimatedMinutes: 150, content: { type: "practical", objective: "Build a small but credible Python domain/service core that becomes the conceptual starting point for Steward API.", scenario: "Steward will later become a Django/DRF service. For now, model a small slice of its behavior using plain Python so framework mechanics cannot hide your understanding of values, functions, collections, modules, exceptions, objects and dependencies.", instructions: ["Define a narrow Steward domain problem and 3–5 explicit rules.", "Design package/module boundaries before implementation.", "Implement domain behavior using the simplest appropriate mix of functions and objects.", "Reject invalid state deliberately and preserve useful error information.", "Add type annotations to important public interfaces.", "Create a tiny executable demonstration or script covering happy, boundary and failure paths.", "Recreate the project in a clean virtual environment from declared dependencies.", "Debug one deliberately introduced defect and keep the evidence log.", "Write a short note identifying what should remain framework-independent when Django is introduced."], deliverables: ["Runnable Python service-core package", "Domain rules and examples", "Dependency/environment declaration", "Failure-path evidence", "Debugging evidence log", "Framework-independence note"], completionCriteria: ["The code demonstrates real domain behavior rather than syntax exercises.", "Package boundaries and dependencies can be explained.", "Invalid states and failures are deliberate and observable.", "A clean environment can reproduce the project.", "The learner can explain which concepts from every Python lesson appear in the implementation."] } },
        { id: "programming-with-python-lab-build-a-small-python-service-core-review", title: "Python Module Review", estimatedMinutes: 20, content: { type: "reflection", prompt: "Review your service core as if another engineer submitted it. Which part most clearly demonstrates Python understanding? Which part is over-engineered? Which hidden assumption would be most dangerous when this becomes an API? What would you deliberately refuse to redesign until Django, PostgreSQL or real requirements give you evidence?" } },
    ] },
];
