import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const awsWellArchitected: LearningResource = { title: "AWS — Well-Architected Framework", url: "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html" };
const azureArchitecture: LearningResource = { title: "Microsoft Azure — Architecture Center", url: "https://learn.microsoft.com/azure/architecture/" };
const googleCloudArchitecture: LearningResource = { title: "Google Cloud — Architecture Framework", url: "https://cloud.google.com/architecture/framework" };
const nistCloud: LearningResource = { title: "NIST — The NIST Definition of Cloud Computing", url: "https://csrc.nist.gov/publications/detail/sp/800-145/final" };

interface LessonSpec {
    id: string;
    title: string;
    intro: string;
    sections: Array<{ heading: string; paragraphs: string[]; list?: string[]; code?: { language: string; code: string; caption?: string } }>;
    practice: string[];
    questions: string[];
}

function richLesson(spec: LessonSpec): Lesson {
    const blocks: LessonBlock[] = [{ type: "paragraph", text: spec.intro }];
    for (const section of spec.sections) {
        blocks.push({ type: "heading", id: section.heading.toLowerCase().replace(/[^a-z0-9]+/g, "-"), text: section.heading, level: 2 });
        for (const paragraph of section.paragraphs) blocks.push({ type: "paragraph", text: paragraph });
        if (section.list) blocks.push({ type: "list", items: section.list });
        if (section.code) blocks.push({ type: "code", language: section.code.language, code: section.code.code, caption: section.code.caption });
    }
    blocks.push({ type: "callout", tone: "steward", title: "Steward cloud checkpoint", body: "Map this capability to a concrete Steward responsibility. Ask what the VPS currently provides, what a cloud service could take over, what responsibility remains with the team, and whether the additional abstraction is justified by evidence rather than novelty." });
    blocks.push({ type: "resources", title: "Continue learning", resources: [awsWellArchitected, azureArchitecture, googleCloudArchitecture] });
    return {
        id: `cloud-building-blocks-${spec.id}`,
        title: spec.title,
        activities: [
            { id: `cloud-building-blocks-${spec.id}-001`, title: spec.title, estimatedMinutes: 40, content: { type: "reading", body: spec.intro, blocks } },
            { id: `cloud-building-blocks-${spec.id}-002`, title: `Apply: ${spec.title}`, estimatedMinutes: 45, content: { type: "practical", objective: `Apply ${spec.title} reasoning to Steward.`, scenario: "Steward already runs on a budget VPS. Your job is not to migrate it blindly. Decompose the existing host into capabilities, compare self-managed and provider-managed boundaries, and make the smallest defensible architecture change.", instructions: spec.practice, deliverables: ["Steward capability mapping", "Responsibility and trade-off note", "Reviewable decision evidence"], completionCriteria: ["The cloud capability is explained independently of one provider's product name.", "The current VPS responsibility and proposed provider responsibility are explicit.", "The decision accounts for failure, security, operations and cost rather than feature count alone."] } },
            { id: `cloud-building-blocks-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.questions.join("\n\n"), minimumCharacters: 180 } },
        ],
    };
}

const specs: LessonSpec[] = [
    { id: "compute", title: "Compute", intro: "Compute is the execution capacity on which software runs. A cloud VM resembles the Steward VPS you already know, while containers, instance groups and managed runtimes move different amounts of operating responsibility to the provider.", sections: [
        { heading: "Start from the workload", paragraphs: ["CPU, memory, architecture, runtime duration and scaling shape the compute choice. A small Steward API does not become better merely because it runs on a more sophisticated compute service.", "A virtual machine leaves the guest OS, patching, runtime and application with you. More-managed compute can remove some of those duties but introduces platform constraints and different failure modes."], list: ["Virtual machine: maximum familiar host control.", "Managed container/runtime: less host administration, more platform contract.", "Horizontal fleet: multiple replaceable compute instances behind traffic distribution."] },
        { heading: "Capacity is not architecture", paragraphs: ["Buying a larger VM can relieve resource pressure but does not create redundancy. Likewise, adding instances without understanding state, database connections and deployment behavior can multiply failure instead of resilience."] },
    ], practice: ["Record the CPU, memory and runtime assumptions of the current Steward VPS.", "Compare one VM-based and one more-managed compute option without changing the deployment.", "State which operational responsibilities move to the provider and which remain with the Steward team."], questions: ["Why is a larger VM not the same as higher availability?", "What responsibility does a managed runtime remove, and what new platform dependency does it introduce?"] },
    { id: "object-storage", title: "Object Storage", intro: "Object storage keeps data as named objects accessed through an API rather than as files on a mounted server filesystem. It is designed for durable blobs, archives, exports and backups—not for pretending every workload is a local disk.", sections: [
        { heading: "Objects are not files on a server", paragraphs: ["An object store usually exposes buckets, keys, metadata and API operations. Applications should assume different consistency, latency and access semantics from a POSIX filesystem.", "For Steward, generated exports, evidence bundles or backup archives are better candidates than PostgreSQL's live data directory."], list: ["Good candidates: backups, reports, exports, static assets and immutable evidence.", "Poor candidate: live relational database storage mounted as though it were a local block device."] },
        { heading: "Durability does not remove lifecycle design", paragraphs: ["Provider durability protects against some storage failures, but retention, deletion, versioning, encryption and access policy remain architecture decisions. A durable accidental deletion is still a deletion if lifecycle controls allow it."] },
    ], practice: ["Inventory Steward data that is currently stored as files or backup archives.", "Classify which items fit object semantics and which do not.", "Design bucket/key, retention and access boundaries for one legitimate Steward object-storage use case."], questions: ["Why should PostgreSQL's live data directory not simply be moved to object storage?", "What responsibilities remain after a provider advertises high durability?"] },
    { id: "block-storage", title: "Block Storage", intro: "Block storage presents addressable storage volumes that an operating system can format and mount. It is closer to a disk than object storage and therefore fits filesystems and stateful workloads that require block semantics.", sections: [
        { heading: "Separate compute lifetime from data lifetime", paragraphs: ["A detachable cloud volume can outlive one VM and be attached to replacement compute, depending on provider and zone constraints. That separation is useful, but it does not automatically make the application highly available."] },
        { heading: "Know the failure and performance contract", paragraphs: ["Volume type, IOPS, throughput, size, attachment rules and availability-zone placement affect behavior. Snapshots can help recovery, but a snapshot is not proof that an application-consistent restore will work."] },
    ], practice: ["Map the current Steward host filesystems and identify any data that truly requires block semantics.", "Document what would happen to that data if the compute instance were replaced.", "Compare local ephemeral disk, provider block volume and managed database storage for the PostgreSQL workload."], questions: ["What problem does separating a volume from VM lifetime solve?", "Why does detachable block storage not by itself provide database high availability?"] },
    { id: "managed-databases", title: "Managed Databases", intro: "A managed database service transfers parts of database infrastructure operation to a provider while leaving schema, queries, data governance and application correctness with the engineering team.", sections: [
        { heading: "Managed does not mean ownerless", paragraphs: ["The provider may handle host replacement, database engine installation, automated backups, patch windows and some replication. You still own access policy, schema migrations, query behavior, retention requirements, restore validation and how the application reacts to database failure."] },
        { heading: "Compare the real operating burden", paragraphs: ["Self-managed PostgreSQL on the Steward VPS may be appropriate for a learning or tiny environment. A managed service becomes compelling when reducing database operational toil, improving recovery options or separating failure domains is worth the recurring cost and provider dependency."], list: ["Ask who patches the engine.", "Ask who tests restores.", "Ask where credentials live.", "Ask how network access is restricted.", "Ask what happens during maintenance or failover."] },
    ], practice: ["Write the current self-managed PostgreSQL responsibility list for Steward.", "Map each responsibility against a candidate managed PostgreSQL service.", "Recommend stay or migrate based on explicit operational, recovery and cost drivers."], questions: ["Which database responsibilities remain with the application team after moving to a managed service?", "When can self-managed PostgreSQL still be the more rational choice?"] },
    { id: "virtual-networks-subnets", title: "Virtual Networks and Subnets", intro: "A cloud virtual network creates a private routing and policy domain for resources. Subnets divide address space and placement so that public reachability is an intentional architecture decision rather than the default for every component.", sections: [
        { heading: "Design address space before resources", paragraphs: ["Choose non-overlapping private CIDR ranges with enough room for the expected topology. A subnet is not inherently public or private solely because of its address range; routing, gateways and public-address association determine reachability."], code: { language: "text", caption: "Conceptual Steward network", code: "VPC 10.20.0.0/16\n├── public  10.20.10.0/24  reverse proxy / ingress\n└── private 10.20.20.0/24  application / database" } },
        { heading: "Segmentation expresses trust", paragraphs: ["Putting every resource in one publicly reachable segment discards useful boundaries. Network segmentation should support the actual communication graph: internet clients need the public entry point, not direct database access." ] },
    ], practice: ["Draw a provider-neutral virtual network for Steward.", "Assign public and private subnet roles and CIDR ranges.", "For every component, state whether it needs a public address and why."], questions: ["What actually makes a cloud subnet public?", "Why should the database usually not need a public IP address?"] },
    { id: "routing-gateways", title: "Routing and Gateways", intro: "Routes decide where packets go; gateways connect routing domains. Cloud networking becomes understandable when you trace explicit destination-to-next-hop decisions rather than treating a VPC as magical connectivity.", sections: [
        { heading: "Read the route table", paragraphs: ["A local route permits communication within the virtual network. A default route may send internet-bound traffic to an internet gateway, NAT service or another appliance. The existence of a route does not override firewall or identity policy."], code: { language: "text", caption: "Conceptual route intent", code: "10.20.0.0/16 -> local\n0.0.0.0/0    -> internet gateway   # public subnet\n0.0.0.0/0    -> NAT/egress path    # private workload, if needed" } },
        { heading: "Inbound and outbound are different needs", paragraphs: ["A private application instance may need outbound access to fetch an artifact without accepting unsolicited inbound internet connections. Egress gateways and private provider endpoints are ways to satisfy outbound dependencies without making the workload publicly addressable."] },
    ], practice: ["Write the minimum routes needed for the Steward network diagram.", "Trace an inbound HTTPS request and an outbound artifact-fetch request separately.", "Identify which path would fail if a gateway or route were removed."], questions: ["Why does a default route not guarantee successful internet access?", "How can a private workload reach an external dependency without becoming a public inbound endpoint?"] },
    { id: "load-balancers", title: "Load Balancers", intro: "A load balancer provides a stable traffic entry point and distributes requests among healthy targets. It becomes useful when there are multiple interchangeable application instances or when managed ingress capabilities justify the additional component.", sections: [
        { heading: "Distribution requires replaceable targets", paragraphs: ["If Steward has only one application instance, adding a load balancer may centralize TLS or provide a stable endpoint but cannot remove that single backend failure. Multiple targets must also share no unsafe local state and must use compatible deployment and database behavior."] },
        { heading: "Health checks are routing decisions", paragraphs: ["A load balancer health check decides whether a target should receive traffic. It should test enough to establish serving ability without making every optional downstream dependency a reason to eject all targets."] },
    ], practice: ["Decide whether the current Steward environment has a real load-balancing requirement.", "Design a future two-instance target group and identify what application assumptions must change first.", "Define a health check and explain exactly what a pass means."], questions: ["Why does placing a load balancer in front of one unhealthy VM not create availability?", "What is the danger of making a health check depend on every downstream system?"] },
    { id: "iam", title: "IAM", intro: "Cloud Identity and Access Management controls which human or workload identity may perform which provider action on which resource. It is the cloud control-plane authorization boundary—not a replacement for Steward's own application authorization.", sections: [
        { heading: "Identity, action and resource", paragraphs: ["A useful policy can be reasoned about as principal + permitted action + resource + conditions. Broad administrator credentials are convenient during experiments but destroy the ability to explain or limit blast radius."] },
        { heading: "Human and workload identities differ", paragraphs: ["CI publishing infrastructure, an operator administering a VPS and a runtime reading one secret do not need the same permissions. Prefer short-lived or role-based workload credentials where the provider supports them, and keep emergency administration exceptional."], list: ["Separate human operator from CI identity.", "Separate read from mutate permissions.", "Scope resources where practical.", "Protect root/owner credentials and require stronger authentication."] },
    ], practice: ["List the provider actions needed by a human operator, CI infrastructure job and Steward runtime.", "Design three separate roles/policies instead of one shared administrator credential.", "Identify one dangerous permission that each identity explicitly does not need."], questions: ["How is cloud IAM different from authorization inside the Steward API?", "Why should CI and the running application not share one provider credential?"] },
    { id: "secrets-management", title: "Secrets Management", intro: "A cloud secrets service centralizes protected values and access policy, but it does not make secret handling correct automatically. The system still needs a deliberate path from authorized identity to runtime value without leaking it into source, images, logs or state.", sections: [
        { heading: "Secrets have a lifecycle", paragraphs: ["Creation, storage, access, rotation, revocation and audit are all part of secret management. A secret copied from a managed vault into a committed environment file has immediately escaped the control boundary you intended to create."] },
        { heading: "Prefer identity-based retrieval", paragraphs: ["Where practical, let the workload authenticate with a provider identity and retrieve only the values it needs. This reduces long-lived bootstrap credentials, but the application and deployment tooling must still avoid printing or persisting retrieved values unnecessarily."] },
    ], practice: ["Inventory the current Steward runtime secrets without exposing their values.", "Design how one database credential would move from provider secret storage to the runtime.", "Document rotation and emergency revocation behavior."], questions: ["Why is storing a value in a secrets manager only one part of secret management?", "What is the bootstrap-credential problem and how can workload identity reduce it?"] },
    { id: "cloud-monitoring", title: "Cloud Monitoring", intro: "Cloud providers expose infrastructure metrics, events and logs that can reveal resource health before you install a full application observability platform. Use them to understand the infrastructure boundary, not as a substitute for later service-level reliability engineering.", sections: [
        { heading: "Observe the resource you rent", paragraphs: ["CPU utilization, disk behavior, network traffic, instance status and provider events help distinguish infrastructure pressure from application symptoms. Provider metrics can also continue when the application process itself is unhealthy."] },
        { heading: "Alert only on actionable signals", paragraphs: ["A dashboard full of metrics is not an operating model. During Cloud Engineer, select a small set of signals that prove infrastructure state and cost behavior. Reliability Engineer will later build deeper application indicators, SLOs and alerting policy."] },
    ], practice: ["Identify the provider-native metrics available for the Steward compute and database choices.", "Choose three infrastructure signals and explain what action each could trigger.", "Create or design one provider alert without duplicating application-level SLO work reserved for Reliability Engineer."], questions: ["What can provider monitoring tell you when the Steward process is down?", "Why should this module avoid prematurely building the full observability strategy?"] },
    { id: "cloud-backup-services", title: "Cloud Backup Services", intro: "Cloud backup services can schedule and retain copies of volumes, databases or objects, but recovery is the outcome that matters. A green backup job is evidence of copy creation, not proof that Steward can be restored.", sections: [
        { heading: "Backup policy follows recovery needs", paragraphs: ["Define what data matters, acceptable data loss, retention and restore destination before selecting a backup schedule. Provider snapshots, managed database backups and object versioning solve different recovery problems."] },
        { heading: "Test the restore path", paragraphs: ["Restoration should be exercised into an isolated target where possible. Verify application-consistent data, credentials, dependencies and the time required to recover. Keep at least some recovery knowledge independent of one operator's memory."] },
    ], practice: ["Classify Steward's database, configuration and artifact/evidence data by recovery need.", "Choose the appropriate provider backup mechanism for each category.", "Write and, where safe, exercise a restore test with explicit success criteria."], questions: ["Why is a successful snapshot job not enough evidence of recoverability?", "Why might different Steward data categories require different backup mechanisms?"] },
    { id: "managed-vs-self-managed", title: "Managed Services versus Self-managed Infrastructure", intro: "Managed services trade direct control for a provider contract that removes some operational work. The right question is not whether managed is modern; it is whether the transferred responsibility is valuable enough to justify cost, constraints and dependency.", sections: [
        { heading: "Draw the responsibility boundary", paragraphs: ["For every candidate service, write what the provider owns and what the Steward team still owns. Managed PostgreSQL may remove host patching while leaving schema design and restore verification. Managed load balancing may remove proxy host maintenance while leaving routing policy and certificate decisions."] },
        { heading: "Pay for removed toil, not labels", paragraphs: ["A small learning deployment can rationally remain on one VPS. A production-critical system may rationally pay for managed database, backup or load-balancing capabilities. Cost should be compared against operational effort, failure impact, skill requirements and recovery objectives."], list: ["Control and customization", "Operational toil", "Failure responsibility", "Portability and provider coupling", "Security boundary", "Recurring cost", "Recovery capability"] },
    ], practice: ["Select three Steward responsibilities currently self-managed on the VPS.", "For each, compare one managed alternative using the same decision criteria.", "Recommend keep, migrate now or reconsider later, with a trigger that would justify revisiting the decision."], questions: ["Why is a managed service not automatically safer or cheaper?", "What kind of trigger should cause a previously rational self-managed decision to be reconsidered?"] },
];

const lab: Lesson = {
    id: "cloud-building-blocks-map-steward",
    title: "Lab: Map Steward Platform to Cloud Building Blocks",
    activities: [
        { id: "cloud-building-blocks-map-steward-001", title: "Baseline the VPS Responsibilities", estimatedMinutes: 45, content: { type: "practical", objective: "Turn the current Steward VPS into a capability and responsibility map.", scenario: "Before designing cloud architecture, make the existing architecture explicit. Treat the VPS as a bundle of compute, storage, networking, database, identity, secret, monitoring and recovery responsibilities.", instructions: ["Draw the current Steward internet environment from client to application to PostgreSQL and artifact dependencies.", "Annotate each component with the capabilities it currently provides.", "Mark who operates, patches, backs up, monitors and recovers each capability.", "Identify every current single point of failure without immediately fixing it."], deliverables: ["Current-state architecture diagram", "Responsibility matrix", "Single-point-of-failure list"], completionCriteria: ["The VPS is decomposed into capabilities rather than treated as one opaque server.", "Operational ownership is visible.", "Observed limitations are separated from proposed solutions."] } },
        { id: "cloud-building-blocks-map-steward-002", title: "Design the Smallest Defensible Cloud Target", estimatedMinutes: 90, content: { type: "practical", objective: "Design a provider-neutral target architecture without adopting every available managed service.", scenario: "Steward needs a plausible next cloud architecture, but budget and complexity matter. Select building blocks only where they address a stated driver.", instructions: ["Define the target drivers: availability, recovery, security, operational effort, scale and budget.", "Map compute, storage, database, networking, IAM, secrets, monitoring and backup choices.", "For every managed service, record the responsibility it removes and the new dependency/cost it creates.", "Keep any component self-managed when the evidence does not justify migration.", "Draw public ingress, private communication and administrative access separately."], deliverables: ["Target architecture diagram", "Managed/self-managed decision table", "Driver-to-component traceability"], completionCriteria: ["Every added building block has a stated driver.", "The design avoids public database/backend exposure.", "The target is understandable without provider-specific product names."] } },
        { id: "cloud-building-blocks-map-steward-003", title: "Map the Target to One Provider", estimatedMinutes: 60, content: { type: "practical", objective: "Translate the provider-neutral design into concrete provider services without changing its reasoning.", scenario: "Only after the architecture is understood do product names become useful. Map the design to one real provider and record where the provider contract changes assumptions.", instructions: ["Choose one provider appropriate to the learning budget.", "Map each target capability to a concrete service or retained VPS component.", "Record region/zone constraints, identity boundaries, backup behavior and major pricing dimensions.", "Identify any provider feature that tempts you to change the architecture without a requirement; reject or justify it explicitly."], deliverables: ["Provider service mapping", "Assumption and constraint register", "Initial cost dimensions"], completionCriteria: ["Provider products implement an already-reasoned architecture.", "Important regional and service constraints are visible.", "No product is present only because it is fashionable."] } },
        { id: "cloud-building-blocks-map-steward-004", title: "Cloud Building Blocks Review", estimatedMinutes: 30, content: { type: "reflection", prompt: "Explain which Steward responsibilities you would keep self-managed today and which you would transfer to managed services. For each transferred responsibility, name the operational burden removed, the new provider dependency introduced, and the evidence that justifies paying for it. Then identify one decision that Infrastructure as Code must make reproducible in the next module.", minimumCharacters: 300 } },
    ],
};

export const cloudBuildingBlocksDeepLessons: Lesson[] = [...specs.map(richLesson), lab];
