import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const awsWellArchitected: LearningResource = { title: "AWS — Well-Architected Framework", url: "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html" };
const googleCloudFramework: LearningResource = { title: "Google Cloud — Architecture Framework", url: "https://cloud.google.com/architecture/framework" };
const azureReliability: LearningResource = { title: "Microsoft Azure — Reliability documentation", url: "https://learn.microsoft.com/azure/reliability/" };
const finops: LearningResource = { title: "FinOps Foundation — FinOps Framework", url: "https://www.finops.org/framework/" };

interface LessonSpec {
    id: string;
    title: string;
    intro: string;
    sections: Array<{ heading: string; paragraphs: string[]; list?: string[]; code?: { language: string; code: string; caption?: string } }>;
    practice: string[];
    questions: string[];
}

function richLesson(spec: LessonSpec): Lesson {
    const blocks: LessonBlock[] = [{ type: "paragraph", text: spec.intro }];
    for (const section of spec.sections) {
        blocks.push({ type: "heading", id: section.heading.toLowerCase().replace(/[^a-z0-9]+/g, "-"), text: section.heading, level: 2 });
        for (const paragraph of section.paragraphs) blocks.push({ type: "paragraph", text: paragraph });
        if (section.list) blocks.push({ type: "list", items: section.list });
        if (section.code) blocks.push({ type: "code", language: section.code.language, code: section.code.code, caption: section.code.caption });
    }
    blocks.push({ type: "callout", tone: "steward", title: "Steward architecture checkpoint", body: "Do not optimize a diagram in isolation. Relate availability, capacity, security, recovery and cost decisions to Steward's real workload, failure impact and operating model. Every extra component adds both capability and responsibility." });
    blocks.push({ type: "resources", title: "Continue learning", resources: [awsWellArchitected, googleCloudFramework, azureReliability, finops] });

    return {
        id: `cloud-architecture-and-cost-${spec.id}`,
        title: spec.title,
        activities: [
            { id: `cloud-architecture-and-cost-${spec.id}-001`, title: spec.title, estimatedMinutes: 40, content: { type: "reading", body: spec.intro, blocks } },
            { id: `cloud-architecture-and-cost-${spec.id}-002`, title: `Apply: ${spec.title}`, estimatedMinutes: 45, content: { type: "practical", objective: `Apply ${spec.title} to Steward's remote architecture.`, scenario: "Steward now has a provider-neutral target architecture and Infrastructure as Code baseline. Review whether that design is actually proportionate, resilient enough, recoverable and affordable before treating it as the Cloud Engineer target.", instructions: spec.practice, deliverables: ["Architecture evidence", "Trade-off note", "Cost or recovery assumptions where relevant"], completionCriteria: ["The decision is tied to a concrete Steward driver.", "Failure and operational consequences are explicit.", "The solution avoids unnecessary architecture for its own sake."] } },
            { id: `cloud-architecture-and-cost-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.questions.join("\n\n"), minimumCharacters: 180 } },
        ],
    };
}

const specs: LessonSpec[] = [
    { id: "availability", title: "Availability in Cloud Environments", intro: "Availability is the probability that a service can perform its required function when needed. Cloud platforms provide building blocks for higher availability, but availability emerges from the whole system, not from a provider label.", sections: [
        { heading: "Remove the right single points of failure", paragraphs: ["A redundant application tier does little if every instance depends on one unrecoverable database. Likewise, a managed database does not help when DNS, credentials or deployment logic can still make the service unavailable.", "Start with the user-visible path and identify which failures can stop it."], list: ["Client name resolution", "Public ingress", "Application compute", "Database", "Credentials and configuration", "Critical external dependencies"] },
        { heading: "Availability has a cost", paragraphs: ["More replicas, zones, managed failover and standby capacity all increase cost and operational complexity. The target should follow business impact and recovery expectations, not a desire to draw a multi-zone diagram."] },
    ], practice: ["Trace the complete Steward request path and mark every single point of failure.", "Select the one availability improvement with the highest value for the current stage.", "State which remaining failure you deliberately accept and why."], questions: ["Why is multi-zone compute insufficient when the database is still a single unrecoverable dependency?", "Why should availability targets be connected to failure impact and cost?"] },
    { id: "scalability-capacity", title: "Scalability and Capacity", intro: "Capacity planning asks how much load the system can handle now and how it should respond as demand changes. Scaling should follow observed resource pressure and workload shape, not vague expectations of future growth.", sections: [
        { heading: "Measure the bottleneck first", paragraphs: ["CPU, memory, storage latency, database connections, query cost and network throughput can constrain Steward independently. Increasing the wrong resource changes cost without increasing useful capacity."] },
        { heading: "Vertical before horizontal can be rational", paragraphs: ["For a small service, a larger instance can be simpler and cheaper than introducing a load balancer, multiple application instances and new coordination concerns. Horizontal scaling becomes more attractive when vertical limits, availability requirements or traffic patterns justify it."] },
    ], practice: ["Define three measurable Steward capacity signals.", "Choose one plausible bottleneck and propose the smallest response.", "Document the trigger that would justify moving from vertical to horizontal scaling."], questions: ["Why can scaling CPU fail to improve throughput?", "When is vertical scaling a better engineering choice than adding instances?"] },
    { id: "security-boundaries", title: "Security Boundaries", intro: "Cloud architecture creates multiple control planes and network boundaries. Good design minimizes which identities and components can reach sensitive resources while keeping the path operable.", sections: [
        { heading: "Separate public, administrative and control-plane access", paragraphs: ["Internet users need HTTPS to Steward's public entry point. Operators need tightly controlled administration. CI or IaC needs cloud control-plane permissions. The database needs application traffic, not public internet exposure. These are different trust relationships and should not share one broad path."] },
        { heading: "Least privilege is architectural", paragraphs: ["IAM policy, subnet placement, firewall rules, secret access and workload identity all shape blast radius. Security is stronger when several boundaries agree on the intended communication graph rather than relying on one perimeter rule."] },
    ], practice: ["Draw Steward's public, administrative, application-to-database and cloud-control paths separately.", "For each path, name the identity and minimum allowed action.", "Remove one unnecessary trust relationship from the target design."], questions: ["Why should public ingress and administrative access be modeled separately?", "How do IAM and network policy complement rather than replace each other?"] },
    { id: "backup-recovery", title: "Backup and Recovery", intro: "Recovery architecture starts from what must be restored, how much data loss is acceptable and how long the service may remain unavailable. Backups are inputs to recovery, not the recovery capability itself.", sections: [
        { heading: "RPO and RTO clarify the target", paragraphs: ["Recovery Point Objective describes acceptable data loss measured in time. Recovery Time Objective describes acceptable restoration time. These objectives guide backup frequency, replication, automation and the amount of standby infrastructure worth paying for."], code: { language: "text", caption: "Example recovery intent", code: "Steward database RPO: 24 hours\nSteward service RTO: 4 hours\n\nImplication: daily recoverable backup may satisfy data-loss tolerance,\nbut restore procedure must be able to rebuild service within four hours." } },
        { heading: "Restore dependencies, not just data", paragraphs: ["A database dump is not enough if DNS, IaC state, secrets, image artifacts or deployment knowledge are unavailable. Recovery planning should identify which artifacts and control-plane assets are required to reconstruct service." ] },
    ], practice: ["Propose provisional RPO and RTO values for Steward and justify them.", "Map every asset needed to rebuild the service from a provider failure.", "Identify one restore step that is still dependent on personal memory and make it explicit."], questions: ["What is the difference between RPO and RTO?", "Why can a valid database backup still be insufficient for service recovery?"] },
    { id: "failure-domains", title: "Failure Domains", intro: "A failure domain is a set of components likely to fail together because they share infrastructure, geography, configuration or control. Architecture improves when redundancy crosses the failure boundary that actually matters.", sections: [
        { heading: "Correlation matters", paragraphs: ["Two application instances on the same VM are process redundancy, not host redundancy. Two VMs in one availability zone may survive an instance failure but not a zone outage. Two zones may still depend on one regional service or shared configuration mistake."] },
        { heading: "Software changes can be a failure domain", paragraphs: ["Infrastructure separation cannot protect against a bad deployment sent everywhere at once. Release controls, configuration scope and recovery artifacts therefore participate in failure-domain thinking alongside hardware and zones." ] },
    ], practice: ["List Steward's current shared failure domains: host, zone, region, database, deployment, IAM and DNS where applicable.", "For each proposed redundancy mechanism, state which domain it actually crosses.", "Reject one form of fake redundancy that does not cross the required failure boundary."], questions: ["Why are two containers on one VM not host-level redundancy?", "How can one bad release defeat otherwise redundant infrastructure?"] },
    { id: "cost-estimation", title: "Cost Estimation", intro: "Cloud estimates are engineering models built from resource inventory, pricing dimensions and usage assumptions. They do not need to predict every cent; they need to reveal what drives spend and how architecture choices change it.", sections: [
        { heading: "Estimate by resource and unit", paragraphs: ["List compute hours, allocated storage, snapshots, managed databases, public addresses, load balancers, DNS, outbound traffic and retained logs separately. Mark which are fixed while allocated and which vary with usage."], code: { language: "text", caption: "Architecture cost model", code: "compute          quantity × hours × rate\nstorage          GB allocated × monthly rate\nbackup           retained GB × rate\nnetwork egress   transferred GB × rate\nmanaged service  instance-hours + storage + I/O where applicable\n\nmonthly estimate = sum(each resource assumption)" } },
        { heading: "Make assumptions reviewable", paragraphs: ["Write the region, size, expected traffic and retention period next to the estimate. A number without its assumptions becomes stale silently when architecture or pricing changes."] },
    ], practice: ["Build a monthly estimate for the current Steward cloud target.", "Show quantity, pricing unit and assumption for every line.", "Identify the top two cost drivers and one architecture change that would materially alter them."], questions: ["Why is a monthly total without assumptions weak engineering evidence?", "Which cloud costs can vary substantially even if compute size never changes?"] },
    { id: "cost-controls-budgets", title: "Cost Controls and Budgets", intro: "Cost control turns an estimate into an operating constraint. Budgets, alerts, tagging and teardown rules reduce the chance that temporary infrastructure becomes permanent unnoticed spend.", sections: [
        { heading: "A budget alert is not a hard safety boundary", paragraphs: ["Many provider budgets notify rather than automatically stop resources. Engineers still need ownership, review cadence and safe teardown procedures. Automated shutdown can also be dangerous for stateful or production resources if used without lifecycle awareness."] },
        { heading: "Ownership makes spend actionable", paragraphs: ["Tags or labels such as system, environment, owner and purpose make cost attribution easier. Temporary learning infrastructure should also have an expiry or teardown decision so that forgotten resources are visible." ] },
    ], practice: ["Set or design a monthly Steward budget threshold and alert path.", "Define required tags/labels for Steward resources.", "Create a teardown rule for temporary environments and identify resources that must never be destroyed automatically."], questions: ["Why does a budget alert not guarantee spending will stop?", "Why can automatic teardown be risky for stateful resources?"] },
    { id: "right-sizing", title: "Resource Right-sizing", intro: "Right-sizing means matching provisioned resources to observed workload needs while preserving enough headroom for expected variability. It is an iterative operating practice, not a one-time purchase decision.", sections: [
        { heading: "Use evidence over average utilization alone", paragraphs: ["A low monthly CPU average can hide short saturation periods. Memory pressure, burst behavior, disk latency and startup requirements also matter. Right-sizing should consider percentiles, peaks and failure behavior, not only averages."] },
        { heading: "Downsizing is a controlled change", paragraphs: ["A cheaper instance is useful only if Steward continues meeting response, deployment and recovery needs. Treat size changes like infrastructure changes: plan, apply, verify and retain rollback options where possible."] },
    ], practice: ["Choose the metrics and observation window needed before resizing Steward compute.", "Propose one downsizing or upsizing experiment with success and rollback criteria.", "Estimate the monthly difference if the change succeeds."], questions: ["Why can low average CPU be misleading?", "Why should right-sizing be treated as a controlled infrastructure change?"] },
    { id: "managed-self-managed", title: "Managed vs Self-managed Trade-offs", intro: "Managed services exchange money and provider coupling for reduced infrastructure responsibility. The decision should be based on toil, failure impact, recovery requirements, skills and total operating cost.", sections: [
        { heading: "Compare total responsibility, not sticker price", paragraphs: ["A self-managed database may have a lower provider bill while requiring patching, backup automation and recovery expertise. A managed database may cost more directly while reducing that toil. Neither is automatically cheaper once engineering effort and failure risk are considered."] },
        { heading: "Provider constraints are part of the price", paragraphs: ["Version availability, maintenance windows, networking models, backup retention, export paths and portability affect long-term flexibility. Managed services should be adopted with awareness of the contract they impose." ] },
    ], practice: ["Compare Steward PostgreSQL as self-managed versus managed across provider cost, engineering toil, recovery, portability and failure responsibility.", "Choose one option for the current stage and state the trigger for revisiting it.", "Repeat the exercise for one other component such as ingress or backups."], questions: ["Why can the cheaper provider bill still produce higher total operating cost?", "What kinds of managed-service constraints should influence architecture decisions?"] },
    { id: "hybrid-tradeoffs", title: "Homelab, VPS and Cloud Hybrid Trade-offs", intro: "A mature engineering decision can keep different responsibilities in different environments. Homelab, VPS and cloud services can coexist when each location has a clear role and the dependencies between them are deliberate.", sections: [
        { heading: "Hybrid should solve constraints, not create a maze", paragraphs: ["The homelab may remain valuable for learning, build infrastructure or non-production experimentation while the remote environment provides stable internet reachability. But production runtime should not silently depend on a home internet connection or a laptop unless that dependency is explicitly acceptable."] },
        { heading: "Trace cross-environment dependencies", paragraphs: ["Nexus, CI runners, DNS administration, backups and secrets may live in different places. Every cross-environment dependency needs a failure expectation: what happens to production if the homelab is offline for a day?" ] },
    ], practice: ["Draw Steward's homelab and remote components on one diagram.", "Mark every dependency crossing the boundary.", "For each dependency, decide whether runtime, deployment-only or optional access is acceptable and remove any accidental production dependency on the homelab."], questions: ["Why can a hybrid architecture be rational for Steward?", "What is dangerous about making production runtime depend on an unreliable home environment?"] },
];

const reviewLab: Lesson = {
    id: "cloud-architecture-and-cost-review-steward",
    title: "Lab: Review the Steward Internet Architecture",
    activities: [
        { id: "cloud-architecture-and-cost-review-steward-001", title: "Architecture Review Baseline", estimatedMinutes: 45, content: { type: "practical", objective: "Review the current Steward target against explicit architecture drivers.", scenario: "Before the Cloud Engineer milestone, subject the IaC-defined target to a design review rather than assuming that reproducibility makes it good architecture.", instructions: ["List the target architecture drivers and constraints.", "Trace the external request path, administrative path, deployment path and recovery path.", "Identify single points of failure and correlated failure domains.", "Record accepted risks separately from defects that must be corrected."], deliverables: ["Architecture review diagram", "Driver and constraint register", "Accepted-risk list"], completionCriteria: ["Architecture is evaluated against stated requirements.", "Failure domains are explicit.", "Accepted risks have reasons and owners rather than being accidental."] } },
        { id: "cloud-architecture-and-cost-review-steward-002", title: "Cost and Capacity Review", estimatedMinutes: 60, content: { type: "practical", objective: "Prove that the proposed Steward architecture has an understandable monthly cost and proportionate capacity.", scenario: "The design must be affordable enough to operate continuously or have explicit teardown rules.", instructions: ["Build the full monthly cost model from current IaC resources.", "Separate baseline from usage-dependent spend.", "Identify top cost drivers and likely idle waste.", "Set a budget threshold and right-sizing review trigger.", "Compare the target against the simpler VPS baseline."], deliverables: ["Monthly cost model", "Budget/control plan", "VPS-versus-target comparison"], completionCriteria: ["Cost assumptions are reviewable.", "The target has an explicit budget boundary.", "Extra architecture cost is justified by specific capability gains."] } },
        { id: "cloud-architecture-and-cost-review-steward-003", title: "Recovery and Failure Review", estimatedMinutes: 75, content: { type: "practical", objective: "Demonstrate that important Steward failures have a deliberate recovery path.", scenario: "Use architecture evidence rather than optimistic assumptions about provider resilience.", instructions: ["Define provisional RPO and RTO.", "Choose at least two safe failure scenarios such as application instance loss, blocked ingress or lost replaceable compute.", "Predict expected behavior before testing.", "Exercise or tabletop the recovery procedure and record actual dependencies.", "Update the architecture or runbook where assumptions prove false."], deliverables: ["RPO/RTO statement", "Failure/recovery evidence", "Corrected recovery assumptions"], completionCriteria: ["Recovery expectations are measurable.", "At least two failure paths are reasoned through with evidence.", "Recovery does not depend entirely on undocumented personal knowledge."] } },
        { id: "cloud-architecture-and-cost-review-steward-004", title: "Cloud Architecture Review", estimatedMinutes: 35, content: { type: "reflection", prompt: "Defend the final Steward internet architecture as though another engineer challenged every extra cloud component. Explain which risks it reduces, which risks remain accepted, its expected monthly cost, the recovery objectives it can realistically support, and why the design is preferable to simply keeping Steward on the original VPS. Then identify what still belongs to the Cloud Engineer milestone rather than to later Quality, Security or Reliability schools.", minimumCharacters: 350 } },
    ],
};

export const cloudArchitectureAndCostDeepLessons: Lesson[] = [...specs.map(richLesson), reviewLab];
