import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";
import { releaseEngineeringLab } from "./delivery-release-engineering-lab-deep";

const semver: LearningResource = { title: "Semantic Versioning", url: "https://semver.org/" };
const twelveFactor: LearningResource = { title: "The Twelve-Factor App — Build, release, run", url: "https://12factor.net/build-release-run" };
const githubReleases: LearningResource = { title: "GitHub documentation — Managing releases", url: "https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository" };
const dora: LearningResource = { title: "DORA — Software delivery performance", url: "https://dora.dev/" };
const sre: LearningResource = { title: "Google SRE Book — Release Engineering", url: "https://sre.google/sre-book/release-engineering/" };

function reading(id: string, title: string, intro: string, blocks: LessonBlock[], resources: LearningResource[]): Lesson {
    return {
        id: `release-engineering-${id}`,
        title,
        activities: [
            {
                id: `release-engineering-${id}-001`,
                title,
                estimatedMinutes: 45,
                content: { type: "reading", body: intro, blocks: [{ type: "paragraph", text: intro }, ...blocks, { type: "callout", tone: "steward", title: "Steward release checkpoint", body: "Use Steward's actual CI, Nexus artifact identities, homelab deployment and release evidence. A release claim is valid only when another engineer can trace it to immutable artifacts and observed runtime evidence." }, { type: "resources", title: "Continue learning", resources }] },
            },
            {
                id: `release-engineering-${id}-002`, title: `Apply: ${title}`, estimatedMinutes: 45,
                content: { type: "practical", objective: `Apply ${title} to Steward's delivery platform.`, scenario: "Steward already has CI, containerized delivery, Nexus-managed artifacts and a reproducible deployment path. Turn those capabilities into a controlled release process rather than adding another isolated tool.", instructions: ["Start from one real Steward source revision and identify the exact package and image artifacts produced from it.", "Define the release decision, evidence and owner relevant to this lesson.", "Exercise both the expected path and one failure, rejection or recovery path.", "Record evidence in a form another engineer could use without relying on your memory."], deliverables: ["Release-process evidence", "Immutable artifact identities", "Short engineering decision record"], completionCriteria: ["The source-to-release chain is traceable.", "A failed or rejected path is visible rather than silently bypassed.", "The learner can distinguish release state from deployment state."] },
            },
        ],
    };
}

const coreReleaseLessons: Lesson[] = [
    reading("release-candidates", "Release Candidates", "A release candidate is a specific, immutable build being evaluated for release. It is not merely 'whatever is currently on main' and it should not be rebuilt after approval under the same identity.", [
        { type: "heading", id: "candidate-identity", text: "Candidate identity", level: 2 }, { type: "paragraph", text: "A credible candidate connects source revision, CI run, application version, package versions, container digest, configuration assumptions and migration requirements. If those inputs change, you have a different candidate even when the intended feature set is unchanged." },
        { type: "code", language: "text", caption: "Example Steward release identity", code: "Release: steward-api 1.4.0-rc.2\nSource: 9d83f41\nImage: nexus.internal/steward/api@sha256:...\nsteward-common: 2.1.0\nMigration set: 0042-0044\nCI run: 1842" },
        { type: "heading", id: "build-once", text: "Build once, evaluate that build", level: 2 }, { type: "paragraph", text: "Testing one image and later rebuilding 'the same version' for production creates a gap between evidence and runtime. Promotion should change the candidate's release status or environment assignment, not its bytes." },
        { type: "callout", tone: "warning", title: "Do not certify a label", body: "A branch name, tag or version string can point at different content if your process permits mutation. Release evidence should ultimately resolve to immutable artifact identities such as package hashes and OCI digests." },
        { type: "heading", id: "candidate-contract", text: "Candidate acceptance contract", level: 2 }, { type: "list", items: ["Required CI checks are complete.", "Artifacts are published to the approved internal repository.", "Candidate identity is immutable and traceable to source.", "Known migration and configuration requirements are recorded.", "Known limitations and rollback constraints are visible."] },
    ], [semver, twelveFactor, sre]),
    reading("promotion-and-gates", "Promotion and Gates", "Promotion is the controlled movement of the same known release candidate through increasingly consequential states or environments. Gates exist to answer explicit risk questions, not to add ceremonial clicks.", [
        { type: "heading", id: "promotion-model", text: "Promotion is a state transition", level: 2 }, { type: "paragraph", text: "A useful release model might move a Steward candidate from built → verified → accepted for UAT → approved → production-deployed. The exact states matter less than making the transition criteria and evidence explicit." },
        { type: "code", language: "text", code: "source\n  ↓ CI\nimmutable candidate\n  ↓ automated verification gate\nUAT candidate\n  ↓ human risk/acceptance gate\napproved release\n  ↓ deployment automation\nproduction deployment" },
        { type: "heading", id: "gate-question", text: "Every gate needs a question", level: 2 }, { type: "list", items: ["Automated test gate: did the candidate satisfy defined technical checks?", "Migration gate: is the data transition understood and compatible with rollback strategy?", "Acceptance gate: has the required stakeholder accepted the behavior?", "Production gate: is this candidate authorized for this environment now?"] },
        { type: "paragraph", text: "A manual approval is justified when judgment is required. If a human is merely checking whether an automated test passed, encode that condition in the pipeline instead." }, { type: "heading", id: "same-artifact", text: "Promote the same artifact", level: 2 }, { type: "paragraph", text: "Environment-specific configuration may change, but the application artifact should remain the one already evaluated. Rebuilding between environments silently turns promotion into a new build." },
    ], [twelveFactor, sre]),
    reading("deployment-evidence", "Deployment Evidence", "A successful deployment command proves that automation finished, not that the intended release is healthy, reachable or even the version actually serving users.", [
        { type: "heading", id: "questions-evidence", text: "Questions deployment evidence must answer", level: 2 }, { type: "list", ordered: true, items: ["What release was intended?", "What immutable artifact was deployed?", "Where and when was it deployed?", "Which configuration and migration assumptions applied?", "Did the deployment mechanism complete?", "Did the runtime become healthy?", "Could an external client exercise the intended path?"] },
        { type: "heading", id: "runtime-proof", text: "Runtime proof beats pipeline optimism", level: 2 }, { type: "paragraph", text: "Combine deployment-system evidence with host/container state, health checks and a client-level verification. For Steward, a useful proof might include the deployed OCI digest, migration result, container health and a successful authenticated service-registry request." },
        { type: "code", language: "bash", caption: "Example post-deployment evidence", code: "docker inspect steward-api --format '{{.Image}} {{.State.Health.Status}}'\ncurl --fail https://steward.internal/health\ncurl --fail -H \"Authorization: Bearer $TOKEN\" https://steward.internal/api/services" },
        { type: "heading", id: "release-record", text: "The release record", level: 2 }, { type: "paragraph", text: "Keep a concise record linking release version, source commit, artifact digest, CI run, approval, target environment, deployment execution and verification result. This becomes the starting point for rollback and incident investigation." },
    ], [githubReleases, dora, sre]),
    reading("release-observability", "Release Observability", "Release observability is the ability to determine what changed, where it changed and whether system behavior changed with it. It is narrower than the full observability discipline taught later in Reliability Engineer.", [
        { type: "heading", id: "change-marker", text: "Make change visible", level: 2 }, { type: "paragraph", text: "When a deployment occurs, operators should be able to correlate the timestamp and release identity with health and behavior. At minimum, expose the running application version and preserve deployment timestamps and verification results." },
        { type: "heading", id: "before-after", text: "Compare before and after", level: 2 }, { type: "paragraph", text: "A post-deployment check should compare known baseline behavior with the new state. A health endpoint returning 200 is useful but insufficient if the service can no longer authenticate users, reach PostgreSQL or register services." },
        { type: "list", items: ["Running release identity", "Process/container health", "Critical dependency reachability", "One or more representative user/API paths", "Error evidence immediately around deployment", "Deployment timestamp and actor/automation identity"] },
        { type: "heading", id: "boundary", text: "Know the curriculum boundary", level: 2 }, { type: "paragraph", text: "Do not prematurely build the later Reliability Engineer monitoring stack just to complete this lesson. Release Engineering needs enough evidence to decide whether a release succeeded and whether to continue, stop or roll back." },
    ], [dora, sre]),
    reading("release-failure-handling", "Release Failure Handling", "A release process is incomplete until it defines what happens when deployment or verification fails. Failure handling starts before the deployment by preserving recoverable artifact and data states.", [
        { type: "heading", id: "failure-stages", text: "Failure can happen at different stages", level: 2 }, { type: "list", items: ["Candidate verification fails before promotion.", "Deployment automation fails before the new process starts.", "The new process starts but never becomes healthy.", "Health succeeds but representative application behavior fails.", "A migration succeeds but makes application rollback unsafe.", "The release appears healthy initially and then causes degradation."] },
        { type: "heading", id: "rollback-not-universal", text: "Rollback is not universally reversible", level: 2 }, { type: "paragraph", text: "Starting the previous container image may be safe for stateless application code but unsafe after an incompatible schema migration or irreversible external side effect. The release plan must state what can be rolled back, what requires forward repair and what data recovery assumptions exist." },
        { type: "code", language: "text", caption: "Failure decision sketch", code: "verification failed?\n├─ before state mutation → stop / redeploy last-known-good\n├─ compatible migration → rollback application if criteria permit\n└─ irreversible state change → contain + forward-fix/recovery plan" },
        { type: "heading", id: "last-known-good", text: "Preserve the last-known-good path", level: 2 }, { type: "paragraph", text: "Nexus retention, immutable image digests and deployment records should make the previous known-good release retrievable. A rollback procedure that depends on rebuilding an old commit during an incident adds unnecessary uncertainty." },
    ], [sre, twelveFactor]),
    reading("release-runbooks", "Release Runbooks", "A release runbook turns release knowledge into an executable operational procedure. It should help a competent engineer act safely under normal and failed conditions without reconstructing the process from chat history or memory.", [
        { type: "heading", id: "runbook-scope", text: "What a useful runbook contains", level: 2 }, { type: "list", items: ["Prerequisites and required access", "Candidate identity and evidence to verify", "Promotion/approval conditions", "Deployment command or pipeline entry point", "Migration and configuration steps", "Post-deployment verification", "Stop/rollback criteria", "Rollback or forward-recovery procedure", "Evidence to preserve", "Escalation or ownership information"] },
        { type: "heading", id: "commands-with-context", text: "Commands need context", level: 2 }, { type: "paragraph", text: "A runbook is not a dump of shell commands. For every consequential action, explain the expected state, what success looks like and what should cause the operator to stop. This prevents a command from being blindly executed against the wrong environment or release." },
        { type: "heading", id: "exercise-runbook", text: "Exercise the runbook", level: 2 }, { type: "paragraph", text: "The strongest review is to have another engineer follow the procedure or to execute it yourself from a clean context. Record unclear assumptions and update the runbook. Documentation that has never been exercised is still a hypothesis." },
        { type: "callout", tone: "note", title: "Keep it close to the system", body: "Version the Steward release runbook with the delivery configuration or in an equally reviewable engineering repository. Changes to the release process should update the procedure in the same change where practical." },
    ], [sre, githubReleases]),
];

export const releaseEngineeringDeepLessons: Lesson[] = [...coreReleaseLessons, releaseEngineeringLab];
