import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const bash: LearningResource = { title: "GNU Bash manual", url: "https://www.gnu.org/software/bash/manual/" };
const shellcheck: LearningResource = { title: "ShellCheck", url: "https://www.shellcheck.net/" };
const make: LearningResource = { title: "GNU Make manual", url: "https://www.gnu.org/software/make/manual/" };
const twelveFactor: LearningResource = { title: "The Twelve-Factor App — Config", url: "https://12factor.net/config" };

function richLesson(id: string, title: string, intro: string, outcomes: string[], sections: Array<{ heading: string; paragraphs: string[]; code?: { language: string; code: string } }>, practice: string[], questions: string[], resources: LearningResource[]): Lesson {
    const blocks: LessonBlock[] = [
        { type: "paragraph", text: intro },
        { type: "heading", id: "learning-outcomes", text: "Learning outcomes", level: 2 },
        { type: "list", items: outcomes },
    ];
    for (const section of sections) {
        const anchor = section.heading.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
        blocks.push({ type: "heading", id: anchor, text: section.heading, level: 2 });
        for (const paragraph of section.paragraphs) blocks.push({ type: "paragraph", text: paragraph });
        if (section.code) blocks.push({ type: "code", language: section.code.language, code: section.code.code });
    }
    blocks.push({ type: "callout", tone: "steward", title: "Steward automation rule", body: "Automate a repeated Steward developer or operator task only when the automation makes intent, failure and rerun behavior clearer than the manual sequence it replaces." });
    blocks.push({ type: "resources", title: "Required and supporting reading", resources });

    const lessonId = `automation-and-shell-${id}`;
    return {
        id: lessonId,
        title,
        activities: [
            { id: `${lessonId}-reading`, title, estimatedMinutes: 35, content: { type: "reading", body: intro, blocks } },
            { id: `${lessonId}-practice`, title: `${title}: Practice`, estimatedMinutes: 45, content: { type: "practical", objective: `Apply ${title.toLowerCase()} to a real Steward workflow.`, scenario: "Use the current Steward repository and homelab. Prefer small scripts and visible failure behavior over clever shell one-liners.", instructions: practice, deliverables: ["Versioned script or task definition", "Successful execution evidence", "One documented failure-path observation"], completionCriteria: ["The automation has a clear input/output contract.", "Failures return non-zero status and are visible.", "Rerunning does not create unexplained destructive side effects."] } },
            { id: `${lessonId}-check`, title: `${title}: Knowledge Check`, estimatedMinutes: 10, content: { type: "reflection", prompt: questions.map((q, i) => `${i + 1}. ${q}`).join("\n") } },
        ],
    };
}

export const automationAndShellDeepLessons: Lesson[] = [
    richLesson("shell-scripting", "Shell Scripting for Engineers", "Shell scripts are small operational programs. The quality bar should therefore be the same as for other code: explicit inputs, readable control flow, safe quoting, predictable outputs and visible failure.", ["Explain when shell is a good automation tool.", "Write scripts with explicit interpreter and strict-enough failure behavior.", "Quote data correctly.", "Prefer readable steps over fragile command chains."], [
        { heading: "Use shell for orchestration", paragraphs: ["Shell is strongest when coordinating existing command-line tools, files and processes. Once parsing, state management or business logic becomes complex, another language may provide safer structure.", "A deployment helper that calls git, docker and curl can be a good shell script. A large configuration engine implemented as hundreds of lines of string parsing usually is not."] },
        { heading: "Start scripts deliberately", paragraphs: ["Use a shebang, fail on important errors, quote variable expansion and make expected inputs explicit. Strict modes are tools, not magic: understand how each option changes behavior."], code: { language: "bash", code: "#!/usr/bin/env bash\nset -euo pipefail\n\nrepo_root=\"${1:-$PWD}\"\ncd \"$repo_root\"\nprintf 'Building Steward from %s\\n' \"$(git rev-parse --short HEAD)\"" } },
    ], ["Create a script that reports the current Steward commit and runs one existing validation/build command.", "Add argument validation and quoted paths.", "Trigger one invalid-input failure and confirm a non-zero exit status.", "Run ShellCheck and review every finding instead of blindly suppressing it."], ["Why is shell often good for orchestration but weak for complex domain logic?", "What bug can unquoted variable expansion introduce?", "Why should strict-mode options be understood individually?"], [bash, shellcheck]),
    richLesson("pipes-exit-codes", "Pipes, Exit Codes and Failure", "Automation is trustworthy only when failure propagates correctly. Shell pipelines can hide errors unless the script deliberately reasons about exit status and stderr.", ["Explain process exit status.", "Distinguish stdout from stderr.", "Understand pipeline failure behavior.", "Design automation that stops or continues intentionally."], [
        { heading: "Exit status is part of the contract", paragraphs: ["By convention, zero means success and non-zero means failure. Callers such as CI systems rely on this signal; printing an error while returning zero creates false success."] },
        { heading: "Pipelines need special attention", paragraphs: ["Without pipefail, a pipeline commonly reports only the status of its last command. An earlier command can fail while a later command succeeds, masking the real failure."], code: { language: "bash", code: "set -o pipefail\n\ncurl --fail --silent http://steward.local/health \\\n  | jq -e '.status == \"ok\"'" } },
    ], ["Write a health verification pipeline for Steward.", "Test healthy response, connection failure and malformed output.", "Capture the exit status for each case.", "Separate operator-facing errors to stderr from machine-consumable stdout where useful."], ["Why can a pipeline return success even when an earlier command failed?", "What is stderr for?", "Why is exit status more reliable for automation than parsing human log text?"], [bash]),
    richLesson("environment", "Environment Variables", "Environment variables are process inputs, not a secret-management system and not a substitute for configuration design. They work well when configuration changes between deployments and remains outside the artifact.", ["Explain environment inheritance.", "Use environment variables for deployment-varying configuration.", "Distinguish configuration from secrets handling.", "Avoid silently relying on undeclared ambient state."], [
        { heading: "Configuration follows the process", paragraphs: ["A child process inherits environment from its parent unless changed. This makes environment useful for injecting database endpoints, runtime mode and similar values without rebuilding the artifact."] },
        { heading: "Validate required variables", paragraphs: ["Automation should fail early when required configuration is missing instead of allowing an application to fail later with an obscure error."], code: { language: "bash", code: ": \"${DATABASE_URL:?DATABASE_URL is required}\"\n: \"${STEWARD_ENV:?STEWARD_ENV is required}\"\nexec ./start-steward" } },
    ], ["List Steward configuration that should vary by environment.", "Classify each value as ordinary configuration or sensitive material.", "Update one helper script to validate mandatory variables before performing work.", "Demonstrate failure when one required value is absent."], ["Why are environment variables useful for build-once/promote-many?", "Why does putting a secret in an environment variable not automatically solve secret management?", "What is ambient configuration?"], [twelveFactor, bash]),
    richLesson("repeatable", "Repeatable Automation Scripts", "A useful script makes a procedure reproducible across engineers and repeated runs. That requires preconditions, deterministic steps, cleanup behavior and meaningful output.", ["Turn an undocumented command sequence into an explicit procedure.", "Check preconditions before mutation.", "Use temporary resources safely.", "Make repeated execution understandable."], [
        { heading: "Declare preconditions", paragraphs: ["Check required commands, files, permissions and target environment before making changes. Partial mutation followed by a preventable error is expensive operational behavior."] },
        { heading: "Control temporary state", paragraphs: ["Use mktemp for temporary files and traps for cleanup when appropriate. Avoid fixed paths that collide across runs or users."], code: { language: "bash", code: "tmp_file=$(mktemp)\ncleanup() { rm -f \"$tmp_file\"; }\ntrap cleanup EXIT\n\ncommand -v curl >/dev/null || { echo 'curl is required' >&2; exit 1; }" } },
    ], ["Select one repeated Steward setup or verification procedure.", "Write precondition checks before mutation.", "Make temporary state unique and cleaned up.", "Run the script twice and explain every difference in output or state."], ["Why should preconditions be checked before mutation?", "What problem does mktemp solve?", "What does a cleanup trap protect against?"], [bash, shellcheck]),
    richLesson("make", "Make and Task Automation", "A task runner gives engineers stable names for common workflows. The value is not Make itself; it is a discoverable interface over commands that would otherwise drift across README snippets and shell history.", ["Explain the role of task automation.", "Create small stable developer/operator targets.", "Understand Make dependencies and phony targets.", "Keep task targets thin and composable."], [
        { heading: "Name outcomes, not command trivia", paragraphs: ["Targets such as test, build, verify and release-check communicate intent better than asking every engineer to remember the underlying command sequence."] },
        { heading: "Keep the interface simple", paragraphs: ["Make can orchestrate scripts while scripts contain non-trivial logic. This prevents an unreadable Makefile from becoming the entire delivery system."], code: { language: "makefile", code: ".PHONY: verify build\n\nverify:\n\t./scripts/verify.sh\n\nbuild: verify\n\t./scripts/build.sh" } },
    ], ["Create a small task interface for two or three current Steward workflows.", "Ensure at least one target depends on another meaningful prerequisite.", "Keep complex logic in a script instead of embedding it in the task file.", "Document how a new engineer discovers available tasks."], ["Why are stable task names useful?", "When should logic move out of a Makefile into a script?", "What does .PHONY communicate?"], [make, bash]),
    richLesson("idempotency", "Idempotency Concepts", "Idempotent automation can be applied repeatedly without accumulating unintended changes. It is a central property of reliable delivery and configuration work because reruns are inevitable after partial failure.", ["Define idempotency operationally.", "Distinguish idempotent from merely successful reruns.", "Use observe-before-change patterns.", "Recognize operations that need guards or unique identifiers."], [
        { heading: "Converge toward intended state", paragraphs: ["An idempotent operation asks what state exists and changes only what is necessary. Appending the same line on every run is repeatable execution but not idempotent behavior."] },
        { heading: "Reruns happen after uncertainty", paragraphs: ["Network timeouts and interrupted deployments can leave unknown partial state. Automation that tolerates safe rerun reduces the pressure to diagnose every partial step manually before continuing."], code: { language: "bash", code: "if ! grep -qxF 'STEWARD_ENV=uat' \"$config\"; then\n  printf '%s\\n' 'STEWARD_ENV=uat' >> \"$config\"\nfi" } },
    ], ["Find one non-idempotent step in a Steward setup/deployment procedure.", "Rewrite it to inspect current state before mutation.", "Execute it three times.", "Compare state after each run and explain why later runs converge rather than accumulate changes."], ["What is the difference between repeatable and idempotent?", "Why does idempotency help after partial failure?", "Can every operation be made naturally idempotent?"], [bash]),
    {
        id: "automation-and-shell-lab",
        title: "Lab: Automate Steward Developer and Operator Tasks",
        activities: [
            { id: "automation-and-shell-lab-brief", title: "Automation Brief", estimatedMinutes: 20, content: { type: "reading", body: "Turn the highest-value repeated Steward commands into a small, reviewable automation interface. The goal is not to automate everything; it is to remove fragile repetition while preserving visibility.", blocks: [
                { type: "heading", id: "scope", text: "Choose useful scope", level: 2 },
                { type: "list", items: ["One developer workflow such as verify/build", "One operator workflow such as health/status/log inspection", "One environment/configuration validation", "One operation that must prove safe rerun behavior"] },
                { type: "callout", tone: "warning", title: "Do not hide operations", body: "A wrapper that makes it impossible to see what failed is worse than the manual commands it replaces. Preserve useful command output and exit status." },
            ] } },
            { id: "automation-and-shell-lab-build", title: "Build the Steward Automation Interface", estimatedMinutes: 120, content: { type: "practical", objective: "Create a small shell/task automation layer for Steward developer and operator workflows.", scenario: "Use only workflows that already exist in the Steward repository or homelab. Do not invent delivery infrastructure that belongs to later modules.", instructions: ["Inventory repeated commands and choose the smallest high-value set.", "Implement scripts with explicit inputs, quoting, precondition checks and meaningful exit codes.", "Expose common entry points through Make or an equivalent task interface.", "Validate required environment/configuration before work starts.", "Run ShellCheck or equivalent static analysis on shell scripts.", "Demonstrate at least one expected failure and verify that automation returns non-zero status.", "Run one mutating workflow repeatedly and show that state converges rather than accumulates unintended changes.", "Document commands, expected outputs and recovery notes."], deliverables: ["Versioned scripts/task definitions", "Short command reference", "Successful run evidence", "Failure propagation evidence", "Idempotency/rerun evidence"], completionCriteria: ["A new engineer can run common workflows without reconstructing shell history.", "Failures are visible to humans and callers.", "Configuration expectations are explicit.", "At least one mutating workflow is demonstrated safe to rerun.", "The automation remains small enough to understand before the Containers and CI modules build on it."] } },
            { id: "automation-and-shell-lab-review", title: "Automation Review", estimatedMinutes: 15, content: { type: "reflection", prompt: "Which manual Steward step did you deliberately leave unautomated, and what additional repetition, risk or evidence would justify automating it later?" } },
        ],
    },
];
