import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const missingShell:LearningResource={title:"MIT Missing Semester — The Shell",url:"https://missing.csail.mit.edu/2020/course-shell/",kind:"course"};
const gitBook:LearningResource={title:"Pro Git — Git Basics",url:"https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository",kind:"reference"};
const gitBranch:LearningResource={title:"Pro Git — Git Branching",url:"https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell",kind:"reference"};
const mdnHttp:LearningResource={title:"MDN — Overview of HTTP",url:"https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview",kind:"reference"};
const missingData:LearningResource={title:"MIT Missing Semester — Data Wrangling",url:"https://missing.csail.mit.edu/2020/data-wrangling/",kind:"course"};

type Spec={id:string;title:string;body:string;practice:string[];resources:LearningResource[]};
function make(s:Spec):Lesson{const blocks:LessonBlock[]=[{type:"paragraph",text:s.body},{type:"callout",tone:"note",title:"Boundary",body:"This lesson builds enough workstation fluency to begin Builder. Platform Builder later teaches operating-system, Linux and networking administration in depth; Delivery Engineer later teaches delivery automation and advanced CI/CD workflows."},{type:"resources",title:"Continue learning",resources:s.resources}];return{id:`engineering-workbench-${s.id}`,title:s.title,activities:[{id:`engineering-workbench-${s.id}-reading`,title:s.title,estimatedMinutes:50,content:{type:"reading",body:s.body,blocks}},{id:`engineering-workbench-${s.id}-lab`,title:`Lab: ${s.title}`,estimatedMinutes:75,content:{type:"practical",objective:`Demonstrate working fluency with ${s.title}.`,scenario:"Use a disposable local workspace and a small repository. Preserve command/output evidence and explain what each important operation changes.",instructions:s.practice,deliverables:["Working artifact or repository evidence","Short command/inspection log","Explanation of one mistake or failure and its correction"],completionCriteria:["The learner can repeat the workflow without copying an opaque command sequence.","Commands are chosen from a mental model of files/repository/network behavior.","Destructive operations are recognized before execution."]}}]}}
const specs:Spec[]=[
{id:"shell-filesystem",title:"Terminal, Shell and Filesystem",body:"The terminal is an engineering interface, not a list of magic commands. Learn current/parent/root/home paths, absolute versus relative paths, files/directories, hidden files, quoting, standard input/output/error, pipes, redirection, environment variables, exit status and command help. Build the habit of inspecting state before changing it.",practice:["Navigate and create a small nested workspace using absolute and relative paths.","Inspect files with safe read/search commands; redirect and pipe output deliberately.","Set/read a temporary environment variable and inspect a command exit status.","Use built-in help/manual information to discover an unfamiliar command option.","Demonstrate one potentially destructive command only on disposable data and explain its scope before running it."],resources:[missingShell,missingData]},
{id:"git-version-control",title:"Git and Version-Control Workflow",body:"Git records a graph of project history. Learn working tree, staging area, commits, branches, HEAD, diffs, remotes and merge/conflict concepts before memorizing team workflows. A commit should represent an understandable change. Inspect before staging, stage intentionally, review the diff, commit, and know how to recover from common local mistakes without deleting history blindly.",practice:["Initialize a repository and make several focused commits.","Use status and diff before staging/committing.","Create a feature branch, change the same file meaningfully and integrate it back.","Create and resolve a controlled merge conflict while explaining the competing versions.","Add a remote or explain fetch/pull/push semantics using a safe repository; do not force-push as a routine fix."],resources:[gitBook,gitBranch]},
{id:"developer-inspection",title:"Developer Inspection: Processes, Ports and Text",body:"Before administering systems, a developer should be able to inspect the local environment enough to answer basic questions: what process is running, what command started it, what port it listens on, where output/logs appear, and whether a file or environment value contains the expected data. The goal is diagnosis, not Linux administration.",practice:["Start a small local HTTP server or development process.","Identify the process and listening endpoint using tools available on your OS.","Capture stdout/stderr and search relevant text output.","Stop/restart the process intentionally and distinguish process failure from application response failure.","Record the minimal evidence another engineer would need to reproduce the observation."],resources:[missingShell,mdnHttp]},
{id:"http-command-line",title:"HTTP from the Command Line",body:"Builder will teach web/API engineering, but the learner should first experience a request as observable data. Use a command-line HTTP client to inspect URL, method, status, headers and body. Distinguish DNS/connection/TLS failures from an HTTP response at a conceptual level without attempting to learn networking administration yet.",practice:["Send GET and POST requests to a safe public or local test endpoint.","Inspect status, selected headers and response body separately.","Change one request input and compare the response.","Trigger or observe a client error and distinguish it from an HTTP 4xx/5xx response.","Save one reproducible request as evidence for the Builder starting point."],resources:[mdnHttp]},
];
export const engineeringApprenticeWorkbenchDeepLessons:Lesson[]=specs.map(make);
