import type { Lesson } from "./lesson";

function practical(id: string, title: string, objective: string, scenario: string, instructions: string[], deliverables: string[], completionCriteria: string[], estimatedMinutes = 120): Lesson {
    return { id, title, activities: [{ id: `${id}-lab`, title, estimatedMinutes, content: { type: "practical", objective, scenario, instructions, deliverables, completionCriteria } }] };
}

export const configurationManagementDeepLessons: Lesson[] = [
    practical("config-management-model", "Desired State, Inventory and Idempotence", "Establish configuration management as declared host state rather than remote shell scripting.", "The Proxmox estate now has multiple Rocky guests. Repeating SSH commands manually causes undocumented drift.", ["Create an Ansible inventory grouped by infrastructure and workload role using names from the operated DNS service.", "Record connection/privilege boundaries and keep credentials out of Git.", "Build a read-only facts/baseline play that reports OS, kernel, selected packages, services and mounts.", "Run it twice and distinguish discovery from desired-state enforcement.", "Define which host properties belong in image/template creation, configuration management, application deployment or secrets management."], ["Versioned inventory without secrets", "Fleet baseline evidence", "Responsibility map"], ["At least two Rocky guests are represented.", "Inventory groups have operational meaning.", "Configuration management is distinguished from provisioning and deployment."]),
    practical("config-management-rocky-baseline", "Reusable Rocky Baseline Role", "Encode a bounded enterprise-Linux baseline as reusable Ansible roles/tasks.", "New Rocky guests should converge on a known operational baseline without manual setup.", ["Create a role that manages a justified package set, a non-secret configuration file/template, one systemd service state and a bounded firewalld rule or equivalent baseline setting.", "Use handlers only when a changed resource requires restart/reload.", "Apply the role to a canary guest and verify the resulting OS state independently of Ansible output.", "Apply to a second guest only after the canary is healthy.", "Run again and prove an unchanged healthy host reports idempotent state."], ["Baseline role/playbook", "Canary and second-host evidence", "Independent state verification", "Idempotent second run"], ["Desired state is encoded with modules rather than opaque shell loops.", "A handler is change-driven.", "A second run does not manufacture changes."]),
    practical("config-management-drift", "Configuration Drift Detection and Repair", "Detect deliberate drift, explain its cause and converge safely.", "An administrator changes a managed file/service manually and the fleet no longer matches the declared baseline.", ["Capture a healthy managed baseline.", "Introduce one safe manual drift on a disposable/canary guest.", "Use Ansible check/diff or a justified read-only comparison to expose the difference before changing it.", "Decide whether code or host is authoritative; if host change is legitimate, update code first, otherwise converge the host.", "Apply the chosen repair and independently verify state.", "Record the incident and rule for emergency manual changes."], ["Drift evidence", "Authority decision", "Repair evidence", "Emergency-change rule"], ["Drift is detected before repair.", "The declared source of truth is explicit.", "Manual emergency work has a reconciliation path."]),
    practical("config-management-secrets-failure", "Secrets, Failure and Safe Fleet Changes", "Operate configuration changes without leaking secrets or turning one bad change into a fleet-wide outage.", "A baseline change needs sensitive input and could restart a service across several hosts.", ["Keep secret values outside committed inventory/vars and integrate with the later/current Vault boundary when available; until then use a protected local mechanism and document the migration.", "Create a non-secret configuration change that triggers a service reload/restart.", "Use serial/canary execution so one host changes first.", "Introduce a deterministic bad canary configuration, prove validation/health check prevents broader rollout, and preserve failure evidence.", "Fix the declared configuration and converge the canary then remaining host(s).", "Verify logs/evidence do not expose secret material."], ["Secret-handling boundary", "Canary failure evidence", "Corrected fleet convergence", "Leakage check"], ["A bad canary does not propagate automatically.", "Secrets are absent from Git/evidence.", "Recovery changes the declared state rather than hand-editing every host."]),
    practical("config-management-milestone", "Milestone: Build and Operate the Rocky Configuration Baseline", "Prove that the Rocky fleet can be configured, changed and recovered from declared Ansible state.", "The individual Ansible exercises now need to become one operating configuration-management system for the homelab rather than a collection of playbooks.", ["Apply the maintained baseline role to at least two Rocky guests using the authoritative inventory.", "Prove a clean second run is idempotent.", "Introduce one safe managed-file or service drift and detect it before repair.", "Repair the drift from declared configuration and independently verify the resulting host state.", "Introduce a deterministic bad canary change and prove it cannot spread to the remaining host before health validation succeeds.", "Correct the declared state, converge the fleet and produce the configuration-management operations runbook."], ["Authoritative inventory and baseline role", "Two-host convergence evidence", "Idempotence evidence", "Drift detection and repair evidence", "Canary failure containment evidence", "Configuration-management runbook"], ["At least two hosts converge from the same declared baseline.", "Manual drift is repaired from source-controlled desired state.", "A failed canary prevents wider rollout.", "Another engineer can apply and troubleshoot the baseline from the runbook."], 180),
    practical("config-management-reassessment", "Reassess Image, Ansible and Platform Ownership", "Define one sustainable configuration-management operating model and its limits.", "TSA now uses Proxmox templates, Ansible, container/Kubernetes delivery and Vault; overlapping ownership can create configuration fights.", ["Create an ADR assigning immutable/base-image concerns, Rocky host baseline, application deployment, runtime orchestration and secrets to explicit owners.", "Identify settings that must not be managed simultaneously by template baking and Ansible without a lifecycle rule.", "Define inventory lifecycle when a VM is created/retired.", "Define evidence that would justify dynamic inventory or a larger enterprise configuration platform later.", "Retire any duplicate manual setup instructions made obsolete by the declared baseline."], ["Configuration ownership ADR", "Inventory lifecycle", "Tool-expansion threshold", "Retired duplication list"], ["Every major configuration class has one authority.", "The model avoids a configuration-management tool zoo.", "The learner can explain when Ansible is no longer the right boundary."], 90),
];
