import type { Activity } from "../activities";
import type { Lesson } from "./lesson";

const pathId = "capstone-production-readiness";
const reviewStandard = "Production readiness is an evidence-based release decision, not a checklist completion exercise. Every conclusion must distinguish demonstrated behavior, assumptions, accepted residual risk and unresolved gaps.";

function reading(id: string, title: string, body: string, evidence: string[]): Lesson {
  const activity: Activity = { id: `${pathId}-${id}-001`, title, estimatedMinutes: 55, content: { type: "reading", body: `${body}\n\nRequired readiness evidence:\n${evidence.map((x) => `- ${x}`).join("\n")}\n\n${reviewStandard}` } };
  return { id: `${pathId}-${id}`, title, activities: [activity] };
}

function practical(id: string, title: string, objective: string, instructions: string[], deliverables: string[], completionCriteria: string[], estimatedMinutes: number): Lesson {
  return { id: `${pathId}-${id}`, title, activities: [{ id: `${pathId}-${id}-001`, title, estimatedMinutes, content: { type: "practical", objective, scenario: "The capstone has completed its first end-to-end release and now needs a formal production-readiness decision. Review the system as if real users, data, operating costs and incident consequences depend on it. Do not invent evidence to satisfy the rubric; unresolved gaps may legitimately block release.", instructions, deliverables, completionCriteria } }] };
}

export const capstoneProductionReadinessDeepLessons: Lesson[] = [
  reading("deployment-readiness", "Deployment Readiness", "Confirm that the release can be produced, configured, deployed, verified and recovered through a repeatable path. Readiness includes artifact identity, environment configuration, migrations, secrets, dependencies, rollback or forward-recovery, release ownership and post-deploy verification. A successful one-off deployment is weaker evidence than a reproducible process.", ["Release artifact/version is traceable to source and build evidence.", "Deployment and migration path is repeatable in the target environment.", "Rollback or forward-recovery conditions and verification are exercised or explicitly risk-accepted."]),
  reading("observability", "Observability", "Verify that operators can detect user-impacting degradation, understand service health and diagnose important failures using the implemented telemetry. Readiness is not measured by dashboard count. Every critical signal should answer an operational question and have an owner or response expectation where action is required.", ["Health/service indicators map to meaningful user or system outcomes.", "A demonstrated failure can be diagnosed from logs/metrics/traces or equivalent telemetry.", "Alert/noise gaps and sensitive-data concerns are recorded."]),
  reading("security-assessment", "Security Assessment", "Assess the implemented system against its current threat model and attack surface. Combine automated scanning with targeted review and controlled testing appropriate to the domain. Findings must be triaged by impact and exploitability; unresolved security risk needs an explicit treatment, acceptance or release-blocking decision.", ["Threat model reflects deployed boundaries and dependencies.", "Security test/scan/manual-review evidence covers material threats.", "Findings have severity, owner, treatment status and residual-risk decision."]),
  reading("performance-evidence", "Performance Evidence", "Test performance against realistic workload assumptions and user-relevant thresholds rather than arbitrary benchmark numbers. Measure latency, throughput, saturation or resource behavior where relevant, identify bottlenecks and state the limits of the test. Performance claims without workload context are not meaningful.", ["Workload model and test assumptions are explicit.", "Observed results are compared with stakeholder-relevant thresholds.", "Capacity limits, bottlenecks and untested scenarios are documented."]),
  reading("reliability-and-failure-testing", "Reliability and Failure Testing", "Challenge the system under credible dependency, network, process, resource or data-path failures. Validate timeout, retry, isolation, degradation and recovery behavior only where those mechanisms are actually part of the design. The purpose is to learn how the system fails, not to manufacture a resilience score.", ["At least one material failure mode is exercised end to end.", "Observed behavior is compared with intended behavior and service objectives.", "Unexpected failure behavior creates remediation or residual-risk records."]),
  reading("backup-and-recovery", "Backup and Recovery", "Demonstrate that important state can be recovered, not merely that backups are configured. Verify backup integrity, restore procedure, permissions, retention and recovery objectives. If the system can rebuild state from another authoritative source, prove that recovery path instead of creating ceremonial backups.", ["Recovery strategy matches the system's data ownership model.", "A restore/rebuild exercise produces verifiable usable state.", "Observed recovery time/data loss is compared with stated objectives or accepted assumptions."]),
  reading("runbooks", "Runbooks", "Ensure operators have concise, exercised guidance for high-consequence or recurring operational actions. Runbooks need prerequisites, commands or actions, expected observations, verification, stop/rollback conditions and escalation. A document that has never been exercised is a hypothesis.", ["Critical runbook(s) are discoverable and owned.", "At least one runbook is exercised against the real environment.", "Exercise findings result in documented corrections where needed."]),
  reading("operational-ownership", "Operational Ownership", "Confirm who owns the service after release: monitoring, incident response, access, dependency updates, maintenance, capacity, backups, changes and stakeholder communication. Ownership must include decision rights and escalation paths, not merely a team name.", ["Service owner and operational responsibilities are explicit.", "Escalation and out-of-hours assumptions are documented where relevant.", "Recurring maintenance and dependency responsibilities have owners/cadence."]),
  reading("risk-and-control-evidence", "Risk and Control Evidence", "Refresh material risks and verify that claimed controls are both appropriately designed and operating. Separate issue status from future uncertainty, and control existence from control effectiveness. Release readiness depends on residual exposure and decision authority, not whether every risk is closed.", ["Risk register reflects current implementation evidence.", "Representative controls have operating evidence.", "Material residual risks have treatment/acceptance/escalation decisions."]),
  reading("dependency-and-supply-chain-readiness", "Dependency and Supply-chain Readiness", "Review external services, open-source packages and internal products as operational dependencies. Confirm approved source, version/provenance, support status, ownership, compatibility, vulnerability exposure and continuity/exit thinking proportionate to criticality. Reused TSA products must remain governed as dependencies rather than copied conveniences.", ["Critical dependency inventory identifies owner/source/version/support status.", "Provenance or equivalent trust evidence exists for release artifacts/dependencies where applicable.", "Unsupported, vulnerable or high-concentration dependencies have explicit decisions."]),
  reading("cost-and-capacity-review", "Cost and Capacity Review", "Validate whether the implemented system remains economically and operationally plausible under expected usage. Compare measured resource behavior with the proposal's cost assumptions, identify dominant cost drivers and note scaling thresholds. More capacity is not automatically better if it buys no required outcome.", ["Current operating-cost estimate is based on implemented architecture.", "Capacity assumptions reference performance/resource evidence.", "Material cost surprises or scaling thresholds have decisions/owners."]),
  reading("release-decision", "Release Decision", "Synthesize readiness evidence into an accountable decision: release, release with conditions, defer, or redesign. The decision should state scope, evidence, accepted residual risks, blocking gaps, owners and follow-up triggers. A checklist cannot make the decision; accountable engineering judgment must.", ["Decision clearly distinguishes blockers, accepted risks and follow-up conditions.", "Decision authority and ownership are explicit.", "Evidence links allow another reviewer to challenge the conclusion."]),
  practical("lab-run-the-capstone-production-readiness-review", "Lab: Run the Capstone Production Readiness Review", "Conduct and defend a full production-readiness review of the independent capstone and make an evidence-backed release decision.", ["Assemble a readiness evidence index covering deployment, observability, security, performance, failure behavior, recovery, operations, risk/controls, dependencies and cost/capacity.", "Run or refresh the most material evidence rather than relying on stale screenshots or proposal assumptions.", "Identify contradictions: green CI with weak operational evidence, configured backups without restore proof, alerts without actionability, standards without operating controls, or dependencies without owners.", "Classify every material gap as blocker, condition, accepted residual risk or future improvement; assign owner and evidence required for closure.", "Hold a mock readiness review with engineering, operations and risk/security perspectives. Record challenge, dissent and changed conclusions.", "Issue a final release / conditional release / defer / redesign decision and update authoritative artifacts, runbooks, risks and roadmap accordingly."], ["Production-readiness evidence index", "Deployment/observability/security/performance/reliability/recovery evidence", "Operational ownership and runbook evidence", "Risk/control and dependency readiness summary", "Cost/capacity review", "Readiness findings and decision log", "Final release decision with conditions, owners and follow-up"], ["Every material readiness claim is traceable to current evidence or explicitly labeled assumption.", "At least one failure or recovery behavior is demonstrated rather than inferred from configuration.", "Security and dependency findings are triaged with explicit residual-risk decisions.", "Operational ownership and runbooks are usable by another engineer.", "The decision can legitimately block release; passing the module does not require a release decision of 'go'.", "The learner can defend trade-offs, uncertainty and decision authority under stakeholder challenge."], 480),
];
