import type { Activity } from "../activities";
import type { Lesson } from "./lesson";

const pathId = "capstone-independent-build";
const review = "Professional Engineer standard: build from the approved proposal, but treat implementation evidence as permission to revise it. Every consequential choice must remain explainable in this new domain; working software does not excuse missing quality, security, reliability, operational or decision evidence.";

function reading(id: string, title: string, body: string, evidence: string[]): Lesson {
  const activity: Activity = { id: `${pathId}-${id}-001`, title, estimatedMinutes: 55, content: { type: "reading", body: `${body}\n\nRequired build evidence:\n${evidence.map((x) => `- ${x}`).join("\n")}\n\n${review}` } };
  return { id: `${pathId}-${id}`, title, activities: [activity] };
}

function practical(id: string, title: string, objective: string, instructions: string[], deliverables: string[], completionCriteria: string[], estimatedMinutes: number): Lesson {
  return { id: `${pathId}-${id}`, title, activities: [{ id: `${pathId}-${id}-001`, title, estimatedMinutes, content: { type: "practical", objective, scenario: "The capstone is a second substantial system in a new problem domain, created from a blank repository. Steward is evidence that you learned the journey, not an implementation template. Reuse TSA internal products only when their contracts fit and preserve independent ownership of capstone-specific code and decisions.", instructions, deliverables, completionCriteria } }] };
}

export const capstoneIndependentBuildDeepLessons: Lesson[] = [
  reading("start-from-a-blank-repository", "Start from a Blank Repository", "Create a genuinely independent repository and establish only the minimum structure needed to begin. Do not fork Steward, copy its domain model, or transplant its architecture. The blank start is an assessment mechanism: it reveals whether you can reconstruct sound engineering practices from principles rather than memory of one codebase.", ["Repository history begins with the capstone rather than Steward-derived source.", "README states problem, current scope, local bootstrap and authoritative proposal links.", "Initial structure is justified by the capstone rather than TSA convention alone."]),
  reading("establish-engineering-conventions", "Establish Engineering Conventions", "Create lightweight conventions that make collaboration and automation predictable: language/tool versions, formatting/linting, commit/branch expectations, configuration boundaries, dependency handling, local commands and review expectations. Automate deterministic rules and keep human review focused on design and risk.", ["Reproducible bootstrap and documented toolchain versions.", "Automated formatting/linting/static checks appropriate to the stack.", "A small conventions record with rationale and ownership."]),
  reading("model-the-domain", "Model the Domain", "Turn the discovery/proposal model into executable domain concepts while learning from implementation. Protect invariants near the model that owns them, keep external representations from silently defining the domain, and update the glossary/decisions when real code exposes incorrect assumptions.", ["Executable model for important entities/value concepts/workflows.", "Tests or other evidence for critical invariants and state transitions.", "Recorded model changes when implementation contradicts the proposal."]),
  reading("implement-the-system", "Implement the System", "Build vertical capabilities that deliver observable stakeholder behavior rather than completing layers in isolation. Keep boundaries coherent, errors intentional, configuration externalized and interfaces understandable. Prefer the simplest code that preserves the system's required qualities; abstraction is earned by repeated or structural need.", ["Thin end-to-end increments tied to capstone outcomes.", "Clear handling of validation, errors and external interactions.", "Reviewable commits/PRs showing incremental integration rather than one final dump."]),
  reading("design-and-evolve-the-data", "Design and Evolve the Data", "Implement persistence from domain and operational requirements. Define keys, constraints, indexes, transaction boundaries, migrations and data lifecycle deliberately. Schema evolution must preserve deployability and recoverability; a migration that works only on an empty developer database is insufficient evidence.", ["Versioned schema/migrations and integrity constraints.", "Representative migration/rollback or forward-recovery evidence.", "Queries/index decisions tied to observed or expected access patterns."]),
  reading("build-infrastructure", "Build Infrastructure", "Provision the environments proposed for the capstone with reproducible infrastructure/configuration where proportionate. Separate environment-specific values from system definition, control privileged access, and make rebuild/recovery feasible. Infrastructure is part of the product's executable design, not a one-time setup screenshot.", ["Reproducible environment definition or documented justified equivalent.", "Network/access/data-service boundaries match the proposal or have a recorded revision.", "Environment creation/change evidence without committed secrets."]),
  reading("automate-delivery", "Automate Delivery", "Implement the real change-to-release path: build, test, artifact versioning, approved dependency resolution, deployment/promotion and verification. Gates should produce evidence and fail for meaningful reasons. Keep deployment logic repeatable and make rollback or recovery behavior explicit before it is needed.", ["Working CI/CD path from source to target environment.", "Immutable/versioned artifact or equivalent release identity.", "Deployment verification plus rollback/recovery evidence."]),
  reading("build-quality-evidence", "Build Quality Evidence", "Execute the risk-based quality strategy against the real system. Combine fast developer feedback, integration/contract evidence, end-to-end confidence and exploratory investigation according to actual risks. Treat flaky tests and misleading green pipelines as quality defects in the evidence system itself.", ["Automated tests mapped to meaningful product risks.", "Exploratory or scenario evidence for risks poorly covered by automation.", "Defect/failure examples that caused tests, design or assumptions to improve."]),
  reading("secure-the-system", "Secure the System", "Apply the capstone-specific threat model throughout implementation: identity/access, validation, secrets, dependency/supply chain, data protection, logging, configuration and deployment boundaries. Validate controls rather than assuming framework defaults. Findings should change code, configuration, risk treatment or acceptance.", ["Updated threat model reflecting implemented boundaries.", "Security tests/scans/manual evidence appropriate to important threats.", "Tracked findings, remediation and explicit residual risk where applicable."]),
  reading("instrument-the-system", "Instrument the System", "Add telemetry that answers operational questions: what is the service doing, is it healthy, why did a request fail, what changed, and are user-relevant outcomes degrading? Design logs, metrics and traces/events around decisions and failure diagnosis, while avoiding sensitive-data leakage and high-cardinality noise.", ["Structured production-useful logging with correlation/context where needed.", "Metrics/health signals tied to service behavior rather than vanity activity.", "Demonstrated diagnosis of at least one failure using telemetry."]),
  reading("build-reliability-evidence", "Build Reliability Evidence", "Turn reliability claims into experiments and operating evidence. Exercise important failure modes, timeouts/retries where justified, degradation, capacity assumptions, backup/restore and recovery. A resilient-looking architecture diagram is not evidence that the implementation recovers.", ["Failure experiment(s) with observed behavior and follow-up.", "Capacity/performance evidence for a meaningful workload assumption.", "Recovery/restore evidence against stated objectives or explicit provisional targets."]),
  reading("operate-internal-dependencies-deliberately", "Operate Internal Dependencies Deliberately", "Treat every reused internal capability as a product relationship. If Nexus, tsa-test-core or another TSA internal product fits, consume an approved version through its intended contract and respect version/provenance/support rules. If it does not fit, reject reuse explicitly. Do not create capstone-specific features inside shared packages merely to claim reuse.", ["Reuse/evolve/reject decision for each relevant internal capability.", "Approved source/version/provenance evidence for reused packages.", "Clear ownership boundary between generic shared capability and capstone-specific behavior."]),
  reading("iterate-on-engineering-decisions", "Iterate on Engineering Decisions", "Implementation is a source of architectural evidence. Revisit assumptions when latency, complexity, domain behavior, operational friction, security findings or cost differ from the proposal. Changing a decision with better evidence is professional engineering; silently drifting away from the proposal is not.", ["At least one decision revalidated using implementation evidence.", "Superseding decision record where a consequential choice changes.", "Impact assessment on tests, operations, risk and milestones."]),
  reading("document-significant-decisions", "Document Significant Decisions", "Maintain a compact decision trail for choices with meaningful consequences or difficult reversibility. Record context, alternatives, decision, evidence and consequences. Keep detailed implementation documentation close to code and use records to preserve why, not narrate every commit.", ["Current ADR/decision index with supersession links where relevant.", "Rejected alternatives preserved for consequential decisions.", "Documentation points to authoritative code/config/evidence instead of duplicating it."]),
  reading("manage-scope-and-technical-debt", "Manage Scope and Technical Debt", "Protect the capstone outcome from both uncontrolled feature growth and perfectionism. Distinguish defects, missing scope, ordinary maintenance and technical debt. Record deliberate compromises when they create future cost/risk, prioritize them by consequence, and preserve explicit non-goals as new ideas appear.", ["Updated scope/non-goal decisions as implementation evolves.", "Debt records explain future consequence rather than disliked code.", "Prioritization shows what was deferred, why and what would trigger reconsideration."]),
  practical("lab-reuse-tsa-test-core-as-a-second-consumer", "Lab: Reuse tsa-test-core as a Second Consumer", "Test whether tsa-test-core is a genuinely reusable internal engineering product by evaluating and, only if justified, consuming it from the capstone as a second real consumer.", ["Compare capstone testing needs with tsa-test-core's published contract; make an explicit reuse or reject decision.", "If reuse fits, consume an approved version through Nexus/internal artifact flow rather than copying source.", "Demonstrate compatibility with capstone tests and record version/provenance evidence.", "If a missing capability appears generic across consumers, propose/evolve it through the shared package lifecycle and prove Steward compatibility; otherwise keep it in capstone test code.", "If reuse is rejected, document the mismatch and use a capstone-owned alternative without penalty."], ["Reuse/evolve/reject decision record", "Second-consumer compatibility evidence or justified rejection", "Package/version/provenance evidence when reused", "Shared-package change and cross-consumer evidence when evolved"], ["Reuse is driven by contract fit rather than a curriculum requirement to use the package.", "Capstone-domain logic does not leak into tsa-test-core.", "Any shared change preserves existing consumer compatibility or explicitly manages a breaking version.", "The evidence demonstrates that internal package governance works beyond Steward."], 240),
  practical("lab-deliver-the-first-end-to-end-capstone-release", "Lab: Deliver the First End-to-End Capstone Release", "Deliver the first integrated production-style capstone release through its real engineering path and use the release to expose remaining gaps before Production Readiness.", ["Select a coherent release slice that demonstrates the capstone's primary value path.", "Build and test it through the real CI path; produce a versioned artifact/release identity and dependency evidence.", "Deploy through the intended infrastructure/configuration path and verify behavior in the target environment.", "Run the planned quality and security evidence for the slice, then inspect telemetry under normal and failing behavior.", "Exercise one meaningful failure/recovery or rollback scenario and capture observations.", "Review implementation against proposal, risks, costs, operations and scope; update authoritative decisions and create a readiness-gap backlog rather than hiding unfinished work."], ["Running end-to-end capstone release", "CI/CD and versioned release evidence", "Deployment and configuration evidence", "Quality/security/observability evidence", "Failure/recovery or rollback evidence", "Updated decisions, risks and Production Readiness gap backlog"], ["The release is produced reproducibly from source rather than assembled manually.", "The primary stakeholder path works end to end in the target environment.", "Important quality/security claims have executable or reviewable evidence.", "Telemetry supports diagnosis of demonstrated behavior/failure.", "A recovery/rollback claim is exercised rather than documented only.", "Known gaps, assumptions and residual risks remain visible for the Production Readiness module."], 480),
];
