import type { Activity } from "../activities";
import type { Lesson } from "./lesson";

const pathId = "capstone-engineering-proposal";
const scenario = "Use the approved Capstone Discovery Brief as the source of truth. The proposal must turn understood outcomes, constraints, quality attributes, risks and evidence needs into a coherent engineering approach for a new system. Do not copy Steward architecture or select technologies because TSA previously used them.";
const completion = ["The proposal traces important engineering choices to discovered needs, constraints, risks or evidence requirements.", "Alternatives, trade-offs, assumptions and unresolved risks are explicit rather than hidden behind diagrams or tool names.", "The proposal is sufficiently concrete to guide an independent build while remaining revisable when implementation evidence disproves assumptions."];

function reading(id: string, title: string, body: string, practice: string[]): Lesson {
    const activity: Activity = { id: `${pathId}-${id}-001`, title, estimatedMinutes: 50, content: { type: "reading", body: `${body}\n\nCapstone application:\n${practice.map((item) => `- ${item}`).join("\n")}\n\nReview standard: explain why the proposal is appropriate for this capstone, what evidence supports it, what alternatives were considered, and what would cause the decision to change.` } };
    return { id: `${pathId}-${id}`, title, activities: [activity] };
}

export const capstoneEngineeringProposalDeepLessons: Lesson[] = [
    reading("system-context-and-boundaries", "System Context and Boundaries", "Define what the system is responsible for, what remains outside it, who or what interacts with it, and which external dependencies cross the boundary. Boundaries are responsibility decisions, not merely boxes on a diagram. A useful context view exposes actors, external systems, trust/dependency relationships and ownership boundaries without prematurely decomposing the internals.", ["Create a solution-neutral context diagram from the Discovery Brief.", "State system responsibilities and explicit exclusions.", "Mark external dependencies, owners and assumptions that could invalidate the boundary."]),
    reading("domain-and-data-model-proposal", "Domain and Data Model Proposal", "Translate the problem language into a proposed domain model and information model. Identify concepts, identities, relationships, invariants, lifecycle states, ownership and data sensitivity. Do not start with database tables. The proposal should explain where consistency matters, what data is authoritative, what can be derived and which unknowns require validation during implementation.", ["Build a domain glossary and conceptual model.", "Identify key invariants and lifecycle transitions.", "Classify important data, ownership, retention assumptions and consistency needs."]),
    reading("architecture-proposal", "Architecture Proposal", "Architecture is the set of consequential structural decisions needed to satisfy the capstone's quality attributes and constraints. Prefer the simplest structure that credibly meets current evidence. Compare realistic alternatives, including a deliberately simple option, and resist introducing services, queues, caches or distributed boundaries merely to demonstrate them.", ["Propose the smallest credible architecture and at least one alternative.", "Trace major structural choices to quality attributes and risks.", "Record rejected complexity and the evidence that would justify adding it later."]),
    reading("infrastructure-and-hosting-proposal", "Infrastructure and Hosting Proposal", "Choose compute, network, storage, data services and environment topology from operational requirements rather than familiarity. Evaluate availability needs, security boundaries, data requirements, recovery, maintainability, portability and cost. Managed services, containers, VMs and cloud platforms are means, not goals.", ["Describe target environments and infrastructure responsibilities.", "Compare credible hosting choices using capstone constraints.", "Identify failure, recovery, access and cost assumptions requiring proof."]),
    reading("delivery-plan", "Delivery Plan", "Design how changes move safely from source to usable releases. The plan should cover version control, review, build, tests, artifact creation, environments, deployment, configuration, secrets, promotion, rollback and evidence. Automation should reduce repeatable risk while preserving explicit decisions where risk genuinely requires judgment.", ["Draw the proposed change-to-production path.", "Define automated gates and evidence produced at each stage.", "Identify rollback/recovery paths and any justified manual decisions."]),
    reading("quality-strategy", "Quality Strategy", "Quality strategy begins with product risks and desired behavior, not a list of test types. Decide what must be prevented, detected or explored at each layer; where automation provides durable evidence; and where human investigation remains valuable. Include functional and relevant non-functional evidence without pursuing arbitrary coverage numbers.", ["Map product risks to test/evidence techniques.", "Define the intended test layers and ownership.", "State what will not be automated and why."]),
    reading("security-strategy", "Security Strategy", "Turn the capstone's assets, trust boundaries, threat exposure and data sensitivity into proportionate security objectives and controls. Reuse Security Steward reasoning, but perform a new threat assessment for this domain. Security claims must ultimately be testable or evidenced; framework labels alone do not establish protection.", ["Identify critical assets, trust boundaries and likely threat scenarios.", "Propose preventive, detective and recovery controls tied to those threats.", "Define security evidence expected before release."]),
    reading("reliability-strategy", "Reliability Strategy", "Define what reliable service means for this system and how it will be observed, protected and recovered. Availability targets, failure handling, observability, capacity, backup and recovery should reflect stakeholder impact and cost. Do not import Steward SLOs or resilience patterns without a capstone-specific reason.", ["Propose service indicators/objectives where justified.", "Identify important failure modes and resilience responses.", "Define evidence for recovery, capacity and failure behavior."]),
    reading("operational-model", "Operational Model", "A production-style system needs an explicit model for ownership after deployment: monitoring, support, incidents, changes, maintenance, access, dependency updates, backups and escalation. Design operations alongside software so that the system is not handed to an imaginary operator after implementation.", ["Define service ownership and operational responsibilities.", "Describe normal operations and credible incident/escalation paths.", "Identify required runbooks, access and maintenance routines."]),
    reading("cost-model", "Cost Model", "Engineering proposals consume money, time and human attention. Estimate material build and operating costs, identify dominant cost drivers and connect spending to required outcomes. Precision is less important than transparent assumptions, ranges and sensitivity. A cheaper design can be superior when additional complexity buys no meaningful value.", ["Estimate infrastructure/service and meaningful engineering/operational costs.", "List assumptions and cost drivers.", "Identify scaling thresholds or decisions that materially change cost."]),
    reading("governance-approach", "Governance Approach", "Define only the decision rights, evidence, controls, standards, exceptions and review cadence needed to keep consequential engineering decisions accountable. The capstone should demonstrate stewardship without recreating a large organization's bureaucracy. Routine low-risk work should remain fast; material risk acceptance must have an explicit owner.", ["Define major decision owners and review points.", "Identify minimum controls/evidence for consequential changes.", "Define how exceptions and residual-risk acceptance will be recorded."]),
    reading("dependency-and-internal-platform-decisions", "Dependency and Internal Platform Decisions", "Evaluate external dependencies and TSA internal capabilities as engineering choices. Reuse Nexus, tsa-test-core or other internal products only where their contracts genuinely fit. Reuse can reduce duplicated capability, but it also creates coupling, lifecycle and availability obligations. Rejection of reuse can be the correct decision when the fit is poor.", ["Inventory important proposed dependencies and their owners/sources.", "Evaluate each relevant TSA internal capability as reuse, evolve or reject.", "Define provenance, version/support and exit expectations for critical dependencies."]),
    reading("implementation-milestones", "Implementation Milestones", "Convert the proposal into thin, evidence-producing increments rather than a component checklist. Early milestones should retire important uncertainty and prove end-to-end behavior. Sequence work around dependencies and risk, preserve demonstrable states, and avoid a long infrastructure phase followed by a late integration surprise.", ["Define milestone outcomes and evidence, not only tasks.", "Prioritize early retirement of high-impact uncertainty.", "Show dependencies, decision points and scope that can be deferred."]),
    reading("architecture-and-risk-review", "Architecture and Risk Review", "Before implementation, challenge the proposal as a coherent system. Test whether architectural choices actually address quality attributes, whether risks have owners/treatments, whether controls are proportionate, whether costs and operations are credible, and whether complexity is justified. The review may approve, conditionally approve, simplify or reject the proposal.", ["Run a structured challenge against discovery evidence and the risk register.", "Identify contradictions, unsupported claims and unnecessary complexity.", "Record decisions, conditions, residual risks and proposal changes."]),
    {
        id: `${pathId}-lab-defend-the-capstone-engineering-proposal`,
        title: "Lab: Defend the Capstone Engineering Proposal",
        activities: [{ id: `${pathId}-lab-defend-the-capstone-engineering-proposal-001`, title: "Lab: Defend the Capstone Engineering Proposal", estimatedMinutes: 420, content: { type: "practical", objective: "Produce and defend a coherent engineering proposal that turns the approved discovery evidence into an implementable, risk-aware plan without copying Steward.", scenario, instructions: ["Phase 1 — Build the proposal: context/boundaries, domain/data model, architecture, infrastructure, delivery, quality, security, reliability and operations.", "Phase 2 — Make economics and stewardship explicit: cost model, governance, dependency/internal-platform decisions, implementation milestones and risk ownership.", "Phase 3 — Conduct an adversarial architecture-and-risk review. Challenge assumptions, complexity, evidence gaps, failure/recovery claims, cost and operational feasibility.", "Revise the proposal from review evidence. Record at least one meaningful rejected alternative and at least one deliberate simplicity/retain-current-choice decision.", "Produce a final go, conditional-go or redesign decision for entering Independent Build, with unresolved assumptions and validation experiments visible."], deliverables: ["Capstone engineering proposal", "System context and domain/data model", "Architecture and infrastructure decision set", "Delivery, quality, security and reliability strategies", "Operational and cost model", "Governance and dependency decisions", "Implementation milestone plan", "Architecture/risk review record and final decision"], completionCriteria: completion } }],
    },
];
