import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const acmEthics:LearningResource={title:"ACM Code of Ethics and Professional Conduct",url:"https://www.acm.org/code-of-ethics",kind:"reference"};
const ieeeEthics:LearningResource={title:"IEEE Code of Ethics",url:"https://www.ieee.org/about/corporate/governance/p7-8.html",kind:"reference"};
const nistPrivacy:LearningResource={title:"NIST Privacy Framework",url:"https://www.nist.gov/privacy-framework",kind:"reference"};
const adr:LearningResource={title:"Architectural Decision Records",url:"https://adr.github.io/",kind:"reference"};

type Spec={id:string;title:string;body:string;practice:string[];resources:LearningResource[]};
function lesson(s:Spec):Lesson{const blocks:LessonBlock[]=[{type:"paragraph",text:s.body},{type:"callout",tone:"steward",title:"Professional standard",body:"Professional engineering judgment includes consequences for users, operators, organizations and the public. Technical feasibility or stakeholder pressure does not remove the duty to surface material harm, uncertainty, conflicts and limits of competence."},{type:"resources",title:"Professional reference",resources:s.resources}];return{id:`professional-practice-${s.id}`,title:s.title,activities:[{id:`professional-practice-${s.id}-reading`,title:s.title,estimatedMinutes:50,content:{type:"reading",body:s.body,blocks}},{id:`professional-practice-${s.id}-practice`,title:`Practice: ${s.title}`,estimatedMinutes:70,content:{type:"practical",objective:`Apply ${s.title} to the independent capstone.`,scenario:"Use the capstone and its real or realistically supplied stakeholder context. Do not manufacture an ethical issue merely to complete the exercise.",instructions:s.practice,deliverables:["Professional-practice decision record","Evidence, affected parties and uncertainty","Action/escalation or explicit no-action rationale"],completionCriteria:["Affected people and consequences are considered beyond implementation convenience.","Material uncertainty and limits of competence are explicit.","The decision can be challenged from durable evidence rather than personal authority."]}}]}}
const specs:Spec[]=[
{id:"ethics-public-interest",title:"Ethics, Harm and the Public Interest",body:"Engineering choices can affect privacy, access, safety, livelihood, financial outcomes, dignity and trust. Identify foreseeable harms and affected parties, including people who are not direct users. Avoid treating legality, stakeholder approval or technical correctness as proof that a decision is ethically acceptable.",practice:["Identify material beneficial and harmful consequences of the capstone.","Identify affected non-users or groups with limited power in the decision.","Define mitigations, unresolved tensions and who has authority to accept remaining organizational risk."],resources:[acmEthics,ieeeEthics]},
{id:"privacy-data-responsibility",title:"Privacy and Responsible Data Practice",body:"Collecting or retaining data because it may become useful creates enduring exposure. Professional practice asks what data is necessary, who is affected, what inference or misuse is possible, how long it should exist and how people can understand or challenge its use.",practice:["Review the capstone data inventory for necessity, sensitivity and lifecycle.","Identify one data element that can be minimized, derived, aggregated or removed.","Record privacy assumptions and residual concerns."],resources:[nistPrivacy,acmEthics]},
{id:"competence-uncertainty",title:"Competence, Uncertainty and Responsible Escalation",body:"Engineers should distinguish what they know, what evidence supports, what remains uncertain and where specialist expertise is required. Responsible escalation is not weakness: it prevents confidence from masquerading as competence in high-consequence decisions.",practice:["Choose one capstone decision outside your strongest expertise.","Separate demonstrated knowledge, assumptions and unknowns.","Define what specialist review or additional evidence would be required before a higher-consequence commitment."],resources:[acmEthics,ieeeEthics]},
{id:"conflicts-pressure",title:"Conflicts, Pressure and Professional Dissent",body:"Schedule, cost, hierarchy and personal incentives can pressure engineers to weaken evidence or hide risk. Professional dissent should be specific, evidence-based and proportionate: explain the concern, consequence, alternatives and escalation path while avoiding both passive silence and performative obstruction.",practice:["Create or use a plausible capstone pressure scenario such as a release despite a material unresolved gap.","Write the recommendation, evidence, consequence and escalation path.","State what compromise is acceptable and what would require formal dissent or refusal to make an unsupported claim."],resources:[acmEthics,ieeeEthics]},
{id:"traceability-accountability",title:"Traceability and Professional Accountability",body:"Professional work should make consequential claims and decisions inspectable after the meeting ends. Traceability connects requirements, risks, decisions, implementation and evidence while preserving ownership and change history. It supports accountability without requiring exhaustive paperwork.",practice:["Select three consequential capstone claims.","Trace each from stakeholder need or obligation through decision to implementation and verification evidence.","Repair one gap where the current record depends on oral history."],resources:[adr,acmEthics]},
];
export const professionalPracticeDeepLessons:Lesson[]=specs.map(lesson);
