import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";
const adr:LearningResource={title:"Architectural Decision Records",url:"https://adr.github.io/",kind:"reference"};
const acm:LearningResource={title:"ACM Code of Ethics and Professional Conduct",url:"https://www.acm.org/code-of-ethics",kind:"reference"};
const docs:LearningResource={title:"Write the Docs — Docs as Code",url:"https://www.writethedocs.org/guide/docs-as-code/",kind:"reference"};
function lesson(id:string,title:string,body:string,instructions:string[],resources:LearningResource[]):Lesson{const blocks:LessonBlock[]=[{type:"paragraph",text:body},{type:"resources",title:"Continue learning",resources}];return{id:`professional-portfolio-${id}`,title,activities:[{id:`professional-portfolio-${id}-reading`,title,estimatedMinutes:45,content:{type:"reading",body,blocks}},{id:`professional-portfolio-${id}-practice`,title:`Practice: ${title}`,estimatedMinutes:90,content:{type:"practical",objective:"Produce durable evidence of transferable professional growth.",scenario:"Use artifacts from the full TSA journey and the independent capstone. The portfolio is evidence of judgment and learning, not a gallery of screenshots, certificates or tool names.",instructions,deliverables:["Curated evidence artifact","Claim-to-evidence mapping","Reflection and next-development action"],completionCriteria:["Claims are supported by inspectable artifacts.","Reflection includes mistakes, changed decisions and remaining limits.","Evidence demonstrates transfer beyond the Steward implementation."]}}]}}
export const professionalPortfolioReflectionDeepLessons:Lesson[]=[
lesson("evidence-portfolio","Engineering Evidence Portfolio","A professional portfolio should demonstrate capabilities through decisions and outcomes: problem framing, code, architecture, delivery, quality, security, reliability, operations, governance and communication. Curate representative artifacts and explain what each proves and what it does not prove.",["Build a claim-to-evidence matrix across the TSA schools.","Prefer a small number of strong artifacts over exhaustive screenshots.","Include both Steward progression and independent-capstone evidence for transferable capabilities."],[docs,adr]),
lesson("reflective-practice","Reflective Engineering Practice","Reflection turns experience into improved future judgment. Reconstruct decisions using evidence available at the time, identify incorrect assumptions, distinguish bad outcomes from bad decision processes, and state what you would repeat or change. Avoid rewriting history so every decision appears correct.",["Choose three decisions that changed materially during TSA or the capstone.","For each, record original evidence, assumption, outcome and learning.","Define a concrete rule, question or practice you will carry forward."],[adr,acm]),
lesson("professional-development","Continuing Professional Development","Professional competence is maintained deliberately. Use demonstrated gaps, changing responsibilities and technology/domain evolution to choose future learning. Certifications, degrees and courses can support a plan but should not replace capability evidence.",["Identify current capability strengths and limits from portfolio evidence.","Choose the next 12-month development objectives based on role direction and evidence gaps.","For each objective define learning, applied practice and proof—not only a credential."],[acm]),
];