import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const istqb: LearningResource = { title: "ISTQB — Certified Tester Foundation Level Syllabus", url: "https://www.istqb.org/certifications/certified-tester-foundation-level" };
const googleTesting: LearningResource = { title: "Google — Software Engineering at Google: Testing Overview", url: "https://abseil.io/resources/swe-book/html/ch11.html" };
const dora: LearningResource = { title: "DORA — Software Delivery Performance", url: "https://dora.dev/" };

type Spec = { id: string; title: string; intro: string; sections: Array<{ title: string; body: string[]; list?: string[]; code?: string }>; practice: string[]; questions: string[] };

function rich(spec: Spec): Lesson {
    const blocks: LessonBlock[] = [{ type: "paragraph", text: spec.intro }];
    for (const section of spec.sections) {
        blocks.push({ type: "heading", id: section.title.toLowerCase().replace(/[^a-z0-9]+/g, "-"), text: section.title, level: 2 });
        section.body.forEach((text) => blocks.push({ type: "paragraph", text }));
        if (section.list) blocks.push({ type: "list", items: section.list });
        if (section.code) blocks.push({ type: "code", language: "text", code: section.code });
    }
    blocks.push({ type: "callout", tone: "steward", title: "Steward quality checkpoint", body: "Quality work must change what the team knows about release risk. Use the real Steward domain, deployed environments and delivery evidence. Do not maximize test counts; maximize useful confidence and make residual uncertainty visible." });
    blocks.push({ type: "resources", title: "Continue learning", resources: [istqb, googleTesting, dora] });
    return { id: `quality-engineering-${spec.id}`, title: spec.title, activities: [
        { id: `quality-engineering-${spec.id}-001`, title: spec.title, estimatedMinutes: 45, content: { type: "reading", body: spec.intro, blocks } },
        { id: `quality-engineering-${spec.id}-002`, title: `Apply: ${spec.title}`, estimatedMinutes: 45, content: { type: "practical", objective: `Apply ${spec.title} to Steward.`, scenario: "Steward is now an internet-hosted engineering service registry with an established delivery path. Treat quality as a product and engineering responsibility, not as a final testing phase.", instructions: spec.practice, deliverables: ["Reviewable quality evidence", "Risk or coverage rationale", "Residual-risk note"], completionCriteria: ["The work begins from a behavior or risk rather than a favorite test tool.", "Evidence is specific enough to influence an engineering decision.", "What remains unproven is stated explicitly."] } },
        { id: `quality-engineering-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.questions.join("\n\n"), minimumCharacters: 180 } },
    ] };
}

const specs: Spec[] = [
    { id: "quality-vs-testing", title: "Quality vs Testing", intro: "Testing is one way to obtain information about a product. Quality is the broader outcome created by requirements, design, implementation, delivery, operations and feedback. A test team cannot inspect quality into a system after every consequential decision has already been made.", sections: [
        { title: "Testing produces information", body: ["A test execution samples behavior under particular conditions. Passing tests support a claim only within their scope; they do not prove the absence of defects. Good testers therefore communicate what was exercised, what evidence was observed and what uncertainty remains.", "Quality engineering uses that information earlier and more broadly: improving testability, challenging ambiguous requirements, shaping interfaces, automating repeatable evidence and feeding production learning back into design."] },
        { title: "Quality is a system property", body: ["Steward can have perfectly passing API tests and still be a poor product if ownership rules are ambiguous, releases are unrecoverable, production configuration is wrong or users cannot understand failure messages. Those are quality concerns even when they are not test-case failures."], list: ["Correctness: does behavior satisfy the intended rule?", "Fitness: does the behavior solve the stakeholder problem?", "Operability: can engineers diagnose and recover it?", "Security and reliability: does it behave acceptably under adverse conditions?", "Maintainability: can the system change without uncontrolled regression?"] },
    ], practice: ["Choose one Steward feature such as service ownership or dependency registration.", "List quality decisions made before execution testing begins.", "Separate what a test can demonstrate from broader quality conditions that require design, delivery or operational evidence."], questions: ["Why can a team with many automated tests still ship a low-quality product?", "What is a more accurate claim than ‘all tests passed, therefore the feature is correct’?"] },
    { id: "quality-risks", title: "Quality Risks", intro: "Quality risk is the possibility that a product characteristic fails in a way that matters. Risk gives testing a reason: instead of asking how many cases exist, ask what could go wrong, how harmful it would be and how likely or uncertain the failure is.", sections: [
        { title: "Risk connects failure to consequence", body: ["A defect becomes important through its impact. An incorrect Steward service owner could route an incident to the wrong team. An authorization defect could let one team alter another team's service. A cosmetic spacing issue usually carries less consequence.", "Likelihood is not always known numerically. Use evidence such as change complexity, defect history, integration count, novelty and operational exposure to make relative judgments."], code: "Risk = consequence × likelihood/uncertainty\nPriority is informed by risk, not produced by arithmetic alone." },
        { title: "Create a living risk model", body: ["Risks change as architecture and evidence change. A newly internet-exposed endpoint, schema migration or identity integration may increase attention. Strong unit evidence or mature controls can reduce uncertainty without making risk disappear."], list: ["Failure mode", "Affected stakeholder or asset", "Impact", "Likelihood/uncertainty drivers", "Detection approach", "Preventive controls", "Residual risk"] },
    ], practice: ["Identify at least eight product-quality risks across Steward ownership, dependencies, environments, authorization and releases.", "Rank them using explicit impact and likelihood/uncertainty reasoning.", "For the top three, identify preventive controls and the evidence testing should add."], questions: ["Why is defect count a weak proxy for product risk?", "What new evidence should cause a quality-risk ranking to change?"] },
    { id: "test-strategy", title: "Test Strategy", intro: "A test strategy explains how quality risks will be investigated and controlled across the system. It is not a giant list of test cases and it should not begin with tool names.", sections: [
        { title: "Strategy answers why and where", body: ["Start with product context, architecture, users, critical behaviors, constraints and risks. Then choose levels, techniques, environments, automation and evidence that efficiently address those risks.", "A useful Steward strategy should explain why ownership authorization receives deeper negative coverage, why domain rules belong close to unit/component tests, why selected API flows need deployed-environment evidence and where manual exploration remains valuable."], list: ["Scope and quality objectives", "Risk model and priorities", "Test levels and types", "Environment and test-data approach", "Automation boundaries", "Entry/exit or release evidence", "Defect and residual-risk communication"] },
        { title: "Strategy must fit delivery", body: ["Tests that cannot run at the right decision point are weak controls. Fast deterministic checks belong early; slower integration or environment evidence can run after deploy or before promotion. The strategy should connect evidence to the release lifecycle built in Delivery Engineer."] },
    ], practice: ["Draft a one-page Steward test strategy anchored in the current architecture and delivery path.", "Map each top quality risk to at least one appropriate evidence source.", "State what will deliberately remain manual or outside the initial strategy and why."], questions: ["Why should a test strategy begin with context and risk rather than Playwright or pytest?", "How should delivery stages influence where different tests execute?"] },
    { id: "levels-types", title: "Test Levels and Test Types", intro: "Test levels describe where evidence is gathered around system boundaries; test types describe characteristics or purposes being investigated. Confusing the two produces redundant suites and coverage gaps.", sections: [
        { title: "Use the smallest useful boundary", body: ["A domain validation rule is usually cheaper and more diagnostic to prove close to the component than through a browser. Database integration behavior needs a real persistence boundary. A deployed API path may be necessary to prove routing, configuration and authentication integration.", "End-to-end tests are valuable when the integrated path itself is the risk. They are expensive substitutes for every lower-level assertion."], list: ["Unit: small logic boundary and fast feedback.", "Component: cohesive service/component behavior with controlled collaborators.", "Integration: interaction with real boundaries such as PostgreSQL or identity infrastructure.", "System/service: deployed Steward behavior through public contracts."] },
        { title: "Types cut across levels", body: ["Functional, performance, accessibility, compatibility, security-oriented and reliability-oriented testing can occur at different levels. The important question is which boundary gives credible evidence at acceptable cost."] },
    ], practice: ["Take five Steward risks and choose the cheapest credible test level for each.", "Identify one risk that genuinely requires an integrated/deployed test.", "Identify one existing or hypothetical end-to-end check that would be better moved lower."], questions: ["Why is more end-to-end coverage not automatically better coverage?", "What is the difference between a test level and a test type?"] },
    { id: "risk-based-testing", title: "Risk-based Testing", intro: "Risk-based testing allocates limited testing effort according to the consequence and uncertainty of failure. It changes depth, technique, timing and evidence—not merely the order in which identical test cases run.", sections: [
        { title: "Spend evidence where it matters", body: ["High-risk Steward authorization rules may deserve decision-table analysis, negative API tests, role combinations and exploratory abuse. A low-impact display label may need one focused check. Equal test effort would ignore the unequal consequences."] },
        { title: "Risk controls both breadth and depth", body: ["Risk can determine which configurations matter, how many boundaries to explore, whether concurrency is relevant, whether production-like data shapes are needed and what blocks release. Explicit risk also makes omissions defensible rather than accidental."], list: ["Prioritize critical failure modes.", "Use stronger techniques where rule complexity is high.", "Increase integration depth where boundary uncertainty is high.", "Reduce repetitive low-value coverage.", "Reassess after defects and architecture changes."] },
    ], practice: ["Select the three highest Steward quality risks from your register.", "For each, design a deeper coverage approach and explain why it is proportionate.", "Select one low-risk area and explicitly limit its coverage."], questions: ["How does risk-based testing change more than execution order?", "When should a previously low-risk area receive more testing attention?"] },
    { id: "shift-left-right", title: "Shift-left and Shift-right", intro: "Shift-left means obtaining useful quality feedback earlier; shift-right means learning from behavior in realistic or production contexts. Neither slogan means moving every test to one end of the lifecycle.", sections: [
        { title: "Shift left by changing decisions sooner", body: ["Examples include reviewing ownership rules before implementation, adding unit tests for lifecycle invariants, contract-checking schemas in CI and designing testability into authentication boundaries. The goal is cheaper feedback before defects become expensive system behavior."] },
        { title: "Shift right without testing recklessly in production", body: ["Deployment verification, synthetic checks, feature exposure controls, runtime telemetry and incident learning provide evidence unavailable in isolated environments. Later Reliability Engineer will deepen observability and SLOs; Quality Steward should understand how runtime evidence complements pre-release testing."], code: "design → fast checks → integration evidence → deployment verification → runtime learning\n          ←──────── feedback improves future design ────────" },
    ], practice: ["Map the current Steward delivery path and place existing or planned quality feedback points on it.", "Move one late discovery opportunity earlier without duplicating the same test everywhere.", "Define one safe post-deployment quality signal and explain what it adds beyond CI."], questions: ["What makes an activity genuinely ‘shift-left’ rather than merely earlier execution?", "Why can pre-release testing never provide all useful quality evidence?"] },
    { id: "testability", title: "Testability", intro: "Testability is the degree to which a system makes important behavior controllable and observable enough to investigate. Poor testability turns simple questions into slow, flaky or ambiguous tests.", sections: [
        { title: "Control inputs and observe outcomes", body: ["Deterministic clocks, injectable collaborators, stable identifiers, explicit APIs, useful logs and isolated data setup reduce test friction. Test hooks should not bypass the very behavior being tested or create unsafe production backdoors.", "For Steward, predictable service fixtures, explicit authorization boundaries and machine-readable error contracts are more valuable than UI-only setup flows for every test."], list: ["Controllability: can the test establish the necessary state?", "Observability: can it distinguish success from hidden failure?", "Determinism: can repeated execution produce explainable outcomes?", "Isolation: can failures be localized to a useful boundary?"] },
        { title: "Testability is architecture feedback", body: ["If a rule can only be tested through a huge integrated scenario, the problem may be excessive coupling rather than insufficient automation skill. Quality engineering can expose design improvements without contorting production architecture solely for tests."] },
    ], practice: ["Identify three Steward behaviors that would be difficult to test deterministically.", "For each, identify whether the constraint is controllability, observability, determinism or isolation.", "Propose one production-safe design improvement that increases testability."], questions: ["Why is testability partly an architecture concern?", "What makes a test-only hook dangerous or misleading?"] },
    { id: "defect-evidence", title: "Defect Evidence and Communication", intro: "A defect report is an engineering handoff. Its job is to let another person understand the observed failure, reproduce or investigate it, assess impact and distinguish evidence from assumption.", sections: [
        { title: "Report the observation before the theory", body: ["Record environment, release identity, preconditions, action, expected behavior, actual behavior and diagnostic evidence. A suspected root cause can be useful, but label it as a hypothesis unless proven.", "The Delivery and Cloud schools already established source, artifact, deployment and runtime identity. Quality evidence should reuse those identifiers so a defect is attached to the exact system that failed."], code: "Release: steward-api 1.5.0-rc.3 @ sha256:...\nEnvironment: UAT\nPrecondition: user belongs to Team A only\nAction: PATCH /api/services/team-b-service\nExpected: 403, no mutation\nActual: 200, owner changed\nEvidence: request id ..., response ..., DB audit record ..." },
        { title: "Severity is impact, priority is decision", body: ["Severity describes consequence; priority reflects when the organization chooses to act given risk and context. Avoid inflating language to force attention. Strong evidence and impact analysis are more persuasive than dramatic labels."] },
    ], practice: ["Write a high-quality defect report for a realistic Steward authorization or ownership failure.", "Tie the report to exact release/environment identity and include minimal reproducible evidence.", "Separate observed facts, impact assessment and root-cause hypothesis."], questions: ["Why should a suspected root cause be separated from observed behavior?", "How do release identity and request evidence reduce defect-triage ambiguity?"] },
];

const strategyLab: Lesson = { id: "quality-engineering-steward-strategy", title: "Lab: Write the Steward Quality Strategy", activities: [
    { id: "quality-engineering-steward-strategy-001", title: "Establish the Quality Context", estimatedMinutes: 45, content: { type: "practical", objective: "Build the context and risk basis for Steward quality engineering.", scenario: "Use the actual Steward domain, system design, internet environment and release path produced by earlier schools.", instructions: ["Summarize Steward users, critical domain behaviors, architecture boundaries and deployment environments.", "Create a ranked quality-risk register covering correctness, authorization, integration, data, environment and operational concerns.", "Record existing controls and evidence so the strategy does not duplicate them blindly."], deliverables: ["Quality context", "Ranked risk register", "Existing-evidence inventory"], completionCriteria: ["Risks connect failures to consequences.", "Architecture and delivery context are represented.", "Existing evidence is distinguished from assumptions."] } },
    { id: "quality-engineering-steward-strategy-002", title: "Design the Evidence Model", estimatedMinutes: 75, content: { type: "practical", objective: "Map risks to proportionate test levels, types and feedback points.", scenario: "The strategy must produce useful release confidence without turning every behavior into a slow end-to-end test.", instructions: ["Map each high-priority risk to the cheapest credible evidence boundary.", "Define unit/component, API/integration, deployed-environment and exploratory responsibilities.", "Add selected non-functional concerns but defer detailed implementation to its later module.", "Map checks to CI, promotion or post-deployment points where they can influence decisions.", "State automation candidates and deliberately manual work."], deliverables: ["Risk-to-evidence matrix", "Test-level model", "Delivery feedback map"], completionCriteria: ["High-risk behavior receives deeper evidence.", "End-to-end testing is not used as a universal default.", "Each evidence source has a decision point it supports."] } },
    { id: "quality-engineering-steward-strategy-003", title: "Define Quality Decision Rules", estimatedMinutes: 45, content: { type: "practical", objective: "Define how evidence affects release and triage decisions.", scenario: "A strategy is incomplete if it collects results but never explains what the team does with them.", instructions: ["Define which failed checks block progression and why.", "Define how flaky or unavailable evidence is treated.", "Define defect evidence standards and residual-risk communication.", "Identify testability improvements that should enter the engineering backlog.", "State strategy limitations and review triggers."], deliverables: ["Quality decision rules", "Defect evidence standard", "Residual-risk and review section"], completionCriteria: ["Gates are tied to risks rather than arbitrary pass percentages.", "Unknown or missing evidence cannot silently become a pass.", "The strategy can evolve after incidents, architecture changes and new evidence."] } },
    { id: "quality-engineering-steward-strategy-004", title: "Quality Engineering Review", estimatedMinutes: 30, content: { type: "reflection", prompt: "Defend the Steward quality strategy. Which three risks deserve the most evidence, which test levels provide that evidence most efficiently, what important behavior remains uncertain, and how will the strategy change when runtime incidents or architecture changes reveal new risk?", minimumCharacters: 300 } },
] };

export const qualityEngineeringDeepLessons: Lesson[] = [...specs.map(rich), strategyLab];
