import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const istqb: LearningResource = { title: "ISTQB — Certified Tester Foundation Level Syllabus", url: "https://www.istqb.org/certifications/certified-tester-foundation-level" };
const guruDecisionTables: LearningResource = { title: "ISTQB Glossary — Decision Table Testing", url: "https://glossary.istqb.org/en_US/term/decision-table-testing-3" };
const exploratory: LearningResource = { title: "DevelopSense — Exploratory Testing", url: "https://www.satisfice.com/exploratory-testing" };

type Spec = { id: string; title: string; intro: string; sections: Array<{ title: string; body: string[]; list?: string[]; code?: string }>; practice: string[]; questions: string[] };

function rich(spec: Spec): Lesson {
    const blocks: LessonBlock[] = [{ type: "paragraph", text: spec.intro }];
    for (const section of spec.sections) {
        blocks.push({ type: "heading", id: section.title.toLowerCase().replace(/[^a-z0-9]+/g, "-"), text: section.title, level: 2 });
        for (const body of section.body) blocks.push({ type: "paragraph", text: body });
        if (section.list) blocks.push({ type: "list", items: section.list });
        if (section.code) blocks.push({ type: "code", language: "text", code: section.code });
    }
    blocks.push({ type: "callout", tone: "steward", title: "Steward analysis checkpoint", body: "Use techniques to reveal meaningful behavior partitions, rules, transitions and interactions in the Steward domain. A technique is useful only when it exposes risk more clearly than ad-hoc case enumeration." });
    blocks.push({ type: "resources", title: "Continue learning", resources: [istqb, guruDecisionTables, exploratory] });
    return { id: `test-analysis-and-design-${spec.id}`, title: spec.title, activities: [
        { id: `test-analysis-and-design-${spec.id}-001`, title: spec.title, estimatedMinutes: 45, content: { type: "reading", body: spec.intro, blocks } },
        { id: `test-analysis-and-design-${spec.id}-002`, title: `Apply: ${spec.title}`, estimatedMinutes: 45, content: { type: "practical", objective: `Apply ${spec.title} to Steward.`, scenario: "Use the actual Steward requirements, domain rules and quality risks. Derive test ideas systematically before automating anything.", instructions: spec.practice, deliverables: ["Test-design artifact", "Coverage rationale", "Residual-risk note"], completionCriteria: ["Cases are derived from explicit analysis.", "The selected technique fits the risk and rule structure.", "Redundant cases are reduced without losing important behavior distinctions."] } },
        { id: `test-analysis-and-design-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.questions.join("\n\n"), minimumCharacters: 180 } },
    ] };
}

const specs: Spec[] = [
    { id: "requirements-analysis", title: "Requirements Analysis for Testing", intro: "Test analysis begins by turning requirements, domain rules, interfaces and stakeholder expectations into testable conditions. The aim is not to copy requirements into cases, but to expose ambiguity, hidden assumptions and failure-relevant behavior.", sections: [
        { title: "Interrogate the requirement", body: ["Ask who acts, under which preconditions, on what data, with what authorization, and what outcome should be observable. Look for missing boundaries, unspecified error behavior and contradictions between business rules and interface contracts.", "For Steward, ‘a team may update its own service’ hides questions about multiple memberships, inactive teams, ownership transfers, service lifecycle state and concurrent edits."] },
        { title: "Build test conditions before cases", body: ["A test condition is a behavior or risk worth investigating. Cases are then examples chosen to cover those conditions. This prevents premature explosion into hundreds of low-value scripts."], list: ["Actors and roles", "Preconditions", "Inputs and partitions", "Business rules", "State and transitions", "Dependencies", "Expected observable outcomes", "Failure behavior"] },
    ], practice: ["Select two Steward requirements and rewrite them as explicit test conditions.", "Identify at least three ambiguities or assumptions in each.", "Mark which questions must be clarified versus which can be safely explored as hypotheses."], questions: ["Why is copying acceptance criteria directly into test cases insufficient analysis?", "What is the advantage of defining test conditions before detailed examples?"] },
    { id: "equivalence-partitioning", title: "Equivalence Partitioning", intro: "Equivalence partitioning groups inputs or states expected to behave similarly so that one representative can provide evidence for the group. The technique reduces redundant testing while keeping meaningful distinctions.", sections: [
        { title: "Partition by behavior, not appearance", body: ["Values belong in the same partition only when the system is expected to process them under the same rule. Two different strings may look similar but belong to different partitions if one violates uniqueness or authorization constraints."] },
        { title: "Valid and invalid partitions", body: ["For a Steward criticality field, valid enum values form one or more valid partitions while unsupported values, missing required values and malformed types form invalid partitions. Domain context can create additional partitions such as lifecycle-dependent behavior."] },
    ], practice: ["Choose three Steward fields or conditions.", "Define valid and invalid equivalence partitions for each.", "Pick representatives and justify why additional values in the same partition add little new evidence."], questions: ["What makes two values truly equivalent for testing purposes?", "When should a seemingly single valid partition be split into multiple partitions?"] },
    { id: "boundary-value-analysis", title: "Boundary Value Analysis", intro: "Boundary value analysis targets edges where behavior changes. Defects often cluster around minimums, maximums, thresholds and off-by-one logic, making boundaries disproportionately valuable test points.", sections: [
        { title: "Find the rule transition", body: ["A boundary is not just a numeric maximum. Length limits, date windows, pagination sizes, retry counts and review intervals all create edges where one rule becomes another."] },
        { title: "Test around the edge", body: ["For a maximum service-name length N, useful values often include N-1, N and N+1. For an interval lower bound, include just below, at and just above the permitted threshold."] },
    ], practice: ["Identify at least five real or proposed Steward boundaries.", "Design just-below, at-boundary and just-above cases where appropriate.", "Explain which boundaries carry the highest risk and why."], questions: ["Why are arbitrary middle values usually less valuable than edge values?", "Name a non-numeric boundary in Steward and explain its rule transition."] },
    { id: "decision-tables", title: "Decision Tables", intro: "Decision tables expose behavior governed by combinations of conditions. They are especially useful when authorization or business outcomes depend on several boolean or categorical rules at once.", sections: [
        { title: "Separate conditions from actions", body: ["List the conditions that influence the outcome, enumerate meaningful combinations and map each to the expected action. Impossible or irrelevant combinations should be marked explicitly rather than silently ignored."], code: "Owns service | Active member | Service locked | Expected\nYes          | Yes           | No             | Update allowed\nYes          | No            | No             | Denied\nNo           | Yes           | No             | Denied\nYes          | Yes           | Yes            | Denied" },
        { title: "Decision tables reveal missing rules", body: ["If you cannot assign an expected outcome to one combination, the requirement may be incomplete. That is a valuable analysis result before execution begins."] },
    ], practice: ["Build a decision table for one Steward authorization or lifecycle rule with at least three conditions.", "Mark impossible combinations and unresolved outcomes.", "Derive a minimal set of tests that covers every meaningful rule row."], questions: ["Why are decision tables stronger than ad-hoc positive/negative cases for combinational rules?", "What should you do when a row has no clear expected action?"] },
    { id: "state-transition-testing", title: "State Transition Testing", intro: "State transition testing models behavior that depends on current state and permitted events. It catches defects that cannot be found by treating each operation as stateless.", sections: [
        { title: "Model states and events", body: ["Identify valid states, events that trigger change, guards and forbidden transitions. For Steward, lifecycle could evolve from proposed to active to deprecated to retired, with different permissions or constraints at each stage."] },
        { title: "Invalid transitions matter", body: ["A robust system should reject impossible transitions and preserve state. Testing only the happy path verifies the diagram's arrows but not the protection around them."], code: "proposed -> active -> deprecated -> retired\n   |          X retired -> active without explicit restore rule" },
    ], practice: ["Create a state model for one Steward entity or review workflow.", "Derive tests for valid transitions, invalid transitions and repeated/idempotent events.", "Identify one transition whose failure could corrupt downstream assumptions."], questions: ["Why can the same request be valid in one state and invalid in another?", "What evidence should an invalid transition test verify beyond the response code?"] },
    { id: "pairwise", title: "Pairwise and Combinatorial Concepts", intro: "Combinatorial testing addresses the explosion created by multiple interacting dimensions. Pairwise coverage aims to exercise every pair of parameter values at least once, reducing combinations while retaining interaction-focused evidence.", sections: [
        { title: "The Cartesian product grows quickly", body: ["Browser × role × lifecycle × criticality × environment can create hundreds of combinations. Exhaustive coverage may be wasteful when most failures arise from lower-order interactions."] },
        { title: "Pairwise is a heuristic, not a guarantee", body: ["Pairwise suites can miss failures requiring three or more specific factors. Use domain risk to force critical combinations even when a generated pairwise set would omit them."] },
    ], practice: ["Choose four Steward dimensions with at least two values each.", "Estimate exhaustive combination count.", "Produce a reduced pairwise-style set manually or with a tool, then add any high-risk combinations that must be forced."], questions: ["What problem does pairwise testing address?", "Why must risk-based mandatory combinations override an automatically reduced set?"] },
    { id: "exploratory-testing", title: "Exploratory Testing", intro: "Exploratory testing combines learning, test design and execution in the same activity. It is disciplined investigation guided by a charter, observations and adaptation—not random clicking.", sections: [
        { title: "Use a charter", body: ["A charter frames mission, target area, risks and useful heuristics while leaving room to follow evidence. Example: explore Steward ownership-transfer behavior with emphasis on stale sessions, concurrent updates and authorization boundaries."] },
        { title: "Capture evidence and learning", body: ["Record observations, test data, questions, defects, coverage and follow-up ideas. Session notes turn exploration into reviewable engineering evidence."] },
    ], practice: ["Write a 45-minute exploratory charter for a high-risk Steward area.", "Execute or simulate the session using at least two heuristics such as boundaries, interruptions, concurrency or privilege changes.", "Write concise session notes including what you learned and what should be automated or investigated next."], questions: ["What distinguishes disciplined exploratory testing from random interaction?", "Why should exploratory findings influence later scripted or automated coverage?"] },
    { id: "negative-testing", title: "Negative Testing", intro: "Negative testing investigates how the system behaves when inputs, permissions, dependencies or sequences violate expectations. Good negative coverage verifies safe failure, not merely that an error occurred.", sections: [
        { title: "Design failure intentionally", body: ["Test missing fields, malformed types, invalid references, unauthorized actors, stale state and unavailable dependencies. The expected outcome includes status, error contract, lack of unintended mutation and useful diagnostics."] },
        { title: "Protect invariants", body: ["A 400 response is insufficient if partial data was persisted. A 403 is insufficient if an audit side effect or ownership mutation still occurred. Negative tests should prove the protected invariant remains intact."] },
    ], practice: ["Choose one Steward write endpoint.", "Design at least eight negative conditions across validation, authorization, state and dependency failures.", "For each, state which invariant must remain unchanged."], questions: ["Why is asserting only an error status weak negative testing?", "What kind of invariant should an authorization-negative test protect?"] },
    { id: "traceability", title: "Traceability", intro: "Traceability links risks, requirements, test conditions, tests and findings so that coverage can be explained. It should support decisions, not become paperwork whose only purpose is to prove a spreadsheet is full.", sections: [
        { title: "Trace from risk to evidence", body: ["A practical chain might be quality risk → rule/requirement → test condition → evidence source → result/defect. This lets the team ask which high-risk behaviors still lack evidence and which tests no longer map to a meaningful concern."] },
        { title: "Bidirectional value", body: ["Forward traceability shows how requirements are covered. Backward traceability shows why a test exists. Tests with no meaningful upstream reason are candidates for review or removal."] },
    ], practice: ["Build a lightweight traceability matrix for at least ten Steward test conditions.", "Include upstream risk/requirement and downstream planned evidence.", "Identify one uncovered high-risk condition and one low-value test idea with no strong upstream justification."], questions: ["How does backward traceability help maintain a test suite?", "Why can high traceability completeness still coexist with poor testing?"] },
];

const lab: Lesson = { id: "test-analysis-and-design-steward-coverage", title: "Lab: Design Risk-based Steward Test Coverage", activities: [
    { id: "test-analysis-and-design-steward-coverage-001", title: "Analyze the Domain", estimatedMinutes: 60, content: { type: "practical", objective: "Turn Steward requirements and risks into explicit test conditions.", scenario: "Use the quality strategy produced in the previous module and focus on ownership, service lifecycle, dependency registration and authorization.", instructions: ["Select the highest-risk domain behaviors.", "Extract actors, rules, states, boundaries and dependencies.", "Record ambiguities and unresolved assumptions before designing cases."], deliverables: ["Test-condition catalog", "Ambiguity register", "Risk links"], completionCriteria: ["Conditions are behavior-focused rather than script-focused.", "Ambiguities are explicit.", "High-risk rules are clearly identified."] } },
    { id: "test-analysis-and-design-steward-coverage-002", title: "Apply Formal Techniques", estimatedMinutes: 90, content: { type: "practical", objective: "Use multiple test-design techniques where they fit the domain.", scenario: "Avoid one-technique-for-everything testing. Choose the method that best exposes each rule structure.", instructions: ["Use equivalence partitions and boundaries for input rules.", "Use a decision table for a combinational authorization or business rule.", "Use a state model for lifecycle behavior.", "Use pairwise reduction for a multi-dimensional compatibility problem where appropriate."], deliverables: ["Partition/boundary artifact", "Decision table", "State model", "Reduced combination set"], completionCriteria: ["Each technique has a clear reason for use.", "Derived tests cover the model's meaningful distinctions.", "Risk-critical combinations are not lost through reduction."] } },
    { id: "test-analysis-and-design-steward-coverage-003", title: "Add Exploration and Negative Coverage", estimatedMinutes: 60, content: { type: "practical", objective: "Cover uncertainty and safe-failure behavior that formal models may miss.", scenario: "The target coverage should combine modeled checks with investigation of unexpected interactions.", instructions: ["Create one exploratory charter for a high-uncertainty area.", "Add negative cases that verify preserved invariants.", "Link every important condition back to a quality risk or requirement."], deliverables: ["Exploratory charter", "Negative-test set", "Traceability map"], completionCriteria: ["Negative cases verify state preservation, not only errors.", "Exploration has a clear mission.", "Coverage can be traced to risk."] } },
    { id: "test-analysis-and-design-steward-coverage-004", title: "Coverage Review", estimatedMinutes: 30, content: { type: "reflection", prompt: "Review the Steward test design. Which technique exposed the most important hidden behavior? Which high-risk condition is still weakly covered? Which test ideas did you deliberately omit as redundant or low value, and why?", minimumCharacters: 300 } },
] };

export const testAnalysisAndDesignDeepLessons: Lesson[] = [...specs.map(rich), lab];
