import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";
const java: LearningResource = { title: "Java Language Guide", url: "https://dev.java/learn/" };
const maven: LearningResource = { title: "Apache Maven Guides", url: "https://maven.apache.org/guides/" };
const junit: LearningResource = { title: "JUnit 5 User Guide", url: "https://docs.junit.org/current/user-guide/" };
type Spec = { id: string; title: string; principle: string; practice: string[]; code?: string };
function lesson(spec: Spec): Lesson {
 const blocks: LessonBlock[]=[{type:"paragraph",text:spec.principle},{type:"heading",id:`${spec.id}-framework`,text:"Why framework engineers need this",level:2},{type:"paragraph",text:"Use the concept immediately in steward-tests. The objective is not Java trivia: it is being able to reason about the code, dependency direction, lifecycle and failure behavior of the test platform you will build."}];
 if(spec.code) blocks.push({type:"code",language:"java",code:spec.code});
 blocks.push({type:"resources",title:"Continue learning",resources:[java,maven,junit]});
 return {id:`quality-java-${spec.id}`,title:spec.title,activities:[{id:`quality-java-${spec.id}-001`,title:spec.title,estimatedMinutes:40,content:{type:"reading",body:spec.principle,blocks}},{id:`quality-java-${spec.id}-002`,title:`Build: ${spec.title}`,estimatedMinutes:50,content:{type:"practical",objective:`Apply ${spec.title} while growing steward-tests.`,scenario:"Every exercise changes the real test project. Avoid disconnected kata code unless it demonstrates a language mechanism before the project change.",instructions:spec.practice,deliverables:["Committed steward-tests increment","Executable example or test","Short design note"],completionCriteria:["The learner can explain the Java mechanism without framework magic.","The increment compiles.","The design keeps dependencies explicit."]}}]};
}
const specs: Spec[]=[
{id:"jvm-maven",title:"Java, the JVM and Maven Project Model",principle:"Understand source compilation, bytecode, the JVM, packages, classpath, Maven coordinates, dependency scopes and the standard Maven layout before relying on build-tool magic.",practice:["Create steward-tests as a Java 17+ Maven project.","Use the Maven standard directory layout deliberately.","Add compiler and Surefire configuration.","Run clean test and inspect the lifecycle."],code:"mvn -U clean test"},
{id:"types-modeling",title:"Classes, Records, Enums and Immutability",principle:"Framework models should make invalid or ambiguous state difficult to represent. Use classes for behavior, records for compact immutable data carriers and enums for controlled vocabularies.",practice:["Model TestSettings as an immutable record.","Model Environment and Lifecycle as enums.","Create a ServicePayload model without mutable global defaults."]},
{id:"interfaces-composition",title:"Interfaces, Composition and Dependency Direction",principle:"Prefer composition and narrow interfaces over inheritance-heavy BaseTest hierarchies. Dependencies should point toward stable contracts rather than concrete global objects.",practice:["Define a TokenProvider contract.","Compose it into a small client rather than constructing credentials globally.","Draw the dependency direction and reject a BaseTest god object."],code:"interface TokenProvider { String token(); }"},
{id:"dependency-injection",title:"Constructor Dependency Injection",principle:"Dependency injection is primarily explicit dependency ownership, not a DI container. Constructor injection makes collaborators visible, replaceable and testable without introducing Spring.",practice:["Inject TestSettings and TokenProvider into a client constructor.","Create a fake TokenProvider for a focused test.","Explain why service-locator and static-singleton alternatives hide coupling."],code:"final class StewardApiClient {\n  private final TestSettings settings;\n  private final TokenProvider tokens;\n  StewardApiClient(TestSettings settings, TokenProvider tokens) {\n    this.settings = settings; this.tokens = tokens;\n  }\n}"},
{id:"generics-collections",title:"Generics and Collections",principle:"Generics let reusable infrastructure preserve type information while collections model groups of test data. Use them when they improve contracts, not to make simple code abstract.",practice:["Use List and Map deliberately in test-data code.","Create one typed deserialization helper and explain T.","Compare the generic helper with an explicit endpoint method and keep the clearer boundary."]},
{id:"exceptions-resources",title:"Exceptions and Resource Management",principle:"Framework failures must preserve the original cause and useful context. Understand checked/unchecked exceptions and try-with-resources before managing browsers, files or other closeable resources.",practice:["Wrap one configuration failure with actionable context without losing its cause.","Use try-with-resources with a closeable resource.","Reject catch-all code that converts infrastructure failure into a passing or skipped test."]},
{id:"annotations-reflection",title:"Annotations and Reflection",principle:"JUnit annotations are metadata discovered at runtime. Understand annotations and the purpose of reflection so @Test, lifecycle callbacks, tags and extensions are mechanisms rather than magic.",practice:["Create and inspect a tiny custom annotation.","Explain how JUnit discovers @Test methods conceptually.","Use @Test, @DisplayName and lifecycle annotations intentionally."]},
{id:"junit-tags",title:"JUnit Tags and Intentional Test Selection",principle:"Tags create execution portfolios such as smoke, api and browser. A small governed vocabulary supports CI decisions; arbitrary feature tags create an unmaintainable second taxonomy.",practice:["Define the initial steward-tests tag vocabulary.","Tag a small test set.","Execute one selected group with Maven/Surefire.","Document forbidden or redundant tags."],code:"@Tag(\"smoke\")\n@Tag(\"api\")\n@Test\nvoid healthEndpointIsAvailable() {}"},
{id:"functional-java",title:"Lambdas, Functional Interfaces, Streams and Optional",principle:"Modern Java functional features are useful for transformations, callbacks and extension points, but readability outranks clever chains.",practice:["Implement one small transformation with a stream.","Implement the same logic imperatively and compare readability.","Use Optional only where absence is part of the contract."]},
{id:"concurrency",title:"Concurrency, Shared State and Thread Safety",principle:"Parallel tests expose hidden shared mutable state. Learn thread-safety fundamentals, immutability and execution isolation before enabling JUnit parallelism.",practice:["Identify every mutable singleton/static value in steward-tests.","Make test identity/data collision-safe.","Explain when ThreadLocal is appropriate and why it is not a substitute for good ownership.","Keep parallel execution disabled until isolation is demonstrated."]}
];
const milestone: Lesson={id:"quality-java-foundation-milestone",title:"Milestone: steward-tests Java Foundation",activities:[{id:"quality-java-foundation-milestone-001",title:"Build the Framework Substrate Without Hiding the Mechanics",estimatedMinutes:120,content:{type:"practical",objective:"Produce the Java/Maven foundation on which the later REST Assured and Playwright framework will grow.",scenario:"The repository should demonstrate Java engineering fundamentals before specialized automation libraries hide them.",instructions:["Make steward-tests compile and execute with Maven and JUnit 5.","Implement validated immutable configuration.","Use constructor injection for dependencies.","Create test-data models/builders with explicit ownership.","Define the governed JUnit tag vocabulary.","Add one tiny Java HttpClient probe so the learner experiences raw HTTP before REST Assured.","Record concurrency hazards before enabling parallel execution."],deliverables:["steward-tests Maven project","JUnit baseline","Configuration/domain support","Tag policy","Raw HTTP probe","Architecture note"],completionCriteria:["mvn test succeeds.","No Spring/DI container is required.","No god BaseTest or mutable global driver/client exists.","Dependencies are explicit.","The learner can explain what JUnit and REST Assured will later abstract."]}}]};
export const javaForTestFrameworkEngineeringDeepLessons: Lesson[]=[...specs.map(lesson),milestone];
