import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const playwright: LearningResource = { title: "Playwright Java", url: "https://playwright.dev/java/" };
const junit: LearningResource = { title: "JUnit 5 User Guide", url: "https://docs.junit.org/current/user-guide/" };
const restAssured: LearningResource = { title: "REST Assured", url: "https://rest-assured.io/" };
const maven: LearningResource = { title: "Apache Maven", url: "https://maven.apache.org/guides/" };

type Spec = { id: string; title: string; core: string; practice: string[]; code?: string; warning?: string };

function lessonFrom(spec: Spec): Lesson {
    const blocks: LessonBlock[] = [
        { type: "paragraph", text: spec.core },
        { type: "heading", id: `${spec.id}-principle`, text: "Engineering principle", level: 2 },
        { type: "paragraph", text: "An automation framework is useful only when it makes high-value checks easier to author, execute, diagnose and maintain. Framework structure must serve test intent; it must not hide Steward domain behavior behind generic abstractions." },
        { type: "heading", id: `${spec.id}-steward`, text: "Apply it to Steward", level: 2 },
        { type: "paragraph", text: `For Steward, ${spec.core.toLowerCase()} The framework should preserve clear release identity, environment configuration and diagnostic evidence while keeping domain workflows close to the tests that need them.` },
    ];
    if (spec.code) blocks.push({ type: "code", language: "java", code: spec.code });
    if (spec.warning) blocks.push({ type: "callout", tone: "warning", title: "Framework risk", body: spec.warning });
    blocks.push({ type: "callout", tone: "steward", title: "Steward automation checkpoint", body: "Generic infrastructure may be reusable. Ownership rules, lifecycle behavior, service registration workflows and Steward-specific assertions are domain code and should remain explicit." });
    blocks.push({ type: "resources", title: "Continue learning", resources: [junit, restAssured, playwright, maven] });
    return { id: `automation-framework-${spec.id}`, title: spec.title, activities: [
        { id: `automation-framework-${spec.id}-001`, title: spec.title, estimatedMinutes: 40, content: { type: "reading", body: spec.core, blocks } },
        { id: `automation-framework-${spec.id}-002`, title: `Apply: ${spec.title}`, estimatedMinutes: 45, content: { type: "practical", objective: `Apply ${spec.title} to the Steward automation project.`, scenario: "Build the automation system incrementally around the real Steward API and environments rather than generating an abstract framework first.", instructions: spec.practice, deliverables: ["Executable framework change", "Focused test using the change", "Diagnostic or maintainability note"], completionCriteria: ["The abstraction removes real repetition or risk.", "Steward domain intent remains readable.", "The change can fail with useful diagnostics."] } },
        { id: `automation-framework-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: `Explain what problem ${spec.title} solves in the Steward test system, what should remain domain-specific, and one way this framework capability could become harmful if overused.`, minimumCharacters: 180 } },
    ] };
}

const specs: Spec[] = [
    { id: "what-framework", title: "What Makes an Automation Framework", core: "A framework is a coherent set of conventions and reusable test infrastructure—not a folder tree. It standardizes recurring concerns such as configuration, execution, clients, fixtures, assertions, evidence and reporting while leaving product behavior visible.", practice: ["Inventory repeated concerns in the current Steward tests.", "Separate genuine infrastructure concerns from Steward domain behavior.", "Write a minimal framework charter describing what the framework will and will not own."], warning: "A framework created before real test repetition exists often becomes speculative infrastructure that tests must work around." },
    { id: "architecture", title: "Framework Architecture", core: "Framework architecture should create clear dependency direction: tests depend on domain helpers and reusable infrastructure; infrastructure must not depend on individual test scenarios. Keep configuration, clients, fixtures, evidence and reporting boundaries understandable.", practice: ["Sketch the Steward automation dependency graph.", "Define packages/modules for infrastructure versus Steward domain workflows.", "Reject any cyclic or test-specific dependency pushed into a generic layer."], code: "src/test/java/com/tsa/steward/\n  api/\n  ui/\n  domain/\n  support/\n    config/\n    evidence/\n    http/\nsrc/test/resources/\npom.xml" },
    { id: "logging", title: "Automation Logging", core: "Automation logs should explain test infrastructure and request context without leaking secrets. Structured context such as environment, release, endpoint and request ID makes failures triageable.", practice: ["Add structured request/test logging.", "Redact authorization headers and tokens.", "Include Steward release/environment identity in test-session diagnostics."] },
    { id: "reports", title: "Reports", core: "Reports summarize evidence for people and systems. They should distinguish failure, skip, xfail and infrastructure error, preserve exact execution identity and avoid converting missing evidence into a green result.", practice: ["Generate a Allure/JUnit report artifact.", "Include environment/release metadata.", "Show how a skipped critical test remains visible to a release reviewer."] },
    { id: "evidence", title: "Screenshots, Traces and Video", core: "Rich browser artifacts are diagnostics, not success metrics. Capture them primarily on failure or for targeted evidence so storage and review remain manageable.", practice: ["Configure screenshot/trace capture on browser failure.", "Attach artifacts with stable test/run identifiers.", "Avoid collecting video for API-only tests where it adds no information."] },
    { id: "retries", title: "Retries and Flaky-test Risk", core: "Retries can distinguish transient symptoms but must not redefine failure as success. Track first-attempt failures, quarantine deliberately when necessary and remove the cause rather than normalizing instability.", practice: ["Introduce a controlled flaky example or analyze an existing one.", "Capture first-attempt failure evidence even when a retry passes.", "Define criteria for quarantine, ownership and removal."], warning: "A green build produced only because failed tests eventually passed can hide real reliability or environment defects." },
    { id: "maintainability", title: "Framework Maintainability", core: "Framework maintenance means preserving simple dependency direction, stable public helpers, fast feedback and clear ownership as the suite grows. Delete unused abstractions and resist centralizing every domain behavior.", practice: ["Review the Steward framework dependency graph.", "Remove or simplify one unnecessary abstraction.", "Document compatibility expectations for reusable infrastructure."] },
];

const frameworkLab: Lesson = { id: "automation-framework-build-steward", title: "Milestone: Consolidate steward-tests as a Coherent Framework", activities: [
    { id: "automation-framework-build-steward-001", title: "Bootstrap the Framework from Existing Tests", estimatedMinutes: 90, content: { type: "practical", objective: "Consolidate the increments already built across Java foundations and API testing into a coherent framework without restarting from a template.", scenario: "steward-tests already exists and has evolved incrementally. Refactor proven repetition; do not regenerate or replace the project.", instructions: ["Review the existing Maven dependency/scoping decisions.", "Consolidate JUnit 5, REST Assured, Jackson and AssertJ support already justified by prior increments, then introduce SLF4J and Allure as diagnostic capabilities.", "Implement validated configuration and release/environment identity.", "Move transport mechanics into a thin API client without moving domain assertions out of tests."], deliverables: ["Coherent evolved framework", "Steward API client", "Configuration model", "Baseline test run"], completionCriteria: ["Existing test intent remains readable.", "No live secret is committed.", "Every retained abstraction is traceable to demonstrated repetition or risk."] } },
    { id: "automation-framework-build-steward-002", title: "Add Data, JUnit Lifecycle and Extensions and Diagnostics", estimatedMinutes: 90, content: { type: "practical", objective: "Make repeatable Steward tests isolated and diagnosable.", scenario: "The framework must support local and CI execution without shared mutable test data becoming hidden coupling.", instructions: ["Add explicit JUnit lifecycle support and test-data builders.", "Add unique identifiers and deterministic cleanup.", "Add safe logging and request evidence.", "Generate reports and failure artifacts appropriate to API/browser tests."], deliverables: ["Lifecycle/data layer", "Evidence/logging layer", "Report artifact", "Cleanup proof"], completionCriteria: ["Tests can run repeatedly without manual cleanup.", "Failures preserve useful evidence.", "Secrets are redacted."] } },
    { id: "automation-framework-build-steward-003", title: "Add Selection, Parallelism and Flake Controls", estimatedMinutes: 75, content: { type: "practical", objective: "Make the framework usable as the suite grows.", scenario: "Execution controls must preserve evidence integrity instead of manufacturing fast green builds.", instructions: ["Define a controlled JUnit tag taxonomy.", "Run a targeted smoke/API selection.", "Document the isolation proof required before parallel execution; actual parallel execution is deferred until the later CI stage.", "Define retry/quarantine policy that keeps first failures visible."], deliverables: ["Tag policy", "Parallel-readiness assessment", "Flake-control policy"], completionCriteria: ["Selection is intentional and reviewable.", "The project has an explicit isolation/readiness decision before parallelism is enabled.", "Retries cannot silently erase first-attempt failures."] } },
] };

export const automationFrameworkEngineeringDeepLessons: Lesson[] = [...specs.map(lessonFrom), frameworkLab];
