import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const pytest: LearningResource = { title: "pytest documentation", url: "https://docs.pytest.org/" };
const playwright: LearningResource = { title: "Playwright API testing", url: "https://playwright.dev/docs/api-testing" };
const pact: LearningResource = { title: "Pact — Contract Testing", url: "https://docs.pact.io/" };

type Spec = { id: string; title: string; intro: string; sections: Array<{ title: string; body: string[]; list?: string[]; code?: string; language?: string }>; practice: string[]; questions: string[] };

function rich(spec: Spec): Lesson {
    const blocks: LessonBlock[] = [{ type: "paragraph", text: spec.intro }];
    for (const section of spec.sections) {
        blocks.push({ type: "heading", id: section.title.toLowerCase().replace(/[^a-z0-9]+/g, "-"), text: section.title, level: 2 });
        section.body.forEach((text) => blocks.push({ type: "paragraph", text }));
        if (section.list) blocks.push({ type: "list", items: section.list });
        if (section.code) blocks.push({ type: "code", language: section.language ?? "text", code: section.code });
    }
    blocks.push({ type: "callout", tone: "steward", title: "Steward integration checkpoint", body: "Use the smallest real boundary required by the risk. Do not mock away the very contract, database behavior, authentication rule or package compatibility you are trying to prove. Broad tests should add new evidence, not duplicate lower-level checks." });
    blocks.push({ type: "resources", title: "Continue learning", resources: [pytest, playwright, pact] });
    return { id: `api-integration-${spec.id}`, title: spec.title, activities: [
        { id: `api-integration-${spec.id}-001`, title: spec.title, estimatedMinutes: 45, content: { type: "reading", body: spec.intro, blocks } },
        { id: `api-integration-${spec.id}-002`, title: `Apply: ${spec.title}`, estimatedMinutes: 55, content: { type: "practical", objective: `Apply ${spec.title} to Steward.`, scenario: "Steward already has unit/component evidence. This module adds confidence at API, persistence, identity, package and service boundaries without turning every test into a full browser scenario.", instructions: spec.practice, deliverables: ["Executable integration evidence", "Boundary rationale", "Diagnostic findings"], completionCriteria: ["The test proves a real contract or integration risk.", "Assertions cover meaningful state and side effects.", "The test leaves the environment reproducible for subsequent execution."] } },
        { id: `api-integration-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.questions.join("\n\n"), minimumCharacters: 180 } },
    ] };
}

const specs: Spec[] = [
    { id: "api-test-design", title: "API Test Design", intro: "API testing treats the service contract as the primary observable boundary. Good API tests combine request semantics, response semantics, persisted effects and authorization rules rather than checking status codes alone.", sections: [
        { title: "Model the contract", body: ["For each Steward endpoint, identify method, route, authentication, request schema, business preconditions, response schema, error contract and side effects. Then derive tests from the same partitions, boundaries and state models created in Test Analysis and Design.", "A 201 response is weak evidence if the service was saved with the wrong owner, lifecycle or environment relationship."], code: "POST /api/services\nAuthorization: Bearer <token>\n\n{\n  \"name\": \"Payments API\",\n  \"slug\": \"payments-api\",\n  \"criticality\": \"high\",\n  \"owner_team_id\": \"team-platform\"\n}\n\nAssert: status + response contract + persisted ownership", language: "http" },
        { title: "Separate protocol from domain claims", body: ["Some assertions prove HTTP behavior: status, headers, content type and schema. Others prove domain behavior: duplicate slugs are rejected, retired services cannot gain dependencies and unauthorized teams cannot mutate ownership. Keep both visible so failures are diagnosable."] },
    ], practice: ["Select one high-risk Steward endpoint.", "Create a test matrix covering happy path, validation, business-rule rejection and authorization.", "For at least one successful request, verify the resulting persisted state rather than the response alone."], questions: ["Why is asserting only the HTTP status code insufficient for many API tests?", "How should earlier equivalence and boundary analysis influence API coverage?"] },
    { id: "auth-testing", title: "Authentication and Authorization Testing", intro: "Authentication establishes who the caller is; authorization determines what that identity may do. Tests must prove both allowed and denied behavior, including the protected state after denial.", sections: [
        { title: "Build an authorization matrix", body: ["Steward has users, teams, memberships and owned services. That creates relationships, not just roles. Test owners, non-owners, privileged operators, missing authentication and stale or invalid credentials where relevant.", "A correct denial has two parts: the API returns the expected error and the protected resource remains unchanged."], list: ["Unauthenticated request", "Authenticated owner-team member", "Authenticated member of another team", "Privileged administrative identity", "Resource with missing or changed ownership"] },
        { title: "Avoid privilege-only happy paths", body: ["Suites that reuse one superuser token can hide broken authorization. Test data and clients should make caller identity explicit in each high-risk scenario."], code: "before = service.owner_team_id\nresponse = other_team_client.patch(url, json={\"owner_team_id\": \"team-other\"})\nassert response.status_code == 403\nservice.refresh_from_db()\nassert service.owner_team_id == before", language: "python" },
    ], practice: ["Create a Steward authorization matrix for service updates and dependency changes.", "Automate at least one allowed and two denied paths.", "For each denied mutation, prove persisted state is unchanged."], questions: ["Why is a 403 assertion alone incomplete evidence for a denied mutation?", "How can a shared admin token hide authorization defects?"] },
    { id: "schema-contract", title: "Schema and Contract Validation", intro: "A stable API contract lets clients depend on field names, types, required properties, status semantics and error shapes. Contract validation detects accidental breaking changes that individual example assertions may miss.", sections: [
        { title: "Validate structure and meaning", body: ["JSON Schema or OpenAPI-based checks can verify structure, but they cannot decide whether a field has the correct business value. Combine structural validation with semantic assertions.", "Error responses deserve a contract too. Generic 500 payloads, untranslated messages or inconsistent field errors make integrations harder to operate even when the happy path works."], list: ["Required fields and types", "Nullable versus omitted fields", "Enum values", "Stable error envelope", "Pagination structure", "Backward-compatible additions versus breaking removals"] },
        { title: "Treat compatibility as a consumer concern", body: ["A provider can satisfy its own tests while breaking a client that depends on a field or behavior. Contract testing becomes especially useful when multiple independently delivered consumers and providers exist." ] },
    ], practice: ["Capture or derive the contract for one Steward collection and one mutation endpoint.", "Add structural checks for both success and validation-error responses.", "Introduce a hypothetical breaking change and explain which check would catch it."], questions: ["What can schema validation prove, and what can it not prove?", "Why should error responses have stable contracts?"] },
    { id: "database-assertions", title: "Database Assertions", intro: "Database assertions are useful when persistence is part of the behavior under test, but they should validate meaningful effects rather than duplicate every ORM detail.", sections: [
        { title: "Use persistence as supporting evidence", body: ["After a Steward ownership change, verifying the persisted owner and audit-relevant relationship can prove the mutation survived beyond serialization. For a rejected request, verifying no row or relationship changed protects invariants.", "Avoid asserting incidental columns or internal query shapes unless those are themselves requirements." ] },
        { title: "Respect transaction boundaries", body: ["Tests should understand when commits occur, how rollback is handled and whether concurrent operations can violate uniqueness or consistency. Database evidence is strongest when the real schema and constraints are active."], code: "response = client.post('/api/services', json=payload)\nassert response.status_code == 201\n\nservice = Service.objects.get(slug='payments-api')\nassert service.owner_team_id == platform_team.id\nassert service.criticality == 'high'", language: "python" },
    ], practice: ["Choose two API scenarios where persistence assertions add meaningful confidence.", "Add a postcondition query for success and a non-mutation assertion for failure.", "Document which database details you deliberately do not assert and why."], questions: ["When do database assertions strengthen an API test?", "Why can over-specific database assertions make tests brittle?"] },
    { id: "integration-boundaries", title: "Integration Boundaries", intro: "Integration tests exist because separately correct components can fail when they meet. The test boundary should include the real interaction whose semantics create risk.", sections: [
        { title: "Name the boundary before writing the test", body: ["Examples in Steward include Django plus PostgreSQL, API plus identity provider, application plus internal package, or deployed service plus reverse proxy. Each boundary has different failure modes and requires different setup.", "If the risk is PostgreSQL uniqueness, an in-memory fake is the wrong boundary. If the risk is application behavior when an email service times out, a controlled substitute may be appropriate."], list: ["What crosses the boundary?", "Which side owns the contract?", "What can drift independently?", "Which failure modes matter?", "What evidence requires the real dependency?"] },
        { title: "Do not confuse breadth with realism", body: ["A larger environment is not automatically more realistic. A focused test with the real dependency under risk often provides stronger evidence and much better diagnostics than an opaque full-stack scenario." ] },
    ], practice: ["Map Steward's major integration boundaries.", "Assign one high-value test to each of three boundaries.", "Explain which dependencies must be real and which may be controlled for each test."], questions: ["Why should an integration test explicitly name its boundary?", "When is a focused integration test more credible than a full end-to-end test?"] },
    { id: "contract-testing", title: "Contract Testing Concepts", intro: "Contract testing checks that independently evolving systems still agree on the interactions they depend on. It is most valuable when provider and consumer releases can drift independently.", sections: [
        { title: "Consumer expectations are part of compatibility", body: ["A schema can remain technically valid while a consumer breaks because a field meaning, status behavior or required interaction changed. Consumer-driven contracts capture examples the consumer actually requires and verify them against the provider.", "Do not introduce contract tooling where there is only one tightly coupled codebase and no independent delivery problem. Use it where organizational or deployment independence creates real compatibility risk." ] },
        { title: "Contracts complement, not replace, integration", body: ["A passing contract does not prove DNS, credentials, database state or production configuration. It reduces one class of compatibility uncertainty so broader integration tests can remain selective." ] },
    ], practice: ["Identify whether any current Steward integration genuinely benefits from consumer-driven contracts.", "Write a small example interaction contract for a plausible consumer of the service registry API.", "State what additional integration evidence remains necessary even if the contract passes."], questions: ["What organizational condition makes contract testing especially valuable?", "Why does a passing contract test not prove the deployed integration works?"] },
    { id: "mocking-virtualization", title: "Mocking and Service Virtualization", intro: "Service virtualization gives tests controllable substitutes for remote systems, especially when real dependencies are expensive, unstable, unavailable or difficult to force into failure states. The substitute must still represent a known contract.", sections: [
        { title: "Virtualize for control, not denial", body: ["A virtual identity or notification service can reproduce timeout, 429, malformed payload and dependency-error scenarios reliably. That is valuable for application error handling. But real integration tests must still verify that assumptions about the actual dependency are true." ] },
        { title: "Version the behavior you simulate", body: ["Untracked mocks become parallel specifications that quietly drift. Keep fixtures or virtualized contracts reviewable and tie them to provider documentation or captured contract evidence."], list: ["Happy response", "Explicit business rejection", "Authentication failure", "Timeout/network failure", "Malformed or incompatible response", "Rate limiting where relevant"] },
    ], practice: ["Choose one Steward external boundary that benefits from controlled failure simulation.", "Define a small virtualization matrix for normal and adverse responses.", "Add one test that proves Steward fails safely when the dependency is unavailable."], questions: ["What is the main risk of an unversioned service mock?", "Which failure modes are often easier to prove with virtualization than with the real provider?"] },
    { id: "package-compatibility", title: "Internal Package Compatibility", intro: "An internal package is also an integration boundary. Versioned dependencies, exported APIs and runtime assumptions can break consumers even when source repositories compile independently.", sections: [
        { title: "Test the dependency as consumed", body: ["Delivery Engineer established internal artifact repositories. Quality Steward should verify Steward against approved package versions exactly as CI and deployment resolve them—not through copied source or local-path shortcuts.", "Compatibility checks should cover public APIs, configuration expectations and the specific behavior Steward relies on. Later the automation framework will extract tsa-test-core and must follow the same discipline." ] },
        { title: "Separate provider tests from consumer confidence", body: ["A package's own unit tests prove its behavior in its repository. Steward still needs evidence that its chosen version integrates with its code and environment. That is a consumer responsibility."], code: "# Example CI intent\npip install --index-url <internal-pypi> tsa-shared==1.4.2\npytest tests/integration/test_shared_package_compatibility.py", language: "bash" },
    ], practice: ["Identify an internal dependency or define a realistic Steward shared-package boundary.", "Design a compatibility test around only the public behavior Steward consumes.", "Ensure the test resolves a versioned artifact rather than a local source path."], questions: ["Why are a package's own passing tests insufficient for every consumer?", "Why does a local-path dependency weaken compatibility evidence?"] },
    { id: "data-setup-cleanup", title: "Data Setup and Cleanup", intro: "Integration tests need data that is explicit, isolated and disposable. Poor test-data management creates order dependence, false failures and environments nobody trusts.", sections: [
        { title: "Own the state you create", body: ["Prefer API factories, database fixtures or builders that create only the relationships required by the scenario. Use unique identifiers so parallel tests do not collide. Cleanup can use transaction rollback, isolated schemas, explicit teardown or disposable environments depending on the boundary." ] },
        { title: "Make preconditions visible", body: ["Hidden global fixtures make tests shorter but harder to understand. A reader should be able to tell why a user belongs to Team A, why a service is retired or why a dependency already exists. Data helpers should express domain intent rather than obscure it."], list: ["Unique test identities", "Minimal domain relationships", "Predictable lifecycle state", "No dependency on execution order", "Safe cleanup after both pass and failure"] },
    ], practice: ["Design reusable data builders for teams, users, services and dependencies.", "Make two integration tests safe to run in parallel.", "Demonstrate cleanup or transaction isolation even when a test fails midway."], questions: ["Why are globally shared fixtures dangerous in integration suites?", "What makes a test-data helper expressive rather than opaque?"] },
];

const lab: Lesson = { id: "api-integration-steward-e2e-service-layer", title: "Lab: Test Steward API End-to-End at the Service Layer", activities: [
    { id: "api-integration-lab-001", title: "Define the Service-layer Test Boundary", estimatedMinutes: 45, content: { type: "practical", objective: "Turn the existing risk model into a focused service-layer integration scope.", scenario: "Use the real Steward API and persistence boundary. Keep browser UI concerns out of this lab unless an endpoint contract itself requires them.", instructions: ["Select critical ownership, lifecycle, dependency and authorization flows.", "Map each scenario to API, database, identity and internal-package boundaries.", "State which dependencies will be real and which will be virtualized.", "Define test data and cleanup strategy before implementation."], deliverables: ["Integration scope", "Boundary map", "Data/cleanup plan"], completionCriteria: ["Every selected test adds evidence not already proven cheaply below.", "Real boundaries match the risk being investigated.", "Environment assumptions are explicit."] } },
    { id: "api-integration-lab-002", title: "Automate Core API and Persistence Flows", estimatedMinutes: 105, content: { type: "practical", objective: "Create executable API evidence with meaningful persistence assertions.", scenario: "Exercise Steward as a service through its API contract using representative identities and real PostgreSQL persistence.", instructions: ["Automate successful service registration and update flows.", "Automate validation and duplicate/conflict behavior.", "Automate ownership and dependency rules derived from earlier test design.", "Assert response contracts and meaningful persisted effects.", "Capture request identifiers and diagnostics for failures."], deliverables: ["API integration suite", "Persistence assertions", "Diagnostic evidence"], completionCriteria: ["Status codes are not the only assertions.", "Persisted state is checked where mutation is the behavior.", "Failures point to contract, domain or persistence causes clearly."] } },
    { id: "api-integration-lab-003", title: "Prove Authorization and Failure Boundaries", estimatedMinutes: 90, content: { type: "practical", objective: "Prove that protected state survives unauthorized and dependency-failure scenarios.", scenario: "High-risk negative paths must demonstrate safe outcomes, not merely error responses.", instructions: ["Run the authorization matrix with distinct caller identities.", "For rejected mutations, prove state remains unchanged.", "Virtualize one external dependency failure such as timeout or malformed response.", "Confirm Steward returns an intentional failure contract and does not partially corrupt state."], deliverables: ["Authorization evidence", "Failure-injection tests", "Protected-state assertions"], completionCriteria: ["Caller identity is explicit.", "Denied writes cannot mutate protected resources.", "Dependency failures result in controlled, diagnosable outcomes."] } },
    { id: "api-integration-lab-004", title: "Add Contract and Compatibility Evidence", estimatedMinutes: 60, content: { type: "practical", objective: "Protect Steward from accidental API and internal dependency drift.", scenario: "Use structural contracts selectively where independent consumers or versioned packages create compatibility risk.", instructions: ["Validate success and error response structures for selected endpoints.", "Add one internal-package compatibility check using a versioned artifact if applicable.", "Document whether consumer-driven contract testing is justified now or should be deferred with a clear trigger.", "Record what these checks still do not prove about deployment/runtime configuration."], deliverables: ["Schema/contract checks", "Package compatibility evidence or justified N/A", "Compatibility decision note"], completionCriteria: ["Contract checks reflect real consumer expectations.", "Local-path shortcuts do not masquerade as package compatibility.", "Limitations of contract evidence are explicit."] } },
    { id: "api-integration-lab-005", title: "API and Integration Testing Review", estimatedMinutes: 30, content: { type: "reflection", prompt: "Defend the Steward API/integration portfolio. Which risks required real PostgreSQL, identity, package or service boundaries; where did virtualization add useful control; what evidence is deliberately left for browser/environment or non-functional testing; and which tests should block a release when they fail?", minimumCharacters: 300 } },
] };

export const apiAndIntegrationTestingDeepLessons: Lesson[] = [...specs.map(rich), lab];
