import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const playwright: LearningResource = { title: "Playwright Python", url: "https://playwright.dev/python/" };
const pytest: LearningResource = { title: "pytest documentation", url: "https://docs.pytest.org/" };
const packaging: LearningResource = { title: "Python Packaging User Guide", url: "https://packaging.python.org/" };

type Spec = { id: string; title: string; core: string; practice: string[]; code?: string; warning?: string };

function lessonFrom(spec: Spec): Lesson {
    const blocks: LessonBlock[] = [
        { type: "paragraph", text: spec.core },
        { type: "heading", id: `${spec.id}-principle`, text: "Engineering principle", level: 2 },
        { type: "paragraph", text: "An automation framework is useful only when it makes high-value checks easier to author, execute, diagnose and maintain. Framework structure must serve test intent; it must not hide Steward domain behavior behind generic abstractions." },
        { type: "heading", id: `${spec.id}-steward`, text: "Apply it to Steward", level: 2 },
        { type: "paragraph", text: `For Steward, ${spec.core.toLowerCase()} The framework should preserve clear release identity, environment configuration and diagnostic evidence while keeping domain workflows close to the tests that need them.` },
    ];
    if (spec.code) blocks.push({ type: "code", language: "python", code: spec.code });
    if (spec.warning) blocks.push({ type: "callout", tone: "warning", title: "Framework risk", body: spec.warning });
    blocks.push({ type: "callout", tone: "steward", title: "Steward automation checkpoint", body: "Generic infrastructure may be reusable. Ownership rules, lifecycle behavior, service registration workflows and Steward-specific assertions are domain code and should remain explicit." });
    blocks.push({ type: "resources", title: "Continue learning", resources: [playwright, pytest, packaging] });
    return { id: `automation-framework-${spec.id}`, title: spec.title, activities: [
        { id: `automation-framework-${spec.id}-001`, title: spec.title, estimatedMinutes: 40, content: { type: "reading", body: spec.core, blocks } },
        { id: `automation-framework-${spec.id}-002`, title: `Apply: ${spec.title}`, estimatedMinutes: 45, content: { type: "practical", objective: `Apply ${spec.title} to the Steward automation project.`, scenario: "Build the automation system incrementally around the real Steward API and environments rather than generating an abstract framework first.", instructions: spec.practice, deliverables: ["Executable framework change", "Focused test using the change", "Diagnostic or maintainability note"], completionCriteria: ["The abstraction removes real repetition or risk.", "Steward domain intent remains readable.", "The change can fail with useful diagnostics."] } },
        { id: `automation-framework-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: `Explain what problem ${spec.title} solves in the Steward test system, what should remain domain-specific, and one way this framework capability could become harmful if overused.`, minimumCharacters: 180 } },
    ] };
}

const specs: Spec[] = [
    { id: "what-framework", title: "What Makes an Automation Framework", core: "A framework is a coherent set of conventions and reusable test infrastructure—not a folder tree. It standardizes recurring concerns such as configuration, execution, clients, fixtures, assertions, evidence and reporting while leaving product behavior visible.", practice: ["Inventory repeated concerns in the current Steward tests.", "Separate genuine infrastructure concerns from Steward domain behavior.", "Write a minimal framework charter describing what the framework will and will not own."], warning: "A framework created before real test repetition exists often becomes speculative infrastructure that tests must work around." },
    { id: "architecture", title: "Framework Architecture", core: "Framework architecture should create clear dependency direction: tests depend on domain helpers and reusable infrastructure; infrastructure must not depend on individual test scenarios. Keep configuration, clients, fixtures, evidence and reporting boundaries understandable.", practice: ["Sketch the Steward automation dependency graph.", "Define packages/modules for infrastructure versus Steward domain workflows.", "Reject any cyclic or test-specific dependency pushed into a generic layer."], code: "tests/\n  api/\n  ui/\nsteward/\n  clients/\n  workflows/\nframework/\n  config/\n  evidence/\n  http/\nconftest.py" },
    { id: "playwright-python", title: "Playwright with Python", core: "Playwright can exercise browser behavior and HTTP APIs from Python. Use browser automation where browser behavior is genuinely under test; use request/API clients for service-layer behavior rather than routing every check through a UI.", practice: ["Initialize Playwright Python in the Steward automation project.", "Create one focused browser smoke check only if Steward has a browser surface to prove.", "Use Playwright request or an API client for a service-level check and compare the evidence cost."], code: "from playwright.sync_api import Page\n\ndef test_service_registry_loads(page: Page, base_url: str):\n    page.goto(base_url)\n    page.get_by_role(\"heading\", name=\"Services\").wait_for()" },
    { id: "pytest", title: "pytest Fundamentals", core: "pytest provides discovery, fixtures, parametrization, markers and concise assertions. Keep test behavior readable and use framework features to reduce setup noise rather than to create hidden execution magic.", practice: ["Create a deterministic pytest smoke test.", "Use plain assertions with readable failure values.", "Organize discovery so local and CI execution collect the intended tests."], code: "def test_service_slug_is_stable(steward_client):\n    service = steward_client.get_service(\"payments-api\")\n    assert service[\"slug\"] == \"payments-api\"" },
    { id: "configuration", title: "Configuration", core: "Configuration should make environment differences explicit without duplicating test logic. Validate required values at startup and distinguish non-secret test settings from credentials or tokens.", practice: ["Define local/UAT configuration inputs for Steward.", "Fail fast when base URL or required identity configuration is absent.", "Ensure secrets are read from approved runtime inputs rather than committed defaults."], code: "@dataclass(frozen=True)\nclass Settings:\n    base_url: str\n    environment: str\n    timeout_ms: int = 10_000" },
    { id: "fixtures", title: "Fixtures", core: "Fixtures provide reusable setup and teardown with explicit scope. Prefer small composable fixtures that expose useful test objects over giant fixtures that silently create an entire world.", practice: ["Create a session-scoped configuration fixture.", "Create a function-scoped Steward client or test-data fixture.", "Demonstrate cleanup that runs even after an assertion fails."], code: "@pytest.fixture\ndef registered_service(steward_client):\n    service = steward_client.create_service(...)\n    yield service\n    steward_client.delete_service(service[\"id\"])" },
    { id: "test-data", title: "Test Data", core: "Test data should be intentional, unique where concurrency matters, and removable. Prefer factories or builders that expose meaningful defaults while allowing tests to state the fields relevant to the behavior.", practice: ["Create a Steward service-data factory with safe defaults.", "Generate unique slugs for parallel-safe tests.", "Make ownership/lifecycle overrides explicit at the call site."], code: "def service_payload(**overrides):\n    data = {\"name\": \"Catalog Test\", \"lifecycle\": \"active\", \"criticality\": \"medium\"}\n    return data | overrides" },
    { id: "api-clients", title: "API Clients", core: "API clients centralize transport mechanics—base URL, headers, serialization, timeouts and raw response capture. They should not hide business expectations or turn every endpoint into a large DSL.", practice: ["Implement a thin Steward API client.", "Preserve status/body/request-id evidence for failing calls.", "Keep business assertions in tests or domain-specific assertion helpers."], code: "class StewardClient:\n    def get_service(self, slug): ...\n    def create_service(self, payload): ...\n    def change_owner(self, slug, team_id): ..." },
    { id: "page-objects", title: "Page Objects and UI Abstractions", core: "UI abstractions should model stable user-facing regions or workflows, not mirror every DOM element. Prefer accessible locators and keep assertions close to the behavior being verified.", practice: ["Identify one stable Steward page or component boundary.", "Create a small page object around meaningful actions.", "Avoid getters for every element and avoid hiding assertions inside navigation methods."], warning: "A page object per page with hundreds of element properties recreates the DOM in Python and increases maintenance cost." },
    { id: "helpers", title: "Helpers and Utilities", core: "Helpers are appropriate for generic repeated mechanics such as unique identifiers, timestamps, polling and artifact paths. Domain rules disguised as utilities create unclear ownership and should remain in Steward-specific code.", practice: ["Extract one truly generic repeated helper.", "Rename or move one domain-specific utility into the Steward layer.", "Add direct tests for any helper with nontrivial behavior."] },
    { id: "assertions", title: "Assertions", core: "Assertions should express meaningful product claims and produce useful diagnostics. Custom assertions are justified when a stable repeated semantic claim exists—not simply to make every assert call look different.", practice: ["Strengthen one Steward API assertion beyond status code.", "Add a domain assertion that includes useful mismatch context.", "Verify denied mutation preserves protected state."], code: "assert response.status_code == 403\nafter = client.get_service(slug)\nassert after[\"owning_team_id\"] == original_team_id" },
    { id: "markers", title: "Markers and Tags", core: "Markers classify tests for intentional selection, ownership or execution constraints. Use a small controlled vocabulary tied to decisions such as smoke, integration, browser or destructive—not arbitrary labels per feature.", practice: ["Define the minimal Steward marker vocabulary.", "Register markers centrally.", "Run one targeted selection and confirm unselected risks remain visible in reporting."], code: "@pytest.mark.smoke\n@pytest.mark.api\ndef test_authenticated_service_lookup(...): ..." },
    { id: "parameterization", title: "Parameterization", core: "Parameterization is valuable when the same behavioral rule applies across meaningful examples. Do not compress distinct scenarios into unreadable tables merely to reduce line count.", practice: ["Parameterize a lifecycle or criticality rule with clear case identifiers.", "Keep expected outcomes visible.", "Split cases when setup or rationale becomes materially different."], code: "@pytest.mark.parametrize(\n    \"lifecycle,can_add_dependency\",\n    [(\"active\", True), (\"retired\", False)],\n    ids=[\"active-allows\", \"retired-rejects\"],\n)" },
    { id: "logging", title: "Automation Logging", core: "Automation logs should explain test infrastructure and request context without leaking secrets. Structured context such as environment, release, endpoint and request ID makes failures triageable.", practice: ["Add structured request/test logging.", "Redact authorization headers and tokens.", "Include Steward release/environment identity in test-session diagnostics."] },
    { id: "reports", title: "Reports", core: "Reports summarize evidence for people and systems. They should distinguish failure, skip, xfail and infrastructure error, preserve exact execution identity and avoid converting missing evidence into a green result.", practice: ["Generate a pytest report artifact.", "Include environment/release metadata.", "Show how a skipped critical test remains visible to a release reviewer."] },
    { id: "evidence", title: "Screenshots, Traces and Video", core: "Rich browser artifacts are diagnostics, not success metrics. Capture them primarily on failure or for targeted evidence so storage and review remain manageable.", practice: ["Configure screenshot/trace capture on browser failure.", "Attach artifacts with stable test/run identifiers.", "Avoid collecting video for API-only tests where it adds no information."] },
    { id: "parallel", title: "Parallel Execution", core: "Parallel execution shortens feedback only if tests are isolated. Shared accounts, static service slugs and mutable global state turn concurrency into nondeterministic interference.", practice: ["Identify Steward data likely to collide under parallelism.", "Make test identities/data unique.", "Run a parallel subset and investigate any ordering assumptions."] },
    { id: "retries", title: "Retries and Flaky-test Risk", core: "Retries can distinguish transient symptoms but must not redefine failure as success. Track first-attempt failures, quarantine deliberately when necessary and remove the cause rather than normalizing instability.", practice: ["Introduce a controlled flaky example or analyze an existing one.", "Capture first-attempt failure evidence even when a retry passes.", "Define criteria for quarantine, ownership and removal."], warning: "A green build produced only because failed tests eventually passed can hide real reliability or environment defects." },
    { id: "maintainability", title: "Framework Maintainability", core: "Framework maintenance means preserving simple dependency direction, stable public helpers, fast feedback and clear ownership as the suite grows. Delete unused abstractions and resist centralizing every domain behavior.", practice: ["Review the Steward framework dependency graph.", "Remove or simplify one unnecessary abstraction.", "Document compatibility expectations for reusable infrastructure." ] },
    { id: "reuse-boundary", title: "Reusable Testing Infrastructure vs Domain Test Code", core: "Reuse should emerge from proven repetition. Generic configuration loading, HTTP foundations, evidence helpers and selected pytest fixtures may serve multiple projects; Steward workflows and business assertions should not be extracted merely because they are reusable inside Steward.", practice: ["Classify current framework modules as generic or Steward-specific.", "Require at least two plausible consumers before extracting shared infrastructure.", "Document what must remain in the Steward repository."] },
    { id: "public-apis", title: "Designing Public APIs for Test Libraries", core: "A shared test library needs a small intentional public API. Consumers should not depend on internal module layout; compatibility changes should be deliberate and versioned.", practice: ["Define the public surface for a candidate tsa-test-core package.", "Hide implementation-only modules.", "Write one consumer example that depends only on the public API."], code: "# tsa_test_core/__init__.py\nfrom .config import load_settings\nfrom .http import ApiSession\n\n__all__ = [\"load_settings\", \"ApiSession\"]" },
    { id: "plugins", title: "Reusable pytest Fixtures and Plugins", core: "pytest plugins can distribute fixtures, hooks and options across projects. Extract only stable generic behavior and avoid plugins that secretly encode Steward test flows.", practice: ["Package one generic fixture or CLI option as a plugin candidate.", "Prove tests can consume it without importing Steward code.", "Keep plugin behavior explicit and documented."], code: "pytest_plugins = [\"tsa_test_core.pytest_plugin\"]" },
    { id: "versioning", title: "Versioning Shared Test Infrastructure", core: "Shared test infrastructure becomes a dependency and therefore needs release identity, compatibility discipline and upgrade evidence. Pin or constrain versions according to the organization's dependency policy.", practice: ["Choose an initial tsa-test-core version.", "Document what constitutes breaking versus additive change.", "Create an upgrade test proving Steward against the candidate package version."] },
];

const frameworkLab: Lesson = { id: "automation-framework-build-steward", title: "Lab: Build the Steward Automation Framework", activities: [
    { id: "automation-framework-build-steward-001", title: "Bootstrap the Framework from Existing Tests", estimatedMinutes: 90, content: { type: "practical", objective: "Create the smallest useful framework around the existing Steward quality evidence.", scenario: "Do not begin from a boilerplate repository. Start from the real API/integration tests already justified by risk.", instructions: ["Create the Python test project and dependency definition.", "Add pytest and Playwright Python where appropriate.", "Implement validated configuration and release/environment identity.", "Move transport mechanics into a thin API client without moving domain assertions out of tests."], deliverables: ["Runnable framework skeleton", "Steward API client", "Configuration model", "Baseline test run"], completionCriteria: ["Existing test intent remains readable.", "No live secret is committed.", "The framework exists because repeated concerns justified it."] } },
    { id: "automation-framework-build-steward-002", title: "Add Data, Fixtures and Diagnostics", estimatedMinutes: 90, content: { type: "practical", objective: "Make repeatable Steward tests isolated and diagnosable.", scenario: "The framework must support local and CI execution without shared mutable test data becoming hidden coupling.", instructions: ["Add composable fixtures and data factories.", "Add unique identifiers and deterministic cleanup.", "Add safe logging and request evidence.", "Generate reports and failure artifacts appropriate to API/browser tests."], deliverables: ["Fixture/data layer", "Evidence/logging layer", "Report artifact", "Cleanup proof"], completionCriteria: ["Tests can run repeatedly without manual cleanup.", "Failures preserve useful evidence.", "Secrets are redacted."] } },
    { id: "automation-framework-build-steward-003", title: "Add Selection, Parallelism and Flake Controls", estimatedMinutes: 75, content: { type: "practical", objective: "Make the framework usable as the suite grows.", scenario: "Execution controls must preserve evidence integrity instead of manufacturing fast green builds.", instructions: ["Register a controlled marker taxonomy.", "Run a targeted smoke/API selection.", "Exercise parallel execution with collision-safe data.", "Define retry/quarantine policy that keeps first failures visible."], deliverables: ["Marker policy", "Parallel run evidence", "Flake-control policy"], completionCriteria: ["Selection is intentional and reviewable.", "Parallelism does not depend on test order.", "Retries cannot silently erase first-attempt failures."] } },
];

const extractionLab: Lesson = { id: "automation-framework-extract-core", title: "Lab: Extract tsa-test-core", activities: [
    { id: "automation-framework-extract-core-001", title: "Prove the Reuse Boundary", estimatedMinutes: 60, content: { type: "practical", objective: "Extract only genuinely generic testing infrastructure from the proven Steward framework.", scenario: "The package should be useful to another future TSA test project without containing Steward business behavior.", instructions: ["Inventory candidate generic modules.", "Reject Steward clients, workflows and domain assertions.", "Define the tsa-test-core public API.", "Move selected configuration/HTTP/evidence/pytest infrastructure behind that API."], deliverables: ["Reuse-boundary decision", "tsa-test-core package", "Public API documentation"], completionCriteria: ["The package imports no Steward domain modules.", "Extraction is based on proven repetition.", "Steward tests remain readable after extraction."] } },
];

const publishLab: Lesson = { id: "automation-framework-publish-core", title: "Lab: Publish and Consume tsa-test-core", activities: [
    { id: "automation-framework-publish-core-001", title: "Build, Publish and Consume the Internal Package", estimatedMinutes: 90, content: { type: "practical", objective: "Turn tsa-test-core into a normal versioned internal dependency.", scenario: "Use the internal PyPI/Nexus capability established during Delivery Engineer; do not use source copying or local-path dependencies as the final integration.", instructions: ["Build a versioned Python distribution.", "Publish it to the internal Python package repository.", "Configure Steward automation to install an approved package version.", "Run the Steward suite using the published artifact.", "Record artifact version and compatibility evidence."], deliverables: ["Published tsa-test-core artifact", "Steward dependency declaration", "Consumer test evidence"], completionCriteria: ["Steward consumes the package through the internal repository.", "No source copy or local-path dependency is required.", "The consumed version is identifiable and reproducible."] } },
    { id: "automation-framework-publish-core-002", title: "Automation Framework Engineering Review", estimatedMinutes: 30, content: { type: "reflection", prompt: "Defend the final framework architecture and tsa-test-core boundary. Which capabilities are genuinely reusable, which Steward behaviors deliberately remain local, how do reports and diagnostics support triage, and what controls prevent parallelism, retries or abstractions from reducing evidence quality?", minimumCharacters: 350 } },
] };

export const automationFrameworkEngineeringDeepLessons: Lesson[] = [
    ...specs.slice(0, 17).map(lessonFrom),
    frameworkLab,
    ...specs.slice(17).map(lessonFrom),
    extractionLab,
    publishLab,
];
