import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const maven: LearningResource = { title: "Apache Maven Guides", url: "https://maven.apache.org/guides/" };
const junit: LearningResource = { title: "JUnit 5 User Guide", url: "https://docs.junit.org/current/user-guide/" };

const boundaryBlocks: LessonBlock[] = [
  { type: "paragraph", text: "Shared test infrastructure becomes justified only after two real product test suites expose stable, demonstrably generic repetition. Quality Steward has only one real product consumer: steward-tests. Do not manufacture another target merely to justify a library. Instead, identify extraction candidates and preserve evidence for the independent Professional Engineer capstone to test later." },
  { type: "heading", id: "reuse-candidates", text: "Audit candidates, do not move folders mechanically", level: 2 },
  { type: "list", items: ["Validated configuration primitives", "Generic REST Assured specification factories", "Playwright browser/context lifecycle foundations", "Evidence and attachment helpers", "Safe logging/redaction", "Selected JUnit extensions", "Generic unique-data utilities"] },
  { type: "heading", id: "must-remain-steward", text: "Keep product behavior with the product", level: 2 },
  { type: "list", items: ["StewardApiClient", "Steward contract DTOs", "Steward page/component objects", "Ownership/lifecycle/dependency workflows", "Steward-specific assertions and test-data semantics"] },
  { type: "resources", title: "Continue learning", resources: [maven, junit] }
];

const boundary: Lesson = { id: "quality-reuse-boundary", title: "Reuse Audit: steward-tests vs tsa-test-core", activities: [
  { id: "quality-reuse-boundary-001", title: "Decide What Is Actually Generic", estimatedMinutes: 50, content: { type: "reading", body: "Perform the reuse audit after Steward test infrastructure is mature enough to expose repeated infrastructure internally. This is a candidate audit, not permission to extract tsa-test-core yet: a second real product consumer does not exist until Professional Engineer. Browser lifecycle participates only when a genuine browser surface was implemented.", blocks: boundaryBlocks } },
  { id: "quality-reuse-boundary-002", title: "Produce the Extraction Decision", estimatedMinutes: 75, content: { type: "practical", objective: "Classify steward-tests infrastructure as product-specific behavior or a candidate for future cross-product reuse.", scenario: "Steward is still the only real product test consumer. Audit mature infrastructure now, but preserve it locally until the independent Professional Engineer capstone creates genuine second-consumer evidence.", instructions: ["Inventory configuration, REST Assured specifications, evidence/logging, JUnit extensions and data utilities that recur inside steward-tests.", "For each candidate record its dependencies, Steward assumptions and the reasons it might or might not transfer to another product.", "Reject anything that imports or encodes Steward domain behavior.", "Define a provisional smallest public API for the strongest generic candidates without extracting them.", "Create a transfer checklist describing what a future second consumer must independently need before extraction is allowed."], deliverables: ["Reuse-boundary decision record", "Candidate/rejected capability table", "Provisional public API", "Professional Engineer transfer checklist"], completionCriteria: ["No fake second product is created.", "Steward-specific workflows remain local.", "Candidates are supported by real repetition inside steward-tests but explicitly remain unextracted.", "The transfer checklist requires independent second-consumer evidence before tsa-test-core can exist."] } }
] };

const handoff: Lesson = { id: "quality-test-core-handoff", title: "Handoff: Earn tsa-test-core with the Next Real Product", activities: [
  { id: "quality-test-core-handoff-001", title: "Preserve the Reuse Hypothesis", estimatedMinutes: 60, content: { type: "practical", objective: "Leave Professional Engineer enough evidence to test the tsa-test-core hypothesis without pre-creating the answer.", scenario: "Quality Steward ends with one mature consumer. The next school will build a genuinely independent system and its tests from a blank repository.", instructions: ["Record candidate capability names and current steward-tests locations.", "Capture representative local duplication and dependencies.", "State the minimum second-consumer evidence required for extraction.", "State that the capstone must implement its initial test infrastructure independently before comparing it with Steward.", "Define extraction rejection conditions: product assumptions, incompatible lifecycle, tiny duplication or an API that would be less clear than local code."], deliverables: ["tsa-test-core reuse hypothesis", "Candidate evidence pack", "Extraction/rejection criteria"], completionCriteria: ["tsa-test-core does not exist yet.", "The handoff is testable by a genuinely independent product.", "Professional Engineer can reject individual candidates while still being required to find and extract at least one truly generic capability after two-consumer evidence exists."] } }
] };

export const qualityReuseAndInternalLibraryDeepLessons: Lesson[] = [boundary, handoff];
