import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const pytest: LearningResource = { title: "pytest documentation", url: "https://docs.pytest.org/" };
const testingGoogle: LearningResource = { title: "Software Engineering at Google — Unit Testing", url: "https://abseil.io/resources/swe-book/html/ch12.html" };
const mocksArentStubs: LearningResource = { title: "Martin Fowler — Mocks Aren't Stubs", url: "https://martinfowler.com/articles/mocksArentStubs.html" };

type Spec = { id: string; title: string; intro: string; sections: Array<{ title: string; body: string[]; list?: string[]; code?: string }>; practice: string[]; questions: string[] };

function rich(spec: Spec): Lesson {
    const blocks: LessonBlock[] = [{ type: "paragraph", text: spec.intro }];
    for (const section of spec.sections) {
        blocks.push({ type: "heading", id: section.title.toLowerCase().replace(/[^a-z0-9]+/g, "-"), text: section.title, level: 2 });
        section.body.forEach((text) => blocks.push({ type: "paragraph", text }));
        if (section.list) blocks.push({ type: "list", items: section.list });
        if (section.code) blocks.push({ type: "code", language: "python", code: section.code });
    }
    blocks.push({ type: "callout", tone: "steward", title: "Steward test-design checkpoint", body: "Use the risk and test-design artifacts from the previous Quality Steward modules. Put evidence at the smallest credible boundary. A fast test that proves the wrong thing is not useful; a huge integrated test for a local rule is unnecessary cost." });
    blocks.push({ type: "resources", title: "Continue learning", resources: [pytest, testingGoogle, mocksArentStubs] });
    return { id: `unit-component-${spec.id}`, title: spec.title, activities: [
        { id: `unit-component-${spec.id}-001`, title: spec.title, estimatedMinutes: 45, content: { type: "reading", body: spec.intro, blocks } },
        { id: `unit-component-${spec.id}-002`, title: `Apply: ${spec.title}`, estimatedMinutes: 50, content: { type: "practical", objective: `Apply ${spec.title} to Steward's Python/Django codebase.`, scenario: "Strengthen Steward at code and component boundaries before adding broader API/integration automation.", instructions: spec.practice, deliverables: ["Executable tests or focused test design", "Reason for the chosen boundary", "Failure-diagnostic note"], completionCriteria: ["Tests express observable behavior rather than implementation trivia.", "Dependencies are real or replaced deliberately according to the risk.", "A failure points toward a useful engineering cause."] } },
        { id: `unit-component-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.questions.join("\n\n"), minimumCharacters: 180 } },
    ] };
}

const specs: Spec[] = [
    { id: "designing-unit-tests", title: "Designing Unit Tests", intro: "A unit test gives fast evidence about a small behavior boundary. The useful definition of a unit is not necessarily one function: it is the smallest coherent boundary that can prove the behavior without irrelevant infrastructure.", sections: [
        { title: "Test behavior, not line execution", body: ["Start from a rule discovered during test analysis. For Steward, a lifecycle transition, ownership invariant or dependency rule is a stronger test target than whether an internal helper was called.", "Arrange only the state relevant to the behavior, perform one meaningful action, then assert the externally meaningful result. Multiple assertions are fine when they describe one outcome."], code: "def test_retired_service_cannot_gain_new_dependency():\n    service = Service(lifecycle=\"retired\")\n\n    result = service.add_dependency(other_service)\n\n    assert result.is_rejected\n    assert result.reason == \"retired_service\"" },
        { title: "Tests are executable examples", body: ["Names and fixtures should explain the rule. Avoid tests whose only purpose is to mirror every branch or private method. Refactoring internal structure should not break tests when externally meaningful behavior remains unchanged."], list: ["One recognizable behavior or rule", "Minimal relevant setup", "Deterministic result", "Meaningful failure message", "No dependence on unrelated network, clock or database behavior"] },
    ], practice: ["Choose three high-risk Steward domain rules from the risk-to-evidence matrix.", "Design unit tests for the rules that can be proven without infrastructure.", "Name each test as a behavioral claim and explain what defect it would detect."], questions: ["Why is one function not always the best definition of a unit?", "What makes a unit test resilient to harmless refactoring?"] },
    { id: "isolation", title: "Isolation", intro: "Isolation removes irrelevant causes of failure from a test. It is a means to speed and diagnosis, not a command to replace every collaborator with a mock.", sections: [
        { title: "Choose the isolation boundary deliberately", body: ["If you are proving a pure ownership rule, PostgreSQL and HTTP add no useful evidence. If you are proving a repository query, replacing the database destroys the behavior you need to investigate. Isolation follows the question.", "Excessive isolation creates tests for an imaginary system where collaborators always behave exactly as configured."] },
        { title: "Control nondeterminism", body: ["Time, randomness, external APIs and shared mutable data are common instability sources. Introduce explicit seams where the product already has a meaningful dependency boundary; do not contort the architecture merely to satisfy a mocking library."], list: ["Keep local domain logic local.", "Use real value objects freely.", "Replace slow or nondeterministic external boundaries when their behavior is not the test target.", "Use real infrastructure when integration semantics are the risk."] },
    ], practice: ["Inspect one Steward test target and list its collaborators.", "Mark each collaborator as relevant or irrelevant to the behavior being proven.", "Design the smallest isolation boundary that preserves credible evidence."], questions: ["When does isolation reduce test credibility?", "Why should a database sometimes remain real in a component test?"] },
    { id: "test-doubles", title: "Test Doubles", intro: "A test double substitutes for a production collaborator so a test can control inputs, observe interactions or avoid an irrelevant external dependency. The important decision is what contract the double represents and why substitution is valid.", sections: [
        { title: "Doubles have different jobs", body: ["A fake implements useful behavior in a lightweight way, a stub returns configured responses, and a spy records interactions. Terminology varies across tools; focus on the role the substitute plays in the evidence model."], list: ["Stub: supplies predetermined indirect input.", "Spy: records calls for later observation.", "Fake: working but simplified implementation, such as in-memory storage.", "Mock: expectation-oriented substitute used to verify interaction."] },
        { title: "A double can lie", body: ["If Steward's identity provider changes its response contract while a hand-written stub remains unchanged, unit tests can stay green. Contract or integration tests must eventually verify the real boundary. A double trades integration realism for control and speed."], code: "class FixedIdentityClient:\n    def __init__(self, team_ids):\n        self.team_ids = team_ids\n\n    def teams_for(self, user_id):\n        return self.team_ids" },
    ], practice: ["Choose a Steward collaborator that is reasonable to replace in a focused test.", "Implement or sketch a minimal double that exposes only the required contract.", "Document which real integration behavior this double cannot prove."], questions: ["What risk is introduced when a stub drifts from the real collaborator contract?", "When is a fake preferable to a heavily configured mock?"] },
    { id: "mocks-stubs-fakes", title: "Mocks, Stubs and Fakes", intro: "Choosing among mocks, stubs and fakes changes what a test asserts. State-based assertions usually ask what outcome occurred; interaction assertions ask how collaborators were used. Both can be valid, but interaction tests couple more tightly to implementation decisions.", sections: [
        { title: "Prefer observable outcomes where possible", body: ["If registering a Steward service should create an ownership record, asserting the resulting component state is usually stronger than asserting that repository.save was called once. Interaction assertions become useful when the interaction itself is the contract—for example, ensuring a sensitive audit event is emitted exactly when required."] },
        { title: "Avoid mock-shaped architecture", body: ["Do not create interfaces for every class only because tests can mock them. Boundaries should exist for domain or architectural reasons. Over-mocked suites often pass while real components fail to collaborate."], code: "# brittle: verifies incidental choreography\nrepo.save.assert_called_once_with(service)\ncache.invalidate.assert_called_once()\n\n# stronger when available: verify the meaningful result\nassert registry.get(service.slug).owner_team_id == platform_team.id" },
    ], practice: ["Review three proposed Steward assertions and classify them as state- or interaction-based.", "Replace one incidental mock assertion with a meaningful outcome assertion.", "Keep one interaction assertion only where the interaction itself is a requirement and justify it."], questions: ["Why are interaction-heavy tests often more sensitive to refactoring?", "Give an example where verifying an interaction is the actual behavior requirement."] },
    { id: "coverage", title: "Coverage and Its Limitations", intro: "Coverage measures which code structures were exercised, not whether important behavior was proven. It is useful as a gap-finding signal and dangerous as a quality target detached from risk.", sections: [
        { title: "Execution is not assertion", body: ["A line can be executed by a test that never checks the consequence. Even 100% statement coverage can miss boundary combinations, missing requirements, concurrency behavior and incorrect assertions.", "Use coverage to ask why important code is untouched, not to declare that a percentage means the product is safe."], code: "# This can execute the branch without proving the rule.\nservice.change_lifecycle(\"retired\")\n\n# Evidence requires a meaningful outcome.\nassert service.lifecycle == \"retired\"\nassert service.accepts_new_dependencies is False" },
        { title: "Risk outranks percentage", body: ["A security-sensitive authorization branch with no direct evidence matters more than several trivial getters that reduce a global percentage. Mutation testing and branch coverage can expose weaknesses, but neither replaces thoughtful test design."] },
    ], practice: ["Run or conceptually inspect coverage for a focused Steward component.", "Identify one uncovered path that matters and one uncovered line that is low value.", "Find one covered behavior whose assertions are too weak and strengthen them."], questions: ["Why can 100% statement coverage coexist with serious defects?", "What is a productive use of coverage data?"] },
    { id: "component-boundaries", title: "Component Boundaries", intro: "A component test exercises a cohesive slice of the application with more real collaboration than a unit test while keeping unrelated external systems controlled. It is often the best place to prove framework wiring, persistence behavior and domain coordination together.", sections: [
        { title: "Choose a meaningful slice", body: ["In Django, a component boundary might include application service, ORM models and a test PostgreSQL database while bypassing public HTTP and external identity infrastructure. That proves database constraints and transaction behavior without paying for the whole deployed system.", "The boundary should be explicit enough that failures are diagnosable and broad enough to include the interactions under risk."], list: ["Domain/service logic", "Real ORM and schema when persistence semantics matter", "Framework validation when relevant", "Controlled external identity/email/cloud collaborators", "No public DNS/TLS/reverse-proxy path unless that is the test target"] },
        { title: "Component tests bridge the pyramid", body: ["Many important defects live between isolated units and full systems. Component tests provide credible integration evidence with better speed and control than broad end-to-end flows, reducing pressure to make the browser or public API suite prove everything."] },
    ], practice: ["Draw one Steward component boundary around service registration or ownership changes.", "Mark which dependencies remain real and which are substituted.", "Design tests that prove one transaction, persistence constraint and domain rule inside that boundary."], questions: ["How does a component test differ from a narrowly isolated unit test?", "Why can component tests reduce reliance on end-to-end tests?"] },
    { id: "fast-feedback", title: "Fast Feedback and Maintainability", intro: "A test suite is production engineering infrastructure. Its value decays when it is slow, flaky, opaque or expensive to change. Fast feedback matters because evidence that arrives after the decision point cannot protect that decision.", sections: [
        { title: "Optimize the feedback portfolio", body: ["Keep deterministic local checks numerous and fast. Reserve slower infrastructure tests for behavior that requires those boundaries. Avoid arbitrary sleeps, shared state and giant fixtures that make failures order-dependent.", "Speed should not be purchased by deleting meaningful evidence. Instead, move each claim to the cheapest boundary that can prove it."], list: ["Deterministic setup and cleanup", "Small expressive fixtures", "Stable behavioral assertions", "Parallel-safe data where appropriate", "Failure output that identifies the violated rule"] },
        { title: "Maintain tests with the product", body: ["Duplication in tests can be cheaper than abstractions that hide intent. Extract helpers when a stable concept repeats, but keep domain meaning visible. Delete tests whose behavior no longer exists; dead tests are not historical documentation."] },
    ], practice: ["Inspect or design a Steward unit/component suite for likely sources of slowness and flakiness.", "Move one claim to a cheaper credible boundary.", "Refactor one fixture/helper only if it improves readability without hiding the business rule."], questions: ["Why is a slow test not automatically a bad test?", "When can DRY abstractions make tests harder to maintain?"] },
];

const lab: Lesson = { id: "unit-component-strengthen-steward", title: "Lab: Strengthen Steward Component Tests", activities: [
    { id: "unit-component-strengthen-steward-001", title: "Select the Evidence Boundary", estimatedMinutes: 45, content: { type: "practical", objective: "Translate the existing Steward test design into unit and component boundaries.", scenario: "Use the risk-based coverage model from Test Analysis and Design rather than starting from source files or coverage percentages.", instructions: ["Select high-value domain and persistence risks.", "Classify which can be proven as units and which require a Django/PostgreSQL component boundary.", "Record collaborators and decide which remain real, fake, stubbed or mocked.", "Explain what broader integration evidence will still be required later."], deliverables: ["Unit/component coverage map", "Boundary diagram", "Double-selection rationale"], completionCriteria: ["Each test boundary is justified by the behavior under risk.", "Real integration semantics are not mocked away accidentally.", "Remaining uncertainty is explicit."] } },
    { id: "unit-component-strengthen-steward-002", title: "Implement High-value Unit Tests", estimatedMinutes: 90, content: { type: "practical", objective: "Create fast executable evidence for Steward domain behavior.", scenario: "Prioritize lifecycle, ownership, dependency and authorization-adjacent domain rules that do not require full infrastructure.", instructions: ["Implement representative positive, negative and boundary cases derived from the previous module.", "Use behavioral names and minimal setup.", "Control time or external collaborators only where necessary.", "Ensure failures identify the violated business rule."], deliverables: ["Executable unit tests", "Focused fixtures/doubles", "Test run evidence"], completionCriteria: ["Tests are deterministic and fast.", "Assertions prove meaningful outcomes.", "Tests do not mirror private implementation structure unnecessarily."] } },
    { id: "unit-component-strengthen-steward-003", title: "Implement Component Evidence", estimatedMinutes: 90, content: { type: "practical", objective: "Prove important collaboration inside Steward without requiring the full deployed system.", scenario: "Use a real persistence/framework boundary where database constraints, transactions or Django behavior are part of the risk.", instructions: ["Configure an isolated test database using the project's established tooling.", "Exercise at least one persistence constraint or transactional behavior.", "Exercise a domain workflow across multiple real internal collaborators.", "Keep unrelated external infrastructure controlled.", "Capture diagnostics for a deliberately failing assertion, then restore the suite."], deliverables: ["Executable component tests", "Database/setup approach", "Failure diagnostic evidence"], completionCriteria: ["The component boundary includes the semantics under test.", "Tests remain reproducible and isolated from developer data.", "A failure is substantially easier to diagnose than an equivalent full-system failure."] } },
    { id: "unit-component-strengthen-steward-004", title: "Review Coverage and Feedback Cost", estimatedMinutes: 45, content: { type: "practical", objective: "Evaluate the suite as an evidence system rather than by test count.", scenario: "The suite must be fast enough to protect normal development while retaining credible coverage of important rules.", instructions: ["Review execution time and coverage signals.", "Find one meaningful gap and strengthen it.", "Identify any redundant or implementation-coupled test and simplify or remove it.", "Document which risks deliberately remain for API/integration testing in the next module."], deliverables: ["Coverage review", "Suite-maintainability note", "API/integration handoff"], completionCriteria: ["Coverage percentages are interpreted rather than treated as targets.", "The suite supports fast developer feedback.", "The next test level has an explicit responsibility rather than duplicate coverage."] } },
    { id: "unit-component-strengthen-steward-005", title: "Unit and Component Testing Review", estimatedMinutes: 30, content: { type: "reflection", prompt: "Defend the final Steward unit/component test portfolio. Which important claims are now proven cheaply, which required a real component boundary, where did you deliberately avoid mocking, and what evidence must still come from API/integration testing?", minimumCharacters: 300 } },
] };

export const unitAndComponentTestingDeepLessons: Lesson[] = [...specs.map(rich), lab];
