import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const playwright: LearningResource = { title: "Playwright Java", url: "https://playwright.dev/java/" };
const junit: LearningResource = { title: "JUnit 5 User Guide", url: "https://docs.junit.org/current/user-guide/" };
const restAssured: LearningResource = { title: "REST Assured", url: "https://rest-assured.io/" };
const maven: LearningResource = { title: "Apache Maven", url: "https://maven.apache.org/guides/" };
const slf4j: LearningResource = { title: "SLF4J Manual", url: "https://www.slf4j.org/manual.html" };
const allureJunit: LearningResource = { title: "Allure — JUnit 5", url: "https://allurereport.org/docs/junit5/" };
const allureAttachments: LearningResource = { title: "Allure — Attachments", url: "https://allurereport.org/docs/attachments/" };

const resourcesFor = (id: string): LearningResource[] => {
    if (id === "logging" || id === "failure-classification") return [slf4j, junit];
    if (id === "allure") return [allureJunit, allureAttachments];
    if (id === "artifact-policy") return [allureAttachments, playwright];
    if (id === "retries" || id === "flake-management") return [junit];
    if (id === "architecture" || id === "what-framework" || id === "maintainability") return [junit, restAssured, playwright];
    return [junit, maven];
};

type Spec = { id: string; title: string; core: string; mechanics?: string[]; signals?: string[]; antiPatterns?: string[]; practice: string[]; code?: string; warning?: string };

function lessonFrom(spec: Spec): Lesson {
    const blocks: LessonBlock[] = [
        { type: "paragraph", text: spec.core },
        { type: "heading", id: `${spec.id}-principle`, text: "Engineering principle", level: 2 },
        { type: "paragraph", text: "An automation framework is useful only when it makes high-value checks easier to author, execute, diagnose and maintain. Framework structure must serve test intent; it must not hide Steward domain behavior behind generic abstractions." },
        { type: "heading", id: `${spec.id}-steward`, text: "Apply it to Steward", level: 2 },
        { type: "paragraph", text: `For Steward, ${spec.core.toLowerCase()} The framework should preserve clear release identity, environment configuration and diagnostic evidence while keeping domain workflows close to the tests that need them.` },
    ];
    if (spec.mechanics) blocks.push({ type: "heading", id: `${spec.id}-mechanics`, text: "Mechanics", level: 2 }, { type: "list", items: spec.mechanics });
    if (spec.signals) blocks.push({ type: "heading", id: `${spec.id}-signals`, text: "Evidence and signals", level: 2 }, { type: "list", items: spec.signals });
    if (spec.antiPatterns) blocks.push({ type: "heading", id: `${spec.id}-anti-patterns`, text: "Failure patterns to recognize", level: 2 }, { type: "list", items: spec.antiPatterns });
    if (spec.code) blocks.push({ type: "code", language: "java", code: spec.code });
    if (spec.warning) blocks.push({ type: "callout", tone: "warning", title: "Framework risk", body: spec.warning });
    blocks.push({ type: "callout", tone: "steward", title: "Steward automation checkpoint", body: "Generic infrastructure may be reusable. Ownership rules, lifecycle behavior, service registration workflows and Steward-specific assertions are domain code and should remain explicit." });
    blocks.push({ type: "resources", title: "Continue learning", resources: resourcesFor(spec.id) });
    return { id: `automation-framework-${spec.id}`, title: spec.title, activities: [
        { id: `automation-framework-${spec.id}-001`, title: spec.title, estimatedMinutes: 40, content: { type: "reading", body: spec.core, blocks } },
        { id: `automation-framework-${spec.id}-002`, title: `Apply: ${spec.title}`, estimatedMinutes: 45, content: { type: "practical", objective: `Apply ${spec.title} to the Steward automation project.`, scenario: "Build the automation system incrementally around the real Steward API and environments rather than generating an abstract framework first.", instructions: spec.practice, deliverables: ["Executable framework change", "Focused test using the change", "Diagnostic or maintainability note"], completionCriteria: ["The abstraction removes real repetition or risk.", "Steward domain intent remains readable.", "The change can fail with useful diagnostics."] } },
        { id: `automation-framework-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: `Explain what problem ${spec.title} solves in the Steward test system, what should remain domain-specific, and one way this framework capability could become harmful if overused.`, minimumCharacters: 180 } },
    ] };
}

const specs: Spec[] = [
    { id: "what-framework", title: "What Makes an Operable Automation Framework", core: "A framework is a coherent set of conventions and reusable infrastructure that makes tests easier to author, execute and diagnose. At this stage the Java/API foundations already exist, so framework work must improve operability rather than invent another abstraction layer.", mechanics: ["Define explicit ownership for configuration, transport, domain clients, evidence and reporting.", "Keep test outcome separate from diagnostic collection.", "Make execution identity available consistently without global mutable state."], signals: ["Can a failed unattended test be understood from its artifacts?", "Can a reviewer identify environment, release and exact test invocation?", "Can infrastructure failure be distinguished from product assertion failure?"], antiPatterns: ["Folder structure presented as architecture.", "Generic helpers that hide Steward behavior.", "Diagnostics that change whether a test passes."], practice: ["Inventory repeated operational concerns in current Steward tests.", "Separate genuine infrastructure concerns from Steward domain behavior.", "Write a framework charter defining responsibilities and non-responsibilities.", "Define a minimum evidence contract for every automated run."], warning: "A framework is not successful because it has many helpers; it is successful when failures remain trustworthy and diagnosable." },

    { id: "architecture", title: "Framework Dependency and Evidence Architecture", core: "The framework needs two understandable flows: dependencies flow from tests toward stable infrastructure, while evidence flows from execution toward logs, attachments and reports. Neither flow should create cycles or hidden domain behavior.", mechanics: ["Tests may depend on Steward clients/pages plus generic support.", "Evidence collectors observe execution but must not own business assertions.", "Run/test identity should connect logs, API evidence, browser artifacts and Allure results.", "Package-private implementation details reduce accidental framework API surface."], signals: ["One run ID/test invocation can correlate artifacts.", "Domain packages do not depend on reporting implementations.", "Evidence failure does not silently turn product failure into success."], antiPatterns: ["Allure calls scattered through every domain assertion.", "A global TestContext storing every client/page/token/artifact.", "Reporting package imported by business models."], practice: ["Sketch dependency and evidence-flow diagrams.", "Identify and remove one potential cycle.", "Define the execution/test identity propagated across evidence.", "Decide which support APIs should remain package-private."], code: "test -> StewardApiClient/Page -> transport/browser support\n                         \\n                          -> evidence events -> logs/Allure/artifacts" },

    { id: "logging", title: "SLF4J, Structured Logging and Secret Redaction", core: "Logs are chronological operational evidence. SLF4J gives Java code a logging API while the runtime logging implementation controls formatting and destinations. Test logs should provide context without becoming a second report or leaking credentials.", mechanics: ["Use parameterized logging rather than string concatenation for structured values.", "Choose levels intentionally: ERROR for failed operations requiring attention, WARN for degraded/risky conditions, INFO for high-value lifecycle identity, DEBUG/TRACE for investigation detail.", "Attach stable fields such as run ID, test ID, environment, release and correlation ID through an explicit context strategy.", "Redact Authorization, cookies, tokens, passwords and sensitive payload fields before serialization/logging.", "Never depend on logging side effects for test behavior."], signals: ["A failure can be correlated across test/API/browser evidence.", "Normal passing runs are not flooded with low-value lines.", "Secrets are absent even when requests fail."], antiPatterns: ["System.out.println as framework logging.", "Logging full request/response bodies by default.", "INFO logs for every locator/action.", "MDC/ThreadLocal context added without cleanup under parallel execution."], practice: ["Add SLF4J with a deliberate runtime implementation/configuration.", "Define the minimum INFO context for a test start/failure.", "Create a redaction utility/policy and test it with representative secrets.", "Correlate one REST Assured request ID with the test log.", "Demonstrate cleanup of any thread-scoped logging context."], code: "log.info(\"test_start testId={} environment={} release={}\", testId, environment, release);\nlog.debug(\"api_request method={} path={} correlationId={}\", method, path, correlationId);" },

    { id: "failure-classification", title: "Failure Classification and Diagnostic Taxonomy", core: "Not every red test means the product violated a requirement. Classify failures so humans and CI can distinguish product evidence from automation, environment and dependency problems without converting uncertainty into green.", mechanics: ["Product assertion failure: observed behavior contradicts the tested claim.", "Automation/framework failure: locator/client/setup/evidence code cannot execute the claim reliably.", "Environment/infrastructure failure: target, network, DNS, certificate, browser worker or test dependency is unavailable/misconfigured.", "Test-data/precondition failure: required state could not be established.", "Dependency failure may itself be product behavior if resilience of that dependency boundary is the claim under test."], signals: ["Classification includes original throwable/cause and execution identity.", "Unknown/unclassified remains visible rather than guessed.", "Trend data can separate product regression rate from test-system health."], antiPatterns: ["Marking environment errors as skipped and calling the run green.", "Catching AssertionError and relabeling it flaky.", "Classifying from exception class alone without execution context."], practice: ["Create examples of each failure class.", "Design a small FailureCategory model and classification decision record.", "Classify five controlled failures while preserving original causes.", "Define what CI/release reporting does with unknown classification."], warning: "Classification is metadata about evidence; it must not rewrite a failed test into a pass." },

    { id: "allure", title: "Allure as an Evidence Presentation Layer", core: "Allure organizes test results, steps, parameters, attachments and environment information for investigation. It should present evidence produced by tests and infrastructure—not become the place where domain logic lives.", mechanics: ["JUnit/Allure integration observes test lifecycle and result status.", "Steps should describe meaningful user/system operations, not every Java method.", "Attachments need stable names, media types, size/retention discipline and sanitization.", "Environment/build metadata should identify the exact target and artifact.", "History/trend features are useful only when test identity remains stable across runs."], signals: ["A failed result links the relevant request/response or browser evidence.", "Critical skips/aborts remain visible.", "The report identifies environment/release/run.", "Attachments are useful without exposing secrets."], antiPatterns: ["@Step on every helper method.", "Attaching every API body on every passing test.", "Using Allure labels as the only source of test taxonomy.", "Report generation failure masking the original test outcome."], practice: ["Integrate Allure with the JUnit execution already built.", "Add meaningful environment/release metadata.", "Attach sanitized API evidence on a controlled failure.", "Add a meaningful high-level step and reject low-value method-level steps.", "Prove a skipped/aborted critical test remains visible."], code: "Allure.addAttachment(\"sanitized-response.json\", \"application/json\", sanitizedBody);" },

    { id: "artifact-policy", title: "Evidence Artifacts, Retention and Sensitivity", core: "Screenshots, traces, videos, payloads and logs have different diagnostic value, storage cost and sensitivity. Evidence policy decides what is captured, when, for how long and who may see it.", mechanics: ["Failure-only capture reduces noise for expensive artifacts.", "API bodies may contain PII/secrets even after header redaction.", "Playwright traces can contain DOM snapshots, network details and storage-related data.", "Artifact naming should include stable run/test identity rather than timestamps alone.", "Retention should reflect investigation windows and organizational controls."], signals: ["Every artifact type has capture trigger, sensitivity and retention rule.", "A reviewer can trace an artifact to one test invocation.", "Missing artifact capture is itself observable."], antiPatterns: ["Always-on video because storage is cheap.", "Uploading raw tokens/cookies into CI artifacts.", "Artifact filenames that collide in parallel runs."], practice: ["Create an evidence-policy table for logs, API request/response, screenshots, traces and video.", "Implement collision-safe artifact naming.", "Sanitize a representative sensitive payload.", "Simulate attachment failure and preserve the original test result." ] },

    { id: "retries", title: "Retries without Manufacturing Green Builds", core: "A retry is an observation strategy for suspected transience, not a correctness strategy. The first failure remains evidence even when a later attempt passes, and mutation retries can create harmful duplicate side effects.", mechanics: ["Record attempt number and preserve first-attempt evidence.", "Retry only explicitly eligible operations/tests with bounded attempts.", "Never automatically retry arbitrary state-changing API operations.", "Differentiate test rerun from transport-level retry; both can duplicate effects.", "A pass-after-retry is a flaky/recovered outcome for trend purposes, not equivalent to first-attempt pass."], signals: ["First-attempt pass rate is measurable.", "Retry eligibility/reason is visible.", "Recovered tests remain queryable as instability.", "No retry hides a permanent product regression."], antiPatterns: ["Retry every failed JUnit test three times.", "Retry POST after timeout without idempotency protection.", "Publishing only the final attempt to reports."], practice: ["Create/analyze one controlled transient failure.", "Preserve first-attempt evidence through a bounded retry experiment.", "Define retry eligibility and forbidden mutation cases.", "Represent pass-after-retry distinctly in the diagnostic record."], warning: "If the dashboard only becomes green after retries, the automation system has hidden information." },

    { id: "flake-management", title: "Flake Measurement, Quarantine and Ownership", core: "Flakiness is nondeterministic evidence under equivalent intended conditions. Treat it as engineering debt with measurable frequency, ownership and an exit condition—not as a permanent suite category.", mechanics: ["Track first-attempt executions, failures and recovered retries per stable test identity.", "Separate product/environment instability from automation nondeterminism when evidence supports that distinction.", "Quarantine removes a test from a blocking gate only under explicit policy; it does not delete visibility.", "Every quarantined test needs owner, reason, date and exit/fix criterion.", "Repeated execution can help reproduce flakiness but can also amplify side effects."], signals: ["First-pass rate and flake/recovery rate are visible over a defined window.", "Quarantine inventory is reviewable and aging is measurable.", "High-flake tests trigger engineering work instead of higher retry counts."], antiPatterns: ["Calling every intermittent environment outage a flaky test.", "Permanent @Tag(\"flaky\") with no owner.", "Deleting unstable tests from reporting to protect pass rate."], practice: ["Define the steward-tests flake record fields.", "Calculate a sample first-pass and recovered-after-retry rate.", "Write quarantine entry/exit criteria.", "Create an ownership workflow for one hypothetical flaky test." ] },

    { id: "maintainability", title: "Framework Maintainability and Operability Review", core: "Maintainability means the framework remains understandable under change and operable under failure. Public helpers should be small, diagnostics consistent, dependencies controlled and unused abstractions deleted.", mechanics: ["Track framework public API surface and dependency direction.", "Prefer stable domain-readable operations over generic meta-frameworks.", "Keep diagnostic integrations replaceable behind narrow boundaries where useful.", "Measure suite runtime, first-pass reliability and diagnostic completeness alongside test count."], signals: ["A new engineer can trace one failure without reading the whole framework.", "Unused abstractions can be deleted without product behavior changes.", "Framework upgrades have focused compatibility evidence."], antiPatterns: ["Test count as the primary framework success metric.", "One central utility class imported everywhere.", "Framework version upgrades without compatibility tests."], practice: ["Review the Steward dependency/evidence graph.", "Remove or simplify one unnecessary abstraction.", "Define three operability indicators beyond pass percentage.", "Document compatibility expectations for future reusable infrastructure." ] },
];

const operabilityMilestone: Lesson = { id: "automation-framework-operability-milestone", title: "Milestone: Diagnose an Unattended Regression Run", activities: [
 { id: "automation-framework-operability-milestone-001", title: "Build the Evidence and Failure-triage Backbone", estimatedMinutes: 180, content: { type: "practical", objective: "Make a mixed API/browser test run diagnosable without rerunning it interactively or exposing secrets.", scenario: "Imagine GitLab CI/CD ran the suite overnight and several tests failed. A morning reviewer must determine what failed, where, against which release, and whether the evidence points to product, automation, environment or precondition problems.", instructions: ["Define run ID and stable test-invocation identity and propagate them through logs/evidence.", "Configure SLF4J logging with deliberate levels and tested redaction.", "Integrate Allure as a presentation layer with environment/release identity.", "Implement the failure-category model while preserving original causes.", "Create an artifact policy for API evidence, screenshots, traces and video.", "Trigger controlled product-assertion, automation and environment/precondition failures and compare their evidence.", "Run a bounded retry experiment that preserves the first failure.", "Create a quarantine record with owner, reason and exit criterion.", "Define first-pass reliability and diagnostic-completeness measures."], deliverables: ["Evidence architecture", "SLF4J configuration and redaction tests", "Allure report", "Failure-classification evidence", "Artifact policy", "Retry evidence preserving attempt one", "Quarantine record", "Operability metrics"], completionCriteria: ["A reviewer can identify environment/release/test/attempt from artifacts.", "No representative secret appears in logs or attachments.", "Product failure is distinguishable from framework/environment/precondition failure.", "Pass-after-retry is not represented as equivalent to first-attempt pass.", "Quarantine cannot make a test disappear from visibility.", "Diagnostic collection failure cannot manufacture a passing result."] } }
] };

const frameworkLab: Lesson = { id: "automation-framework-build-steward", title: "Milestone: Consolidate steward-tests as a Coherent Framework", activities: [
    { id: "automation-framework-build-steward-001", title: "Bootstrap the Framework from Existing Tests", estimatedMinutes: 90, content: { type: "practical", objective: "Consolidate the increments already built across Java foundations and API testing into a coherent framework without restarting from a template.", scenario: "steward-tests already exists and has evolved incrementally. Refactor proven repetition; do not regenerate or replace the project.", instructions: ["Review the existing Maven dependency/scoping decisions.", "Consolidate JUnit 5, REST Assured, Jackson and AssertJ support already justified by prior increments, then introduce SLF4J and Allure as diagnostic capabilities.", "Implement validated configuration and release/environment identity.", "Move transport mechanics into a thin API client without moving domain assertions out of tests."], deliverables: ["Coherent evolved framework", "Steward API client", "Configuration model", "Baseline test run"], completionCriteria: ["Existing test intent remains readable.", "No live secret is committed.", "Every retained abstraction is traceable to demonstrated repetition or risk."] } },
    { id: "automation-framework-build-steward-002", title: "Add Data, JUnit Lifecycle and Extensions and Diagnostics", estimatedMinutes: 90, content: { type: "practical", objective: "Make repeatable Steward tests isolated and diagnosable.", scenario: "The framework must support local and CI execution without shared mutable test data becoming hidden coupling.", instructions: ["Add explicit JUnit lifecycle support and test-data builders.", "Add unique identifiers and deterministic cleanup.", "Add safe logging and request evidence.", "Generate reports and failure artifacts appropriate to API/browser tests."], deliverables: ["Lifecycle/data layer", "Evidence/logging layer", "Report artifact", "Cleanup proof"], completionCriteria: ["Tests can run repeatedly without manual cleanup.", "Failures preserve useful evidence.", "Secrets are redacted."] } },
    { id: "automation-framework-build-steward-003", title: "Add Selection, Parallelism and Flake Controls", estimatedMinutes: 75, content: { type: "practical", objective: "Make the framework usable as the suite grows.", scenario: "Execution controls must preserve evidence integrity instead of manufacturing fast green builds.", instructions: ["Define a controlled JUnit tag taxonomy.", "Run a targeted smoke/API selection.", "Document the isolation proof required before parallel execution; actual parallel execution is deferred until the later CI stage.", "Define retry/quarantine policy that keeps first failures visible."], deliverables: ["Tag policy", "Parallel-readiness assessment", "Flake-control policy"], completionCriteria: ["Selection is intentional and reviewable.", "The project has an explicit isolation/readiness decision before parallelism is enabled.", "Retries cannot silently erase first-attempt failures."] } },
] };

export const automationFrameworkEngineeringDeepLessons: Lesson[] = [...specs.map(lessonFrom), operabilityMilestone, frameworkLab];
