import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const maven: LearningResource = { title: "Apache Maven Guides", url: "https://maven.apache.org/guides/" };
const junit: LearningResource = { title: "JUnit 5 User Guide", url: "https://docs.junit.org/current/user-guide/" };

const boundaryBlocks: LessonBlock[] = [
  { type: "paragraph", text: "Shared test infrastructure becomes justified only after two real consumers expose stable, demonstrably generic repetition. TSA deliberately creates that second consumer before extraction; Steward domain behavior must remain local even when many Steward tests use it." },
  { type: "heading", id: "reuse-candidates", text: "Audit candidates, do not move folders mechanically", level: 2 },
  { type: "list", items: ["Validated configuration primitives", "Generic REST Assured specification factories", "Playwright browser/context lifecycle foundations", "Evidence and attachment helpers", "Safe logging/redaction", "Selected JUnit extensions", "Generic unique-data utilities"] },
  { type: "heading", id: "must-remain-steward", text: "Keep product behavior with the product", level: 2 },
  { type: "list", items: ["StewardApiClient", "Steward contract DTOs", "Steward page/component objects", "Ownership/lifecycle/dependency workflows", "Steward-specific assertions and test-data semantics"] },
  { type: "resources", title: "Continue learning", resources: [maven, junit] }
];

const boundary: Lesson = { id: "quality-reuse-boundary", title: "Reuse Audit: steward-tests vs tsa-test-core", activities: [
  { id: "quality-reuse-boundary-001", title: "Decide What Is Actually Generic", estimatedMinutes: 50, content: { type: "reading", body: "Perform the reuse audit after Steward test infrastructure is mature enough to compare against a second real TSA test consumer. Browser lifecycle participates only when a genuine browser surface was implemented.", blocks: boundaryBlocks } },
  { id: "quality-reuse-boundary-002", title: "Produce the Extraction Decision", estimatedMinutes: 75, content: { type: "practical", objective: "Create a second real TSA test consumer, then classify repeated capabilities as product-specific or genuinely reusable.", scenario: "TSA now introduces a small independent verification target outside Steward specifically to test transfer of test infrastructure. Build its tests without tsa-test-core first so duplication is observable rather than assumed.", instructions: ["Create a small independent TSA verification target with at least API/configuration/evidence needs that overlap steward-tests but no Steward domain model.", "Implement its initial JUnit/REST Assured tests locally without importing Steward test packages.", "Inventory configuration, API specifications, evidence/logging, JUnit and data utilities repeated across the two consumers.", "For each candidate record both consumers, dependencies and product assumptions.", "Reject anything that imports or encodes Steward domain behavior.", "Define the smallest intentional public API for capabilities proven generic by both consumers."], deliverables: ["Second-consumer test project and passing baseline", "Reuse-boundary decision record", "Accepted/rejected candidate table", "Proposed public API"], completionCriteria: ["Two independent consumers exist before extraction.", "Every accepted capability is demonstrated in both consumers.", "No Steward workflow crosses the boundary.", "At least one stable product-independent capability is identified for the required extraction milestone."] } }
] };

const extract: Lesson = { id: "quality-extract-test-core", title: "Milestone: Extract tsa-test-core", activities: [
  { id: "quality-extract-test-core-001", title: "Extract Only the Approved Infrastructure", estimatedMinutes: 120, content: { type: "practical", objective: "Extract the product-independent capability proven by the two-consumer audit into tsa-test-core.", scenario: "The preceding exercise has already produced two independent consumers and demonstrated at least one stable generic capability. Extraction is now required, but its scope must remain the smallest boundary supported by that evidence.", instructions: ["Review the two-consumer evidence and select only capabilities demonstrated generic in both systems.", "Create the tsa-test-core Maven project.", "Move only approved generic capabilities.", "Keep implementation internals package-private where possible.", "Add focused library tests.", "Update both consumers to use the locally built artifact during extraction.", "Prove tsa-test-core has no dependency on Steward or second-consumer domain packages.", "Run both consumer suites and compare readability/duplication with the pre-extraction baseline."], deliverables: ["tsa-test-core Maven project", "Library tests and small public API", "Two-consumer compatibility runs", "Before/after reuse evidence"], completionCriteria: ["No consumer domain package is imported by tsa-test-core.", "Both consumers resolve the same generic capability through tsa-test-core.", "Both suites remain readable and passing.", "Extraction reduces demonstrated duplication/coupling rather than merely moving files."] } }
] };

const publish: Lesson = { id: "quality-publish-test-core", title: "Milestone: Publish and Consume tsa-test-core", activities: [
  { id: "quality-publish-test-core-001", title: "Use tsa-test-core as a Versioned Internal Dependency", estimatedMinutes: 105, content: { type: "practical", objective: "Publish the earned tsa-test-core library through Nexus and consume the same version from both real test projects.", scenario: "The shared library now has two proven consumers. Source copying and local-path integration are no longer acceptable as the final distribution state.", instructions: ["Assign a version according to the compatibility policy.", "Build and deploy the JAR to Nexus.", "Declare the approved dependency in both consumer pom.xml files.", "Remove temporary local-project coupling used during extraction.", "Run both compatibility suites from clean dependency resolution.", "Record artifact version, provenance and upgrade evidence."], deliverables: ["Versioned Nexus artifact", "Maven dependency declaration", "Compatibility evidence", "Versioning note"], completionCriteria: ["Both consumers resolve tsa-test-core from Nexus.", "The exact version is traceable and a compatibility failure can block promotion.", "No copied library source or local-path dependency remains in either consumer.", "The shared package remains free of either product domain."] } }
] };

export const qualityReuseAndInternalLibraryDeepLessons: Lesson[] = [boundary, extract, publish];
