import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";
const java: LearningResource = { title: "Java Language Guide", url: "https://dev.java/learn/" };
const maven: LearningResource = { title: "Apache Maven Guides", url: "https://maven.apache.org/guides/" };
const junit: LearningResource = { title: "JUnit 5 User Guide", url: "https://docs.junit.org/current/user-guide/" };
type Spec = {
 id: string; title: string; principle: string; mechanics: string[]; frameworkUse: string[];
 antiPatterns: string[]; practice: string[]; questions: string[]; code?: string;
};
function lesson(spec: Spec): Lesson {
 const blocks: LessonBlock[]=[
  {type:"paragraph",text:spec.principle},
  {type:"heading",id:`${spec.id}-mechanics`,text:"Mechanics you must understand",level:2},
  {type:"list",style:"unordered",items:spec.mechanics},
  {type:"heading",id:`${spec.id}-framework`,text:"Why framework engineers need this",level:2},
  {type:"list",style:"unordered",items:spec.frameworkUse},
  {type:"heading",id:`${spec.id}-failure-patterns`,text:"Failure patterns to recognize",level:2},
  {type:"list",style:"unordered",items:spec.antiPatterns},
 ];
 if(spec.code) blocks.push({type:"code",language:"java",code:spec.code});
 blocks.push({type:"heading",id:`${spec.id}-check`,text:"Check your understanding",level:2},{type:"list",style:"unordered",items:spec.questions},{type:"resources",title:"Continue learning",resources:[java,maven,junit]});
 return {id:`quality-java-${spec.id}`,title:spec.title,activities:[
  {id:`quality-java-${spec.id}-001`,title:spec.title,estimatedMinutes:55,content:{type:"reading",body:spec.principle,blocks}},
  {id:`quality-java-${spec.id}-002`,title:`Build: ${spec.title}`,estimatedMinutes:65,content:{type:"practical",objective:`Apply ${spec.title} while growing steward-tests.`,scenario:"Every exercise changes the real test project. Small isolated experiments are allowed only to expose a Java mechanism before applying it to steward-tests.",instructions:spec.practice,deliverables:["Committed steward-tests increment","Executable example or test","Short design note answering the lesson questions"],completionCriteria:["The learner can explain the Java mechanism without framework magic.","The increment compiles and tests execute.","The design keeps dependencies explicit.","The learner can identify the lesson anti-patterns in a code review."]}}
 ]};
}

const specs: Spec[]=[
{id:"jvm-maven",title:"Java, the JVM and Maven Project Model",principle:"A Java test framework is compiled software. Learn how source becomes bytecode, how the JVM loads classes and how Maven constructs the compile/test classpaths so build failures are diagnosable rather than mysterious.",
mechanics:["JDK tools compile source into JVM bytecode; the JVM executes loaded classes.","Packages provide namespacing; imports are source-level name resolution, not dependency installation.","The classpath determines which compiled classes and JARs are visible at compile/test/runtime.","Maven coordinates identify artifacts as groupId:artifactId:version.","Dependency scopes change classpath visibility; test-scoped automation dependencies should not leak into production artifacts.","Maven phases form a lifecycle; plugins bind goals such as compilation and Surefire test execution.","Surefire discovers/runs unit-style JUnit tests during test; Failsafe can later separate integration-test lifecycle semantics when justified."],
frameworkUse:["Diagnose dependency/version/classpath failures in enterprise Maven projects.","Know why a JUnit test can compile but fail during execution due to runtime dependencies.","Reason about internal Nexus artifacts rather than treating pom.xml as configuration magic."],
antiPatterns:["Adding dependencies until compilation happens to pass.","Using compile scope for every test library.","Confusing Maven dependency resolution with Java imports.","Running only from an IDE and never proving the Maven build."],
practice:["Create steward-tests as a Java 17+ Maven project.","Inspect javac/target/classes and target/test-classes after a build.","Use the Maven standard directory layout deliberately.","Add compiler and Surefire configuration.","Inspect dependency:tree and explain one transitive dependency.","Run clean test from the command line and narrate the relevant lifecycle phases."],
questions:["What is the difference between the JDK, JVM and Java source language?","What does Maven do that JUnit does not?","Why can dependency scope affect runtime behavior?","Where does Surefire fit between Maven and JUnit?"],code:"mvn -U clean test\nmvn dependency:tree"},

{id:"types-modeling",title:"Classes, Records, Enums and Immutability",principle:"Framework state should be explicit and hard to corrupt. Java's type system can make configuration, environment identity and test data safer before any automation library is involved.",
mechanics:["A class combines state and behavior; constructors establish valid initial state.","Records provide concise nominal immutable data carriers, though referenced mutable objects can still mutate.","Enums model a closed set of named values and may contain behavior.","final prevents reassignment/overriding depending on context; it does not recursively make object graphs immutable.","Access modifiers define API boundaries inside the framework."],
frameworkUse:["Represent environment/configuration without stringly typed values.","Keep test configuration stable throughout one execution.","Expose only intentional framework APIs and keep implementation details package-private."],
antiPatterns:["public mutable fields used as framework configuration.","String values such as \"qa\" and \"prod\" copied throughout tests.","A giant mutable TestContext carrying unrelated state.","Assuming final makes a mutable List immutable."],
practice:["Model TestSettings as an immutable record.","Model Environment and Lifecycle as enums.","Validate invariants at construction/loading boundaries.","Create a ServicePayload model without mutable global defaults.","Choose access modifiers deliberately and justify one package-private type."],
questions:["When would you choose a record over a normal class?","What does final guarantee and what does it not?","Why are enums safer than arbitrary environment strings?"]},


{id:"equality-object-contracts",title:"Object Contracts: equals, hashCode and toString",principle:"Test code compares objects constantly. Understand Java object equality and hashing so assertions, Sets, Maps and diagnostic output behave predictably.",
mechanics:["Object identity (== for references) asks whether two references point to the same object; equals expresses logical equality when implemented.","Equal objects must produce equal hashCode values for hash-based collections to behave correctly.","Records generate component-based equals, hashCode and toString automatically.","A useful toString aids diagnostics but must not leak secrets."],
frameworkUse:["Compare DTOs and expected models correctly.","Use records safely as Map keys/Set members where appropriate.","Produce readable failure messages without dumping tokens/passwords."],
antiPatterns:["Using == to compare Strings or DTO instances.","Overriding equals without a consistent hashCode.","Auto-generated toString exposing credentials or authorization headers."],
practice:["Demonstrate identity versus logical equality with two equivalent objects.","Use a record and inspect generated equality/hash behavior.","Use an object in a HashSet and explain the contract.","Review framework models for sensitive toString output."],
questions:["What does == compare for object references?","Why must equals and hashCode agree?","Why can convenient diagnostic output become a security problem?"]},
{id:"interfaces-composition",title:"Interfaces, Composition and Dependency Direction",principle:"A maintainable framework assembles small capabilities rather than inheriting behavior from a giant base class. Interfaces are contracts; composition decides which implementations collaborate.",
mechanics:["Interfaces define callable contracts independently of a concrete implementation.","implements satisfies a contract; extends creates inheritance and tighter structural coupling.","Composition stores/receives collaborators and delegates behavior to them.","Dependency inversion means high-level policy can depend on stable abstractions rather than concrete infrastructure."],
frameworkUse:["Swap token acquisition without rewriting API clients.","Separate transport, configuration and evidence responsibilities.","Keep tests independent from a framework inheritance hierarchy."],
antiPatterns:["BaseTest owns browser, API client, credentials, data and reporting.","Deep inheritance chains where changing setup breaks unrelated tests.","Interface-per-class ceremony with no alternate boundary or architectural value."],
practice:["Define a TokenProvider contract.","Create two tiny implementations or one implementation plus fake.","Compose it into a client rather than constructing credentials globally.","Draw the dependency direction and identify which side owns the interface.","Reject a BaseTest god object in a short architecture note."],
questions:["Composition versus inheritance: what changes in coupling?","When is an interface useful and when is it ceremony?","Which direction should a product-specific client depend on authentication infrastructure?"],code:"interface TokenProvider { String token(); }"},

{id:"dependency-injection",title:"Constructor Dependency Injection",principle:"Dependency injection is explicit collaborator supply, not synonymous with Spring. Constructor injection makes required dependencies visible and prevents partially initialized framework objects.",
mechanics:["A constructor can require all collaborators needed for valid operation.","The composition root chooses concrete implementations and assembles the object graph.","A fake or stub can satisfy the same contract in focused tests.","DI containers automate object construction/lifetime; they do not create dependency inversion by themselves."],
frameworkUse:["Supply TestSettings, TokenProvider and later specifications/browser factories explicitly.","Make framework components testable without network credentials.","Understand Spring/Guice later without needing them for a small automation project."],
antiPatterns:["new TokenProvider() hidden inside StewardApiClient.","Static service locators such as Context.get(ApiClient.class).","Field injection that permits invisible/uninitialized dependencies.","Adding Spring solely because the framework has constructors."],
practice:["Inject TestSettings and TokenProvider into a client constructor.","Create a fake TokenProvider for a focused test.","Create a small composition root/factory where concrete objects are assembled.","Compare constructor injection with service-locator and static-singleton alternatives."],
questions:["What exactly is being injected?","Where should object construction happen?","What problem would a DI container solve here, and do we have that problem yet?"],code:"final class StewardApiClient {\n  private final TestSettings settings;\n  private final TokenProvider tokens;\n  StewardApiClient(TestSettings settings, TokenProvider tokens) {\n    this.settings = settings; this.tokens = tokens;\n  }\n}"},

{id:"generics-collections",title:"Generics and Collections",principle:"Generics preserve type contracts across reusable code; collections represent groups and mappings. Framework code needs enough mastery to read library APIs and avoid unsafe casting, not abstraction for its own sake.",
mechanics:["List, Set and Map encode different collection semantics.","Generic type parameters such as T are compile-time type variables.","Bounded generics constrain acceptable types; wildcards express variance at API boundaries.","Type erasure means most generic type arguments are not directly available at runtime."],
frameworkUse:["Understand REST Assured/Jackson APIs and typed helper signatures.","Choose Set where uniqueness is semantic and Map where keyed lookup is semantic.","Recognize why deserializing nested generic JSON can require explicit type information."],
antiPatterns:["Using Map<String,Object> for every response forever.","Raw List/Map types and unchecked casts.","A universal generic API client that obscures endpoint semantics.","Streams/generics used only to make code look sophisticated."],
practice:["Use List, Set and Map deliberately in test-data code.","Create one small typed helper and explain T.","Observe a type-erasure consequence with a nested collection example.","Compare the generic helper with an explicit endpoint method and retain the clearer contract."],
questions:["What does T mean at compile time?","What information does type erasure remove?","Why might List<ServiceResponse> need special deserialization handling?"]},

{id:"exceptions-resources",title:"Exceptions and Resource Management",principle:"Automation infrastructure fails too: configuration, files, HTTP setup and browsers can all break. Preserve causes, classify failures honestly and close owned resources deterministically.",
mechanics:["Checked exceptions must be declared/handled; unchecked exceptions derive from RuntimeException.","Exception chaining preserves the original cause.","try-with-resources closes AutoCloseable resources even when work fails.","finally exists for cleanup but try-with-resources expresses ownership more safely when supported."],
frameworkUse:["Produce actionable configuration failures.","Later manage Playwright/browser/file resources safely.","Distinguish test assertion failure from framework/environment failure."],
antiPatterns:["catch (Exception e) {}.","Catching infrastructure failure and calling it a skipped/passed test.","Throwing a new exception without the original cause.","Opening resources whose ownership/cleanup is unclear."],
practice:["Wrap one configuration failure with actionable context without losing its cause.","Use try-with-resources with a closeable resource.","Write one test proving cleanup happens on failure.","Reject catch-all code that converts infrastructure failure into a passing or skipped test."],
questions:["When does try-with-resources call close?","Why preserve the cause?","What is dangerous about treating environment failure as a test failure or skip without classification?"]},

{id:"annotations-reflection",title:"Annotations and Reflection",principle:"JUnit's programming model relies on metadata and runtime discovery. Understanding the mechanism prevents annotation-heavy framework code from becoming magic.",
mechanics:["Annotations attach structured metadata to declarations.","Retention controls whether annotation metadata survives into class files/runtime.","Target restricts where an annotation can be applied.","Reflection lets code inspect classes, methods and annotations at runtime.","JUnit discovers annotated tests/lifecycle methods and invokes them through its engine."],
frameworkUse:["Understand @Test, @BeforeEach, @Tag, @ParameterizedTest and @ExtendWith.","Later design custom composed annotations only when repeated semantics justify them.","Debug why a test is or is not discovered."],
antiPatterns:["Creating custom annotations for aesthetics.","Assuming annotations execute behavior by themselves.","Reflection-heavy helpers that bypass normal type safety without need."],
practice:["Create a tiny runtime annotation and inspect it via reflection.","Explain conceptually how JUnit discovers @Test methods.","Use @Test, @DisplayName and lifecycle annotations intentionally.","Break test discovery deliberately once, diagnose it, then restore it."],
questions:["Does @Test itself execute a method?","Why does retention matter?","What component interprets JUnit annotations?"]},

{id:"junit-tags",title:"JUnit 5 Architecture, Lifecycle and Tags",principle:"JUnit is more than @Test. Understand Platform, Jupiter, discovery, instances, lifecycle callbacks, parameterization and tags before building extensions or CI selection around it.",
mechanics:["JUnit Platform provides discovery/execution infrastructure; Jupiter is the JUnit 5 programming model/engine.","Test instances and @BeforeEach/@AfterEach lifecycle affect state ownership.","Parameterized tests execute one behavior against multiple argument sets.","Tags are metadata used by launchers/build tooling for intentional selection.","Extensions provide explicit lifecycle/interception/parameter-resolution hooks when ordinary composition is insufficient."],
frameworkUse:["Create smoke/api/browser portfolios without duplicating suites.","Choose lifecycle boundaries for test-owned data.","Understand how Maven Surefire delegates execution to the JUnit Platform."],
antiPatterns:["A tag for every feature or Jira ticket.","Order-dependent tests sharing instance/static state.","Extensions used to hide ordinary object construction.","@BeforeAll creating mutable global product state."],
practice:["Define the initial steward-tests tag vocabulary.","Demonstrate @BeforeEach/@AfterEach ownership.","Create one @ParameterizedTest with MethodSource.","Tag a small test set and execute one selected group with Maven/Surefire.","Document forbidden/redundant tags and when an extension would be justified."],
questions:["What is the difference between JUnit Platform and Jupiter?","Who interprets @Tag during Maven execution?","When should setup remain explicit instead of becoming an extension?"],code:"@Tag(\"smoke\")\n@Tag(\"api\")\n@Test\nvoid healthEndpointIsAvailable() {}"},

{id:"functional-java",title:"Lambdas, Functional Interfaces, Streams and Optional",principle:"Functional Java is useful for callbacks and transformations common in libraries, but framework code must optimize for diagnosis and readability.",
mechanics:["A functional interface has one abstract method and can be implemented with a lambda.","Method references are concise lambda forms when intent remains obvious.","Streams form lazy transformation pipelines terminated by an operation such as toList or collect.","Optional models a value that may be absent; it is not a universal replacement for null or every field."],
frameworkUse:["Read modern Java/library APIs confidently.","Express small test-data transformations and callbacks.","Understand functional hooks encountered in framework/library APIs."],
antiPatterns:["Ten-stage streams that are harder to debug than a loop.","Optional fields everywhere in DTOs without semantic reason.","Side effects hidden inside map/filter operations."],
practice:["Implement one small transformation with a stream.","Implement the same logic imperatively and compare diagnosis/readability.","Use a method reference where it genuinely improves clarity.","Use Optional only where absence is part of the contract."],
questions:["What makes an interface functional?","When does a stream actually execute?","When is a loop clearer than a stream?"]},

{id:"concurrency",title:"Concurrency, Shared State and Thread Safety",principle:"Parallel automation is concurrent software. Learn enough Java concurrency to recognize unsafe framework state before JUnit or CI executes tests simultaneously.",
mechanics:["Threads can interleave access to shared state nondeterministically.","Immutable values reduce synchronization needs.","Atomicity, visibility and ordering are separate concurrency concerns.","ThreadLocal associates state with a thread but introduces lifecycle/cleanup risks and does not fix bad ownership.","Concurrent collections solve specific data-structure hazards, not domain-level race conditions."],
frameworkUse:["Recognize why static clients/pages/test data become flaky under parallel execution.","Design unique test identities and isolated browser contexts later.","Make an evidence-based decision before enabling JUnit parallelism."],
antiPatterns:["static mutable currentUser/currentPage/currentService.","Adding synchronized everywhere after flakes appear.","ThreadLocal used as a global-variable disguise.","Enabling parallel=true because CI is slow before proving isolation."],
practice:["Identify every mutable singleton/static value in steward-tests.","Create a tiny race demonstration and explain why its outcome is unsafe.","Make test identity/data collision-safe.","Explain one legitimate ThreadLocal use and its cleanup obligation.","Keep parallel execution disabled and write the conditions required to enable it later."],
questions:["What state is actually shared between concurrent tests?","Why does immutability help?","What problem does ThreadLocal solve, and what problems does it not solve?"]}
];
const milestone: Lesson={id:"quality-java-foundation-milestone",title:"Milestone: steward-tests Java Foundation",activities:[{id:"quality-java-foundation-milestone-001",title:"Build the Framework Substrate Without Hiding the Mechanics",estimatedMinutes:120,content:{type:"practical",objective:"Produce the Java/Maven foundation on which the later REST Assured and Playwright framework will grow.",scenario:"The repository should demonstrate Java engineering fundamentals before specialized automation libraries hide them.",instructions:["Make steward-tests compile and execute with Maven and JUnit 5.","Implement validated immutable configuration.","Use constructor injection for dependencies.","Create test-data models/builders with explicit ownership.","Define the governed JUnit tag vocabulary.","Add one tiny Java HttpClient probe so the learner experiences raw HTTP before REST Assured.","Record concurrency hazards before enabling parallel execution."],deliverables:["steward-tests Maven project","JUnit baseline","Configuration/domain support","Tag policy","Raw HTTP probe","Architecture note"],completionCriteria:["mvn test succeeds.","No Spring/DI container is required.","No god BaseTest or mutable global driver/client exists.","Dependencies are explicit.","The learner can explain what JUnit and REST Assured will later abstract."]}}]};
export const javaForTestFrameworkEngineeringDeepLessons: Lesson[]=[...specs.map(lesson),milestone];
