import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const junit: LearningResource = { title: "JUnit 5 User Guide", url: "https://docs.junit.org/current/user-guide/" };
const restAssured: LearningResource = { title: "REST Assured", url: "https://rest-assured.io/" };
const pact: LearningResource = { title: "Pact — Contract Testing", url: "https://docs.pact.io/" };

type Spec = { id: string; title: string; intro: string; sections: Array<{ title: string; body: string[]; list?: string[]; code?: string; language?: string }>; practice: string[]; questions: string[] };

function rich(spec: Spec): Lesson {
    const blocks: LessonBlock[] = [{ type: "paragraph", text: spec.intro }];
    for (const section of spec.sections) {
        blocks.push({ type: "heading", id: section.title.toLowerCase().replace(/[^a-z0-9]+/g, "-"), text: section.title, level: 2 });
        section.body.forEach((text) => blocks.push({ type: "paragraph", text }));
        if (section.list) blocks.push({ type: "list", items: section.list });
        if (section.code) blocks.push({ type: "code", language: section.language ?? "text", code: section.code });
    }
    blocks.push({ type: "callout", tone: "steward", title: "Steward integration checkpoint", body: "Use the smallest real boundary required by the risk. Do not mock away the very contract, database behavior, authentication rule or package compatibility you are trying to prove. Broad tests should add new evidence, not duplicate lower-level checks." });
    blocks.push({ type: "resources", title: "Continue learning", resources: [junit, restAssured, pact] });
    return { id: `api-integration-${spec.id}`, title: spec.title, activities: [
        { id: `api-integration-${spec.id}-001`, title: spec.title, estimatedMinutes: 45, content: { type: "reading", body: spec.intro, blocks } },
        { id: `api-integration-${spec.id}-002`, title: `Apply: ${spec.title}`, estimatedMinutes: 55, content: { type: "practical", objective: `Apply ${spec.title} to Steward.`, scenario: "Steward already has unit/component evidence. This module adds confidence at API, persistence, identity, package and service boundaries without turning every test into a full browser scenario.", instructions: spec.practice, deliverables: ["Executable integration evidence", "Boundary rationale", "Diagnostic findings"], completionCriteria: ["The test proves a real contract or integration risk.", "Assertions cover meaningful state and side effects.", "The test leaves the environment reproducible for subsequent execution."] } },
        { id: `api-integration-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.questions.join("\n\n"), minimumCharacters: 180 } },
    ] };
}

const specs: Spec[] = [
    { id: "http-semantics", title: "HTTP Semantics for Test Engineers", intro: "REST Assured is an HTTP client DSL; it cannot compensate for weak HTTP reasoning. Learn the protocol semantics first so assertions distinguish transport behavior, representation metadata and Steward business rules.", sections: [
        { title: "Method semantics and safety", body: ["GET and HEAD are defined as safe methods; PUT and DELETE are idempotent by semantics while POST generally is not. Idempotency means repeating the same intended request has the same intended effect, not necessarily an identical response body or zero server work.", "Tests should challenge duplicate/retry behavior where payment-like or create operations could cause harmful repeated effects."], list: ["GET: retrieve representation", "POST: process/create according to resource semantics", "PUT: replace/create at a known resource target", "PATCH: partial modification semantics defined by the media type/API", "DELETE: remove target semantics"] },
        { title: "Status and representation semantics", body: ["Status families communicate protocol outcomes, but exact codes should reflect the API contract. A response also has headers and a representation whose Content-Type tells the client how to interpret the body.", "Distinguish 401 authentication problems from 403 authorization refusal, 404 resource absence, 409 state conflict and validation-oriented 4xx contracts according to the API's documented semantics." ] },
        { title: "Caching, conditional requests and correlation", body: ["ETag/If-Match or similar conditional semantics can prevent lost updates when an API supports them. Correlation/request identifiers make distributed failures traceable and should be captured without leaking secrets."], list: ["Content-Type describes the representation sent", "Accept expresses representations the client can consume", "Authorization carries credentials and must be redacted", "Location may identify a newly created resource", "Retry-After can guide clients after throttling/service conditions"] },
    ], practice: ["Use curl or Java HttpClient to inspect one Steward request/response at the wire-contract level.", "Classify its method as safe/idempotent or neither and explain retry implications.", "Assert Content-Type and one meaningful header in addition to status/body.", "Record a correlation/request ID where available.", "Design one duplicate-request/idempotency scenario."], questions: ["What does idempotent mean and what does it not guarantee?", "What is the difference between Content-Type and Accept?", "Why are 401 and 403 materially different evidence?", "When can a retry create a business defect?"] },

    { id: "rest-assured-model", title: "REST Assured Request, Response and Assertion Model", intro: "Use REST Assured as an explicit HTTP automation DSL. Learn its request construction, execution, extraction and assertion model before wrapping it in framework helpers.", sections: [
        { title: "given / when / then is a separation of concerns", body: ["given configures request state, when executes the HTTP interaction and then validates the response. The fluent shape is useful only if it keeps protocol and domain intent visible.", "Start with direct tests before extracting specifications or clients so you can see which repetition is real."] , code: "Response response = given()\n    .baseUri(settings.baseUrl())\n    .accept(ContentType.JSON)\n.when()\n    .get(\"/api/services/{slug}\", slug);\n\nassertThat(response.statusCode()).isEqualTo(200);", language: "java" },
        { title: "Extraction is not assertion", body: ["REST Assured can assert inline or return/extract Response data. Prefer whichever keeps the domain rule readable. Do not bury every expectation inside a generic response specification." ] },
    ], practice: ["Reimplement the Java HttpClient health probe with direct REST Assured syntax.", "Write one request using path/query parameters rather than string concatenation.", "Extract a response value and assert it with AssertJ.", "Compare inline REST Assured assertions with domain assertions and document the boundary."], questions: ["Which responsibilities belong in given, when and then?", "Why should the first REST Assured tests avoid a large helper layer?", "When is Response extraction useful?"] },

    { id: "specifications", title: "Request and Response Specifications", intro: "Specifications remove stable transport repetition. They should standardize protocol configuration without becoming global bags of authentication, business data and expectations.", sections: [
        { title: "RequestSpecification owns transport defaults", body: ["Base URI, common content negotiation, safe logging filters and stable headers are candidates. Caller identity should remain explicit where authorization is part of the test.", "Build specifications through factories/builders rather than mutating a shared static specification across tests." ] },
        { title: "ResponseSpecification should stay narrow", body: ["A response specification may express truly universal protocol expectations, but a universal expected status or schema quickly hides scenario intent. Business assertions belong with the behavior being tested." ] },
    ], practice: ["Identify repetition across at least two direct REST Assured tests.", "Extract only stable transport defaults into ApiSpecifications.", "Prove two tests can use different caller identities safely.", "Reject one tempting business assertion from the shared specification and explain why."], questions: ["What belongs in a RequestSpecification?", "Why is a mutable static specification dangerous?", "What kind of response expectation is too scenario-specific to centralize?"] },

    { id: "serialization-jackson", title: "Jackson, JSON and Typed API Contracts", intro: "JSON is a wire representation; Java objects are an in-memory model. Jackson bridges them, but DTO design should clarify the API contract rather than reproduce every payload as Map<String,Object>.", sections: [
        { title: "Serialization and deserialization", body: ["Serialization converts Java values to JSON; deserialization creates Java values from JSON. Records are useful for immutable contract models when their shape matches the representation.", "Unknown/missing/null fields and naming rules are compatibility decisions. Tests should know whether absence, null and default values mean the same thing." ] },
        { title: "Typed models versus flexible trees", body: ["Typed DTOs improve compile-time contracts and assertion readability. JsonNode or maps remain useful for highly dynamic/partial structures. Choose based on the contract rather than enforcing one representation everywhere."], code: "record ServiceResponse(String id, String slug, String lifecycle) {}\n\nServiceResponse service = response.as(ServiceResponse.class);\nassertThat(service.slug()).isEqualTo(expectedSlug);", language: "java" },
    ], practice: ["Create typed request/response records for one stable Steward endpoint.", "Round-trip or deserialize representative JSON.", "Test missing/null/unknown-field behavior deliberately.", "Use JsonNode once for a case where a full DTO would add noise and explain the choice."], questions: ["What is serialization versus deserialization?", "When is a record a good DTO?", "Why can unknown-field handling affect compatibility evidence?", "When is JsonNode preferable to a typed DTO?"] },

    { id: "api-auth", title: "Authentication Architecture for API Tests", intro: "Authentication infrastructure should acquire and attach credentials without making authorization scenarios implicit. Tokens are sensitive execution inputs, not convenient global constants.", sections: [
        { title: "Separate acquisition from use", body: ["TokenProvider owns how a token is obtained. Request construction decides which identity is used. This lets tests express owner/non-owner/admin callers while authentication mechanics remain reusable.", "Token caching must respect expiry, audience/scope and thread safety. Never solve authentication by sharing one privileged token across the entire suite." ] },
        { title: "Redaction is mandatory", body: ["Authorization headers, refresh tokens, client secrets and credential responses must not appear in logs, Allure attachments or exception messages. Diagnostic value stops before secret disclosure." ] },
    ], practice: ["Implement one TokenProvider behind the existing interface.", "Represent at least two caller identities explicitly.", "Attach authorization without storing the token in a mutable global specification.", "Prove request logging redacts Authorization.", "Document token refresh/cache ownership and concurrency assumptions."], questions: ["Why separate token acquisition from request execution?", "How can a shared admin token destroy authorization coverage?", "What makes token caching a concurrency concern?"] },

    { id: "filters-observability", title: "REST Assured Filters, Correlation and Safe Diagnostics", intro: "Filters can observe or modify REST Assured interactions and are useful for cross-cutting evidence, but they are middleware: powerful enough to create invisible behavior if abused.", sections: [
        { title: "Use filters for cross-cutting transport concerns", body: ["Filters can capture timing, correlation IDs, sanitized request/response evidence or integrate reporting. They should not silently rewrite business payloads or decide whether a scenario passes.", "Capture enough evidence to reconstruct the interaction while applying size limits and redaction." ] },
        { title: "Failures need identity", body: ["Environment, release/build, endpoint, caller role (not credential), correlation ID and sanitized response are more useful than indiscriminate full-body logging." ] },
    ], practice: ["Create a narrow filter that captures correlation/request identity or sanitized diagnostics.", "Demonstrate that Authorization is redacted.", "Trigger a controlled failure and verify the evidence is sufficient to triage it.", "Reject a filter design that mutates business payloads invisibly."], questions: ["What is a REST Assured filter analogous to conceptually?", "Which concerns are appropriate for filters?", "Why is logging everything not the same as observability?"] },

    { id: "api-client-boundary", title: "API Client Boundaries without a Generic REST God Client", intro: "An API client should translate product operations into HTTP interactions while keeping test expectations visible. Generic transport helpers are useful only below a domain-readable client boundary.", sections: [
        { title: "Thin product client", body: ["StewardApiClient can expose operations such as createService or changeOwner while ApiSpecifications owns transport defaults and TokenProvider owns credentials. The client should return useful response/domain information rather than asserting that every call succeeded.", "A universal request(method,path,body,type) wrapper often saves few lines while erasing endpoint meaning." ] },
        { title: "Separate infrastructure from domain", body: ["Generic HTTP/specification/evidence primitives may eventually move to tsa-test-core. Steward routes, models and workflows remain product code even when many tests reuse them."], code: "ServiceResponse createService(ServiceRequest request, Caller caller) {\n    return given()\n        .spec(specifications.forCaller(caller))\n        .body(request)\n    .when()\n        .post(\"/api/services\")\n    .then()\n        .extract().as(ServiceResponse.class);\n}", language: "java" },
    ], practice: ["Implement two thin StewardApiClient operations after direct REST Assured repetition exists.", "Keep a negative-path method capable of exposing status/body rather than throwing away failure evidence.", "Compare the product client with a hypothetical generic execute(method,path,body) API and explain which is more readable.", "Mark which lower-level pieces might someday qualify for tsa-test-core."], questions: ["What should StewardApiClient hide?", "What must it not hide?", "Why can a generic REST wrapper reduce readability?", "Which API-layer pieces are product-specific?"] },

    { id: "negative-resilience", title: "Negative API Testing, Idempotency and Resilience", intro: "Negative testing is not random invalid input. It systematically challenges validation, state transitions, authorization, duplicate delivery and dependency failure while proving the system remains safe.", sections: [
        { title: "Prove protected state", body: ["For rejected writes, capture state before the request and prove the forbidden/invalid request did not partially mutate it. Error response correctness and state safety are separate assertions." ] },
        { title: "Retries and duplicate delivery", body: ["Network timeouts can leave a client unsure whether a write succeeded. For operations with duplicate-risk, test the API's idempotency strategy or explicitly document the absence/risk. Never make the test framework automatically retry arbitrary POST mutations." ] },
        { title: "Failure contracts", body: ["Timeouts, malformed dependency responses, throttling and downstream errors should produce intentional observable behavior. Virtualize only the dependency behavior needed to create the failure; keep the boundary under test real." ] },
    ], practice: ["Build a validation matrix from one request DTO.", "Prove non-mutation for one rejected write.", "Design and, where supported, execute a duplicate-delivery/idempotency test.", "Inject one dependency failure and assert both response contract and resulting state.", "Document which requests the framework must never retry automatically."], questions: ["Why is invalid input generation alone insufficient negative testing?", "Why are automatic retries dangerous for POST/write operations?", "What must be asserted after a denied or failed mutation?"] },


    { id: "api-test-design", title: "API Test Design", intro: "API testing treats the service contract as the primary observable boundary. Good API tests combine request semantics, response semantics, persisted effects and authorization rules rather than checking status codes alone.", sections: [
        { title: "Model the contract", body: ["For each Steward endpoint, identify method, route, authentication, request schema, business preconditions, response schema, error contract and side effects. Then derive tests from the same partitions, boundaries and state models created in Test Analysis and Design.", "A 201 response is weak evidence if the service was saved with the wrong owner, lifecycle or environment relationship."], code: "POST /api/services\nAuthorization: Bearer <token>\n\n{\n  \"name\": \"Payments API\",\n  \"slug\": \"payments-api\",\n  \"criticality\": \"high\",\n  \"owner_team_id\": \"team-platform\"\n}\n\nAssert: status + response contract + persisted ownership", language: "http" },
        { title: "Separate protocol from domain claims", body: ["Some assertions prove HTTP behavior: status, headers, content type and schema. Others prove domain behavior: duplicate slugs are rejected, retired services cannot gain dependencies and unauthorized teams cannot mutate ownership. Keep both visible so failures are diagnosable."] },
    ], practice: ["Select one high-risk Steward endpoint.", "Create a test matrix covering happy path, validation, business-rule rejection and authorization.", "For at least one successful request, verify the resulting persisted state rather than the response alone."], questions: ["Why is asserting only the HTTP status code insufficient for many API tests?", "How should earlier equivalence and boundary analysis influence API coverage?"] },
    { id: "auth-testing", title: "Authentication and Authorization Testing", intro: "Authentication establishes who the caller is; authorization determines what that identity may do. Tests must prove both allowed and denied behavior, including the protected state after denial.", sections: [
        { title: "Build an authorization matrix", body: ["Steward has users, teams, memberships and owned services. That creates relationships, not just roles. Test owners, non-owners, privileged operators, missing authentication and stale or invalid credentials where relevant.", "A correct denial has two parts: the API returns the expected error and the protected resource remains unchanged."], list: ["Unauthenticated request", "Authenticated owner-team member", "Authenticated member of another team", "Privileged administrative identity", "Resource with missing or changed ownership"] },
        { title: "Avoid privilege-only happy paths", body: ["Suites that reuse one superuser token can hide broken authorization. Test data and clients should make caller identity explicit in each high-risk scenario."], code: "ServiceResponse before = api.getService(serviceId);\nResponse denied = otherTeamApi.updateOwner(serviceId, \"team-other\");\nassertThat(denied.statusCode()).isEqualTo(403);\nServiceResponse after = api.getService(serviceId);\nassertThat(after.ownerTeamId()).isEqualTo(before.ownerTeamId());", language: "java" },
    ], practice: ["Create a Steward authorization matrix for service updates and dependency changes.", "Automate at least one allowed and two denied paths.", "For each denied mutation, prove persisted state is unchanged."], questions: ["Why is a 403 assertion alone incomplete evidence for a denied mutation?", "How can a shared admin token hide authorization defects?"] },
    { id: "schema-contract", title: "Schema and Contract Validation", intro: "A stable API contract lets clients depend on field names, types, required properties, status semantics and error shapes. Contract validation detects accidental breaking changes that individual example assertions may miss.", sections: [
        { title: "Validate structure and meaning", body: ["JSON Schema or OpenAPI-based checks can verify structure, but they cannot decide whether a field has the correct business value. Combine structural validation with semantic assertions.", "Error responses deserve a contract too. Generic 500 payloads, untranslated messages or inconsistent field errors make integrations harder to operate even when the happy path works."], list: ["Required fields and types", "Nullable versus omitted fields", "Enum values", "Stable error envelope", "Pagination structure", "Backward-compatible additions versus breaking removals"] },
        { title: "Treat compatibility as a consumer concern", body: ["A provider can satisfy its own tests while breaking a client that depends on a field or behavior. Contract testing becomes especially useful when multiple independently delivered consumers and providers exist." ] },
    ], practice: ["Capture or derive the contract for one Steward collection and one mutation endpoint.", "Add structural checks for both success and validation-error responses.", "Introduce a hypothetical breaking change and explain which check would catch it."], questions: ["What can schema validation prove, and what can it not prove?", "Why should error responses have stable contracts?"] },
    { id: "database-assertions", title: "Database Assertions", intro: "Database assertions are useful when persistence is part of the behavior under test, but they should validate meaningful effects rather than duplicate every ORM detail.", sections: [
        { title: "Use persistence as supporting evidence", body: ["After a Steward ownership change, verifying the persisted owner and audit-relevant relationship can prove the mutation survived beyond serialization. For a rejected request, verifying no row or relationship changed protects invariants.", "Avoid asserting incidental columns or internal query shapes unless those are themselves requirements." ] },
        { title: "Respect transaction boundaries", body: ["Tests should understand when commits occur, how rollback is handled and whether concurrent operations can violate uniqueness or consistency. Database evidence is strongest when the real schema and constraints are active."], code: "Response created = api.createService(payload);\nassertThat(created.statusCode()).isEqualTo(201);\n\nServiceRow persisted = database.findServiceBySlug(\"payments-api\");\nassertThat(persisted.ownerTeamId()).isEqualTo(platformTeamId);\nassertThat(persisted.criticality()).isEqualTo(\"high\");", language: "java" },
    ], practice: ["Choose two API scenarios where persistence assertions add meaningful confidence.", "Add a postcondition query for success and a non-mutation assertion for failure.", "Document which database details you deliberately do not assert and why."], questions: ["When do database assertions strengthen an API test?", "Why can over-specific database assertions make tests brittle?"] },
    { id: "integration-boundaries", title: "Integration Boundaries", intro: "Integration tests exist because separately correct components can fail when they meet. The test boundary should include the real interaction whose semantics create risk.", sections: [
        { title: "Name the boundary before writing the test", body: ["Examples in Steward include Django plus PostgreSQL, API plus identity provider, application plus internal package, or deployed service plus reverse proxy. Each boundary has different failure modes and requires different setup.", "If the risk is PostgreSQL uniqueness, an in-memory fake is the wrong boundary. If the risk is application behavior when an email service times out, a controlled substitute may be appropriate."], list: ["What crosses the boundary?", "Which side owns the contract?", "What can drift independently?", "Which failure modes matter?", "What evidence requires the real dependency?"] },
        { title: "Do not confuse breadth with realism", body: ["A larger environment is not automatically more realistic. A focused test with the real dependency under risk often provides stronger evidence and much better diagnostics than an opaque full-stack scenario." ] },
    ], practice: ["Map Steward's major integration boundaries.", "Assign one high-value test to each of three boundaries.", "Explain which dependencies must be real and which may be controlled for each test."], questions: ["Why should an integration test explicitly name its boundary?", "When is a focused integration test more credible than a full end-to-end test?"] },
    { id: "contract-testing", title: "Contract Testing Concepts", intro: "Contract testing checks that independently evolving systems still agree on the interactions they depend on. It is most valuable when provider and consumer releases can drift independently.", sections: [
        { title: "Consumer expectations are part of compatibility", body: ["A schema can remain technically valid while a consumer breaks because a field meaning, status behavior or required interaction changed. Consumer-driven contracts capture examples the consumer actually requires and verify them against the provider.", "Do not introduce contract tooling where there is only one tightly coupled codebase and no independent delivery problem. Use it where organizational or deployment independence creates real compatibility risk." ] },
        { title: "Contracts complement, not replace, integration", body: ["A passing contract does not prove DNS, credentials, database state or production configuration. It reduces one class of compatibility uncertainty so broader integration tests can remain selective." ] },
    ], practice: ["Identify whether any current Steward integration genuinely benefits from consumer-driven contracts.", "Write a small example interaction contract for a plausible consumer of the service registry API.", "State what additional integration evidence remains necessary even if the contract passes."], questions: ["What organizational condition makes contract testing especially valuable?", "Why does a passing contract test not prove the deployed integration works?"] },
    { id: "mocking-virtualization", title: "Mocking and Service Virtualization", intro: "Service virtualization gives tests controllable substitutes for remote systems, especially when real dependencies are expensive, unstable, unavailable or difficult to force into failure states. The substitute must still represent a known contract.", sections: [
        { title: "Virtualize for control, not denial", body: ["A virtual identity or notification service can reproduce timeout, 429, malformed payload and dependency-error scenarios reliably. That is valuable for application error handling. But real integration tests must still verify that assumptions about the actual dependency are true." ] },
        { title: "Version the behavior you simulate", body: ["Untracked mocks become parallel specifications that quietly drift. Keep fixtures or virtualized contracts reviewable and tie them to provider documentation or captured contract evidence."], list: ["Happy response", "Explicit business rejection", "Authentication failure", "Timeout/network failure", "Malformed or incompatible response", "Rate limiting where relevant"] },
    ], practice: ["Choose one Steward external boundary that benefits from controlled failure simulation.", "Define a small virtualization matrix for normal and adverse responses.", "Add one test that proves Steward fails safely when the dependency is unavailable."], questions: ["What is the main risk of an unversioned service mock?", "Which failure modes are often easier to prove with virtualization than with the real provider?"] },
    { id: "data-setup-cleanup", title: "Data Setup and Cleanup", intro: "Integration tests need data that is explicit, isolated and disposable. Poor test-data management creates order dependence, false failures and environments nobody trusts.", sections: [
        { title: "Own the state you create", body: ["Prefer API factories, database fixtures or builders that create only the relationships required by the scenario. Use unique identifiers so parallel tests do not collide. Cleanup can use transaction rollback, isolated schemas, explicit teardown or disposable environments depending on the boundary." ] },
        { title: "Make preconditions visible", body: ["Hidden global fixtures make tests shorter but harder to understand. A reader should be able to tell why a user belongs to Team A, why a service is retired or why a dependency already exists. Data helpers should express domain intent rather than obscure it."], list: ["Unique test identities", "Minimal domain relationships", "Predictable lifecycle state", "No dependency on execution order", "Safe cleanup after both pass and failure"] },
    ], practice: ["Design reusable data builders for teams, users, services and dependencies.", "Make two integration tests safe to run in parallel.", "Demonstrate cleanup or transaction isolation even when a test fails midway."], questions: ["Why are globally shared fixtures dangerous in integration suites?", "What makes a test-data helper expressive rather than opaque?"] },
];

const httpMilestone: Lesson = { id: "api-http-engineering-milestone", title: "Milestone: Prove the HTTP Contract Before Framework Abstraction", activities: [
 { id: "api-http-engineering-milestone-001", title: "Build the Protocol Evidence Baseline", estimatedMinutes: 120, content: { type: "practical", objective: "Demonstrate protocol-level reasoning using the existing raw HTTP capability before REST Assured hides transport ceremony.", scenario: "The learner must be able to inspect a request/response and explain its semantics independently of any testing DSL.", instructions: ["Select one read and one mutation endpoint.", "Document method safety/idempotency, authentication, Content-Type/Accept, expected status semantics and side effects.", "Capture a sanitized real request/response including a correlation/request identifier where available.", "Design one retry/duplicate-delivery risk scenario.", "Separate protocol assertions from Steward domain assertions."], deliverables: ["HTTP contract note", "Sanitized wire evidence", "Idempotency/retry analysis", "Protocol-vs-domain assertion map"], completionCriteria: ["HTTP semantics are explained without REST Assured terminology.", "No credential appears in evidence.", "Retry safety is not assumed from status codes.", "Domain claims are distinguishable from protocol claims."] } }
] };

const apiArchitectureMilestone: Lesson = { id: "api-architecture-milestone", title: "Milestone: Evolve REST Assured into a Steward API Architecture", activities: [
 { id: "api-architecture-milestone-001", title: "Refactor Only Proven API Repetition", estimatedMinutes: 150, content: { type: "practical", objective: "Turn direct REST Assured tests into a maintainable API layer while keeping product behavior visible.", scenario: "At least two direct tests must exist before specifications/clients are extracted. Every abstraction needs a before/after justification.", instructions: ["Extract stable transport defaults into an immutable/factory-built RequestSpecification.", "Implement explicit caller identity through TokenProvider without a global admin token.", "Add Jackson typed models for a stable contract and retain flexible JSON for one intentionally dynamic case.", "Create a narrow diagnostics filter that redacts credentials and captures correlation identity.", "Extract two StewardApiClient operations from demonstrated repetition.", "Add negative/non-mutation and duplicate/retry evidence.", "Classify each API-layer class as Steward-specific or future generic candidate without extracting tsa-test-core yet."], deliverables: ["ApiSpecifications", "Authentication implementation", "Typed DTOs", "Safe diagnostics filter", "Thin StewardApiClient", "Negative/idempotency evidence", "Reuse classification"], completionCriteria: ["Business assertions remain visible.", "No mutable global RequestSpecification/token exists.", "Logs and Allure-ready evidence are sanitized.", "The client exposes meaningful product operations rather than a generic REST DSL.", "No tsa-test-core extraction occurs yet."] } }
] };

const restAssuredBuild: Lesson = { id: "api-integration-rest-assured-build", title: "Build: Introduce REST Assured into steward-tests", activities: [
    { id: "api-integration-rest-assured-build-001", title: "Replace Raw HTTP Mechanics Deliberately", estimatedMinutes: 90, content: { type: "practical", objective: "Introduce REST Assured only after the learner has experienced Java's raw HTTP mechanics.", scenario: "The Java foundation milestone already proved a tiny HTTP call. Now replace repeated transport ceremony while preserving explicit domain assertions.", instructions: ["Add REST Assured through Maven.", "Create a minimal reusable RequestSpecification for base URI, content type and safe diagnostics.", "Keep authentication injectable rather than static.", "Reimplement the raw health probe as a JUnit/REST Assured test.", "Compare what REST Assured removed and what responsibility remains in your code."], deliverables: ["REST Assured dependency", "Request specification foundation", "First API smoke test", "Before/after abstraction note"], completionCriteria: ["The learner can explain the abstraction gained.", "No business assertion is hidden in the request specification.", "Credentials are not global mutable state."] } }
] };

const apiClientBuild: Lesson = { id: "api-integration-client-build", title: "Build: Grow the Steward API Layer", activities: [
    { id: "api-integration-client-build-001", title: "Add Typed API Clients and Domain Models", estimatedMinutes: 105, content: { type: "practical", objective: "Grow steward-tests from individual HTTP checks into a maintainable service-layer test system.", scenario: "Transport repetition now justifies a thin Steward-specific API layer; it does not yet justify tsa-test-core.", instructions: ["Add Jackson DTO/record mapping for selected contracts.", "Create thin StewardApiClient methods around transport mechanics.", "Add AssertJ assertions that keep domain expectations in tests.", "Use test-data builders with unique identities.", "Preserve raw response/request identifiers for diagnosis."], deliverables: ["Typed models", "Steward API client", "Data builders", "Focused domain tests"], completionCriteria: ["API methods do not encode pass/fail expectations.", "Models make contracts clearer.", "Tests remain readable as product behavior."] } }
] };

const lab: Lesson = { id: "api-integration-steward-e2e-service-layer", title: "Lab: Test Steward API End-to-End at the Service Layer", activities: [
    { id: "api-integration-lab-001", title: "Define the Service-layer Test Boundary", estimatedMinutes: 45, content: { type: "practical", objective: "Turn the existing risk model into a focused service-layer integration scope.", scenario: "Use the real Steward API and persistence boundary. Keep browser UI concerns out of this lab unless an endpoint contract itself requires them.", instructions: ["Select critical ownership, lifecycle, dependency and authorization flows.", "Map each scenario to API, database, identity and internal-package boundaries.", "State which dependencies will be real and which will be virtualized.", "Define test data and cleanup strategy before implementation."], deliverables: ["Integration scope", "Boundary map", "Data/cleanup plan"], completionCriteria: ["Every selected test adds evidence not already proven cheaply below.", "Real boundaries match the risk being investigated.", "Environment assumptions are explicit."] } },
    { id: "api-integration-lab-002", title: "Automate Core API and Persistence Flows", estimatedMinutes: 105, content: { type: "practical", objective: "Create executable API evidence with meaningful persistence assertions.", scenario: "Exercise Steward as a service through its API contract using representative identities and real PostgreSQL persistence.", instructions: ["Automate successful service registration and update flows.", "Automate validation and duplicate/conflict behavior.", "Automate ownership and dependency rules derived from earlier test design.", "Assert response contracts and meaningful persisted effects.", "Capture request identifiers and diagnostics for failures."], deliverables: ["API integration suite", "Persistence assertions", "Diagnostic evidence"], completionCriteria: ["Status codes are not the only assertions.", "Persisted state is checked where mutation is the behavior.", "Failures point to contract, domain or persistence causes clearly."] } },
    { id: "api-integration-lab-003", title: "Prove Authorization and Failure Boundaries", estimatedMinutes: 90, content: { type: "practical", objective: "Prove that protected state survives unauthorized and dependency-failure scenarios.", scenario: "High-risk negative paths must demonstrate safe outcomes, not merely error responses.", instructions: ["Run the authorization matrix with distinct caller identities.", "For rejected mutations, prove state remains unchanged.", "Virtualize one external dependency failure such as timeout or malformed response.", "Confirm Steward returns an intentional failure contract and does not partially corrupt state."], deliverables: ["Authorization evidence", "Failure-injection tests", "Protected-state assertions"], completionCriteria: ["Caller identity is explicit.", "Denied writes cannot mutate protected resources.", "Dependency failures result in controlled, diagnosable outcomes."] } },
    { id: "api-integration-lab-004", title: "Add Contract and Compatibility Evidence", estimatedMinutes: 60, content: { type: "practical", objective: "Protect Steward from accidental API and internal dependency drift.", scenario: "Use structural contracts selectively where independent consumers or versioned packages create compatibility risk.", instructions: ["Validate success and error response structures for selected endpoints.", "Add one internal-package compatibility check using a versioned artifact if applicable.", "Document whether consumer-driven contract testing is justified now or should be deferred with a clear trigger.", "Record what these checks still do not prove about deployment/runtime configuration."], deliverables: ["Schema/contract checks", "Package compatibility evidence or justified N/A", "Compatibility decision note"], completionCriteria: ["Contract checks reflect real consumer expectations.", "Local-path shortcuts do not masquerade as package compatibility.", "Limitations of contract evidence are explicit."] } },
    { id: "api-integration-lab-005", title: "API and Integration Testing Review", estimatedMinutes: 30, content: { type: "reflection", prompt: "Defend the Steward API/integration portfolio. Which risks required real PostgreSQL, identity, package or service boundaries; where did virtualization add useful control; what evidence is deliberately left for browser/environment or non-functional testing; and which tests should block a release when they fail?", minimumCharacters: 300 } },
] };

export const apiAndIntegrationTestingDeepLessons: Lesson[] = [httpMilestone, restAssuredBuild, ...specs.map(rich), apiArchitectureMilestone, apiClientBuild, lab];
