import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";
const java: LearningResource = { title: "Java Language Guide", url: "https://dev.java/learn/" };
const maven: LearningResource = { title: "Apache Maven Guides", url: "https://maven.apache.org/guides/" };
const junit: LearningResource = { title: "JUnit 5 User Guide", url: "https://docs.junit.org/current/user-guide/" };
const mavenLifecycle: LearningResource = { title: "Maven — Build Lifecycle", url: "https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle" };
const mavenDependencies: LearningResource = { title: "Maven — Dependency Mechanism", url: "https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism" };
const mavenPlugins: LearningResource = { title: "Maven — Plugins and Goals", url: "https://maven.apache.org/guides/introduction/introduction-to-plugins.html" };
const junitParameterized: LearningResource = { title: "JUnit — Parameterized Tests", url: "https://docs.junit.org/current/user-guide/#writing-tests-parameterized-tests" };
const junitExtensions: LearningResource = { title: "JUnit — Extension Model", url: "https://docs.junit.org/current/user-guide/#extensions" };
const javaConcurrency: LearningResource = { title: "Java — Concurrency", url: "https://dev.java/learn/concurrency/" };

const resourcesFor = (id: string): LearningResource[] => {
 if (id === "maven-lifecycle" || id === "surefire-failsafe") return [mavenLifecycle, mavenPlugins];
 if (id === "maven-dependencies") return [mavenDependencies, maven];
 if (id === "junit-parameterization") return [junitParameterized, junit];
 if (id === "junit-extensions" || id === "annotations-reflection") return [junitExtensions, junit];
 if (id === "concurrency") return [javaConcurrency, junit];
 if (id.startsWith("junit-")) return [junit, java];
 if (id === "jvm-maven") return [java, mavenLifecycle];
 return [java, junit];
};

type Spec = {
 id: string; title: string; principle: string; mechanics: string[]; frameworkUse: string[];
 antiPatterns: string[]; practice: string[]; questions: string[]; code?: string;
};
function lesson(spec: Spec): Lesson {
 const blocks: LessonBlock[]=[
  {type:"paragraph",text:spec.principle},
  {type:"heading",id:`${spec.id}-mechanics`,text:"Mechanics you must understand",level:2},
  {type:"list",items:spec.mechanics},
  {type:"heading",id:`${spec.id}-framework`,text:"Why framework engineers need this",level:2},
  {type:"list",items:spec.frameworkUse},
  {type:"heading",id:`${spec.id}-failure-patterns`,text:"Failure patterns to recognize",level:2},
  {type:"list",items:spec.antiPatterns},
 ];
 if(spec.code) blocks.push({type:"code",language:"java",code:spec.code});
 blocks.push({type:"heading",id:`${spec.id}-check`,text:"Check your understanding",level:2},{type:"list",items:spec.questions},{type:"resources",title:"Continue learning",resources:resourcesFor(spec.id)});
 return {id:`quality-java-${spec.id}`,title:spec.title,activities:[
  {id:`quality-java-${spec.id}-001`,title:spec.title,estimatedMinutes:55,content:{type:"reading",body:spec.principle,blocks}},
  {id:`quality-java-${spec.id}-002`,title:`Build: ${spec.title}`,estimatedMinutes:65,content:{type:"practical",objective:`Apply ${spec.title} while growing steward-tests.`,scenario:"Every exercise changes the real test project. Small isolated experiments are allowed only to expose a Java mechanism before applying it to steward-tests.",instructions:spec.practice,deliverables:["Committed steward-tests increment","Executable example or test","Short design note answering the lesson questions"],completionCriteria:["The learner can explain the Java mechanism without framework magic.","The increment compiles and tests execute.","The design keeps dependencies explicit.","The learner can identify the lesson anti-patterns in a code review."]}}
 ]};
}

const specs: Spec[]=[
{id:"jvm-maven",title:"Java, the JVM and Maven Project Model",principle:"A Java test framework is compiled software. Learn how source becomes bytecode, how the JVM loads classes and how Maven constructs the compile/test classpaths so build failures are diagnosable rather than mysterious.",
mechanics:["JDK tools compile source into JVM bytecode; the JVM executes loaded classes.","Packages provide namespacing; imports are source-level name resolution, not dependency installation.","The classpath determines which compiled classes and JARs are visible at compile/test/runtime.","Maven coordinates identify artifacts as groupId:artifactId:version.","Dependency scopes change classpath visibility; test-scoped automation dependencies should not leak into production artifacts.","Maven phases form a lifecycle; plugins bind goals such as compilation and Surefire test execution.","Surefire discovers/runs unit-style JUnit tests during test; Failsafe can later separate integration-test lifecycle semantics when justified."],
frameworkUse:["Diagnose dependency/version/classpath failures in enterprise Maven projects.","Know why a JUnit test can compile but fail during execution due to runtime dependencies.","Reason about internal Nexus artifacts rather than treating pom.xml as configuration magic."],
antiPatterns:["Adding dependencies until compilation happens to pass.","Using compile scope for every test library.","Confusing Maven dependency resolution with Java imports.","Running only from an IDE and never proving the Maven build."],
practice:["Create steward-tests as a Java 17+ Maven project.","Inspect javac/target/classes and target/test-classes after a build.","Use the Maven standard directory layout deliberately.","Add compiler and Surefire configuration.","Inspect dependency:tree and explain one transitive dependency.","Run clean test from the command line and narrate the relevant lifecycle phases."],
questions:["What is the difference between the JDK, JVM and Java source language?","What does Maven do that JUnit does not?","Why can dependency scope affect runtime behavior?","Where does Surefire fit between Maven and JUnit?"],code:"mvn -U clean test\nmvn dependency:tree"},


{id:"maven-lifecycle",title:"Maven Lifecycle, Plugins and Goals",principle:"Maven is an execution orchestrator with conventions. Learn the difference between lifecycle phases, plugin goals and bindings so commands are predictable rather than incantations.",
mechanics:["The default lifecycle includes validate, compile, test, package, verify, install and deploy phases; invoking a later phase runs preceding phases in that lifecycle.","A plugin provides goals; goals can be bound to lifecycle phases by packaging defaults or explicit configuration.","clean belongs to a separate lifecycle and removes prior build output.","package creates the project artifact; install places it in the local repository; deploy publishes it to a configured remote repository.","Plugin version pinning makes builds more reproducible."],
frameworkUse:["Know exactly why mvn clean test, mvn verify and mvn deploy do different work.","Later bind Allure/quality tooling deliberately instead of accumulating opaque plugin configuration.","Understand how tsa-test-core moves from source to local artifact to Nexus artifact."],
antiPatterns:["Calling every command mvn clean install regardless of intent.","Confusing a plugin goal with a lifecycle phase.","Depending on whatever plugin version Maven happens to resolve.","Putting network-heavy integration behavior into an early phase accidentally."],
practice:["Run test, package, verify and install and inspect what changes in target and ~/.m2/repository.","Invoke one plugin goal directly and contrast it with a lifecycle phase.","Use help:effective-pom to inspect inherited/default configuration.","Document which lifecycle phase steward-tests CI should use at the current checkpoint."],
questions:["Why does mvn package run tests by default?","What is the difference between install and deploy?","What does clean test mean when clean is a separate lifecycle?","What is a Maven plugin goal?"],code:"mvn test\nmvn package\nmvn verify\nmvn install\nmvn help:effective-pom"},

{id:"maven-dependencies",title:"Maven Dependency Resolution, Scopes and Nexus",principle:"Enterprise Java builds are dependency graphs. Learn direct/transitive dependencies, mediation, scopes, repositories and local caching before tsa-test-core becomes an internal Nexus artifact.",
mechanics:["A direct dependency can bring transitive dependencies; Maven resolves a graph, not a flat list.","Version mediation can select one version when paths disagree; dependencyManagement can centralize versions without adding the dependency by itself.","Scopes affect classpaths and transitivity; test is appropriate for libraries used only by test code.","The local repository caches artifacts; remote repositories such as Nexus provide organization-controlled artifacts.","SNAPSHOT versions represent mutable development coordinates and require different reproducibility discipline from releases.","Exclusions are surgical tools, not a substitute for understanding the dependency graph."],
frameworkUse:["Diagnose REST Assured/Jackson/JUnit version conflicts.","Consume tsa-test-core from Nexus safely later.","Understand why an internal artifact can resolve on one machine and fail on another."],
antiPatterns:["Random exclusions to silence dependency conflicts.","Duplicating versions throughout pom.xml.","Treating ~/.m2 as the source of truth.","Using mutable SNAPSHOT artifacts without traceability in controlled CI evidence."],
practice:["Inspect dependency:tree and dependency:tree -Dverbose.","Find one transitive dependency and trace why it exists.","Use dependencyManagement for a controlled version decision.","Inspect where one artifact lives under ~/.m2/repository.","Explain how Maven will later resolve tsa-test-core from Nexus."],
questions:["Does dependencyManagement add a dependency?","What makes a dependency transitive?","Why can deleting ~/.m2 appear to fix a problem without fixing its cause?","What reproducibility risk does SNAPSHOT introduce?"],code:"mvn dependency:tree\nmvn dependency:tree -Dverbose"},

{id:"surefire-failsafe",title:"Surefire, Failsafe and Test Execution Boundaries",principle:"Maven does not execute JUnit tests itself. Test-execution plugins bridge Maven lifecycle phases to the JUnit Platform, and their lifecycle semantics affect whether cleanup and verification run correctly.",
mechanics:["Surefire normally runs tests in the test phase.","Failsafe is designed for integration-test and verify, separating execution from final verification so post-integration-test cleanup can run.","Test naming/includes/excludes affect discovery before JUnit sees candidates.","Forked JVM configuration can change system properties, memory, concurrency and isolation.","Skipping compilation/tests and ignoring failures are distinct build controls with different risks."],
frameworkUse:["Choose a deliberate boundary between fast checks and environment-dependent integration evidence.","Diagnose 'no tests found' at Maven-plugin versus JUnit-discovery layers.","Avoid pipelines that terminate before environment cleanup."],
antiPatterns:["Using Surefire/Failsafe interchangeably without lifecycle reasoning.","Renaming tests until discovery happens accidentally.","-DskipTests or failure-ignore embedded in CI without visible policy.","Fork settings copied from Stack Overflow without understanding process isolation."],
practice:["Inspect which steward-tests classes Surefire discovers.","Deliberately violate the naming convention and diagnose the result.","Configure an explicit include/tag selection without duplicating suites.","Write a decision note on when steward-tests would justify Failsafe."],
questions:["Who starts the JUnit Platform in a Maven build?","Why does Failsafe separate integration-test and verify?","How can a test exist in source yet never reach JUnit discovery?"]},

{id:"junit-platform",title:"JUnit Platform, Jupiter Engine and Discovery",principle:"JUnit 5 is an ecosystem. Understand the Platform/Launcher/Engine/Jupiter relationship so discovery and execution failures can be located at the right layer.",
mechanics:["The JUnit Platform defines the foundation for discovering/executing tests and hosting test engines.","Jupiter supplies the programming model and TestEngine for JUnit Jupiter tests.","A launcher builds a discovery request, engines discover descriptors and execution traverses the resulting test plan.","Annotations such as @Test are interpreted by Jupiter; they do not execute themselves.","Maven Surefire can launch the JUnit Platform when the appropriate provider/engine is available."],
frameworkUse:["Diagnose missing engine/provider/version problems.","Understand how IDE, Maven and CI can all launch the same JUnit model through different front ends.","Later understand custom extensions without confusing them with Maven plugins."],
antiPatterns:["Calling everything 'JUnit' without knowing which layer failed.","Adding junit-platform-launcher versions randomly to fix discovery.","Assuming an IDE green run proves Maven/CI discovery is configured correctly."],
practice:["Draw the execution chain from mvn test to one @Test method.","Run the same test from IDE and Maven and identify what changes versus what remains JUnit.","Inspect the test plan/output for nested or parameterized cases.","Break the engine/dependency setup in a controlled experiment, observe the failure, then restore it."],
questions:["What is Jupiter relative to the JUnit Platform?","What is a TestEngine?","Who interprets @Test?","Why can IDE execution work while Maven execution fails?"],code:"mvn test\n# Maven lifecycle -> Surefire -> JUnit Platform -> Jupiter TestEngine -> test lifecycle -> @Test"},

{id:"junit-lifecycle",title:"JUnit Test Instances and Lifecycle Ownership",principle:"Lifecycle annotations are resource-ownership decisions. Understand test instance creation and callback ordering before setup code becomes a hidden shared-state framework.",
mechanics:["The default PER_METHOD lifecycle creates a new test instance for each test method.","@BeforeEach/@AfterEach surround each test; @BeforeAll/@AfterAll surround the container lifecycle.","PER_CLASS changes test-instance reuse and can enable non-static @BeforeAll, but also increases shared-state risk.","Nested tests have their own lifecycle context.","Assumptions abort tests based on runtime preconditions and must not hide missing mandatory evidence."],
frameworkUse:["Own created test data deterministically.","Later own browser contexts per test without global state.","Choose suite-level resources only when their sharing semantics are safe."],
antiPatterns:["Mutable fields assuming test method order.","@BeforeAll creating business data mutated by multiple tests.","PER_CLASS chosen only to avoid static methods.","Cleanup that runs only after successful assertions."],
practice:["Instrument constructor/@BeforeEach/@AfterEach and observe instance identities.","Compare PER_METHOD and PER_CLASS behavior.","Create and clean test-owned data around a focused test.","Cause the assertion to fail and prove cleanup still executes."],
questions:["What is JUnit's default test-instance lifecycle?","Why can PER_CLASS make parallel execution harder?","Which layer should own data created for one test?"]},

{id:"junit-parameterization",title:"JUnit Parameterized Tests and Dynamic Inputs",principle:"Parameterization should express one behavioral rule over meaningful cases, not compress unrelated tests into a table nobody can diagnose.",
mechanics:["ParameterizedTest delegates invocations to argument sources.","ValueSource/CsvSource are compact for simple literals; MethodSource supports typed/domain-rich cases.","Invocation display names should identify the failing case.","Arguments are data for one behavior; materially different behavior deserves a different test.","DynamicTest exists for runtime-generated tests but has different lifecycle semantics and should be used deliberately."],
frameworkUse:["Express lifecycle matrices and validation boundaries clearly.","Keep CI/Allure evidence understandable per case.","Avoid copy/paste tests without creating unreadable mega-parameterization."],
antiPatterns:["Twenty boolean parameters controlling branches inside one test.","CSV strings standing in for rich domain models.","Parameterized tests whose cases have different setup/assertion logic.","Dynamic tests used simply because inputs come from a collection."],
practice:["Convert two duplicated lifecycle-rule tests into one MethodSource parameterized test.","Give each invocation a diagnostic name.","Keep one materially different case as a separate test and explain why.","Observe lifecycle behavior for parameterized invocations."],
questions:["When should two cases not be parameterized together?","Why prefer MethodSource for domain-rich data?","How does parameterized invocation identity affect diagnostics?"]},

{id:"junit-extensions",title:"JUnit Extension Model and Parameter Resolution",principle:"Extensions are framework integration points, not a place to hide every helper. Learn callbacks, parameter resolution and extension registration only after ordinary composition/lifecycle is understood.",
mechanics:["Extension callbacks hook into defined points such as before/after test execution.","ParameterResolver can supply values to supported constructor/method parameters.","@ExtendWith registers extensions declaratively; service loading/programmatic mechanisms exist for broader registration.","ExtensionContext exposes scoped stores and metadata; scope/lifetime choices matter.","Composed annotations can combine extension registration and metadata but create a public framework API."],
frameworkUse:["Later centralize genuinely cross-cutting evidence/context behavior.","Supply carefully scoped infrastructure without a god BaseTest.","Understand how Allure and other integrations hook into test execution conceptually."],
antiPatterns:["An extension that creates every client/page/data object automatically.","Hidden network calls in ParameterResolver.","Global extension state without scoped cleanup.","Custom annotations before repeated semantic usage proves their value."],
practice:["Build a tiny diagnostic extension that records test identity without network behavior.","Build one narrow ParameterResolver for a simple immutable execution context.","Compare explicit constructor/helper composition with extension injection and choose the simpler option.","Document when the extension should not be used."],
questions:["What problem does ParameterResolver solve?","Why can extension convenience reduce test readability?","Where should extension-owned state live and be cleaned up?"]},
{id:"types-modeling",title:"Classes, Records, Enums and Immutability",principle:"Framework state should be explicit and hard to corrupt. Java's type system can make configuration, environment identity and test data safer before any automation library is involved.",
mechanics:["A class combines state and behavior; constructors establish valid initial state.","Records provide concise nominal immutable data carriers, though referenced mutable objects can still mutate.","Enums model a closed set of named values and may contain behavior.","final prevents reassignment/overriding depending on context; it does not recursively make object graphs immutable.","Access modifiers define API boundaries inside the framework."],
frameworkUse:["Represent environment/configuration without stringly typed values.","Keep test configuration stable throughout one execution.","Expose only intentional framework APIs and keep implementation details package-private."],
antiPatterns:["public mutable fields used as framework configuration.","String values such as \"qa\" and \"prod\" copied throughout tests.","A giant mutable TestContext carrying unrelated state.","Assuming final makes a mutable List immutable."],
practice:["Model TestSettings as an immutable record.","Model Environment and Lifecycle as enums.","Validate invariants at construction/loading boundaries.","Create a ServicePayload model without mutable global defaults.","Choose access modifiers deliberately and justify one package-private type."],
questions:["When would you choose a record over a normal class?","What does final guarantee and what does it not?","Why are enums safer than arbitrary environment strings?"]},


{id:"equality-object-contracts",title:"Object Contracts: equals, hashCode and toString",principle:"Test code compares objects constantly. Understand Java object equality and hashing so assertions, Sets, Maps and diagnostic output behave predictably.",
mechanics:["Object identity (== for references) asks whether two references point to the same object; equals expresses logical equality when implemented.","Equal objects must produce equal hashCode values for hash-based collections to behave correctly.","Records generate component-based equals, hashCode and toString automatically.","A useful toString aids diagnostics but must not leak secrets."],
frameworkUse:["Compare DTOs and expected models correctly.","Use records safely as Map keys/Set members where appropriate.","Produce readable failure messages without dumping tokens/passwords."],
antiPatterns:["Using == to compare Strings or DTO instances.","Overriding equals without a consistent hashCode.","Auto-generated toString exposing credentials or authorization headers."],
practice:["Demonstrate identity versus logical equality with two equivalent objects.","Use a record and inspect generated equality/hash behavior.","Use an object in a HashSet and explain the contract.","Review framework models for sensitive toString output."],
questions:["What does == compare for object references?","Why must equals and hashCode agree?","Why can convenient diagnostic output become a security problem?"]},
{id:"interfaces-composition",title:"Interfaces, Composition and Dependency Direction",principle:"A maintainable framework assembles small capabilities rather than inheriting behavior from a giant base class. Interfaces are contracts; composition decides which implementations collaborate.",
mechanics:["Interfaces define callable contracts independently of a concrete implementation.","implements satisfies a contract; extends creates inheritance and tighter structural coupling.","Composition stores/receives collaborators and delegates behavior to them.","Dependency inversion means high-level policy can depend on stable abstractions rather than concrete infrastructure."],
frameworkUse:["Swap token acquisition without rewriting API clients.","Separate transport, configuration and evidence responsibilities.","Keep tests independent from a framework inheritance hierarchy."],
antiPatterns:["BaseTest owns browser, API client, credentials, data and reporting.","Deep inheritance chains where changing setup breaks unrelated tests.","Interface-per-class ceremony with no alternate boundary or architectural value."],
practice:["Define a TokenProvider contract.","Create two tiny implementations or one implementation plus fake.","Compose it into a client rather than constructing credentials globally.","Draw the dependency direction and identify which side owns the interface.","Reject a BaseTest god object in a short architecture note."],
questions:["Composition versus inheritance: what changes in coupling?","When is an interface useful and when is it ceremony?","Which direction should a product-specific client depend on authentication infrastructure?"],code:"interface TokenProvider { String token(); }"},

{id:"dependency-injection",title:"Constructor Dependency Injection",principle:"Dependency injection is explicit collaborator supply, not synonymous with Spring. Constructor injection makes required dependencies visible and prevents partially initialized framework objects.",
mechanics:["A constructor can require all collaborators needed for valid operation.","The composition root chooses concrete implementations and assembles the object graph.","A fake or stub can satisfy the same contract in focused tests.","DI containers automate object construction/lifetime; they do not create dependency inversion by themselves."],
frameworkUse:["Supply TestSettings, TokenProvider and later specifications/browser factories explicitly.","Make framework components testable without network credentials.","Understand Spring/Guice later without needing them for a small automation project."],
antiPatterns:["new TokenProvider() hidden inside StewardApiClient.","Static service locators such as Context.get(ApiClient.class).","Field injection that permits invisible/uninitialized dependencies.","Adding Spring solely because the framework has constructors."],
practice:["Inject TestSettings and TokenProvider into a client constructor.","Create a fake TokenProvider for a focused test.","Create a small composition root/factory where concrete objects are assembled.","Compare constructor injection with service-locator and static-singleton alternatives."],
questions:["What exactly is being injected?","Where should object construction happen?","What problem would a DI container solve here, and do we have that problem yet?"],code:"final class StewardApiClient {\n  private final TestSettings settings;\n  private final TokenProvider tokens;\n  StewardApiClient(TestSettings settings, TokenProvider tokens) {\n    this.settings = settings; this.tokens = tokens;\n  }\n}"},

{id:"generics-collections",title:"Generics and Collections",principle:"Generics preserve type contracts across reusable code; collections represent groups and mappings. Framework code needs enough mastery to read library APIs and avoid unsafe casting, not abstraction for its own sake.",
mechanics:["List, Set and Map encode different collection semantics.","Generic type parameters such as T are compile-time type variables.","Bounded generics constrain acceptable types; wildcards express variance at API boundaries.","Type erasure means most generic type arguments are not directly available at runtime."],
frameworkUse:["Understand REST Assured/Jackson APIs and typed helper signatures.","Choose Set where uniqueness is semantic and Map where keyed lookup is semantic.","Recognize why deserializing nested generic JSON can require explicit type information."],
antiPatterns:["Using Map<String,Object> for every response forever.","Raw List/Map types and unchecked casts.","A universal generic API client that obscures endpoint semantics.","Streams/generics used only to make code look sophisticated."],
practice:["Use List, Set and Map deliberately in test-data code.","Create one small typed helper and explain T.","Observe a type-erasure consequence with a nested collection example.","Compare the generic helper with an explicit endpoint method and retain the clearer contract."],
questions:["What does T mean at compile time?","What information does type erasure remove?","Why might List<ServiceResponse> need special deserialization handling?"]},

{id:"exceptions-resources",title:"Exceptions and Resource Management",principle:"Automation infrastructure fails too: configuration, files, HTTP setup and browsers can all break. Preserve causes, classify failures honestly and close owned resources deterministically.",
mechanics:["Checked exceptions must be declared/handled; unchecked exceptions derive from RuntimeException.","Exception chaining preserves the original cause.","try-with-resources closes AutoCloseable resources even when work fails.","finally exists for cleanup but try-with-resources expresses ownership more safely when supported."],
frameworkUse:["Produce actionable configuration failures.","Later manage Playwright/browser/file resources safely.","Distinguish test assertion failure from framework/environment failure."],
antiPatterns:["catch (Exception e) {}.","Catching infrastructure failure and calling it a skipped/passed test.","Throwing a new exception without the original cause.","Opening resources whose ownership/cleanup is unclear."],
practice:["Wrap one configuration failure with actionable context without losing its cause.","Use try-with-resources with a closeable resource.","Write one test proving cleanup happens on failure.","Reject catch-all code that converts infrastructure failure into a passing or skipped test."],
questions:["When does try-with-resources call close?","Why preserve the cause?","What is dangerous about treating environment failure as a test failure or skip without classification?"]},

{id:"annotations-reflection",title:"Annotations and Reflection",principle:"JUnit's programming model relies on metadata and runtime discovery. Understanding the mechanism prevents annotation-heavy framework code from becoming magic.",
mechanics:["Annotations attach structured metadata to declarations.","Retention controls whether annotation metadata survives into class files/runtime.","Target restricts where an annotation can be applied.","Reflection lets code inspect classes, methods and annotations at runtime.","JUnit discovers annotated tests/lifecycle methods and invokes them through its engine."],
frameworkUse:["Understand @Test, @BeforeEach, @Tag, @ParameterizedTest and @ExtendWith.","Later design custom composed annotations only when repeated semantics justify them.","Debug why a test is or is not discovered."],
antiPatterns:["Creating custom annotations for aesthetics.","Assuming annotations execute behavior by themselves.","Reflection-heavy helpers that bypass normal type safety without need."],
practice:["Create a tiny runtime annotation and inspect it via reflection.","Explain conceptually how JUnit discovers @Test methods.","Use @Test, @DisplayName and lifecycle annotations intentionally.","Break test discovery deliberately once, diagnose it, then restore it."],
questions:["Does @Test itself execute a method?","Why does retention matter?","What component interprets JUnit annotations?"]},

{id:"junit-tags",title:"JUnit 5 Architecture, Lifecycle and Tags",principle:"JUnit is more than @Test. Understand Platform, Jupiter, discovery, instances, lifecycle callbacks, parameterization and tags before building extensions or CI selection around it.",
mechanics:["JUnit Platform provides discovery/execution infrastructure; Jupiter is the JUnit 5 programming model/engine.","Test instances and @BeforeEach/@AfterEach lifecycle affect state ownership.","Parameterized tests execute one behavior against multiple argument sets.","Tags are metadata used by launchers/build tooling for intentional selection.","Extensions provide explicit lifecycle/interception/parameter-resolution hooks when ordinary composition is insufficient."],
frameworkUse:["Create smoke/api/browser portfolios without duplicating suites.","Choose lifecycle boundaries for test-owned data.","Understand how Maven Surefire delegates execution to the JUnit Platform."],
antiPatterns:["A tag for every feature or Jira ticket.","Order-dependent tests sharing instance/static state.","Extensions used to hide ordinary object construction.","@BeforeAll creating mutable global product state."],
practice:["Define the initial steward-tests tag vocabulary.","Demonstrate @BeforeEach/@AfterEach ownership.","Create one @ParameterizedTest with MethodSource.","Tag a small test set and execute one selected group with Maven/Surefire.","Document forbidden/redundant tags and when an extension would be justified."],
questions:["What is the difference between JUnit Platform and Jupiter?","Who interprets @Tag during Maven execution?","When should setup remain explicit instead of becoming an extension?"],code:"@Tag(\"smoke\")\n@Tag(\"api\")\n@Test\nvoid healthEndpointIsAvailable() {}"},

{id:"functional-java",title:"Lambdas, Functional Interfaces, Streams and Optional",principle:"Functional Java is useful for callbacks and transformations common in libraries, but framework code must optimize for diagnosis and readability.",
mechanics:["A functional interface has one abstract method and can be implemented with a lambda.","Method references are concise lambda forms when intent remains obvious.","Streams form lazy transformation pipelines terminated by an operation such as toList or collect.","Optional models a value that may be absent; it is not a universal replacement for null or every field."],
frameworkUse:["Read modern Java/library APIs confidently.","Express small test-data transformations and callbacks.","Understand functional hooks encountered in framework/library APIs."],
antiPatterns:["Ten-stage streams that are harder to debug than a loop.","Optional fields everywhere in DTOs without semantic reason.","Side effects hidden inside map/filter operations."],
practice:["Implement one small transformation with a stream.","Implement the same logic imperatively and compare diagnosis/readability.","Use a method reference where it genuinely improves clarity.","Use Optional only where absence is part of the contract."],
questions:["What makes an interface functional?","When does a stream actually execute?","When is a loop clearer than a stream?"]},

{id:"concurrency",title:"Concurrency, Shared State and Thread Safety",principle:"Parallel automation is concurrent software. Learn enough Java concurrency to recognize unsafe framework state before JUnit or CI executes tests simultaneously.",
mechanics:["Threads can interleave access to shared state nondeterministically.","Immutable values reduce synchronization needs.","Atomicity, visibility and ordering are separate concurrency concerns.","ThreadLocal associates state with a thread but introduces lifecycle/cleanup risks and does not fix bad ownership.","Concurrent collections solve specific data-structure hazards, not domain-level race conditions."],
frameworkUse:["Recognize why static clients/pages/test data become flaky under parallel execution.","Design unique test identities and isolated browser contexts later.","Make an evidence-based decision before enabling JUnit parallelism."],
antiPatterns:["static mutable currentUser/currentPage/currentService.","Adding synchronized everywhere after flakes appear.","ThreadLocal used as a global-variable disguise.","Enabling parallel=true because CI is slow before proving isolation."],
practice:["Identify every mutable singleton/static value in steward-tests.","Create a tiny race demonstration and explain why its outcome is unsafe.","Make test identity/data collision-safe.","Explain one legitimate ThreadLocal use and its cleanup obligation.","Keep parallel execution disabled and write the conditions required to enable it later."],
questions:["What state is actually shared between concurrent tests?","Why does immutability help?","What problem does ThreadLocal solve, and what problems does it not solve?"]}
];
const executionMilestone: Lesson={id:"quality-java-execution-backbone-milestone",title:"Milestone: Explain and Control the Maven → JUnit Execution Chain",activities:[{id:"quality-java-execution-backbone-milestone-001",title:"Build and Debug the Execution Backbone",estimatedMinutes:150,content:{type:"practical",objective:"Prove that steward-tests execution is understood from Maven command to individual JUnit invocation.",scenario:"A mature framework engineer must locate failures at the correct layer rather than changing dependencies/plugins until the build turns green.",instructions:["Draw and document: shell/CI → Maven lifecycle → Surefire → JUnit Platform → Jupiter TestEngine → discovery/test plan → test instance/lifecycle → test method.","Pin the important Maven plugin/dependency versions used by the project.","Use dependency:tree and effective-pom to explain the resolved build.","Demonstrate tag selection through Maven without duplicating suites.","Demonstrate one MethodSource parameterized test.","Implement one tiny JUnit extension or ParameterResolver, then document why most setup should remain ordinary composition.","Create controlled failures at two different layers (for example Maven discovery/configuration and a real assertion) and record how their symptoms differ.","Write the future decision rule for Surefire versus Failsafe in steward-tests."],deliverables:["Execution-chain diagram","Resolved dependency/build note","Tag-selection command/evidence","Parameterized test","Narrow extension experiment","Failure-diagnosis evidence","Surefire/Failsafe decision"],completionCriteria:["The learner can narrate mvn test end-to-end.","The learner distinguishes Maven/plugin/discovery/engine/lifecycle/assertion failures.","The build works from CLI, not only an IDE.","No extension exists merely to hide ordinary construction.","Dependency resolution is explainable from the effective POM and dependency tree."]}}]};

const milestone: Lesson={id:"quality-java-foundation-milestone",title:"Milestone: steward-tests Java Foundation",activities:[{id:"quality-java-foundation-milestone-001",title:"Build the Framework Substrate Without Hiding the Mechanics",estimatedMinutes:120,content:{type:"practical",objective:"Produce the Java/Maven foundation on which the later REST Assured and Playwright framework will grow.",scenario:"The repository should demonstrate Java engineering fundamentals before specialized automation libraries hide them.",instructions:["Make steward-tests compile and execute with Maven and JUnit 5.","Implement validated immutable configuration.","Use constructor injection for dependencies.","Create test-data models/builders with explicit ownership.","Define the governed JUnit tag vocabulary.","Add one tiny Java HttpClient probe so the learner experiences raw HTTP before REST Assured.","Record concurrency hazards before enabling parallel execution."],deliverables:["steward-tests Maven project","JUnit baseline","Configuration/domain support","Tag policy","Raw HTTP probe","Architecture note"],completionCriteria:["mvn test succeeds.","No Spring/DI container is required.","No god BaseTest or mutable global driver/client exists.","Dependencies are explicit.","The learner can explain what JUnit and REST Assured will later abstract."]}}]};
export const javaForTestFrameworkEngineeringDeepLessons: Lesson[]=[...specs.map(lesson),executionMilestone,milestone];
