import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const playwright: LearningResource = { title: "Playwright — Browsers", url: "https://playwright.dev/python/docs/browsers" };
const mdnResponsive: LearningResource = { title: "MDN — Responsive web design", url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Responsive_Design" };
const browserstack: LearningResource = { title: "BrowserStack — Cross browser testing", url: "https://www.browserstack.com/guide/cross-browser-testing" };

type Spec = { id: string; title: string; intro: string; sections: Array<{ title: string; body: string[]; list?: string[]; code?: string }>; practice: string[]; questions: string[] };

function rich(spec: Spec): Lesson {
    const blocks: LessonBlock[] = [{ type: "paragraph", text: spec.intro }];
    for (const section of spec.sections) {
        blocks.push({ type: "heading", id: `${spec.id}-${section.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`, text: section.title, level: 2 });
        section.body.forEach((text) => blocks.push({ type: "paragraph", text }));
        if (section.list) blocks.push({ type: "list", items: section.list });
        if (section.code) blocks.push({ type: "code", language: "python", code: section.code });
    }
    blocks.push({ type: "callout", tone: "steward", title: "Steward browser checkpoint", body: "Browser and environment tests must add evidence that service-layer tests cannot provide. Record the exact browser, operating system, viewport, environment and release identity for every meaningful failure." });
    blocks.push({ type: "resources", title: "Continue learning", resources: [playwright, mdnResponsive, browserstack] });
    return { id: `browser-environment-${spec.id}`, title: spec.title, activities: [
        { id: `browser-environment-${spec.id}-001`, title: spec.title, estimatedMinutes: 45, content: { type: "reading", body: spec.intro, blocks } },
        { id: `browser-environment-${spec.id}-002`, title: `Apply: ${spec.title}`, estimatedMinutes: 45, content: { type: "practical", objective: `Apply ${spec.title} to Steward's browser and deployed environments.`, scenario: "Use the existing pytest/Playwright framework and the real Steward environment. Do not move API-only checks into the browser merely because browser automation exists.", instructions: spec.practice, deliverables: ["Executable browser/environment evidence", "Risk-based coverage rationale", "Failure-diagnostic record"], completionCriteria: ["The selected browser/environment adds unique evidence.", "The test remains diagnosable.", "The coverage choice is tied to risk rather than matrix size."] } },
        { id: `browser-environment-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.questions.join("\n\n"), minimumCharacters: 180 } },
    ] };
}

const specs: Spec[] = [
    { id: "browser-differences", title: "Browser Differences", intro: "Modern browsers implement shared web standards, but rendering engines, defaults, feature support, accessibility behavior and timing can still differ. Cross-browser quality begins by identifying which differences could affect users, not by executing every test everywhere.", sections: [
        { title: "Engines matter more than logos", body: ["Chromium, Firefox and WebKit represent distinct browser-engine families. Two browsers built on Chromium may share most rendering behavior, while Safari and Firefox can expose different layout, input, storage or timing behavior.", "For Steward, focus on user-critical flows such as navigating the service registry, editing ownership metadata, filtering services and completing authenticated actions."], list: ["Rendering/layout differences", "JavaScript/Web API support", "Form and input behavior", "Cookie/storage semantics", "Accessibility tree differences", "Timing and event-order differences"] },
        { title: "Reproduce with identity", body: ["A browser defect report without browser version, OS, viewport and release identity is weak evidence. Reproduction context belongs beside the observed behavior."], code: "def browser_identity(page):\n    return {\n        \"user_agent\": page.evaluate(\"navigator.userAgent\"),\n        \"viewport\": page.viewport_size,\n    }" },
    ], practice: ["List Steward browser behaviors whose risk could vary by engine.", "Classify which require Chromium-only, multi-engine or manual exploratory coverage.", "Capture browser identity in one existing Playwright failure path."], questions: ["Why is testing Chrome, Edge and another Chromium browser not equivalent to testing three engine families?", "What browser metadata is required to make a failure reproducible?"] },
    { id: "responsive-testing", title: "Responsive Testing", intro: "Responsive testing verifies that the product remains usable as available space, input mode and content shape change. Screenshot similarity alone cannot prove that users can still complete their work.", sections: [
        { title: "Test behavior across layout states", body: ["Choose viewports around meaningful layout transitions rather than a long device catalog. Verify that actions remain reachable, text remains legible, tables and filters remain usable, and important information is not silently hidden.", "Steward may have dense service metadata. Narrow layouts can expose overflow, inaccessible action menus or ownership fields that disappear without an alternative interaction."], list: ["Navigation remains reachable", "Primary actions remain operable", "No critical information is clipped or inaccessible", "Focus order and keyboard use remain coherent", "Horizontal overflow is intentional where unavoidable"] },
        { title: "Prefer semantic assertions", body: ["A screenshot can support diagnosis, but behavioral checks should assert what a user can see and do. Use screenshots selectively where visual regression risk genuinely matters."], code: "page.set_viewport_size({\"width\": 390, \"height\": 844})\npage.goto(f\"{base_url}/services\")\nexpect(page.get_by_role(\"heading\", name=\"Services\")).to_be_visible()\nexpect(page.get_by_role(\"button\", name=\"Add service\")).to_be_visible()" },
    ], practice: ["Identify Steward's meaningful responsive breakpoints from behavior, not device brands.", "Create one narrow-viewport and one wide-viewport test for a critical flow.", "Record any behavior that should remain exploratory rather than screenshot-automated."], questions: ["Why is a screenshot-only responsive suite insufficient?", "How should you choose viewport widths for automated coverage?"] },
    { id: "cross-browser", title: "Cross-browser Testing", intro: "Cross-browser testing is a coverage-selection problem. The goal is confidence across supported user environments with the smallest matrix that can reveal meaningful compatibility risk.", sections: [
        { title: "Build a risk-based matrix", body: ["Use supported-user data, engine diversity, feature sensitivity and business criticality to decide where tests run. A smoke path may run across every supported engine while a large regression suite stays on a primary browser unless evidence justifies expansion.", "Do not multiply all tests by all browsers automatically. That increases runtime and triage cost without necessarily increasing useful confidence."], list: ["Primary browser: broad regression", "Representative alternate engines: critical smoke and compatibility-sensitive flows", "Known-risk features: targeted matrix expansion", "Unsupported browsers: documented rather than accidentally tested"] },
        { title: "Separate product defects from environment defects", body: ["When one engine fails, compare the same release and data on another engine. Capture traces, console/network errors and relevant rendering evidence before concluding that the backend is wrong."] },
    ], practice: ["Define Steward's initial supported browser matrix and justify each entry.", "Select a cross-browser smoke subset from existing tests.", "Document one rule for expanding or shrinking the matrix based on evidence."], questions: ["Why is running the entire suite on every browser often wasteful?", "What evidence should cause you to expand cross-browser coverage?"] },
    { id: "browserstack", title: "BrowserStack or Equivalent", intro: "Remote browser platforms provide access to browser/OS combinations and execution infrastructure that may be difficult to maintain locally. They solve environment access, not test design.", sections: [
        { title: "Treat the provider as infrastructure", body: ["Your tests should preserve the same behavioral intent whether executed locally or remotely. Provider capabilities, credentials, network tunnels and artifact URLs belong in infrastructure/configuration layers—not inside Steward domain assertions.", "A remote pass does not prove production parity if the test bypasses the real route or uses materially different configuration."], list: ["Version browser/OS targets explicitly", "Keep provider credentials secret", "Preserve traces/screenshots/logs", "Record provider session identifiers", "Distinguish provider outage from product failure"] },
        { title: "Know when local engines are enough", body: ["Playwright's local Chromium, Firefox and WebKit cover many engine-level risks. Use a remote provider when real browser/OS combinations, mobile devices, corporate constraints or broader compatibility evidence justify the cost." ] },
    ], practice: ["Decide whether Steward currently needs a remote provider and write the evidence-based reason.", "If available, map one Playwright smoke scenario to a remote target without changing the test's domain assertion.", "Define how provider outages are represented in test results."], questions: ["What problem does BrowserStack solve that test design does not?", "When might local Playwright browser engines provide sufficient evidence?"] },
    { id: "local-remote", title: "Local vs Remote Execution", intro: "A trustworthy automation system behaves consistently across developer machines, CI workers and remote browser infrastructure while making unavoidable differences visible. Local speed and remote realism are complementary.", sections: [
        { title: "Execution location changes dependencies", body: ["Local runs may reach localhost services, use developer-installed certificates or inherit shell configuration. CI and remote browsers often use different networking, credentials and DNS. Hidden assumptions become environment-specific failures.", "Make base URLs, timeouts, credentials and artifact paths explicit inputs. Do not branch test behavior with large if-local/if-CI blocks."], code: "@dataclass(frozen=True)\nclass RunContext:\n    environment: str\n    base_url: str\n    browser: str\n    remote: bool" },
        { title: "Keep the same claim", body: ["A smoke test that means one thing locally and another in CI is two tests disguised as one. Infrastructure can vary; the business claim should remain stable." ] },
    ], practice: ["Run or design the same Steward browser smoke test locally and in CI/remote infrastructure.", "List hidden dependencies exposed by the second execution location.", "Move those dependencies into explicit configuration or documented prerequisites."], questions: ["Why should business assertions remain stable across local and remote execution?", "Give three hidden local assumptions that often fail in CI."] },
    { id: "environment-parity", title: "Environment Parity and Configuration Risk", intro: "Environment parity does not mean every environment is byte-for-byte identical. It means differences that can change behavior are known, intentional and accounted for in evidence and release decisions.", sections: [
        { title: "Configuration is part of the product behavior", body: ["Different identity providers, feature flags, datasets, proxies, TLS termination, database versions or dependency endpoints can change what users experience even when the application artifact is identical.", "Reuse Delivery and Cloud discipline: identify the exact Steward artifact and separately record environment configuration. When UAT passes, state what production differences remain."], list: ["Application artifact/version", "Environment variables and feature flags", "Database/schema version", "Identity/auth configuration", "Ingress/TLS/reverse proxy", "External/internal dependency endpoints", "Representative data and permissions"] },
        { title: "Parity risk should be explicit", body: ["Do not claim that a lower environment proves production if critical differences are untested. Record residual parity risks and add deployment/runtime verification where appropriate rather than pretending environments are equivalent."], code: "release: steward-api@sha256:abc...\nenvironment: uat\nidentity_provider: uat-idp\nfeature_flags:\n  ownership_reviews: true\nknown_prod_difference:\n  tls_termination: managed_edge" },
    ], practice: ["Create a Steward environment-parity inventory for local, UAT and production-like targets.", "Identify the three differences most likely to change test outcomes.", "Define evidence or verification for each important difference."], questions: ["Why can the same application artifact behave differently across environments?", "What should a tester communicate when UAT and production are not fully equivalent?"] },
];

const lab: Lesson = { id: "browser-environment-steward-lab", title: "Lab: Run Steward Tests Across Environments", activities: [
    { id: "browser-environment-steward-lab-001", title: "Design the Browser and Environment Matrix", estimatedMinutes: 60, content: { type: "practical", objective: "Define the smallest credible browser/environment matrix for Steward.", scenario: "Start from actual supported users, critical browser flows and known environment differences rather than generating a Cartesian product.", instructions: ["List critical browser-facing Steward behaviors.", "Select the primary browser and representative alternate engines.", "Identify responsive layout states worth automated coverage.", "Map local, CI, UAT and any remote-browser execution contexts.", "Record what is deliberately excluded and why."], deliverables: ["Risk-based browser matrix", "Environment matrix", "Explicit exclusions"], completionCriteria: ["Every matrix entry has a risk reason.", "The matrix does not multiply all tests indiscriminately.", "Exclusions preserve visible residual risk."] } },
    { id: "browser-environment-steward-lab-002", title: "Execute Critical Browser Evidence", estimatedMinutes: 90, content: { type: "practical", objective: "Execute selected Steward browser flows across the chosen matrix.", scenario: "Use the pytest/Playwright framework built in the previous module and keep API-only evidence at the service layer.", instructions: ["Run the critical browser smoke subset on the primary engine.", "Run targeted scenarios on at least one alternate engine where available.", "Run responsive coverage at meaningful layout states.", "Capture traces/screenshots only when useful for failure diagnosis.", "Record browser/OS/viewport/release/environment identity."], deliverables: ["Cross-browser run evidence", "Responsive evidence", "Diagnostic artifacts"], completionCriteria: ["The browser checks prove user-facing behavior.", "Every failure is reproducible from recorded context.", "The suite avoids duplicating service-layer assertions without reason."] } },
    { id: "browser-environment-steward-lab-003", title: "Compare Environments and Diagnose Drift", estimatedMinutes: 75, content: { type: "practical", objective: "Identify behaviorally meaningful differences between Steward environments.", scenario: "A successful local run must not be treated as equivalent to UAT or production-like evidence without examining configuration and routing differences.", instructions: ["Compare application artifact and relevant configuration across execution targets.", "Run the same critical claim in two environments where available.", "Classify any difference as expected configuration, environment defect, product defect or unresolved evidence gap.", "Record production differences that remain after UAT."], deliverables: ["Environment parity inventory", "Comparison evidence", "Residual parity-risk note"], completionCriteria: ["Behavior-changing differences are visible.", "Product and environment failures are distinguished with evidence.", "Unverified production differences are not silently treated as covered."] } },
    { id: "browser-environment-steward-lab-004", title: "Browser and Environment Testing Review", estimatedMinutes: 30, content: { type: "reflection", prompt: "Defend the final Steward browser/environment matrix. Which browser risks required multi-engine evidence, which responsive states mattered, what environment differences remain, and how did you avoid turning cross-browser testing into an expensive Cartesian product?", minimumCharacters: 300 } },
] };

export const browserAndEnvironmentTestingDeepLessons: Lesson[] = [...specs.map(rich), lab];
