import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const playwright: LearningResource = { title: "Playwright — Browsers", url: "https://playwright.dev/java/docs/browsers" };
const mdnResponsive: LearningResource = { title: "MDN — Responsive web design", url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Responsive_Design" };
const browserstack: LearningResource = { title: "BrowserStack — Cross browser testing", url: "https://www.browserstack.com/guide/cross-browser-testing" };

type Spec = { id: string; title: string; intro: string; sections: Array<{ title: string; body: string[]; list?: string[]; code?: string }>; practice: string[]; questions: string[] };

function rich(spec: Spec): Lesson {
    const blocks: LessonBlock[] = [{ type: "paragraph", text: spec.intro }];
    for (const section of spec.sections) {
        blocks.push({ type: "heading", id: `${spec.id}-${section.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`, text: section.title, level: 2 });
        section.body.forEach((text) => blocks.push({ type: "paragraph", text }));
        if (section.list) blocks.push({ type: "list", items: section.list });
        if (section.code) blocks.push({ type: "code", language: "java", code: section.code });
    }
    blocks.push({ type: "callout", tone: "steward", title: "Steward browser checkpoint", body: "Browser and environment tests must add evidence that service-layer tests cannot provide. Record the exact browser, operating system, viewport, environment and release identity for every meaningful failure." });
    blocks.push({ type: "resources", title: "Continue learning", resources: [playwright, mdnResponsive, browserstack] });
    return { id: `browser-environment-${spec.id}`, title: spec.title, activities: [
        { id: `browser-environment-${spec.id}-001`, title: spec.title, estimatedMinutes: 45, content: { type: "reading", body: spec.intro, blocks } },
        { id: `browser-environment-${spec.id}-002`, title: `Apply: ${spec.title}`, estimatedMinutes: 45, content: { type: "practical", objective: `Apply ${spec.title} to Steward's browser and deployed environments.`, scenario: "Use the existing JUnit/Playwright Java framework and the real Steward environment. Do not move API-only checks into the browser merely because browser automation exists.", instructions: spec.practice, deliverables: ["Executable browser/environment evidence", "Risk-based coverage rationale", "Failure-diagnostic record"], completionCriteria: ["The selected browser/environment adds unique evidence.", "The test remains diagnosable.", "The coverage choice is tied to risk rather than matrix size."] } },
        { id: `browser-environment-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.questions.join("\n\n"), minimumCharacters: 180 } },
    ] };
}

const specs: Spec[] = [
    { id: "playwright-runtime-model", title: "Playwright Runtime and Browser Ownership", intro: "Playwright automation is resource-owning concurrent software. Understand Playwright, Browser, BrowserContext and Page lifetimes before hiding them behind fixtures or extensions.", sections: [
        { title: "Ownership hierarchy", body: ["Playwright owns the driver/runtime connection; Browser represents a launched browser process; BrowserContext is an isolated browser session; Page is a tab/document surface inside a context.", "A test normally needs isolated context state even when a browser process is shared for efficiency. Ownership must make cleanup deterministic after both success and failure."], list: ["Playwright: runtime/driver resources", "Browser: engine process connection", "BrowserContext: isolated cookies/storage/permissions", "Page: tab/document interaction surface"] },
        { title: "Context is the primary isolation boundary", body: ["Sharing a Page or authenticated BrowserContext across tests couples cookies, local storage, navigation and permissions. New contexts are cheap enough to make per-test isolation the default unless evidence supports another lifetime."], code: "try (Playwright playwright = Playwright.create()) {\n  Browser browser = playwright.chromium().launch();\n  BrowserContext context = browser.newContext();\n  Page page = context.newPage();\n  // test interaction\n  context.close();\n  browser.close();\n}" },
    ], practice: ["Create a minimal Playwright Java smoke experiment and label who owns each resource.", "Demonstrate that two BrowserContexts do not share a cookie/session by default.", "Force an assertion failure and prove context/browser cleanup still occurs.", "Write the intended browser-vs-context lifetime for steward-tests without implementing a global singleton."], questions: ["What state belongs to BrowserContext rather than Page?", "Why is sharing one Page across tests unsafe?", "Which resources may reasonably be longer-lived than one test and under what constraints?"] },

    { id: "dom-accessibility-locators", title: "DOM, Accessibility Tree and Locator Strategy", intro: "Browser automation should target user-facing semantics where possible. Understand the DOM, accessible roles/names and test-specific contracts before choosing CSS or XPath.", sections: [
        { title: "The DOM is implementation; accessibility semantics describe interaction", body: ["HTML elements form the DOM. Browsers derive an accessibility tree using roles, names, states and relationships. Playwright role/label/text locators can align automation with how controls are exposed to users and assistive technology.", "Accessible locators are not automatically perfect: duplicate names, hidden elements or incorrect ARIA can make them ambiguous and reveal a product accessibility problem." ] },
        { title: "Choose the strongest stable contract", body: ["Prefer role plus accessible name for interactive controls, labels for form fields and explicit test IDs when no stable user-facing semantic exists. CSS may be appropriate for structural cases; brittle XPath tied to nested markup should be exceptional."], list: ["getByRole: semantic interactive contract", "getByLabel: labeled form controls", "getByText: visible textual contract when unique/stable", "getByTestId: explicit automation contract", "CSS: targeted structural fallback", "XPath: last-resort structural coupling"] },
    ], practice: ["Inspect one Steward screen's DOM and accessible roles/names.", "Implement the same locator three ways and rank them by contract stability.", "Find one accessibility ambiguity or explain why the chosen semantic locator is unique.", "Define Steward's locator policy."], questions: ["What is the difference between the DOM and accessibility tree?", "Why can getByRole improve both stability and accessibility feedback?", "When is a test ID preferable to visible text?"] },

    { id: "actionability-auto-waiting", title: "Actionability, Auto-waiting and Synchronization", intro: "Playwright reduces timing flakiness by waiting for actionable elements and retrying web-first assertions. Framework engineers must understand what it waits for so they do not reintroduce sleeps or confuse application readiness with element readiness.", sections: [
        { title: "Actions have preconditions", body: ["Before interactions such as click, Playwright checks relevant conditions such as resolution to the expected element, visibility, stability, event receivability and enabled state. This removes many explicit waits, but it cannot infer that a backend job or business workflow is complete unless that completion becomes observable." ] },
        { title: "Assertions are synchronization tools", body: ["Web-first assertions retry until their condition is satisfied or times out. Prefer an observable UI/network/state condition over Thread.sleep. A longer timeout does not repair a missing readiness signal."], code: "Locator save = page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName(\"Save\"));\nsave.click();\nassertThat(page.getByText(\"Service updated\")).isVisible();" },
    ], practice: ["Remove one artificial sleep from a controlled browser example and replace it with an observable condition.", "Create a delayed UI state and observe Playwright's retry behavior.", "Identify one condition auto-waiting cannot know about and define the correct readiness signal.", "Document timeout escalation as diagnosis, not a default fix."], questions: ["What does Playwright auto-wait for?", "Why is Thread.sleep usually weak synchronization?", "When can an element be clickable while the business operation is not ready?"] },

    { id: "navigation-network", title: "Navigation, Network and Application Readiness", intro: "A page load event is not the same thing as application readiness. Modern SPAs continue fetching and rendering after navigation, so tests should synchronize on the behavior they actually need.", sections: [
        { title: "Navigation lifecycle is only one signal", body: ["DOMContentLoaded/load describe document lifecycle events. Network-idle heuristics can be misleading for applications with polling, analytics or persistent connections. Prefer a specific UI state or expected network response tied to the user action." ] },
        { title: "Network observation is evidence, not a substitute backend test", body: ["Playwright can observe requests/responses, wait for a response and intercept routes. Use this to synchronize or diagnose browser behavior. Keep comprehensive API contract assertions in the API layer." ] },
    ], practice: ["Navigate to a Steward SPA route and identify what makes it actually ready for the intended action.", "Wait for a specific observable state instead of generic network idle.", "Capture one failed network response during a browser scenario for diagnostics.", "Explain which assertion belongs in the API suite instead."], questions: ["Why can network idle be unreliable?", "When should a browser test inspect network traffic?", "What is the difference between browser synchronization and API contract testing?"] },

    { id: "browser-state", title: "Cookies, Storage and Authentication State", intro: "Browser identity is state. Cookies, local/session storage and storage snapshots can accelerate tests, but reused state can also hide authentication defects and couple scenarios.", sections: [
        { title: "Know where session state lives", body: ["Cookies are scoped by domain/path and security attributes; localStorage is origin-scoped and persistent; sessionStorage is page/tab-session scoped. Applications may combine them with server-side sessions.", "Playwright storage state can bootstrap authenticated contexts, but the state file is sensitive and should be generated/managed securely rather than committed with live credentials." ] },
        { title: "Choose login evidence deliberately", body: ["A small number of tests should prove the real login UI when it is in scope. Most unrelated UI tests may establish state through API/auth setup if that reduces runtime while preserving the behavior under test." ] },
    ], practice: ["Inspect which browser storage mechanisms Steward authentication uses.", "Create two isolated contexts and prove state does not leak.", "Design API-assisted authentication for a non-login UI test.", "Define how storage-state artifacts are protected and refreshed."], questions: ["Why is storage state sensitive?", "When should a test log in through the UI?", "How can shared authenticated state hide defects?"] },

    { id: "ui-test-selection", title: "Choosing What Deserves a Browser Test", intro: "The browser is the most expensive layer in this Quality Steward stack. Use it for evidence that depends on rendering, browser state or real user interaction—not as a second API regression suite.", sections: [
        { title: "Ask what unique evidence the browser adds", body: ["Browser tests are justified for navigation, rendered state, forms, client-side validation, accessibility semantics, browser storage, routing and integration of frontend behavior with backend responses.", "If the claim is simply that an API rejects an unauthorized mutation or returns a schema, REST Assured is faster and more diagnosable." ] },
        { title: "Build a thin high-value UI portfolio", body: ["Prefer a small set of critical user journeys plus targeted browser-specific risks. Use API setup to reach the state needed for UI evidence without clicking through unrelated workflows." ] },
    ], practice: ["Take ten candidate Steward scenarios and classify them API, browser, both with distinct claims, or exploratory/manual.", "For each browser candidate write the unique browser-level evidence in one sentence.", "Remove one redundant browser scenario from the hypothetical suite and move its claim to API coverage."], questions: ["What makes a scenario inherently browser-level?", "When is API-assisted setup appropriate?", "Why can fewer UI tests produce stronger overall evidence?"] },

    { id: "page-components", title: "Page Objects and Component Objects from Proven Repetition", intro: "Page Objects are product-facing interaction abstractions, not mandatory wrappers around every route or DOM element. Extract them after direct flows reveal stable repeated capabilities.", sections: [
        { title: "Model capabilities, not markup", body: ["A ServiceRegistryPage might expose searchForService or openService; a reusable navigation component might expose openRegistry. Avoid public Locator fields for every element and avoid embedding all assertions in the object.", "Component objects are useful when a stable widget such as navigation, modal or table appears across pages." ] },
        { title: "Keep assertions at the right level", body: ["Objects may expose observable state or narrow component invariants, but tests should retain the domain claim so failure intent is obvious. Do not create a page object that returns only booleans and hides diagnostic context." ] },
    ], practice: ["Write a second related direct-locator flow before extraction.", "Mark repeated stable interactions.", "Extract the smallest Page/Component Object justified by those repetitions.", "Compare before/after test readability and delete an abstraction that adds no value."], questions: ["Why should page objects not mirror the DOM?", "When is a component object better than a page object?", "Where should domain assertions normally remain?"] },

    { id: "advanced-browser-interactions", title: "Uploads, Downloads, Frames, Popups and Dialogs", intro: "Real browser workflows cross interaction boundaries that require explicit event ownership. Learn Playwright's event-oriented model rather than adding sleeps around downloads, new tabs or frames.", sections: [
        { title: "Wait for the event you cause", body: ["Downloads and popups often begin as a consequence of a click. Register the Playwright wait around the triggering action so the event cannot race ahead of the test. Frames require targeting the correct frame context; dialogs can block execution until handled." ] },
        { title: "Treat files as test resources", body: ["Uploads should use controlled fixtures with known content/type. Downloads should be validated for meaningful filename/content/size semantics and cleaned up; do not rely on a developer machine's Downloads directory." ] },
    ], practice: ["Implement one controlled upload or download example relevant to Steward or a sandbox page.", "Demonstrate event-safe popup/download waiting.", "Inspect one frame/dialog pattern even if Steward does not currently use it.", "Document cleanup ownership for generated files."], questions: ["Why should the event wait wrap the triggering action?", "What makes file tests non-reproducible on developer machines?", "How do frames change locator context?"] },

    { id: "browser-diagnostics", title: "Browser Diagnostics: Traces, Screenshots, Console and Network", intro: "A failed browser assertion is often the end of a chain of frontend, network or environment events. Capture layered evidence that explains the chain without producing enormous sensitive artifacts on every passing test.", sections: [
        { title: "Trace tells a richer story", body: ["Playwright traces can preserve actions, DOM snapshots and network context useful for replay/triage. Screenshots show one visual moment; console messages and failed responses expose other failure classes.", "Prefer trace/screenshot retention on failure or targeted investigation. Apply retention, size and secret-handling policies." ] },
        { title: "Attach execution identity", body: ["Record environment/release, browser engine/version, viewport and correlation identifiers beside artifacts. A screenshot without identity is weak regression evidence." ] },
    ], practice: ["Trigger a controlled browser failure.", "Capture trace, screenshot, relevant console error and failed request/response metadata.", "Attach sanitized evidence to the reporting layer.", "Decide which artifacts are failure-only versus always-on."], questions: ["What does a trace provide that a screenshot does not?", "Why can always-on video/trace be operationally expensive?", "Which browser artifacts can contain sensitive information?"] },

    { id: "browser-parallelism", title: "Parallel Browser Execution and Isolation", intro: "Parallel Playwright execution is safe only when browser contexts, users, data and external side effects are isolated. Concurrency multiplies hidden ownership mistakes.", sections: [
        { title: "Parallelize contexts, not shared mutable pages", body: ["JUnit workers may execute tests concurrently. Each test needs independent context/page state and collision-safe data. Sharing one Page or mutable static context turns ordering/timing into test behavior.", "Browser process sharing can be an optimization if the lifecycle implementation is thread-safe and contexts remain isolated; correctness comes before optimization." ] },
        { title: "External state is still shared", body: ["Separate BrowserContexts do not isolate the backend database. Two tests can still collide on the same service slug, account or workflow. Browser isolation and data isolation are separate problems." ] },
    ], practice: ["Audit browser/session/data state for parallel hazards.", "Run two isolated-context tests concurrently only after the audit passes.", "Introduce a controlled data collision and diagnose why BrowserContext isolation did not prevent it.", "Document maximum safe concurrency and remaining external bottlenecks."], questions: ["What does BrowserContext isolate?", "What does it not isolate?", "When might sharing a Browser process be acceptable?", "Why must data uniqueness precede parallelism?"] },


    { id: "browser-differences", title: "Browser Differences", intro: "Modern browsers implement shared web standards, but rendering engines, defaults, feature support, accessibility behavior and timing can still differ. Cross-browser quality begins by identifying which differences could affect users, not by executing every test everywhere.", sections: [
        { title: "Engines matter more than logos", body: ["Chromium, Firefox and WebKit represent distinct browser-engine families. Two browsers built on Chromium may share most rendering behavior, while Safari and Firefox can expose different layout, input, storage or timing behavior.", "For Steward, focus on user-critical flows such as navigating the service registry, editing ownership metadata, filtering services and completing authenticated actions."], list: ["Rendering/layout differences", "JavaScript/Web API support", "Form and input behavior", "Cookie/storage semantics", "Accessibility tree differences", "Timing and event-order differences"] },
        { title: "Reproduce with identity", body: ["A browser defect report without browser version, OS, viewport and release identity is weak evidence. Reproduction context belongs beside the observed behavior."], code: "def browser_identity(page):\n    return {\n        \"user_agent\": page.evaluate(\"navigator.userAgent\"),\n        \"viewport\": page.viewport_size,\n    }" },
    ], practice: ["List Steward browser behaviors whose risk could vary by engine.", "Classify which require Chromium-only, multi-engine or manual exploratory coverage.", "Capture browser identity in one existing Playwright failure path."], questions: ["Why is testing Chrome, Edge and another Chromium browser not equivalent to testing three engine families?", "What browser metadata is required to make a failure reproducible?"] },
    { id: "responsive-testing", title: "Responsive Testing", intro: "Responsive testing verifies that the product remains usable as available space, input mode and content shape change. Screenshot similarity alone cannot prove that users can still complete their work.", sections: [
        { title: "Test behavior across layout states", body: ["Choose viewports around meaningful layout transitions rather than a long device catalog. Verify that actions remain reachable, text remains legible, tables and filters remain usable, and important information is not silently hidden.", "Steward may have dense service metadata. Narrow layouts can expose overflow, inaccessible action menus or ownership fields that disappear without an alternative interaction."], list: ["Navigation remains reachable", "Primary actions remain operable", "No critical information is clipped or inaccessible", "Focus order and keyboard use remain coherent", "Horizontal overflow is intentional where unavoidable"] },
        { title: "Prefer semantic assertions", body: ["A screenshot can support diagnosis, but behavioral checks should assert what a user can see and do. Use screenshots selectively where visual regression risk genuinely matters."], code: "page.set_viewport_size({\"width\": 390, \"height\": 844})\npage.goto(f\"{base_url}/services\")\nexpect(page.get_by_role(\"heading\", name=\"Services\")).to_be_visible()\nexpect(page.get_by_role(\"button\", name=\"Add service\")).to_be_visible()" },
    ], practice: ["Identify Steward's meaningful responsive breakpoints from behavior, not device brands.", "Create one narrow-viewport and one wide-viewport test for a critical flow.", "Record any behavior that should remain exploratory rather than screenshot-automated."], questions: ["Why is a screenshot-only responsive suite insufficient?", "How should you choose viewport widths for automated coverage?"] },
    { id: "cross-browser", title: "Cross-browser Testing", intro: "Cross-browser testing is a coverage-selection problem. The goal is confidence across supported user environments with the smallest matrix that can reveal meaningful compatibility risk.", sections: [
        { title: "Build a risk-based matrix", body: ["Use supported-user data, engine diversity, feature sensitivity and business criticality to decide where tests run. A smoke path may run across every supported engine while a large regression suite stays on a primary browser unless evidence justifies expansion.", "Do not multiply all tests by all browsers automatically. That increases runtime and triage cost without necessarily increasing useful confidence."], list: ["Primary browser: broad regression", "Representative alternate engines: critical smoke and compatibility-sensitive flows", "Known-risk features: targeted matrix expansion", "Unsupported browsers: documented rather than accidentally tested"] },
        { title: "Separate product defects from environment defects", body: ["When one engine fails, compare the same release and data on another engine. Capture traces, console/network errors and relevant rendering evidence before concluding that the backend is wrong."] },
    ], practice: ["Define Steward's initial supported browser matrix and justify each entry.", "Select a cross-browser smoke subset from existing tests.", "Document one rule for expanding or shrinking the matrix based on evidence."], questions: ["Why is running the entire suite on every browser often wasteful?", "What evidence should cause you to expand cross-browser coverage?"] },
    { id: "browserstack", title: "BrowserStack or Equivalent", intro: "Remote browser platforms provide access to browser/OS combinations and execution infrastructure that may be difficult to maintain locally. They solve environment access, not test design.", sections: [
        { title: "Treat the provider as infrastructure", body: ["Your tests should preserve the same behavioral intent whether executed locally or remotely. Provider capabilities, credentials, network tunnels and artifact URLs belong in infrastructure/configuration layers—not inside Steward domain assertions.", "A remote pass does not prove production parity if the test bypasses the real route or uses materially different configuration."], list: ["Version browser/OS targets explicitly", "Keep provider credentials secret", "Preserve traces/screenshots/logs", "Record provider session identifiers", "Distinguish provider outage from product failure"] },
        { title: "Know when local engines are enough", body: ["Playwright's local Chromium, Firefox and WebKit cover many engine-level risks. Use a remote provider when real browser/OS combinations, mobile devices, corporate constraints or broader compatibility evidence justify the cost." ] },
    ], practice: ["Decide whether Steward currently needs a remote provider and write the evidence-based reason.", "If available, map one Playwright smoke scenario to a remote target without changing the test's domain assertion.", "Define how provider outages are represented in test results."], questions: ["What problem does BrowserStack solve that test design does not?", "When might local Playwright browser engines provide sufficient evidence?"] },
    { id: "local-remote", title: "Local vs Remote Execution", intro: "A trustworthy automation system behaves consistently across developer machines, CI workers and remote browser infrastructure while making unavoidable differences visible. Local speed and remote realism are complementary.", sections: [
        { title: "Execution location changes dependencies", body: ["Local runs may reach localhost services, use developer-installed certificates or inherit shell configuration. CI and remote browsers often use different networking, credentials and DNS. Hidden assumptions become environment-specific failures.", "Make base URLs, timeouts, credentials and artifact paths explicit inputs. Do not branch test behavior with large if-local/if-CI blocks."], code: "@dataclass(frozen=True)\nclass RunContext:\n    environment: str\n    base_url: str\n    browser: str\n    remote: bool" },
        { title: "Keep the same claim", body: ["A smoke test that means one thing locally and another in CI is two tests disguised as one. Infrastructure can vary; the business claim should remain stable." ] },
    ], practice: ["Run or design the same Steward browser smoke test locally and in CI/remote infrastructure.", "List hidden dependencies exposed by the second execution location.", "Move those dependencies into explicit configuration or documented prerequisites."], questions: ["Why should business assertions remain stable across local and remote execution?", "Give three hidden local assumptions that often fail in CI."] },
    { id: "environment-parity", title: "Environment Parity and Configuration Risk", intro: "Environment parity does not mean every environment is byte-for-byte identical. It means differences that can change behavior are known, intentional and accounted for in evidence and release decisions.", sections: [
        { title: "Configuration is part of the product behavior", body: ["Different identity providers, feature flags, datasets, proxies, TLS termination, database versions or dependency endpoints can change what users experience even when the application artifact is identical.", "Reuse Delivery and Cloud discipline: identify the exact Steward artifact and separately record environment configuration. When UAT passes, state what production differences remain."], list: ["Application artifact/version", "Environment variables and feature flags", "Database/schema version", "Identity/auth configuration", "Ingress/TLS/reverse proxy", "External/internal dependency endpoints", "Representative data and permissions"] },
        { title: "Parity risk should be explicit", body: ["Do not claim that a lower environment proves production if critical differences are untested. Record residual parity risks and add deployment/runtime verification where appropriate rather than pretending environments are equivalent."], code: "release: steward-api@sha256:abc...\nenvironment: uat\nidentity_provider: uat-idp\nfeature_flags:\n  ownership_reviews: true\nknown_prod_difference:\n  tls_termination: managed_edge" },
    ], practice: ["Create a Steward environment-parity inventory for local, UAT and production-like targets.", "Identify the three differences most likely to change test outcomes.", "Define evidence or verification for each important difference."], questions: ["Why can the same application artifact behave differently across environments?", "What should a tester communicate when UAT and production are not fully equivalent?"] },
];

const lab: Lesson = { id: "browser-environment-steward-lab", title: "Lab: Run Steward Tests Across Environments", activities: [
    { id: "browser-environment-steward-lab-001", title: "Design the Browser and Environment Matrix", estimatedMinutes: 60, content: { type: "practical", objective: "Define the smallest credible browser/environment matrix for Steward.", scenario: "Start from actual supported users, critical browser flows and known environment differences rather than generating a Cartesian product.", instructions: ["List critical browser-facing Steward behaviors.", "Select the primary browser and representative alternate engines.", "Identify responsive layout states worth automated coverage.", "Map local, CI, UAT and any remote-browser execution contexts.", "Record what is deliberately excluded and why."], deliverables: ["Risk-based browser matrix", "Environment matrix", "Explicit exclusions"], completionCriteria: ["Every matrix entry has a risk reason.", "The matrix does not multiply all tests indiscriminately.", "Exclusions preserve visible residual risk."] } },
    { id: "browser-environment-steward-lab-002", title: "Execute Critical Browser Evidence", estimatedMinutes: 90, content: { type: "practical", objective: "Execute selected Steward browser flows across the chosen matrix.", scenario: "Use the JUnit/Playwright Java framework built in the previous module and keep API-only evidence at the service layer.", instructions: ["Run the critical browser smoke subset on the primary engine.", "Run targeted scenarios on at least one alternate engine where available.", "Run responsive coverage at meaningful layout states.", "Capture traces/screenshots only when useful for failure diagnosis.", "Record browser/OS/viewport/release/environment identity."], deliverables: ["Cross-browser run evidence", "Responsive evidence", "Diagnostic artifacts"], completionCriteria: ["The browser checks prove user-facing behavior.", "Every failure is reproducible from recorded context.", "The suite avoids duplicating service-layer assertions without reason."] } },
    { id: "browser-environment-steward-lab-003", title: "Compare Environments and Diagnose Drift", estimatedMinutes: 75, content: { type: "practical", objective: "Identify behaviorally meaningful differences between Steward environments.", scenario: "A successful local run must not be treated as equivalent to UAT or production-like evidence without examining configuration and routing differences.", instructions: ["Compare application artifact and relevant configuration across execution targets.", "Run the same critical claim in two environments where available.", "Classify any difference as expected configuration, environment defect, product defect or unresolved evidence gap.", "Record production differences that remain after UAT."], deliverables: ["Environment parity inventory", "Comparison evidence", "Residual parity-risk note"], completionCriteria: ["Behavior-changing differences are visible.", "Product and environment failures are distinguished with evidence.", "Unverified production differences are not silently treated as covered."] } },
    { id: "browser-environment-steward-lab-004", title: "Browser and Environment Testing Review", estimatedMinutes: 30, content: { type: "reflection", prompt: "Defend the final Steward browser/environment matrix. Which browser risks required multi-engine evidence, which responsive states mattered, what environment differences remain, and how did you avoid turning cross-browser testing into an expensive Cartesian product?", minimumCharacters: 300 } },
] };

const browserEngineeringMilestone: Lesson = { id: "browser-engineering-milestone", title: "Milestone: Prove Browser Ownership and User-level Evidence", activities: [
 { id: "browser-engineering-milestone-001", title: "Build the Direct Playwright Evidence Baseline", estimatedMinutes: 150, content: { type: "practical", objective: "Prove one high-value browser behavior with explicit resource ownership and no speculative UI framework.", scenario: "The API layer already covers service contracts. This milestone is accepted only if the browser adds unique evidence.", instructions: ["Write the unique browser-level claim before automating it.", "Implement Playwright/Browser/BrowserContext/Page ownership with deterministic cleanup.", "Use direct semantic locators before introducing Page Objects.", "Use observable readiness/web-first assertions rather than Thread.sleep.", "Establish test state through API setup when UI setup adds no evidence.", "Prove a second BrowserContext does not inherit the first context's session.", "Capture failure trace/screenshot plus browser/environment/release identity."], deliverables: ["Browser-evidence rationale", "Direct-locator Playwright test", "Lifecycle/cleanup proof", "Context-isolation proof", "Failure diagnostics"], completionCriteria: ["The scenario genuinely requires browser evidence.", "No global mutable Page/BrowserContext exists.", "No arbitrary sleep is required.", "Failure artifacts are reproducible and sanitized.", "No Page Object exists yet unless repetition has already been demonstrated."] } }
] };

const browserArchitectureMilestone: Lesson = { id: "browser-architecture-milestone", title: "Milestone: Evolve the Browser Layer from Proven Repetition", activities: [
 { id: "browser-architecture-milestone-001", title: "Extract the Smallest Sustainable Browser Architecture", estimatedMinutes: 150, content: { type: "practical", objective: "Grow the browser layer only after multiple direct flows reveal stable repeated capabilities.", scenario: "The objective is not a page-object framework. It is a small, diagnosable browser architecture that cooperates with the existing API/config/evidence layers.", instructions: ["Add a second related direct browser flow.", "Extract only repeated stable interactions into Page/Component Objects.", "Define and apply the locator policy.", "Use API-assisted setup for unrelated prerequisites.", "Add secure authentication/storage-state handling where justified.", "Integrate failure-only trace/screenshot/console/network diagnostics.", "Audit browser and backend data for parallel hazards before enabling concurrency.", "Classify browser infrastructure as Steward-specific or future tsa-test-core candidate without extracting it yet."], deliverables: ["Second browser flow", "Justified Page/Component Object", "Locator policy", "Authentication/setup strategy", "Diagnostic integration", "Parallel-readiness audit", "Reuse classification"], completionCriteria: ["Page/component abstractions are justified by before/after repetition.", "Business assertions remain visible.", "Storage/credential artifacts are protected.", "BrowserContext and backend data isolation are separately understood.", "tsa-test-core has not yet been extracted."] } }
] };

const playwrightBuild: Lesson = { id: "browser-environment-playwright-build", title: "Build: Add the Browser Layer to steward-tests", activities: [
  { id: "browser-environment-playwright-build-001", title: "Introduce Playwright Java Without Creating a Second Framework", estimatedMinutes: 120, content: { type: "practical", objective: "Add browser automation to the existing Java/JUnit project while reusing only infrastructure that is truly common.", scenario: "steward-tests already has configuration, identity, data and API capabilities. Browser automation should join that architecture rather than inventing parallel configuration and lifecycle systems.", instructions: ["Add Playwright Java through Maven and install the required browser runtime.", "Create explicit browser and BrowserContext ownership with deterministic cleanup.", "Automate one high-value Steward browser smoke flow directly with locators before creating a page object.", "Use the API layer for test-data setup when that is cheaper than UI setup.", "Capture a screenshot/trace on a controlled failure and preserve environment/browser identity."], deliverables: ["Playwright Java dependency", "Browser lifecycle implementation", "Direct-locator smoke test", "Failure diagnostic artifact"], completionCriteria: ["No static global Page or BrowserContext exists.", "API-only assertions remain outside the UI layer.", "Browser resources close after failures.", "The first test works without a speculative page-object hierarchy."] } },
  { id: "browser-environment-playwright-build-002", title: "Extract Page and Component Objects from Proven Repetition", estimatedMinutes: 90, content: { type: "practical", objective: "Introduce UI abstractions only where the first browser flows demonstrate stable repeated behavior.", scenario: "Page/component objects model user-facing capabilities; they must not become a DOM mirror or assertion dumping ground.", instructions: ["Add a second related browser flow.", "Identify repeated stable interactions.", "Extract the smallest page/component object justified by the repetition.", "Prefer accessible locators.", "Keep domain assertions visible in tests."], deliverables: ["Second browser flow", "Small page/component abstraction", "Abstraction decision note"], completionCriteria: ["The abstraction removes demonstrated repetition.", "Assertions remain understandable.", "The object does not expose every DOM element as a field."] } }
] };

export const browserAndEnvironmentTestingDeepLessons: Lesson[] = [browserEngineeringMilestone, playwrightBuild, ...specs.map(rich), browserArchitectureMilestone, lab];
