import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const sreAlerting: LearningResource = { title: "Google SRE Workbook - Alerting on SLOs", url: "https://sre.google/workbook/alerting-on-slos/" };
const promAlerting: LearningResource = { title: "Prometheus Alerting Rules", url: "https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/" };
const alertmanager: LearningResource = { title: "Prometheus Alertmanager", url: "https://prometheus.io/docs/alerting/latest/alertmanager/" };

type Spec = { id: string; title: string; intro: string; principles: string[]; steward: string[]; practice: string[]; reflection: string };

function lessonFrom(spec: Spec): Lesson {
    const blocks: LessonBlock[] = [
        { type: "paragraph", text: spec.intro },
        { type: "heading", id: `${spec.id}-mental-model`, text: "Alerting mental model", level: 2 },
        { type: "list", items: spec.principles },
        { type: "heading", id: `${spec.id}-steward`, text: "Apply it to Steward", level: 2 },
        ...spec.steward.map((text): LessonBlock => ({ type: "paragraph", text })),
        { type: "callout", tone: "steward", title: "Page on symptoms that require action", body: "The purpose of an alert is not to report every abnormal metric. It is to create timely human action when user-visible reliability is at risk and automation alone is insufficient." },
        { type: "resources", title: "Continue learning", resources: [sreAlerting, promAlerting, alertmanager] },
    ];
    return { id: `alerting-and-on-call-${spec.id}`, title: spec.title, activities: [
        { id: `alerting-and-on-call-${spec.id}-001`, title: spec.title, estimatedMinutes: 45, content: { type: "reading", body: spec.intro, blocks } },
        { id: `alerting-and-on-call-${spec.id}-002`, title: `Design: ${spec.title}`, estimatedMinutes: 55, content: { type: "practical", objective: `Apply ${spec.title} to Steward operations.`, scenario: "Use the SLOs, error-budget model, Prometheus metrics and diagnostic logs already created. Design alerts around meaningful service symptoms, ownership and response actions rather than around every available metric.", instructions: spec.practice, deliverables: ["Alert/on-call design artifact", "Trigger or routing evidence", "Operational action/risk note"], completionCriteria: ["The alert corresponds to a real action or escalation.", "Severity is tied to impact and urgency.", "The learner can explain why the condition should alert, page or remain dashboard-only."] } },
        { id: `alerting-and-on-call-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.reflection, minimumCharacters: 200 } },
    ] };
}

const specs: Spec[] = [
    { id: "symptoms-vs-causes", title: "Symptoms vs Causes", intro: "Users experience symptoms such as failed or slow requests; operators investigate causes such as CPU pressure, database contention or dependency failure. Paging directly on low-level causes often produces noise and misses the real reliability objective.", principles: ["Page primarily on user-visible symptoms or imminent SLO risk.", "Use cause-oriented signals to diagnose after detection.", "Avoid assuming one resource metric uniquely identifies service impact.", "Correlate symptoms and causes across the same time window."], steward: ["A high database connection count may be worth investigation, but failed Steward requests or rapid error-budget burn are stronger paging signals.", "Nexus disk pressure may be an early warning while package-download failures are the consumer-visible symptom."], practice: ["Choose three Steward metrics and classify them as symptom, cause or contextual signal.", "Pick one cause-based alert candidate and redesign it around service impact.", "Document the cause metrics that should remain available for diagnosis.", "Define when an early-warning cause signal is still justified."], reflection: "Why is paging on high CPU usually weaker than paging on a sustained user-visible failure rate?" },
    { id: "actionable-alerts", title: "Actionable Alerts", intro: "An actionable alert gives a responder enough context to decide what to do next. If no reasonable action exists, the signal may belong in a dashboard, report or capacity review instead of the paging path.", principles: ["Every alert needs a clear owner and expected response.", "Include service, symptom, severity and investigation context.", "Link to the runbook or diagnostic view.", "Prefer fewer trustworthy alerts over many informational notifications."], steward: ["A Steward alert should point to relevant Grafana views, logs and a runbook instead of only saying that a threshold was crossed.", "Alerts for the artifact platform should explain consumer impact and whether CI/deployment workflows are affected."], practice: ["Draft one Steward alert message.", "Add the first diagnostic link/action and owner.", "State what the responder should verify within the first few minutes.", "Decide whether the condition truly deserves notification or paging."], reflection: "What makes an alert operationally actionable rather than merely informative?" },
    { id: "alert-fatigue", title: "Alert Fatigue", intro: "Alert fatigue occurs when responders receive enough noisy, duplicate or low-value notifications that they stop trusting the alerting system. Reliability then degrades because real incidents compete with background noise.", principles: ["Delete or downgrade alerts that repeatedly require no action.", "Deduplicate related conditions and suppress expected cascades.", "Tune thresholds and duration using evidence from real behavior.", "Review alert quality after incidents and false positives."], steward: ["If Steward creates separate pages for API errors, database pressure and downstream timeouts during one dependency outage, the responder may receive three descriptions of the same incident.", "Alert quality should be measured through usefulness, false-positive behavior and operator response—not alert count."], practice: ["Review a hypothetical set of Steward alerts during one failure.", "Identify duplicates and non-actionable pages.", "Propose grouping, inhibition or downgrade rules.", "Define one metric for tracking alert quality over time."], reflection: "Why can adding more alerts make a service less operationally reliable?" },
    { id: "severity", title: "Severity", intro: "Severity expresses the impact and urgency of an incident condition. It should drive response expectations consistently rather than reflect how technically interesting the underlying failure appears.", principles: ["Base severity on user/business impact and urgency.", "Keep severity definitions stable and understandable.", "Avoid making every production issue critical.", "Allow severity to change as evidence about impact changes."], steward: ["Complete inability to authenticate or use the core Steward API may justify a higher severity than one failed background metric scrape.", "A Nexus outage during an active release may have higher operational urgency than the same outage during a quiet period, depending on established service expectations."], practice: ["Define a simple Steward severity matrix.", "Classify four example conditions.", "Explain one case where technical failure looks dramatic but severity should remain low.", "Define an escalation expectation for each severity."], reflection: "Why should incident severity represent impact rather than the complexity of the technical root cause?" },
    { id: "escalation", title: "Escalation", intro: "Escalation moves an incident to people or teams with the authority, context or access needed to make progress. Good escalation paths reduce stalled incidents and prevent the first responder from becoming a single point of failure.", principles: ["Escalate based on need for expertise, authority or time-bound response.", "Define fallback paths when the primary owner is unavailable.", "Transfer context, not just the alert title.", "Avoid escalation loops without decision ownership."], steward: ["A responder may identify Nexus or database failure but require a different owner to repair the dependency. The escalation package should include impact, timeline, evidence and actions already attempted.", "Even a learner-operated environment should model realistic ownership boundaries so on-call work does not become heroic guesswork."], practice: ["Create escalation paths for Steward API, database and Nexus issues.", "Define what evidence must accompany escalation.", "Add a time/impact trigger for escalating one unresolved condition.", "Identify one access or ownership gap that would block escalation today."], reflection: "What information should accompany an escalation so the next responder does not restart the investigation from zero?" },
    { id: "alert-routing", title: "Alert Routing Concepts", intro: "Routing maps alert labels and ownership information to the correct notification channel, schedule or responder. Reliable routing depends on stable metadata and deliberate grouping rather than hard-coding every condition independently.", principles: ["Route by service, team, severity and environment where meaningful.", "Group related notifications to reduce duplicate noise.", "Use inhibition or suppression when one parent failure explains downstream symptoms.", "Test routing like any other operational configuration."], steward: ["Prometheus rules can produce labeled alerts and Alertmanager-style routing can group or direct them by Steward component and severity.", "The learner should understand the conceptual pipeline even if the lab uses a simplified local notification target."], practice: ["Define labels needed to route Steward alerts.", "Sketch a routing tree for API, database and Nexus conditions.", "Create one grouping or inhibition example.", "Design a safe test proving the alert reaches the expected route."], reflection: "Why should alert-routing configuration be tested rather than trusted because its YAML parses successfully?" },
    { id: "runbooks", title: "Runbooks", intro: "A runbook captures the repeatable first actions for diagnosing and mitigating known operational conditions. It should accelerate judgment, not replace it with a brittle list of commands.", principles: ["Start with impact verification and safety checks.", "Link to dashboards, logs and commands that answer specific questions.", "Include mitigation and rollback/recovery paths.", "State when to stop and escalate."], steward: ["A Steward high-error-rate runbook can guide the responder from SLO symptom to deployment, database and dependency evidence without assuming the root cause.", "Nexus runbooks should include consumer checks and storage/dependency context, not only process restart commands."], practice: ["Write a runbook for one Steward alert.", "Include first-five-minute checks, likely evidence sources and safe mitigations.", "Add stop/escalation conditions.", "Dry-run the runbook against a controlled scenario and revise ambiguous steps."], reflection: "Why should a runbook begin by validating impact instead of immediately restarting the suspected component?" },
    { id: "handover", title: "On-call Handover and Context", intro: "On-call handover preserves operational context across responders and shifts. A handover should surface active incidents, degraded dependencies, risky changes and temporary exceptions so the next responder does not discover them through an alert.", principles: ["Transfer active risk and unfinished investigation explicitly.", "Include recent changes and known degraded states.", "Keep temporary suppressions and maintenance conditions visible.", "Separate current operational facts from historical noise."], steward: ["A Steward handover can mention current SLO burn, a partially degraded Nexus state, a pending database capacity risk or an alert temporarily muted during controlled work.", "The discipline matters even in a solo learning environment because it creates the artifacts expected in team operations."], practice: ["Create a short Steward handover template.", "Populate it from a simulated degraded environment.", "Include active alerts, recent changes, risk and next action.", "Remove historical details that do not affect the next responder."], reflection: "What information belongs in on-call handover even when no formal incident is currently open?" },
];

const lab: Lesson = { id: "alerting-and-on-call-steward-alerts-runbooks", title: "Lab: Build Steward Alerts and Runbooks", activities: [
    { id: "alerting-and-on-call-steward-alerts-runbooks-001", title: "Design the Steward Paging Policy", estimatedMinutes: 90, content: { type: "practical", objective: "Translate Steward SLOs and operational risks into a minimal alert policy.", scenario: "Start from existing SLIs/SLOs, Prometheus metrics and the reliability risk register. Decide which conditions need immediate human action and which belong elsewhere.", instructions: ["Select representative user-visible and dependency risks.", "Define alert condition, evaluation window, severity, owner and expected action.", "Include at least one SLO/error-budget-based condition.", "Classify lower-urgency signals as ticket/report/dashboard-only where appropriate.", "Document expected false-positive and missed-detection risks."], deliverables: ["Steward paging policy", "Alert specification table", "Severity/routing model"], completionCriteria: ["Every page has a clear reason and response.", "SLO context influences at least one trigger.", "Not every abnormal metric becomes an alert." ] } },
    { id: "alerting-and-on-call-steward-alerts-runbooks-002", title: "Implement and Test Alerts", estimatedMinutes: 120, content: { type: "practical", objective: "Implement representative Steward alert rules and prove they trigger and recover correctly.", scenario: "Use Prometheus-compatible rules and the available notification/routing mechanism. Trigger conditions only in controlled learner-owned environments.", instructions: ["Implement at least two alert rules with meaningful labels and annotations.", "Configure grouping/routing appropriate to the environment.", "Generate a controlled failure or synthetic condition.", "Capture pending/firing/resolved behavior and notification evidence.", "Tune thresholds/duration if evidence reveals noise or instability."], deliverables: ["Alert rules", "Routing configuration", "Firing/resolution evidence", "Tuning notes"], completionCriteria: ["Rules trigger on known behavior and resolve after recovery.", "Notifications contain actionable context.", "The learner verifies routing rather than assuming configuration works." ] } },
    { id: "alerting-and-on-call-steward-alerts-runbooks-003", title: "Build and Exercise Runbooks", estimatedMinutes: 105, content: { type: "practical", objective: "Make Steward alerts operable by pairing them with concise diagnostic and mitigation guidance.", scenario: "Treat the runbook as an interface between observability and human response. It should use the Grafana, Prometheus and logging paths already built.", instructions: ["Write a runbook for each implemented page-worthy alert.", "Include impact verification, diagnostic views/queries, likely dependency checks and safe mitigations.", "Define escalation and stop conditions.", "Dry-run one runbook against the controlled failure used for alert testing.", "Record where the runbook lacked evidence or sent the responder down an unhelpful path and revise it."], deliverables: ["Steward alert runbooks", "Runbook exercise evidence", "Revision notes", "On-call handover template"], completionCriteria: ["Runbooks accelerate diagnosis without presuming root cause.", "Escalation boundaries are explicit.", "A controlled exercise validates at least one runbook end to end." ] } },
] };

export const alertingAndOnCallDeepLessons: Lesson[] = [...specs.map(lessonFrom), lab];
