import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const sreBook: LearningResource = { title: "Google Site Reliability Engineering", url: "https://sre.google/sre-book/table-of-contents/" };
const sreWorkbook: LearningResource = { title: "Google SRE Workbook", url: "https://sre.google/workbook/table-of-contents/" };
const awsReliability: LearningResource = { title: "AWS Well-Architected Reliability Pillar", url: "https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/welcome.html" };

type Spec = { id: string; title: string; intro: string; principles: string[]; steward: string[]; practice: string[]; reflection: string };

function blocksFor(spec: Spec): LessonBlock[] {
    return [
        { type: "paragraph", text: spec.intro },
        { type: "heading", id: `${spec.id}-mental-model`, text: "Reliability mental model", level: 2 },
        { type: "list", items: spec.principles },
        { type: "heading", id: `${spec.id}-steward`, text: "Apply it to Steward", level: 2 },
        ...spec.steward.map((text): LessonBlock => ({ type: "paragraph", text })),
        { type: "callout", tone: "steward", title: "Operational evidence", body: "Reliability is a property experienced over time. A design diagram or successful deployment is not enough: Steward must produce evidence about failure, recovery and user-visible behavior under real operating conditions." },
        { type: "resources", title: "Continue learning", resources: [sreBook, sreWorkbook, awsReliability] },
    ];
}

function lessonFrom(spec: Spec): Lesson {
    return { id: `reliability-and-sre-${spec.id}`, title: spec.title, activities: [
        { id: `reliability-and-sre-${spec.id}-001`, title: spec.title, estimatedMinutes: 50, content: { type: "reading", body: spec.intro, blocks: blocksFor(spec) } },
        { id: `reliability-and-sre-${spec.id}-002`, title: `Analyze: ${spec.title}`, estimatedMinutes: 55, content: { type: "practical", objective: `Apply ${spec.title} to the operated Steward ecosystem.`, scenario: "Treat Steward as a service with users and dependencies rather than a project that merely builds successfully. Start with a reliability question or failure hypothesis and use current architecture and operational evidence.", instructions: spec.practice, deliverables: ["Steward reliability analysis", "Evidence or measurement plan", "Improvement or risk note"], completionCriteria: ["The analysis connects technical behavior to service/user impact.", "Assumptions and missing evidence are explicit.", "The learner identifies an operational decision or next measurement rather than only describing terminology."] } },
        { id: `reliability-and-sre-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.reflection, minimumCharacters: 200 } },
    ] };
}

const specs: Spec[] = [
    { id: "reliability-quality-attribute", title: "Reliability as a Quality Attribute", intro: "Reliability is the ability of a system to deliver its intended service over time under expected and unexpected conditions. It includes prevention of failure, tolerance of failure and recovery when failure inevitably occurs.", principles: ["Define reliability from the user's/service perspective.", "Distinguish component health from successful service delivery.", "Expect failure and design recovery as a normal capability.", "Measure reliability over meaningful periods rather than from isolated successful tests."], steward: ["Steward can have healthy processes while users cannot authenticate, resolve dependencies or persist data. Reliability therefore crosses the API, PostgreSQL, network, delivery path and internal artifact platform.", "The Security Steward residual-risk register is useful input because some security controls and failure modes directly affect availability and recovery."], practice: ["Identify Steward's primary user-visible capabilities.", "For each capability, list dependencies whose failure can prevent success.", "Define what degraded, unavailable and recovered would mean.", "Choose one capability whose reliability is currently assumed rather than measured."], reflection: "Why is 'the server is up' an inadequate definition of Steward reliability?" },
    { id: "availability", title: "Availability", intro: "Availability describes whether a service is usable when needed. The meaningful unit is usually a successful user interaction or service capability, not merely whether a machine responds to a health check.", principles: ["Define what counts as available before calculating a percentage.", "Measure at a boundary meaningful to users.", "Understand that small percentage differences represent substantial downtime at scale.", "Account for planned and unplanned behavior according to the service objective."], steward: ["A Steward API process may answer `/health` while database-backed requests fail. A Nexus host may respond while package downloads are broken. Availability indicators must therefore test useful service behavior.", "Later SLI/SLO work will formalize targets; here the learner establishes what availability means operationally."], practice: ["Choose one Steward capability and define a binary success criterion for an availability event.", "List false-positive health checks that could report healthy while the capability is unusable.", "Propose a better availability measurement point.", "Estimate how different availability targets change allowable downtime."], reflection: "What should Steward count as available if its API responds but every database-backed operation fails?" },
    { id: "failure-recovery", title: "Failure and Recovery", intro: "Reliable systems are not systems that never fail. They limit failure impact, detect degradation and restore useful service within acceptable time. Recovery therefore deserves the same design attention as normal operation.", principles: ["Separate fault, failure and user-visible impact.", "Define detection and recovery paths before incidents.", "Prefer recovery procedures that can be exercised safely.", "Measure recovery rather than assuming restart or failover works."], steward: ["Steward can fail through application crashes, database loss, exhausted resources, broken internal dependencies, expired certificates or failed deployments.", "Each failure path may require a different recovery mechanism and evidence. Later disaster-recovery and fault-injection modules will test these mechanisms directly."], practice: ["Select three plausible Steward faults and trace how each becomes user-visible failure.", "For each, identify detection, containment and recovery mechanisms.", "Find one recovery step that has never been tested.", "Define the evidence a controlled exercise would need to prove recovery."], reflection: "Why is having a restart command in a runbook not proof that Steward can recover reliably?" },
    { id: "sre-principles", title: "SRE Principles", intro: "Site Reliability Engineering applies software-engineering methods to operations. It makes reliability measurable, treats operational work as an engineering problem and balances service reliability with the need to continue changing the system.", principles: ["Use service objectives to make reliability concrete.", "Automate repetitive operational work when automation reduces risk and toil.", "Engineer for failure and recovery rather than relying on heroics.", "Use evidence and error budgets to negotiate reliability versus delivery."], steward: ["Steward's existing CI/CD, testing, security and infrastructure work becomes the substrate for SRE: the learner now asks how those systems behave continuously and how operators know when intervention is needed.", "Prometheus, Grafana and OpenTelemetry will be introduced later as tools serving operational questions, not as the definition of SRE."], practice: ["Identify three current Steward operational activities.", "Classify each as engineering work, useful operational work or likely toil.", "Choose one recurring problem that software or automation could reduce.", "State the reliability outcome the automation should improve."], reflection: "Why does installing Prometheus and Grafana not by itself mean a team is practicing SRE?" },
    { id: "toil", title: "Toil", intro: "Toil is repetitive, manual, automatable operational work that scales with service growth and produces limited enduring value. Not every manual task is toil; diagnosis, learning and one-off engineering work can be highly valuable.", principles: ["Look for repetitive and automatable work tied to service operation.", "Measure toil before automating blindly.", "Automate the cause where possible rather than scripting symptoms forever.", "Keep humans in loops that require judgment or carry meaningful risk."], steward: ["Repeatedly restarting Steward after the same known failure, manually checking Nexus disk usage or copying identical deployment evidence can become toil if the pattern persists.", "A first manual restore drill is learning, not toil. Repeating the same deterministic recovery steps every week may become an automation candidate."], practice: ["Create a small inventory of Steward operational tasks.", "Score frequency, manual effort, growth tendency and judgment required.", "Choose one credible toil candidate.", "Propose whether to automate, eliminate, redesign or intentionally keep it manual."], reflection: "Give an example of a manual Steward task that should not yet be automated and explain why." },
    { id: "risk-tradeoffs", title: "Reliability and Risk Trade-offs", intro: "More reliability is not free. Redundancy, stronger recovery, stricter release controls and additional observability consume money and engineering time. Reliability engineering chooses where that investment produces justified value.", principles: ["Reliability targets should reflect user and business consequences.", "Every control has cost, complexity and possible new failure modes.", "Avoid maximizing uptime without considering change velocity and system importance.", "Make accepted reliability risk explicit."], steward: ["Running five database replicas for a learner Steward environment may add complexity without proportional value, while testing backups may reduce a much more realistic risk.", "The internal artifact repository may deserve stronger recovery because CI, deployment and test pipelines can all depend on it."], practice: ["Choose two Steward reliability risks with different impact profiles.", "Propose a high-cost and low-cost mitigation for each.", "Compare expected benefit, complexity and operational burden.", "Recommend an investment level and state the risk deliberately left open."], reflection: "Why can adding redundancy make a small system less reliable if the team cannot operate the added complexity?" },
    { id: "reliability-ownership", title: "Reliability Ownership", intro: "Reliability is shared across design, development, delivery and operations. Ownership means knowing who responds, who improves systemic causes and which team or component owns each service dependency and objective.", principles: ["Assign ownership to services and dependencies, not only incidents.", "Separate immediate incident responsibility from long-term corrective-action ownership.", "Make escalation and decision boundaries explicit.", "Avoid treating reliability as the operations team's problem after development is finished."], steward: ["Steward's API, database, infrastructure, Nexus/artifact platform and CI pipeline have different responsibilities even in a one-person learning environment. Modeling ownership now prepares the system for realistic team operation.", "A dependency without an owner, recovery expectation or escalation path is an operational risk even when it is currently healthy."], practice: ["Create an ownership map for Steward services and critical dependencies.", "Assign incident-response and corrective-action responsibilities conceptually.", "Identify one dependency whose ownership is ambiguous.", "Define what information an on-call engineer would need to escalate it effectively."], reflection: "Why should the engineer who mitigates an incident not automatically become the permanent owner of every corrective action?" },
];

const lab: Lesson = { id: "reliability-and-sre-risk-map", title: "Lab: Build the Steward Reliability Risk Map", activities: [
    { id: "reliability-and-sre-risk-map-001", title: "Map Critical Service Capabilities", estimatedMinutes: 75, content: { type: "practical", objective: "Model Steward as an operated service and identify the capabilities whose failure matters.", scenario: "Start from current Steward architecture and the evidence produced by previous schools.", instructions: ["List user-visible and delivery-critical capabilities.", "Map each capability to application, data, network, CI/CD, Nexus and external dependencies.", "Define available, degraded and unavailable states.", "Record current owners and known recovery mechanisms."], deliverables: ["Service capability map", "Dependency map", "Availability-state definitions"], completionCriteria: ["Capabilities are expressed in service/user terms.", "Critical internal platform dependencies are visible.", "Recovery assumptions are identifiable." ] } },
    { id: "reliability-and-sre-risk-map-002", title: "Prioritize Failure and Recovery Risks", estimatedMinutes: 90, content: { type: "practical", objective: "Create a risk-driven reliability backlog for Steward.", scenario: "Use impact, likelihood/exposure, detectability and recovery confidence rather than choosing work because a monitoring tool makes it easy.", instructions: ["Identify representative failure modes for each critical capability.", "Score user impact and current detection/recovery confidence.", "Identify single points of failure and untested recovery assumptions.", "Prioritize the five most important reliability risks.", "For each, define the next evidence needed: telemetry, experiment, restore test, capacity baseline or engineering change."], deliverables: ["Steward reliability risk register", "Top-five reliability risks", "Evidence/measurement backlog"], completionCriteria: ["Priorities are justified by service impact.", "Unknowns are not presented as verified resilience.", "Each top risk has a concrete next evidence step." ] } },
    { id: "reliability-and-sre-risk-map-003", title: "Define the Reliability Engineering Agenda", estimatedMinutes: 60, content: { type: "practical", objective: "Turn the risk map into the operating questions that will drive the rest of Reliability Engineer.", scenario: "The next modules will add observability, logging, metrics, SLOs, alerting, capacity, resilience, recovery, incident management and fault experiments. Decide what those capabilities need to prove for Steward.", instructions: ["Write 5–8 concrete operational questions about Steward.", "Map each question to the later Reliability Engineer module most likely to answer it.", "Identify likely toil or ownership gaps exposed by the risk map.", "Record reliability tradeoffs that should be revisited after measurement."], deliverables: ["Operational question set", "Reliability learning/engineering agenda", "Toil and ownership notes"], completionCriteria: ["Questions are answerable with evidence rather than dashboard aesthetics.", "The agenda follows current Steward risks.", "The output can directly feed Observability." ] } },
] };

export const reliabilityAndSreDeepLessons: Lesson[] = [...specs.map(lessonFrom), lab];
