import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const sre: LearningResource = { title: "Google SRE: Addressing Cascading Failures", url: "https://sre.google/sre-book/addressing-cascading-failures/" };
const aws: LearningResource = { title: "AWS Builders' Library: Timeouts, Retries and Backoff with Jitter", url: "https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/" };
const azure: LearningResource = { title: "Azure Architecture Center: Reliability Patterns", url: "https://learn.microsoft.com/azure/architecture/framework/resiliency/reliability-patterns" };

type Spec = { id: string; title: string; intro: string; principles: string[]; steward: string[]; practice: string[]; reflection: string };

function lessonFrom(spec: Spec): Lesson {
    const blocks: LessonBlock[] = [
        { type: "paragraph", text: spec.intro },
        { type: "heading", id: `${spec.id}-principles`, text: "Failure model", level: 2 },
        { type: "list", items: spec.principles },
        { type: "heading", id: `${spec.id}-steward`, text: "Apply it to Steward", level: 2 },
        ...spec.steward.map((text): LessonBlock => ({ type: "paragraph", text })),
        { type: "callout", tone: "steward", title: "Resilience is bounded failure", body: "The goal is not to pretend dependencies never fail. Design Steward so a dependency can be slow, unavailable or partially successful without turning one failure into duplicate work, resource exhaustion or ecosystem-wide collapse." },
        { type: "resources", title: "Continue learning", resources: [sre, aws, azure] },
    ];
    return { id: `resilience-distributed-failure-${spec.id}`, title: spec.title, activities: [
        { id: `resilience-distributed-failure-${spec.id}-001`, title: spec.title, estimatedMinutes: 50, content: { type: "reading", body: spec.intro, blocks } },
        { id: `resilience-distributed-failure-${spec.id}-002`, title: `Harden: ${spec.title}`, estimatedMinutes: 60, content: { type: "practical", objective: `Apply ${spec.title} to a Steward dependency path.`, scenario: "Use Steward's measured latency/capacity baselines and existing telemetry. Model one dependency failure before changing code, then verify whether the control bounds latency, work amplification and user impact.", instructions: spec.practice, deliverables: ["Failure-path model", "Resilience-control evidence", "Telemetry and trade-off note"], completionCriteria: ["The failure mode is explicit.", "The control has a bounded behavior rather than an infinite or arbitrary policy.", "Normal, failure and recovery behavior are observable." ] } },
        { id: `resilience-distributed-failure-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.reflection, minimumCharacters: 200 } },
    ] };
}

const specs: Spec[] = [
    { id: "timeouts", title: "Timeouts", intro: "A remote call can fail by returning an error, but it can also fail by never completing within a useful time. Timeouts bound how long a caller is willing to consume resources and wait for a dependency before choosing another outcome.", principles: ["Set timeouts from measured latency and user/service budgets, not folklore.", "Distinguish connection, request and end-to-end deadlines where the stack supports them.", "A timeout does not cancel work automatically in every downstream system.", "Timeouts that are too short create false failures; unbounded waits create resource exhaustion."], steward: ["Steward calls to databases, identity services or other dependencies must fit inside the user-facing latency budget.", "A timeout should produce observable context so operators can distinguish slow dependency behavior from application failure."], practice: ["Choose one Steward dependency call and map its latency budget.", "Define a timeout with evidence from the performance baseline.", "Simulate a slow dependency and observe caller behavior.", "Verify recovery and record whether downstream work continues after the caller gives up."], reflection: "Why is adding a five-second timeout everywhere not a defensible resilience policy?" },
    { id: "retries", title: "Retries", intro: "Retries can turn transient failures into successful operations, but every retry is additional load and may repeat side effects. A retry policy is therefore a controlled risk decision, not a universal error-handling technique.", principles: ["Retry only failures likely to be transient.", "Bound attempts and total elapsed time.", "Consider idempotency before retrying state-changing operations.", "Instrument attempts separately from logical operations so amplification is visible."], steward: ["A transient read failure may be retryable while a create/update operation can duplicate work unless its semantics are protected.", "Retries must consume the same end-to-end latency/error budget as the original attempt."], practice: ["Classify representative Steward failures as retryable or non-retryable.", "Define maximum attempts and total retry budget for one safe path.", "Generate a transient failure and compare logical requests with dependency attempts.", "Verify permanent failures stop rather than retry forever."], reflection: "How can retries reduce visible errors while simultaneously making a dependency outage worse?" },
    { id: "backoff-jitter", title: "Exponential Backoff and Jitter", intro: "When many clients retry together, immediate or synchronized retries can create repeated traffic spikes. Backoff spaces attempts over time; jitter randomizes them so clients do not repeatedly synchronize.", principles: ["Increase delay between repeated attempts rather than retrying in a tight loop.", "Add randomness to reduce synchronized retry waves.", "Cap backoff and total retry duration.", "Measure retry volume because a quiet user-facing error rate can hide amplified dependency traffic."], steward: ["If multiple Steward instances lose the same dependency, identical retry timing can create a thundering herd when it begins recovering.", "Jitter improves system behavior by spreading retry demand, not by making the dependency itself healthier."], practice: ["Model retry timing for several concurrent Steward callers.", "Compare immediate, exponential and jittered retry schedules.", "Implement or configure bounded jittered backoff on an appropriate path.", "Observe attempt distribution during a controlled dependency failure/recovery."], reflection: "What failure pattern does jitter address that exponential backoff by itself may not eliminate?" },
    { id: "circuit-breakers", title: "Circuit Breakers", intro: "A circuit breaker stops repeatedly calling a dependency that is already failing, then cautiously probes for recovery. It can protect resources and reduce useless work, but it introduces state and must be tuned to real failure behavior.", principles: ["Closed permits calls; open fails fast; half-open probes recovery.", "Trip criteria should reflect meaningful failure, not one arbitrary error.", "Fail-fast behavior must map to a defined user/service outcome.", "Observe breaker state transitions and rejected calls."], steward: ["A failing non-critical dependency may justify a breaker plus degraded behavior; a critical database path may instead require clear failure rather than fabricated success.", "Breaker configuration should be evaluated alongside timeouts and retries because the controls interact."], practice: ["Choose a Steward dependency where a breaker is justified or explain why not.", "Define trip, open-duration and recovery-probe behavior.", "Simulate repeated failure and verify calls become bounded.", "Restore the dependency and verify controlled recovery."], reflection: "Why is a circuit breaker not simply a more sophisticated retry mechanism?" },
    { id: "idempotency", title: "Idempotency", intro: "Distributed systems often cannot know whether a timed-out request failed before or after a side effect occurred. Idempotency lets repeated delivery of the same logical operation converge on one intended effect instead of duplicating it.", principles: ["Separate request attempts from logical operation identity.", "Use stable idempotency keys or naturally idempotent state transitions where appropriate.", "Persist enough outcome information to recognize repeats.", "Define retention and scope for idempotency records."], steward: ["If a Steward write succeeds in the database but the response is lost, a blind retry must not create duplicate registrations or relationships.", "Idempotency is especially important when retrying across network boundaries or asynchronous delivery."], practice: ["Select one state-changing Steward operation.", "Describe the ambiguous-outcome scenario after a timeout.", "Design an idempotency strategy and expected repeated-response behavior.", "Test two attempts with the same logical operation identity."], reflection: "Why can a timeout make the caller uncertain even when the server completed the requested change successfully?" },
    { id: "partial-failure", title: "Partial Failure", intro: "In a distributed workflow, one component can succeed while another fails. Treating the whole system as simply up or down hides ambiguous state, compensation needs and user-visible inconsistency.", principles: ["Model each externally visible side effect and its commit point.", "Do not assume cross-service atomicity.", "Expose pending, failed or compensating states when they are real business states.", "Design reconciliation for outcomes that cannot be resolved synchronously."], steward: ["A Steward operation that writes local state and then publishes or calls another service can finish only part of its intended workflow.", "The API must not report a clean success if required downstream state is unknown."], practice: ["Map a multi-step Steward operation.", "Inject failure after one side effect succeeds.", "Document resulting state and what the user sees.", "Design retry, compensation or reconciliation behavior and verify it is observable."], reflection: "Why is returning HTTP 500 insufficient as a design for a workflow in which one side effect has already committed?" },
    { id: "dependency-failure", title: "Dependency Failure", intro: "Dependencies fail in different ways: fast errors, latency, stale responses, throttling, connection loss and partial availability. Resilience begins by modeling these modes instead of using one generic 'dependency down' scenario.", principles: ["Inventory critical dependencies and failure modes.", "Distinguish hard failure from degradation and incorrect responses.", "Define which capabilities depend on each dependency.", "Use telemetry to attribute impact without requiring perfect certainty."], steward: ["PostgreSQL, identity, Nexus and delivery infrastructure have different consumer paths and therefore different resilience options.", "Nexus unavailability may not break a running Steward API, but it can block builds, tests, rollbacks or deployments."], practice: ["Choose one runtime and one delivery dependency.", "Enumerate at least three failure modes for each.", "Map affected Steward capabilities and existing detection.", "Prioritize one missing resilience control based on impact and likelihood."], reflection: "Why should Nexus failure be included in Steward reliability even if currently running API instances continue serving traffic?" },
    { id: "cascading-failure", title: "Cascading Failure", intro: "A local failure becomes a cascading failure when it increases pressure on other components until they also degrade. Queues, retries, blocked threads, connection pools and autoscaling can all amplify the original fault.", principles: ["Look for positive feedback loops during degradation.", "Bound concurrency, waiting and retry work.", "Protect healthy dependencies from traffic created by failing paths.", "Prefer shedding work to allowing the entire service to collapse."], steward: ["A slow PostgreSQL query can hold connections, grow request concurrency, trigger retries and eventually make unrelated endpoints slow.", "Performance baselines help identify the resource boundary at which amplification begins."], practice: ["Draw a causal chain from one Steward dependency slowdown to ecosystem impact.", "Identify amplification points such as retries, queues or pools.", "Choose one bounding control.", "Verify with telemetry that the control limits spread during a controlled scenario."], reflection: "What turns an isolated dependency slowdown into a system-wide cascading failure?" },
    { id: "queues-backpressure", title: "Queues and Backpressure", intro: "Queues decouple producers and consumers, but they do not create infinite capacity. Backpressure communicates or enforces that downstream work cannot safely accept demand at the current rate.", principles: ["Treat queue depth and age as operational signals.", "Bound queues so overload becomes explicit.", "Define producer behavior when capacity is exhausted.", "Consider priority, fairness and dead-letter/reconciliation behavior where relevant."], steward: ["If Steward later processes asynchronous events or background jobs, an unbounded queue can convert overload into delayed failure and memory/storage pressure.", "Backpressure may mean rejecting, delaying or rate-limiting work rather than silently accepting more than can be processed."], practice: ["Model a producer/consumer Steward workflow.", "Define sustainable service rate and overload behavior.", "Choose bounded queue/backpressure semantics.", "Describe metrics that reveal growing delay before outright failure."], reflection: "Why can an unbounded queue make a service look healthy temporarily while actually making reliability worse?" },
    { id: "graceful-degradation", title: "Graceful Degradation", intro: "Graceful degradation preserves a smaller truthful capability when a non-essential dependency fails. It is not returning fake success; it is an explicit product decision about what remains safe and useful.", principles: ["Classify capabilities as essential, optional or safely stale/read-only.", "Make degraded state visible to users and operators.", "Never bypass security or integrity controls to preserve availability.", "Test return to full service as carefully as entry into degradation."], steward: ["Steward might continue read-only discovery when a secondary enrichment service fails, but should not accept writes whose integrity cannot be guaranteed.", "Security Steward controls remain non-negotiable during degraded operation."], practice: ["Choose a Steward dependency failure and classify affected capabilities.", "Define truthful degraded behavior.", "Verify telemetry and user/API response make degradation visible.", "Restore the dependency and test recovery without inconsistent state."], reflection: "What distinguishes graceful degradation from hiding a failure behind a misleading success response?" },
    { id: "retry-storms", title: "Retry Storms and Amplification", intro: "Retries across multiple layers can multiply one user request into many downstream attempts. If clients, proxies and services all retry independently, the effective load during an outage can far exceed normal traffic.", principles: ["Count attempts at each layer, not only top-level requests.", "Assign retry responsibility deliberately.", "Use budgets so nested retries cannot multiply without bound.", "Combine backoff, jitter, concurrency limits and fail-fast behavior as appropriate."], steward: ["A client retrying Steward while Steward retries PostgreSQL or another API can create multiplicative work.", "Dashboards should make logical request rate and dependency attempt rate separately visible."], practice: ["Model a two-layer retry policy for Steward.", "Calculate worst-case downstream attempts for one logical request.", "Remove or bound duplicate retry responsibility.", "Verify telemetry exposes amplification ratio during failure."], reflection: "If a client retries three times and Steward also performs three attempts per call, why is the downstream load not merely three attempts?" },
    { id: "dependency-budgets", title: "Dependency Availability Budgets", intro: "A service cannot promise reliability independently of the systems it requires. Dependency availability and latency consume part of the service's reliability budget, especially when there is no fallback or redundancy.", principles: ["Map SLI-critical paths to required dependencies.", "Do not assume a downstream SLA automatically becomes your achievable SLO.", "Account for serial dependencies and correlated failures.", "Use architecture, caching, degradation or redundancy only where the reliability value justifies complexity."], steward: ["Steward's user-facing SLOs must be reconciled with PostgreSQL and identity dependencies, while delivery reliability has separate dependence on Nexus and CI infrastructure.", "This creates an architectural input for later schools: some reliability targets may be impossible without changing dependency design."], practice: ["Take one Steward SLI and map its required dependency chain.", "Compare the target with known/assumed dependency reliability.", "Identify where no remaining error-budget margin exists.", "Propose one architectural or product trade-off rather than simply raising every dependency target."], reflection: "Why can a 99.9% dependency make a 99.99% end-to-end target unrealistic when Steward has no alternative path?" },
];

const lab: Lesson = { id: "resilience-distributed-failure-harden-steward", title: "Lab: Harden Steward Against Dependency Failure", activities: [
    { id: "resilience-distributed-failure-harden-steward-001", title: "Select and Model a Failure Path", estimatedMinutes: 90, content: { type: "practical", objective: "Turn a high-priority Steward dependency risk into an explicit failure model.", scenario: "Choose a runtime dependency path from the Reliability Risk Map and performance evidence. The goal is to understand the failure before stacking resilience patterns onto it.", instructions: ["Map caller, dependency, latency budget, side effects and existing retry/timeout behavior.", "Define at least fast-failure, slow-failure and ambiguous-outcome scenarios.", "Identify amplification and cascading-failure risks.", "Choose the smallest justified control set: timeout, retry/backoff, breaker, idempotency, backpressure or degradation."], deliverables: ["Dependency failure map", "Failure hypotheses", "Control design with trade-offs"], completionCriteria: ["Controls map to explicit failure modes.", "Retry and latency budgets are bounded.", "Integrity/security constraints remain explicit." ] } },
    { id: "resilience-distributed-failure-harden-steward-002", title: "Implement and Exercise the Controls", estimatedMinutes: 150, content: { type: "practical", objective: "Prove that the selected resilience controls bound failure rather than merely changing error messages.", scenario: "Implement the justified controls in learner-owned Steward infrastructure and exercise them under controlled dependency failure.", instructions: ["Capture normal baseline behavior first.", "Introduce controlled latency, transient failure and/or unavailability within a safe environment.", "Measure user latency/errors, dependency attempts, queue/concurrency/resource pressure and relevant breaker/retry state.", "Verify ambiguous state or repeated writes cannot create unintended duplicate effects.", "Restore the dependency and observe recovery to steady state."], deliverables: ["Implementation/configuration evidence", "Failure telemetry", "Integrity/idempotency evidence where applicable", "Recovery evidence"], completionCriteria: ["The experiment has bounded blast radius.", "Failure does not produce uncontrolled retries or waiting.", "Recovery is demonstrated rather than assumed." ] } },
    { id: "resilience-distributed-failure-harden-steward-003", title: "Publish the Steward Resilience Decision Record", estimatedMinutes: 75, content: { type: "practical", objective: "Convert the exercise into durable operational and architectural evidence.", scenario: "Document what Steward now guarantees, what it deliberately does not guarantee and what residual dependency risk remains.", instructions: ["Record failure mode, control and measured before/after behavior.", "Document timeout/retry/idempotency/degradation semantics that future changes must preserve.", "Update dashboards/alerts/runbooks if the experiment revealed missing operational evidence.", "Identify one remaining dependency risk for later fault-injection or architecture work."], deliverables: ["Steward resilience decision record", "Updated operational artifacts", "Residual-risk backlog"], completionCriteria: ["The record is evidence-backed.", "Future engineers can understand the intended failure semantics.", "Residual risk is explicit rather than described as solved." ] } },
] };

export const resilienceAndDistributedFailureDeepLessons: Lesson[] = [...specs.map(lessonFrom), lab];
