import type { Activity } from "../activities";
import type { LearningPath } from "./learning-path";
import type { Lesson } from "./lesson";
import { alertingAndOnCallDeepLessons } from "./reliability-alerting-on-call-deep";
import { dataProtectionAndDisasterRecoveryDeepLessons } from "./reliability-data-protection-disaster-recovery-deep";
import { incidentManagementDeepLessons } from "./reliability-incident-management-deep";
import { metricsPrometheusGrafanaDeepLessons } from "./reliability-metrics-prometheus-grafana-deep";
import { observabilityDeepLessons } from "./reliability-observability-deep";
import { performanceAndCapacityDeepLessons } from "./reliability-performance-capacity-deep";
import { productionLoggingDeepLessons } from "./reliability-production-logging-deep";
import { reliabilityAndSreDeepLessons } from "./reliability-sre-foundations-deep";
import { resilienceAndDistributedFailureDeepLessons } from "./reliability-resilience-distributed-failure-deep";
import { serviceLevelEngineeringDeepLessons } from "./reliability-service-level-engineering-deep";

function slug(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
function lesson(pathId: string, title: string, focus?: string): Lesson { const lessonId=`${pathId}-${slug(title)}`; const practical=title.startsWith("Lab:")||title.startsWith("Milestone:"); const activity:Activity={id:`${lessonId}-001`,title,estimatedMinutes:title.startsWith("Milestone:")?420:practical?75:12,content:practical?{type:"practical",objective:focus??`Apply ${title.replace(/^(Lab|Milestone): /,"")} to the Steward platform.`,scenario:"Treat the deployed Steward ecosystem as an operated service rather than a project. Use application, infrastructure, delivery, test, Nexus and dependency telemetry to detect, explain, recover from and learn from real failure modes.",instructions:["State the reliability question, user impact or failure hypothesis before adding telemetry or changing infrastructure.","Prefer signals that support diagnosis and decisions over dashboards built for appearance.","Define the expected steady state and the evidence that would prove degradation or recovery.","Where failure is introduced deliberately, constrain blast radius and define a stop/recovery condition first.","Capture timelines, commands, metrics, logs and recovery evidence.","Convert meaningful findings into runbook, alert, capacity, resilience or engineering changes."],deliverables:["Operational evidence from the Steward environment","Reliability analysis or runbook artifact","Recovery or improvement evidence"],completionCriteria:["The learner connects telemetry to user-visible or system reliability rather than collecting signals without purpose.","Recovery behavior is demonstrated where the lab involves failure.","The learner can explain remaining reliability risk and operational trade-offs."]}:{type:"reading",body:focus??`This breadth lesson establishes ${title} as a reliability-engineering capability for the Steward ecosystem. Deep authoring will add researched TSA teaching, worked incidents, official resources, exercises and knowledge checks.`}}; return{id:lessonId,title,activities:[activity]}; }

export const reliabilityAndSre:LearningPath={id:"reliability-and-sre",title:"Reliability and SRE Foundations",lessons:reliabilityAndSreDeepLessons};
export const observability:LearningPath={id:"observability",title:"Observability",lessons:observabilityDeepLessons};
export const productionLogging:LearningPath={id:"logging",title:"Production Logging",lessons:productionLoggingDeepLessons};
export const metricsPrometheusGrafana:LearningPath={id:"metrics-prometheus-grafana",title:"Metrics, Prometheus and Grafana",lessons:metricsPrometheusGrafanaDeepLessons};
export const serviceLevelEngineering:LearningPath={id:"service-level-engineering",title:"Service Level Engineering",lessons:serviceLevelEngineeringDeepLessons};
export const alertingAndOnCall:LearningPath={id:"alerting-and-on-call",title:"Alerting and On-call",lessons:alertingAndOnCallDeepLessons};
export const performanceAndCapacity:LearningPath={id:"performance-and-capacity",title:"Performance and Capacity",lessons:performanceAndCapacityDeepLessons};
export const resilienceAndDistributedFailure:LearningPath={id:"resilience-and-distributed-failure",title:"Resilience and Distributed Failure",lessons:resilienceAndDistributedFailureDeepLessons};
export const dataProtectionAndDisasterRecovery:LearningPath={id:"data-protection-and-disaster-recovery",title:"Data Protection and Disaster Recovery",lessons:dataProtectionAndDisasterRecoveryDeepLessons};
export const incidentManagement:LearningPath={id:"incident-management",title:"Incident Management",lessons:incidentManagementDeepLessons};
export const faultInjection:LearningPath={id:"fault-injection",title:"Fault Injection and Reliability Experiments",lessons:["Hypothesis-driven Reliability Experiments","Controlled Failure Injection","Blast Radius and Safety","Process and Container Failure","Resource Exhaustion Concepts","Network and Dependency Failure Simulation","Database Failure Scenarios","Artifact Repository Failure Scenarios","Recovery Verification","Chaos Engineering Principles and Safety"].map((title)=>lesson("fault-injection",title)).concat([lesson("fault-injection","Lab: Run a Steward Reliability Experiment","Define a falsifiable hypothesis about Steward behavior under failure, constrain blast radius, inject a controlled failure into learner-owned infrastructure, observe detection and recovery, and turn the evidence into a concrete reliability improvement.")])};
export const stewardReliabilityProgram:LearningPath={id:"steward-reliability-program",title:"Reliability Engineer Milestone",lessons:[lesson("steward-reliability-program","Milestone: Steward Reliability Program","Operate Steward as a measurable service: instrument application and infrastructure signals; centralize useful logs; expose Prometheus metrics and Grafana dashboards; define SLIs/SLOs and an error-budget model; implement actionable alerts and runbooks; establish performance/capacity baselines; harden representative dependency-failure paths; prove backup/restore capability; run an incident exercise and at least one controlled reliability experiment; and include the internal Nexus/artifact platform as a dependency whose availability, storage and recovery are measured. Produce a reliability review with evidence, unresolved risks and prioritized improvements.")]};
export const reliabilityEngineerPaths:LearningPath[]=[reliabilityAndSre,observability,productionLogging,metricsPrometheusGrafana,serviceLevelEngineering,alertingAndOnCall,performanceAndCapacity,resilienceAndDistributedFailure,dataProtectionAndDisasterRecovery,incidentManagement,faultInjection,stewardReliabilityProgram];
