import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const sreBook: LearningResource = { title: "Google SRE Book — Addressing Cascading Failures", url: "https://sre.google/sre-book/addressing-cascading-failures/" };
const prometheus: LearningResource = { title: "Prometheus Documentation", url: "https://prometheus.io/docs/introduction/overview/" };
const grafana: LearningResource = { title: "Grafana Documentation", url: "https://grafana.com/docs/grafana/latest/" };

type Spec = { id: string; title: string; intro: string; principles: string[]; steward: string[]; practice: string[]; reflection: string };

function lessonFrom(spec: Spec): Lesson {
    const blocks: LessonBlock[] = [
        { type: "paragraph", text: spec.intro },
        { type: "heading", id: `${spec.id}-model`, text: "Performance and capacity mental model", level: 2 },
        { type: "list", items: spec.principles },
        { type: "heading", id: `${spec.id}-steward`, text: "Apply it to Steward", level: 2 },
        ...spec.steward.map((text): LessonBlock => ({ type: "paragraph", text })),
        { type: "callout", tone: "steward", title: "Baseline before threshold", body: "Performance work starts with measured behavior under a defined workload. Avoid treating arbitrary CPU, latency or throughput numbers as capacity limits until the workload, saturation point and user impact are understood." },
        { type: "resources", title: "Continue learning", resources: [sreBook, prometheus, grafana] },
    ];
    return { id: `performance-and-capacity-${spec.id}`, title: spec.title, activities: [
        { id: `performance-and-capacity-${spec.id}-001`, title: spec.title, estimatedMinutes: 50, content: { type: "reading", body: spec.intro, blocks } },
        { id: `performance-and-capacity-${spec.id}-002`, title: `Analyze: ${spec.title}`, estimatedMinutes: 60, content: { type: "practical", objective: `Apply ${spec.title} to Steward performance evidence.`, scenario: "Use the existing Prometheus/Grafana/logging stack and a controlled workload. Define the workload and expected service behavior before interpreting resource or latency signals.", instructions: spec.practice, deliverables: ["Performance evidence", "Workload definition", "Capacity or bottleneck conclusion"], completionCriteria: ["The workload is defined and reproducible.", "The conclusion connects resource behavior to user-visible service behavior.", "Unknowns and confounding variables are explicit."] } },
        { id: `performance-and-capacity-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.reflection, minimumCharacters: 200 } },
    ] };
}

const specs: Spec[] = [
    { id: "latency-throughput", title: "Latency and Throughput", intro: "Latency measures how long work takes; throughput measures how much work completes over time. They interact, but improving one does not automatically improve the other.", principles: ["Define latency from a meaningful start and end boundary.", "Use distributions and percentiles rather than averages alone.", "Measure throughput under a defined workload.", "Expect latency to rise as a system approaches saturation."], steward: ["For Steward, useful measures include API request latency, database operation latency and package publish/download duration for Nexus-dependent workflows.", "A throughput increase is only healthy if latency and error behavior remain acceptable."], practice: ["Choose one Steward request flow.", "Define latency and throughput measurements.", "Generate a controlled workload at two rates.", "Compare latency distribution, throughput and errors."], reflection: "Why can higher throughput coincide with worse user experience?" },
    { id: "saturation", title: "Saturation", intro: "Saturation is the point where a constrained resource can no longer absorb additional work without queueing, delay or failure. It may appear in CPU, memory, connections, threads, disk, queues or database resources.", principles: ["Look for constrained resources, not generic utilization alone.", "Correlate saturation with latency, queueing and errors.", "Recognize that 100% is not the only meaningful saturation point.", "Measure headroom under realistic load."], steward: ["Steward may saturate at database connections or worker concurrency before host CPU is exhausted.", "Nexus can become capacity-constrained through storage or JVM/resource pressure even while the host remains reachable."], practice: ["Identify likely Steward saturation resources.", "Observe at least one under increasing workload.", "Record the first user-visible symptom.", "Estimate remaining headroom at the current operating point."], reflection: "Why is host CPU below 100% not proof that Steward still has capacity?" },
    { id: "bottlenecks", title: "Bottlenecks", intro: "A bottleneck is the limiting part of a workload path. Removing one often reveals the next, so performance engineering is iterative rather than a one-time optimization pass.", principles: ["Trace the full request path before optimizing.", "Use evidence to identify the limiting resource.", "Change one major variable at a time when possible.", "Retest because bottlenecks move after improvements."], steward: ["A slow Steward request may be constrained by application code, PostgreSQL queries, network delay or dependency behavior.", "A CI pipeline may be bottlenecked by package resolution or Nexus rather than the build process itself."], practice: ["Select one slow Steward path.", "Build a latency/resource breakdown hypothesis.", "Use telemetry to identify the strongest bottleneck candidate.", "Propose and validate one targeted improvement."], reflection: "Why can optimizing application code fail to improve end-to-end latency if PostgreSQL is the true bottleneck?" },
    { id: "load-stress", title: "Load and Stress Testing", intro: "Load testing evaluates behavior under expected or planned demand. Stress testing intentionally pushes beyond expected demand to discover degradation, saturation and failure behavior.", principles: ["Define workload shape, data and concurrency before running a test.", "Separate steady-state load from ramp and spike behavior.", "Protect shared environments with explicit limits.", "Observe recovery after overload, not only failure during overload."], steward: ["Steward tests should run only in learner-controlled environments and should include both API and dependency telemetry.", "Stress testing is valuable when it reveals how the system fails and recovers, not when it merely produces a maximum request number."], practice: ["Define a safe Steward load profile.", "Run baseline and increasing-load stages.", "Capture latency, errors, saturation and recovery.", "Identify the first breached reliability expectation."], reflection: "What does a stress test teach that a normal load test may not?" },
    { id: "capacity-planning", title: "Capacity Planning", intro: "Capacity planning estimates when current resources and architecture will stop meeting demand or reliability objectives, leaving enough time to scale, optimize or redesign before failure.", principles: ["Plan from demand growth and measured capacity, not guesswork.", "Include safety margin for variability and incidents.", "Track multiple constrained resources.", "Revisit assumptions as workloads and architecture change."], steward: ["Steward capacity includes application and database resources plus supporting platforms such as Nexus storage and CI execution capacity.", "A small learner system still benefits from learning to project growth from evidence rather than waiting for exhaustion."], practice: ["Choose one Steward capacity dimension.", "Estimate current consumption and growth.", "Define a practical warning point and intervention lead time.", "Document assumptions that could invalidate the forecast."], reflection: "Why should a capacity plan include intervention lead time instead of alerting only when a resource is nearly exhausted?" },
    { id: "resource-utilization", title: "Resource Utilization", intro: "Utilization shows how much of a resource is in use, but interpretation depends on the resource's behavior and workload. High utilization can be efficient or dangerous depending on queueing and headroom.", principles: ["Interpret utilization alongside saturation and service symptoms.", "Know resource-specific limits and burst behavior.", "Do not optimize for low utilization as an end in itself.", "Measure both average and peak behavior where relevant."], steward: ["CPU, memory, disk, connections and storage all have different failure characteristics in Steward.", "The goal is enough efficient headroom to meet reliability expectations, not universally low utilization."], practice: ["Pick three Steward resources.", "Define useful utilization and saturation signals for each.", "Compare a quiet and loaded period.", "Explain which resource deserves action and why."], reflection: "Why can 80% utilization be harmless for one resource and dangerous for another?" },
    { id: "database-app-bottlenecks", title: "Database and Application Bottlenecks", intro: "Application and database behavior are tightly coupled: inefficient queries, lock contention, connection exhaustion and excessive round trips can dominate end-to-end performance.", principles: ["Measure query latency and frequency before tuning.", "Look for lock/connection contention as well as slow queries.", "Reduce unnecessary round trips and repeated work.", "Retest with representative data volume."], steward: ["PostgreSQL may become Steward's limiting component as data grows even when API code remains unchanged.", "Observability should distinguish application wait time from database execution and contention where feasible."], practice: ["Identify a database-heavy Steward operation.", "Capture query/request timing and resource evidence.", "Inspect one likely inefficiency or contention point.", "Validate an improvement or record why evidence remains inconclusive."], reflection: "Why can a query that is fast on an empty database become a production bottleneck later?" },
    { id: "performance-baselines", title: "Performance Baselines", intro: "A performance baseline is a reproducible snapshot of service behavior under a defined workload and environment. It provides a reference for detecting regressions and evaluating later changes.", principles: ["Record workload, environment and data conditions with results.", "Use distributions, throughput, errors and resource signals together.", "Version baselines when architecture changes materially.", "Avoid comparing runs whose conditions are not meaningfully comparable."], steward: ["Steward baselines should become evidence for later release, capacity and resilience decisions.", "A baseline is not a permanent target; it is a documented reference point."], practice: ["Define one representative Steward baseline workload.", "Capture latency, throughput, errors and key resource metrics.", "Store the result with environment/test metadata.", "Define what degree of regression would trigger investigation rather than automatic rejection."], reflection: "What makes two performance test runs legitimately comparable?" },
    { id: "queueing-contention", title: "Queueing and Contention Concepts", intro: "When concurrent work competes for limited resources, requests wait. Queueing can cause nonlinear latency growth even before obvious resource exhaustion.", principles: ["Expect wait time to rise rapidly near capacity limits.", "Identify shared resources that serialize or constrain work.", "Distinguish useful buffering from unbounded queues.", "Measure queue depth, wait time and service time separately when possible."], steward: ["Database pools, worker limits and CI runners can create queues in the Steward ecosystem.", "Increasing concurrency without increasing the constrained resource can worsen latency rather than improve throughput."], practice: ["Identify one contention point in Steward.", "Model what happens as concurrency increases.", "Observe queueing or waiting evidence if available.", "Propose a safe concurrency or queue boundary."], reflection: "Why can adding more concurrent workers make an already constrained system slower?" },
    { id: "artifact-capacity", title: "Storage Growth and Artifact Capacity", intro: "Artifact repositories accumulate packages, metadata, logs and caches over time. Storage exhaustion can block delivery suddenly, so growth rate and cleanup/retention policy are reliability concerns.", principles: ["Measure current storage and growth trend.", "Understand what data can safely expire.", "Keep cleanup policy aligned with rollback and reproducibility needs.", "Alert early enough to expand or clean capacity safely."], steward: ["Nexus stores internal dependencies including steward-common and tsa-test-core, making storage capacity part of delivery reliability.", "Cleanup must not remove artifacts still required for rollback or reproducible builds."], practice: ["Measure or model Nexus storage consumption.", "Estimate growth from package publication behavior.", "Define a warning threshold and intervention lead time.", "Draft a retention/cleanup policy that preserves required artifacts."], reflection: "Why is deleting old artifacts blindly a risky response to Nexus storage pressure?" },
];

const lab: Lesson = { id: "performance-and-capacity-baseline-lab", title: "Lab: Establish Steward Capacity Baselines", activities: [
    { id: "performance-and-capacity-baseline-lab-001", title: "Define Representative Workloads", estimatedMinutes: 90, content: { type: "practical", objective: "Create reproducible Steward workloads for performance measurement.", scenario: "Use learner-controlled Steward infrastructure and the existing observability stack.", instructions: ["Select representative API and dependency workflows.", "Define request mix, concurrency, duration and test data.", "Define safe stop conditions and environment constraints.", "Record expected user-visible behavior and SLO-related limits."], deliverables: ["Workload specification", "Safety/stop conditions", "Measurement plan"], completionCriteria: ["The workload is reproducible.", "The environment and test data are documented.", "Safety limits prevent uncontrolled resource exhaustion." ] } },
    { id: "performance-and-capacity-baseline-lab-002", title: "Measure Baseline, Saturation and Bottlenecks", estimatedMinutes: 150, content: { type: "practical", objective: "Measure how Steward behaves from normal load through the first meaningful capacity constraint.", scenario: "Increase load progressively while observing service and resource telemetry.", instructions: ["Run the baseline workload and capture latency, throughput, errors and resources.", "Increase demand in controlled stages.", "Identify the first saturation/bottleneck signal and user impact.", "Capture recovery after load is reduced.", "Repeat or isolate a suspect bottleneck if evidence is ambiguous."], deliverables: ["Performance baseline", "Saturation evidence", "Bottleneck analysis", "Recovery evidence"], completionCriteria: ["The first meaningful constraint is evidence-backed.", "Service symptoms are correlated with resource/dependency behavior.", "Recovery after overload is observed." ] } },
    { id: "performance-and-capacity-baseline-lab-003", title: "Create the Capacity and Growth Plan", estimatedMinutes: 90, content: { type: "practical", objective: "Turn measured limits into a practical Steward capacity plan.", scenario: "Include application/database capacity and the Nexus/internal artifact platform where growth is relevant.", instructions: ["Estimate current headroom for the tested workload.", "Define capacity warning points and intervention lead times.", "Project at least one growth dimension such as traffic, database size or Nexus storage.", "Prioritize optimization, scaling or architecture actions.", "Record assumptions and remeasurement triggers."], deliverables: ["Steward capacity baseline report", "Capacity/growth forecast", "Prioritized improvement backlog"], completionCriteria: ["Capacity claims trace to measured evidence.", "Growth assumptions are explicit.", "Actions are prioritized before exhaustion rather than after failure." ] } },
] };

export const performanceAndCapacityDeepLessons: Lesson[] = [...specs.map(lessonFrom), lab];
