import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const otelLogs: LearningResource = { title: "OpenTelemetry Logs", url: "https://opentelemetry.io/docs/concepts/signals/logs/" };
const twelveFactor: LearningResource = { title: "The Twelve-Factor App: Logs", url: "https://12factor.net/logs" };
const owaspLogging: LearningResource = { title: "OWASP Logging Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html" };

type Spec = { id: string; title: string; intro: string; principles: string[]; steward: string[]; practice: string[]; reflection: string; warning?: string };

function blocksFor(spec: Spec): LessonBlock[] {
    const blocks: LessonBlock[] = [
        { type: "paragraph", text: spec.intro },
        { type: "heading", id: `${spec.id}-principles`, text: "Logging principles", level: 2 },
        { type: "list", items: spec.principles },
        { type: "heading", id: `${spec.id}-steward`, text: "Apply it to Steward", level: 2 },
        ...spec.steward.map((text): LessonBlock => ({ type: "paragraph", text })),
    ];
    if (spec.warning) blocks.push({ type: "callout", tone: "warning", title: "Operational warning", body: spec.warning });
    blocks.push({ type: "callout", tone: "steward", title: "Diagnostic standard", body: "A production log should help reconstruct what happened, to which component or request, with what outcome and enough context to investigate—without leaking secrets or creating unbounded noise." });
    blocks.push({ type: "resources", title: "Continue learning", resources: [otelLogs, twelveFactor, owaspLogging] });
    return blocks;
}

function lessonFrom(spec: Spec): Lesson {
    return { id: `logging-${spec.id}`, title: spec.title, activities: [
        { id: `logging-${spec.id}-001`, title: spec.title, estimatedMinutes: 45, content: { type: "reading", body: spec.intro, blocks: blocksFor(spec) } },
        { id: `logging-${spec.id}-002`, title: `Implement: ${spec.title}`, estimatedMinutes: 55, content: { type: "practical", objective: `Apply ${spec.title} to Steward's production-like logging path.`, scenario: "Use Steward's observability questions as the source of logging requirements. Change only learner-controlled code/configuration, preserve sensitive-data boundaries and verify that the resulting events support diagnosis.", instructions: spec.practice, deliverables: ["Logging change or assessment", "Representative log evidence", "Diagnostic usefulness note"], completionCriteria: ["Log structure and context support a concrete operational question.", "Sensitive values are not exposed.", "The learner can explain why the event belongs at its chosen level and retention path."] } },
        { id: `logging-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.reflection, minimumCharacters: 200 } },
    ] };
}

const specs: Spec[] = [
    { id: "structured-logs", title: "Structured Logs", intro: "Structured logs encode stable fields alongside human-readable messages so events can be filtered, aggregated and correlated reliably. Structure turns logs from text archives into queryable operational evidence.", principles: ["Prefer explicit fields for stable attributes such as service, event, outcome and duration.", "Keep field names and types consistent across equivalent events.", "Separate event identity from free-text explanation.", "Design schemas around diagnostic questions rather than logging every object."], steward: ["Steward request, authentication, dependency and background-job events should expose useful fields without forcing operators to parse sentence fragments.", "A JSON format is useful only when the fields have stable semantics."], practice: ["Choose one important Steward event currently represented weakly or only as text.", "Define a compact event schema.", "Emit the structured event in a learner-controlled path.", "Show how an operator could filter or group the event by useful fields."], reflection: "Why is emitting arbitrary JSON not enough to claim that Steward has structured logging?" },
    { id: "log-levels", title: "Log Levels", intro: "Log levels express operational significance, not developer emotion. A useful level policy helps operators separate routine state from conditions that require investigation while avoiding both silence and permanent alarm noise.", principles: ["Define levels by expected operator action and abnormality.", "Do not log normal control flow as errors.", "Reserve debug detail for contexts where its cost and sensitivity are acceptable.", "Keep equivalent events at consistent levels."], steward: ["A denied request may be normal policy behavior while a database connection failure may threaten service availability. They should not automatically share severity.", "The later alerting path should not depend on every warning becoming a page."], practice: ["Review representative Steward log statements.", "Classify them against an explicit level policy.", "Correct at least one misleading level or missing event.", "Explain how the change improves operational interpretation."], reflection: "Why can excessive ERROR logging make incident detection worse instead of better?" },
    { id: "correlation-ids", title: "Correlation IDs", intro: "Correlation identifiers connect related events that belong to one logical request or operation. They reduce the time required to reconstruct behavior across middleware, application code and dependencies.", principles: ["Generate or accept correlation context at a defined boundary.", "Propagate it consistently through related events.", "Do not use correlation identifiers as authentication or authorization evidence.", "Keep identifier format stable and safe to log."], steward: ["One Steward API request may create events in request handling, database access and dependency calls. A shared request/correlation ID lets the operator follow that path.", "External request IDs can be preserved carefully, but an internal trusted identifier may still be needed."], practice: ["Trace one Steward request across multiple log statements.", "Add or verify a correlation ID at the request boundary.", "Propagate it through related events.", "Demonstrate a query or manual trace that reconstructs the request."], reflection: "What can a correlation ID prove about a request, and what can it not prove?" },
    { id: "request-trace-context", title: "Request and Trace Context", intro: "Request context enriches logs with operationally useful attributes such as route, method, status, duration and trace identifiers. The goal is enough context to explain behavior without duplicating entire request bodies or sensitive state.", principles: ["Capture route templates rather than high-cardinality raw paths where possible.", "Include outcome and duration for service operations.", "Propagate trace/span context when distributed tracing exists.", "Avoid logging tokens, passwords and sensitive payload fields."], steward: ["Steward logs should make it possible to distinguish a slow endpoint, failed dependency and authorization denial while preserving privacy.", "Trace context created later through OpenTelemetry should align with logging fields rather than forming a separate diagnostic universe."], practice: ["Define the minimum request context for one Steward endpoint.", "Capture status, route, duration and correlation/trace context.", "Verify sensitive headers/body fields are excluded.", "Use the event to answer a concrete latency or failure question."], reflection: "Why is logging the full HTTP request often worse than logging a deliberate request-context schema?" },
    { id: "centralized-logging", title: "Centralized Logging", intro: "Centralized logging makes events from multiple components searchable from one operational surface. It improves incident reconstruction, but introduces its own availability, retention, access-control and cost concerns.", principles: ["Ship logs off individual hosts when cross-service diagnosis requires it.", "Preserve source/service identity and timestamps.", "Secure access to centralized logs as potentially sensitive operational data.", "Design for temporary shipping or backend failure without crashing the application."], steward: ["Steward application, host and Nexus/platform logs may eventually converge into one searchable system while retaining clear source identity.", "Centralization should complement—not replace—local recovery paths and bounded buffering."], practice: ["Map current Steward log sources and destinations.", "Design a centralization path for application plus one supporting dependency.", "Identify failure behavior if the collector/backend is unavailable.", "Define access and retention boundaries for the centralized store."], reflection: "What new reliability risk is introduced when operators depend on one centralized logging backend during incidents?" },
    { id: "useful-noisy", title: "Useful vs Noisy Logs", intro: "Logging more events does not necessarily increase observability. Noise consumes storage and attention, hides meaningful signals and can raise cardinality or cost without improving diagnosis.", principles: ["Every recurring event should answer a diagnostic, audit or service question.", "Prefer aggregation/metrics for high-volume repetitive state when individual event detail is unnecessary.", "Sample only when the loss of individual events is acceptable.", "Review log value after real investigations."], steward: ["A per-request success event may be useful initially, while an identical heartbeat every second may belong in metrics instead.", "The observability design should determine what belongs in logs versus later Prometheus metrics."], practice: ["Review a representative Steward logging stream.", "Classify events as essential, contextual, redundant or better represented as metrics.", "Remove or reduce one noisy pattern.", "Confirm that a concrete diagnostic question remains answerable."], reflection: "When should a high-volume operational fact become a metric rather than a log event?" },
    { id: "privacy-security", title: "Privacy and Security in Logs", intro: "Logs frequently become accidental data stores for credentials, personal information and internal implementation details. Production logging must deliberately minimize sensitive content while preserving investigative value.", principles: ["Never log passwords, active tokens or secret material.", "Minimize personal and sensitive business data.", "Use stable identifiers instead of raw sensitive values when possible.", "Treat log access as privileged access."], steward: ["Steward authentication, user, package and security events must remain diagnosable without copying JWTs, passwords, repository credentials or unnecessary user data into logs.", "Security Steward evidence and Production Logging should enforce the same secret-handling expectations."], practice: ["Inspect representative Steward events for sensitive fields.", "Create a do-not-log field list.", "Redact or remove one unsafe field/path.", "Verify diagnostics still work without the sensitive value."], reflection: "Why is redacting only passwords insufficient for safe Steward logging?", warning: "Do not use real secret values as evidence. Demonstrate field names, redaction behavior or synthetic values instead." },
    { id: "retention", title: "Log Retention Concepts", intro: "Retention determines how long operational evidence remains available. Longer retention can improve historical investigation but increases storage cost, privacy exposure and governance obligations.", principles: ["Set retention from diagnostic, audit and legal/business needs rather than keeping everything forever.", "Different log classes may need different retention periods.", "Account for storage growth and query performance.", "Ensure deletion/expiration behavior is understood and testable where needed."], steward: ["High-volume request logs, security-relevant events and Nexus operational records may justify different retention windows.", "Later capacity planning should include log growth as a real storage workload."], practice: ["Classify Steward log categories by operational value.", "Propose retention windows and rationale.", "Estimate which category is likely to dominate storage.", "Define what investigation capability is lost when each category expires."], reflection: "Why is 'keep all logs forever' usually a weak reliability and governance decision?" },
];

const lab: Lesson = { id: "logging-steward-diagnostic-path", title: "Lab: Build a Steward Diagnostic Logging Path", activities: [
    { id: "logging-steward-diagnostic-path-001", title: "Define the Diagnostic Question and Event Model", estimatedMinutes: 60, content: { type: "practical", objective: "Turn one high-value Steward reliability question into a deliberate logging design.", scenario: "Use the Observability module output and choose a request or dependency path where logs provide useful event-level detail.", instructions: ["State the operational question and expected failure modes.", "Define event names, stable fields, levels and correlation context.", "Define sensitive fields that must never be captured.", "Specify which component emits each event."], deliverables: ["Diagnostic question", "Logging/event schema", "Sensitivity and level policy"], completionCriteria: ["Fields have stable meaning.", "The design supports the selected question.", "Sensitive-data exclusions are explicit." ] } },
    { id: "logging-steward-diagnostic-path-002", title: "Implement and Correlate the Logging Path", estimatedMinutes: 105, content: { type: "practical", objective: "Produce end-to-end diagnostic evidence for one Steward operation.", scenario: "Instrument the learner-controlled Steward path with structured events and correlation context.", instructions: ["Implement structured events at the chosen boundaries.", "Propagate correlation/request context.", "Exercise one success case and one controlled failure case.", "Collect the resulting events and reconstruct the timeline."], deliverables: ["Logging implementation/configuration", "Success/failure log evidence", "Reconstructed operation timeline"], completionCriteria: ["Events correlate across the selected path.", "The controlled failure is diagnosable from the evidence.", "No prohibited sensitive values are present." ] } },
    { id: "logging-steward-diagnostic-path-003", title: "Evaluate Noise, Centralization and Retention", estimatedMinutes: 75, content: { type: "practical", objective: "Make the logging path operationally sustainable.", scenario: "Treat logging itself as a production dependency with cost, storage and access implications.", instructions: ["Identify noisy or redundant events.", "Define which sources should be centralized and how source identity is preserved.", "Define behavior during log-shipping/backend failure.", "Choose retention expectations for the implemented event classes.", "Record follow-up metrics/traces that should be handled by later modules instead of logs."], deliverables: ["Logging operating model", "Noise/cost review", "Centralization and retention plan", "Metrics/tracing handoff"], completionCriteria: ["The logging path remains useful without unnecessary volume.", "Centralization failure does not become an undefined application failure mode.", "The output feeds the upcoming Metrics/Prometheus/Grafana work." ] } },
] };

export const productionLoggingDeepLessons: Lesson[] = [...specs.map(lessonFrom), lab];
