import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const sreWorkbook: LearningResource = { title: "Google SRE Workbook — Implementing SLOs", url: "https://sre.google/workbook/implementing-slos/" };
const sreBook: LearningResource = { title: "Google SRE — Service Level Objectives", url: "https://sre.google/sre-book/service-level-objectives/" };

type Spec = { id: string; title: string; intro: string; principles: string[]; steward: string[]; practice: string[]; reflection: string };

function deepLesson(spec: Spec): Lesson {
    const blocks: LessonBlock[] = [
        { type: "paragraph", text: spec.intro },
        { type: "heading", id: `${spec.id}-model`, text: "Service-level mental model", level: 2 },
        { type: "list", items: spec.principles },
        { type: "heading", id: `${spec.id}-steward`, text: "Apply it to Steward", level: 2 },
        ...spec.steward.map((text): LessonBlock => ({ type: "paragraph", text })),
        { type: "callout", tone: "steward", title: "Measure user-visible reliability", body: "A service objective is useful only when its indicator represents behavior users or dependent systems actually care about and when the target changes engineering decisions." },
        { type: "resources", title: "Reference material", resources: [sreWorkbook, sreBook] },
    ];
    return { id: `service-level-engineering-${spec.id}`, title: spec.title, activities: [
        { id: `service-level-engineering-${spec.id}-001`, title: spec.title, estimatedMinutes: 50, content: { type: "reading", body: spec.intro, blocks } },
        { id: `service-level-engineering-${spec.id}-002`, title: `Engineer: ${spec.title}`, estimatedMinutes: 60, content: { type: "practical", objective: `Apply ${spec.title} to Steward.`, scenario: "Use the Prometheus/Grafana metrics and operational questions already built for Steward. Avoid inventing targets before checking what can be measured reliably.", instructions: spec.practice, deliverables: ["Service-level artifact", "Measurement evidence", "Decision/trade-off note"], completionCriteria: ["The indicator and target have explicit semantics.", "The measure reflects service behavior rather than host health alone.", "The learner explains how the result affects an engineering or release decision."] } },
        { id: `service-level-engineering-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.reflection, minimumCharacters: 200 } },
    ] };
}

const specs: Spec[] = [
    { id: "slis", title: "SLIs", intro: "A Service Level Indicator is a quantitative measure of service behavior, typically expressed as a ratio or distribution over valid events. The important design decision is what event counts as good, bad or valid.", principles: ["Choose indicators at user-visible service boundaries.", "Define valid events and good events precisely.", "Prefer indicators that can be computed consistently from trustworthy telemetry.", "Avoid proxy indicators when direct success evidence exists."], steward: ["For Steward, an availability SLI might be successful authenticated API operations divided by valid attempts, while a latency SLI could measure the proportion of valid requests below a chosen threshold.", "Nexus can have separate consumer-facing indicators such as successful package downloads or publishes."], practice: ["Choose two critical Steward capabilities.", "Define valid and good events for each.", "Map each SLI to existing Prometheus metrics or identify the instrumentation gap.", "Test the calculation with known good and bad events."], reflection: "Why is host uptime usually a weaker SLI than successful Steward API operations?" },
    { id: "slos", title: "SLOs", intro: "A Service Level Objective is a target for an SLI over a defined window. Its purpose is to express how much unreliability is acceptable and to support prioritization, not to promise perfection.", principles: ["Attach every objective to a named SLI and window.", "Choose targets from user need and engineering reality, not prestige.", "Avoid 100% unless failure is truly unacceptable and economically justified.", "Review objectives when service expectations or measurement quality changes."], steward: ["A Steward SLO should say exactly which operation population is measured, what success means and over what rolling or calendar window.", "Different capabilities may justify different targets; package resolution, interactive API requests and administrative workflows need not share one number."], practice: ["Propose an SLO for one Steward availability SLI and one latency SLI.", "State the measurement window and rationale.", "Calculate the permitted bad-event fraction.", "Explain what evidence would make you tighten or relax the target."], reflection: "Why can a 99.99% target be worse engineering than 99.9% when the business need does not justify the additional complexity?" },
    { id: "slas", title: "SLAs", intro: "A Service Level Agreement is a commitment with consequences, often contractual or customer-facing. It should be distinguished from the internal engineering objective used to manage reliability.", principles: ["Keep internal SLOs and external commitments conceptually separate.", "Set operational objectives with enough margin to protect contractual commitments.", "Define exclusions and measurement sources explicitly when commitments exist.", "Do not call every reliability target an SLA."], steward: ["Steward is primarily an internal learning/service platform, so most targets belong as SLOs. This lesson teaches how the model would change if Steward offered a contractual service to another team or customer."], practice: ["Compare a hypothetical Steward SLA with its supporting internal SLO.", "Define what consequences make the agreement materially different.", "Identify measurement and exclusion disputes that could occur.", "Explain why the internal target should normally be stricter than the external commitment."], reflection: "What makes an SLA different from an SLO besides the percentage written in it?" },
    { id: "error-budgets", title: "Error Budgets", intro: "An error budget is the amount of unreliability allowed by an SLO. It turns reliability from an abstract aspiration into consumable risk that can be discussed alongside feature delivery and change velocity.", principles: ["Derive the budget mathematically from the SLO.", "Track consumption using the same event semantics as the SLI.", "Treat rapid burn differently from slow, expected consumption.", "Use the budget to trigger agreed actions rather than merely reporting it."], steward: ["If Steward has a 99.9% success SLO, the remaining 0.1% of valid events forms the error budget for the window.", "The useful question is not only how much remains, but what type of failure consumed it and whether current release behavior is sustainable."], practice: ["Calculate error budgets for two example Steward SLOs.", "Simulate normal and high-burn failure periods.", "Plot or query budget consumption from existing metrics.", "Define one engineering action that should occur at a chosen burn threshold."], reflection: "Why is an error budget valuable only if its consumption influences behavior?" },
    { id: "user-visible", title: "User-visible Reliability", intro: "Reliability engineering should optimize successful user outcomes rather than internal component perfection. A service can be technically healthy while its users experience failure, slowness or stale results.", principles: ["Measure close to the service-consumer boundary.", "Model important workflows, not only individual components.", "Distinguish partial degradation from total unavailability.", "Include dependent internal systems when their failure changes user outcomes."], steward: ["Steward users may care about authenticating, reading/updating service records and completing administrative workflows; developers may care about resolving internal packages from Nexus.", "Those outcomes should anchor service-level measurement."], practice: ["List Steward's top user-visible outcomes.", "Map component failures that can break each outcome.", "Identify one current metric that could look healthy during user failure.", "Propose a better outcome-level indicator."], reflection: "How can every Steward container be healthy while a user-visible SLO is failing?" },
    { id: "good-indicators", title: "Choosing Good Indicators", intro: "Good indicators are understandable, measurable and tightly connected to the experience being protected. Poor indicators are easy to collect but weakly related to actual service success.", principles: ["Prefer outcome measures over implementation proxies.", "Keep indicator populations stable and interpretable.", "Exclude invalid events only with documented rationale.", "Avoid indicators whose telemetry fails in the same way as the service without independent visibility."], steward: ["HTTP 2xx percentage may be useful, but only if status semantics match actual business success. A request returning 200 with a failed domain operation can invalidate the SLI design."], practice: ["Review three candidate Steward indicators.", "Challenge each for false-good and false-bad cases.", "Refine event semantics where needed.", "Choose the strongest indicator and defend the trade-off."], reflection: "Why can an HTTP status-based SLI misrepresent actual Steward success?" },
    { id: "windowing", title: "Windowing and Measurement Concepts", intro: "The same event data can produce different reliability conclusions depending on aggregation window. Rolling windows, calendar windows and short diagnostic windows serve different purposes.", principles: ["Match windows to the decision being made.", "Understand how low traffic changes statistical confidence.", "Avoid hiding short severe incidents inside long averages.", "Use consistent windows when comparing targets and budget consumption."], steward: ["Steward may have low traffic in a learning environment, making event-based objectives more interpretable than assumptions borrowed from high-volume systems.", "Short windows help detect burn; longer windows express the objective."], practice: ["Calculate one SLI over multiple windows.", "Show how a short outage appears in each.", "Discuss low-volume effects for Steward.", "Choose a primary objective window and justify it."], reflection: "Why can a monthly SLI hide a severe short incident that still matters operationally?" },
    { id: "targets-tradeoffs", title: "Reliability Targets and Trade-offs", intro: "Targets encode an economic and engineering choice. Raising them increases the amount of redundancy, automation, operational discipline and change control a system may need.", principles: ["Tie target strictness to impact of failure.", "Account for dependency ceilings and architecture limits.", "Do not choose an SLO the system cannot meaningfully measure.", "Make the cost of higher reliability visible."], steward: ["A strict Steward API target may be impossible if a single PostgreSQL instance or Nexus dependency provides a lower practical reliability ceiling.", "This is a signal to redesign or choose a realistic objective, not to manipulate the metric."], practice: ["Choose one proposed Steward SLO.", "Identify dependency and architecture constraints.", "Estimate what engineering work a stricter target would require.", "Recommend a target and document the accepted reliability risk."], reflection: "How can a dependency's reliability limit the meaningful SLO of the service that depends on it?" },
    { id: "release-decisions", title: "Error Budgets and Release Decisions", intro: "Error budgets are most powerful when teams pre-agree how budget health changes release behavior. The goal is not a rigid universal freeze rule, but an explicit policy that balances reliability risk and delivery value.", principles: ["Define decision thresholds before pressure arrives.", "Consider burn rate and failure cause, not only remaining percentage.", "Separate emergency/security changes from routine feature changes.", "Resume normal change only when evidence supports the decision."], steward: ["Steward can use a simple policy: healthy budget allows normal delivery; elevated burn triggers investigation and tighter change review; exhausted budget prioritizes reliability work except urgent risk-reducing changes.", "The exact policy should be proportional to the service rather than copied from a hyperscale organization."], practice: ["Draft a Steward error-budget release policy.", "Define healthy, warning and exhausted states.", "Test the policy against a feature release, a reliability fix and a critical security patch.", "Record exceptions and who can approve them."], reflection: "Why should a critical security fix not necessarily be blocked by a generic reliability release freeze?" },
];

const lab: Lesson = { id: "service-level-engineering-define-steward-slos", title: "Lab: Define Steward SLOs", activities: [
    { id: "service-level-engineering-define-steward-slos-001", title: "Select and Implement Steward SLIs", estimatedMinutes: 120, content: { type: "practical", objective: "Implement defensible service-level indicators for critical Steward outcomes.", scenario: "Use the existing Prometheus/Grafana telemetry and Reliability Risk Map. Prefer a small number of indicators with strong semantics over broad coverage.", instructions: ["Choose two or three user-visible Steward capabilities.", "Define valid events, good events and measurement sources.", "Implement PromQL or recording expressions for the indicators.", "Generate known success/failure traffic and verify calculations."], deliverables: ["Steward SLI specification", "PromQL/recording evidence", "Known-event validation"], completionCriteria: ["Indicators are user-relevant and measurable.", "Event semantics are explicit.", "Queries have been validated against known behavior." ] } },
    { id: "service-level-engineering-define-steward-slos-002", title: "Set SLOs and Error Budgets", estimatedMinutes: 105, content: { type: "practical", objective: "Choose reliability targets and quantify permitted unreliability.", scenario: "Treat targets as engineering decisions constrained by user need, dependency reliability and current architecture.", instructions: ["Set target and window for each SLI.", "Document target rationale and dependency constraints.", "Calculate error budgets.", "Create a Grafana or query view showing objective performance and budget consumption.", "Document any measurement uncertainty."], deliverables: ["Steward SLO document", "Error-budget calculations", "SLO/budget dashboard or query evidence"], completionCriteria: ["Targets have defensible rationale.", "Budgets are mathematically consistent with SLOs.", "Dependency ceilings and uncertainty are visible." ] } },
    { id: "service-level-engineering-define-steward-slos-003", title: "Create the Steward Error-budget Policy", estimatedMinutes: 90, content: { type: "practical", objective: "Turn reliability measurement into explicit release and reliability-work decisions.", scenario: "Define a lightweight policy appropriate to Steward now, while preserving concepts that scale to a real production service.", instructions: ["Define healthy, warning and exhausted budget states.", "Specify actions for high burn and budget exhaustion.", "Define treatment of reliability fixes, urgent security changes and routine releases.", "Run three hypothetical release scenarios through the policy.", "Record owner/review expectations."], deliverables: ["Error-budget policy", "Scenario decision evidence", "Policy trade-off note"], completionCriteria: ["The policy changes behavior based on evidence.", "Exceptions are deliberate rather than implicit.", "The learner can explain how reliability and delivery are balanced." ] } },
] };

export const serviceLevelEngineeringDeepLessons: Lesson[] = [...specs.map(deepLesson), lab];
