import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const otelDocs: LearningResource = { title: "OpenTelemetry Documentation", url: "https://opentelemetry.io/docs/" };
const sreBook: LearningResource = { title: "Google Site Reliability Engineering", url: "https://sre.google/sre-book/table-of-contents/" };
const grafanaObs: LearningResource = { title: "Grafana Observability", url: "https://grafana.com/docs/" };

type Spec = { id: string; title: string; intro: string; principles: string[]; steward: string[]; practice: string[]; reflection: string };

function blocksFor(spec: Spec): LessonBlock[] {
  return [
    { type: "paragraph", text: spec.intro },
    { type: "heading", id: `${spec.id}-principles`, text: "Observability principles", level: 2 },
    { type: "list", items: spec.principles },
    { type: "heading", id: `${spec.id}-steward`, text: "Apply it to Steward", level: 2 },
    ...spec.steward.map((text): LessonBlock => ({ type: "paragraph", text })),
    { type: "callout", tone: "steward", title: "Question before signal", body: "Do not add telemetry because a tool can collect it. Start with a concrete question about Steward behavior, then choose the smallest set of signals and context that can answer it reliably." },
    { type: "resources", title: "Continue learning", resources: [otelDocs, sreBook, grafanaObs] },
  ];
}

function lessonFrom(spec: Spec): Lesson {
  return { id: `observability-${spec.id}`, title: spec.title, activities: [
    { id: `observability-${spec.id}-001`, title: spec.title, estimatedMinutes: 50, content: { type: "reading", body: spec.intro, blocks: blocksFor(spec) } },
    { id: `observability-${spec.id}-002`, title: `Observe: ${spec.title}`, estimatedMinutes: 60, content: { type: "practical", objective: `Apply ${spec.title} to Steward.`, scenario: "Use the current Steward architecture and the Reliability Risk Map. Start from a user-visible or operational question, instrument only what is necessary, then verify that the resulting telemetry actually answers the question.", instructions: spec.practice, deliverables: ["Operational question", "Telemetry evidence", "Interpretation and gap note"], completionCriteria: ["The signal is tied to a concrete question.", "Context is sufficient to distinguish relevant causes or requests.", "The learner records what the telemetry still cannot prove."] } },
    { id: `observability-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.reflection, minimumCharacters: 200 } },
  ] };
}

const specs: Spec[] = [
  { id: "observability-vs-monitoring", title: "Observability vs Monitoring", intro: "Monitoring checks known conditions; observability helps engineers investigate system state using emitted evidence, including questions they did not fully anticipate when instrumentation was created.", principles: ["Monitoring usually starts from known failure conditions.", "Observability depends on sufficiently rich internal signals and context.", "Neither eliminates the need for system understanding.", "Good telemetry should support diagnosis, not only status display."], steward: ["A Steward dashboard showing CPU and request count is monitoring. Being able to explain why a specific user request became slow across API, database and dependency boundaries requires deeper observability.", "The reliability risk map should determine which unknowns deserve investigation capability."], practice: ["Choose one known Steward failure and one broader diagnostic question.", "Identify which can be answered by a simple monitor and which needs richer context.", "Inspect current evidence sources.", "Document the missing observability capability."], reflection: "Why is a system with many dashboards not necessarily observable?" },
  { id: "logs-metrics-traces", title: "Logs, Metrics and Traces", intro: "Logs capture discrete events, metrics summarize numeric behavior over time, and traces connect work across request and dependency boundaries. They overlap but answer different classes of operational questions.", principles: ["Use metrics for trends, rates and aggregate health.", "Use logs for event detail and diagnostic context.", "Use traces for causality and latency across a request path.", "Do not force every question into one telemetry type."], steward: ["A spike in Steward latency may be detected with metrics, narrowed to a route with dimensions, explained through traces and confirmed with correlated application/database logs.", "Nexus publish failures may require different signals from API request latency."], practice: ["Take one Steward reliability question and state what logs, metrics and traces could each contribute.", "Identify redundant or missing signals.", "Capture one example of each available signal type.", "Explain which signal gives the strongest evidence for the question."], reflection: "When would a trace be more useful than adding another log line to Steward?" },
  { id: "telemetry-design", title: "Telemetry Design", intro: "Telemetry design selects events, measurements, dimensions and context that preserve useful operational meaning without creating uncontrolled cost or cardinality.", principles: ["Design from decisions and diagnostic questions.", "Choose dimensions that separate meaningful system behavior.", "Avoid unbounded high-cardinality attributes in metric labels.", "Emit enough context to connect symptoms to components and operations."], steward: ["Useful Steward dimensions may include route, status class, operation type, dependency and environment; raw user IDs or arbitrary resource names may be inappropriate metric labels.", "Security and privacy constraints from Security Steward remain part of telemetry design."], practice: ["Select three questions from the Reliability Risk Map.", "Design the minimum telemetry for each.", "Classify proposed fields as metric labels, log fields or trace attributes.", "Remove one field whose value or cardinality does not justify its cost."], reflection: "Why can adding user_id as a Prometheus label create an operational problem even if it seems diagnostically useful?" },
  { id: "correlation-context", title: "Correlation and Context", intro: "Individual telemetry records become far more useful when engineers can connect them across layers. Correlation identifiers, trace context, timestamps and stable service metadata turn isolated events into an incident timeline.", principles: ["Propagate request or trace context across boundaries.", "Use consistent service/environment identifiers.", "Preserve timestamps and outcome context.", "Avoid correlation fields that expose sensitive values."], steward: ["A Steward request may pass through reverse proxy, API logic, PostgreSQL and internal services. Without shared context, simultaneous log entries can be difficult to associate confidently.", "The same principle applies to delivery events that publish or consume internal packages."], practice: ["Trace one Steward request through currently available evidence.", "Identify where correlation breaks.", "Add or design one correlation mechanism.", "Verify that a single transaction can be reconstructed without searching by sensitive payload values."], reflection: "Why are timestamps alone often insufficient to correlate events across Steward components?" },
  { id: "instrumentation", title: "Instrumentation", intro: "Instrumentation is the code and configuration that produces telemetry. Effective instrumentation lives near meaningful work: request boundaries, dependency calls, state transitions and failure handling.", principles: ["Instrument service boundaries and important operations.", "Measure outcomes as well as attempts.", "Capture latency around work whose duration matters.", "Keep instrumentation maintainable and testable."], steward: ["Steward should instrument API request behavior and important dependency interactions without scattering ad-hoc debug prints throughout domain code.", "Framework middleware and shared telemetry helpers can standardize common fields, while domain-specific events remain close to the domain action."], practice: ["Choose one Steward operation with insufficient evidence.", "Identify the best instrumentation boundary.", "Add or design an event/measurement/span with outcome and duration context.", "Exercise success and failure paths and compare emitted evidence."], reflection: "Why should instrumentation usually target a service or operation boundary rather than every function call?" },
  { id: "opentelemetry", title: "OpenTelemetry Concepts", intro: "OpenTelemetry provides vendor-neutral APIs, SDKs, semantic conventions and transport mechanisms for traces, metrics and logs. Its value is consistency and portability, not automatic observability.", principles: ["Separate instrumentation from telemetry backend choice where practical.", "Understand providers, exporters, resources and context propagation.", "Use semantic conventions when they improve interoperability.", "Adopt incrementally around concrete operational needs."], steward: ["Steward can use OpenTelemetry to standardize service identity, request spans and dependency context while still exporting to different analysis backends later.", "Instrumentation must still be designed around Steward's questions; OpenTelemetry does not decide what matters."], practice: ["Map OpenTelemetry resource, span and exporter concepts to Steward.", "Instrument or sketch one request/dependency span.", "Include service/environment metadata and outcome.", "Verify propagation across one boundary where feasible."], reflection: "What problem does OpenTelemetry solve for Steward, and what observability problems does it deliberately not solve?" },
  { id: "golden-signals", title: "Golden Signals and Service Questions", intro: "Latency, traffic, errors and saturation are useful starting signals because they describe common service symptoms. They are most powerful when adapted to actual service capabilities and user questions.", principles: ["Use golden signals as prompts, not mandatory dashboards.", "Measure latency distributions rather than only averages.", "Define errors from user/service semantics.", "Measure saturation at constrained resources that can affect service."], steward: ["Steward traffic may be API requests or important background operations; errors should distinguish expected client rejection from service failure; saturation may come from database connections, CPU, memory or repository storage.", "Nexus has different service questions: download/publish success, latency, storage growth and dependency availability."], practice: ["Choose one Steward capability.", "Define relevant latency, traffic, error and saturation questions.", "Identify where each signal would come from.", "Mark any golden signal that is not meaningful and replace it with a better service-specific question."], reflection: "Why should a 404 validation or lookup result not automatically count as a Steward reliability error?" },
  { id: "telemetry-cost-noise", title: "Telemetry Cost and Noise", intro: "Telemetry consumes storage, network, compute and human attention. Excess volume and high cardinality can make observability slower, more expensive and harder to use during incidents.", principles: ["Retain signals according to diagnostic and compliance value.", "Control high-cardinality dimensions deliberately.", "Sample where appropriate without destroying critical evidence.", "Remove telemetry that no longer supports decisions."], steward: ["Recording every request body, unique user identifier and dependency payload would create cost and security problems without proportional reliability value.", "Later production-logging and metrics modules will deepen signal-specific retention and aggregation decisions."], practice: ["Review a proposed Steward telemetry set.", "Identify high-volume, high-cardinality and sensitive fields.", "Decide what to aggregate, sample, retain or remove.", "Document the diagnostic capability lost by each cost reduction."], reflection: "Why can excessive telemetry make incident diagnosis worse rather than better?" },
];

const lab: Lesson = { id: "observability-steward-lab", title: "Lab: Design Steward Observability", activities: [
  { id: "observability-steward-lab-001", title: "Turn Reliability Risks into Questions", estimatedMinutes: 75, content: { type: "practical", objective: "Translate the Steward Reliability Risk Map into concrete operational questions.", scenario: "Use the previous module's risk and capability maps as the source of observability requirements.", instructions: ["Select 5–8 high-value reliability questions.", "For each, define the decision or diagnosis it should support.", "Identify the relevant user/service boundary and dependencies.", "State what evidence would be sufficient and what would remain unknown."], deliverables: ["Observability question catalog", "Evidence requirements", "Priority ranking"], completionCriteria: ["Questions are tied to real Steward risks.", "Questions describe decisions or diagnosis rather than desired dashboards.", "Unknowns are explicit." ] } },
  { id: "observability-steward-lab-002", title: "Design the Telemetry Model", estimatedMinutes: 105, content: { type: "practical", objective: "Design logs, metrics, traces and correlation context that answer the selected Steward questions.", scenario: "Use the smallest telemetry model that preserves useful diagnostic power.", instructions: ["Map each question to logs, metrics, traces or a combination.", "Define service/environment/resource context.", "Define correlation and trace propagation requirements.", "Review metric cardinality, sensitive-data risk and expected volume.", "Mark telemetry that belongs later in Production Logging or Prometheus/Grafana implementation."], deliverables: ["Steward telemetry model", "Correlation design", "Cost/privacy review", "Implementation backlog"], completionCriteria: ["Every proposed signal answers at least one question.", "High-cardinality and sensitive fields are controlled.", "Implementation responsibilities are separated by later module." ] } },
  { id: "observability-steward-lab-003", title: "Prototype and Validate One Diagnostic Path", estimatedMinutes: 90, content: { type: "practical", objective: "Prove that the observability design can explain one representative Steward behavior end to end.", scenario: "Implement a narrow slice rather than the entire future observability stack.", instructions: ["Choose one request or dependency flow.", "Add the minimum useful instrumentation and correlation context.", "Execute normal and controlled failure/degradation behavior.", "Use emitted telemetry to reconstruct what happened.", "Record gaps that Production Logging, metrics or tracing implementation must close."], deliverables: ["Prototype telemetry", "Diagnostic walkthrough", "Observed gaps", "Refined implementation backlog"], completionCriteria: ["Telemetry supports a real diagnosis.", "Success and failure evidence can be distinguished.", "The learner can state what remains unobservable." ] } },
] };

export const observabilityDeepLessons: Lesson[] = [...specs.map(lessonFrom), lab];
