import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const aws: LearningResource = { title: "AWS Well-Architected: Disaster Recovery", url: "https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/plan-for-disaster-recovery-dr.html" };
const postgres: LearningResource = { title: "PostgreSQL: Backup and Restore", url: "https://www.postgresql.org/docs/current/backup.html" };
const cisa: LearningResource = { title: "CISA: Data Backup Options", url: "https://www.cisa.gov/news-events/news/data-backup-options", kind: "reference" };
const postgresContinuous: LearningResource = { title: "PostgreSQL — Continuous Archiving and PITR", url: "https://www.postgresql.org/docs/current/continuous-archiving.html", kind: "documentation" };
const awsRpoRto: LearningResource = { title: "AWS — Disaster Recovery Objectives", url: "https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/plan-for-disaster-recovery-dr.html", kind: "reference" };
const resourcesByRecoveryTopic: Record<string, LearningResource[]> = {
  backups: [cisa, postgres], "backup-integrity": [cisa, postgres],
  "restore-testing": [postgres, aws], "rpo-rto": [awsRpoRto, postgresContinuous],
  "disaster-scenarios": [aws], "recovery-procedures": [aws, cisa],
  "database-recovery": [postgres, postgresContinuous],
  "artifact-repository-recovery": [aws, cisa],
  "configuration-infrastructure-recovery": [aws],
  "recovery-evidence": [awsRpoRto, postgres],
};

type Spec = { id: string; title: string; intro: string; principles: string[]; steward: string[]; practice: string[]; reflection: string };
function lessonFrom(spec: Spec): Lesson {
    const blocks: LessonBlock[] = [{ type: "paragraph", text: spec.intro }, { type: "heading", id: `${spec.id}-principles`, text: "Recovery model", level: 2 }, { type: "list", items: spec.principles }, { type: "heading", id: `${spec.id}-steward`, text: "Apply it to Steward", level: 2 }, ...spec.steward.map((text): LessonBlock => ({ type: "paragraph", text })), { type: "callout", tone: "steward", title: "A backup is not a recovery", body: "Steward is recoverable only when required data, configuration, artifacts and dependencies can be restored into a usable service within understood loss and time bounds. Backup-job success alone is not proof." }, { type: "resources", title: "Continue learning", resources: resourcesByRecoveryTopic[spec.id] ?? [aws, postgres] }];
    return { id: `data-protection-dr-${spec.id}`, title: spec.title, activities: [
        { id: `data-protection-dr-${spec.id}-001`, title: spec.title, estimatedMinutes: 50, content: { type: "reading", body: spec.intro, blocks } },
        { id: `data-protection-dr-${spec.id}-002`, title: `Recover: ${spec.title}`, estimatedMinutes: 60, content: { type: "practical", objective: `Apply ${spec.title} to Steward recovery planning.`, scenario: "Start from the exact Reliability baseline and classify each active component as authoritative mutable state, reproducible state, derived/rebuildable state or external dependency. Protect only what recovery actually requires, then prove the recovery path with learner-owned evidence.", instructions: spec.practice, deliverables: ["Recovery design or evidence", "Measured/declared loss and time assumptions", "Residual-risk note"], completionCriteria: ["The protected asset and failure scenario are explicit.", "Recovery depends on evidence rather than backup-job status.", "Security and integrity requirements remain valid during restoration." ] } },
        { id: `data-protection-dr-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.reflection, minimumCharacters: 200 } },
    ] };
}

const specs: Spec[] = [
    { id: "backups", title: "Backups", intro: "Backups create recoverable copies of state outside the failure domain of the primary system. A useful backup strategy starts from assets and failure scenarios, then chooses frequency, isolation, retention and protection accordingly.", principles: ["Inventory state before selecting backup tools.", "Keep recovery copies outside the same failure domain as the primary.", "Protect backup confidentiality and access as strongly as production data.", "Retention and frequency should follow recovery needs, not storage habit."], steward: ["PostgreSQL is Steward's authoritative application data store and its transactional outbox contains durable publication intent. Nexus contains retained internal release/package artifacts required for deterministic build/rollback workflows, while Git-backed application, infrastructure and environment declarations are reproducible sources of desired state. Redis cache state is derived. RabbitMQ is not authoritative business state, but durable queued messages may be delivery-critical until consumed; its recovery treatment must follow the established broker durability/replay design rather than being dismissed as merely transient. Prometheus/Tempo telemetry and other derived data must not automatically be promoted to authoritative backup scope.", "A backup stored on the same disk or host may disappear with the primary failure."], practice: ["Inventory the actual Steward baseline and classify PostgreSQL, Nexus, Git-backed definitions, Vault/PKI recovery material and any Redis/RabbitMQ state by authority and recovery semantics before choosing backup methods.", "Map each protected asset to backup method, frequency, location and retention.", "Identify shared failure domains.", "Document access/encryption expectations without exposing real secrets."], reflection: "Why is copying the Steward database to another directory on the same host a weak disaster-recovery strategy?" },
    { id: "backup-integrity", title: "Backup Integrity", intro: "A backup can exist and still be unusable because it is incomplete, corrupted, inconsistent, encrypted with an unavailable key or silently missing required state. Integrity controls make backup quality observable before an emergency.", principles: ["Verify backup completion and expected content.", "Use checksums or tool-supported validation where appropriate.", "Protect metadata, encryption keys and restore instructions needed to interpret the copy.", "Alert on missing or stale backups, not only explicit job failures."], steward: ["A successful PostgreSQL dump command is weaker evidence than a copy that can be parsed/restored and whose expected schema/data are present.", "Nexus recovery also depends on consistent repository/blob/configuration state according to the platform's supported procedure."], practice: ["Choose one Steward backup artifact.", "Define integrity and freshness checks.", "Verify the copy without modifying production state.", "Document a failure that job-success monitoring would miss."], reflection: "How can a backup job report success while the organization still has no usable recovery point?" },
    { id: "restore-testing", title: "Restore Testing", intro: "Restore testing converts backup assumptions into recovery evidence. The test must reconstruct usable state in an isolated target and verify application-level outcomes, not merely confirm that files can be copied back.", principles: ["Restore into an isolated or controlled target.", "Measure the process from decision/start through usable service state.", "Verify data and application behavior after restoration.", "Capture manual steps and hidden dependencies as improvement opportunities."], steward: ["A restored Steward database should be consumed by an application instance and checked through representative service behavior.", "Restore drills expose missing roles, configuration, credentials, DNS, storage or artifact dependencies that backup creation alone cannot reveal."], practice: ["Choose a recent controlled recovery point.", "Restore it to an isolated Steward environment.", "Verify schema, representative data and one application workflow.", "Record elapsed time, failures and undocumented steps."], reflection: "Why is successfully importing a PostgreSQL dump not by itself proof that Steward has recovered?" },
    { id: "rpo-rto", title: "RPO and RTO", intro: "Recovery Point Objective expresses tolerable data loss in time; Recovery Time Objective expresses the desired time to restore a capability after disruption. They are business/reliability targets that drive technical design and must be distinguished from measured outcomes.", principles: ["RPO is about acceptable state loss; RTO is about acceptable recovery duration.", "Targets should reflect capability criticality and cost trade-offs.", "Backup frequency alone does not guarantee RPO.", "Measured restore duration should be compared with RTO rather than confused with it."], steward: ["Steward database and Nexus may have different RPO/RTO expectations because losing current registry state differs from temporarily losing artifact publication/download capability.", "The learner should state assumptions explicitly before choosing expensive replication or very frequent backups."], practice: ["Define provisional RPO/RTO for Steward database and artifact platform.", "Explain business/engineering rationale.", "Compare current backup frequency and measured restore evidence to those objectives.", "Identify any gap without hiding it behind a target."], reflection: "If Steward has an RTO of one hour but the last drill took 95 minutes, what does that tell you?" },
    { id: "disaster-scenarios", title: "Disaster Scenarios", intro: "Disaster recovery planning should be scenario-based because different failures destroy different combinations of data, infrastructure, credentials and control-plane access. One generic 'server down' plan rarely covers the real recovery problem.", principles: ["Model loss of host, storage, database, region/site, credentials and operator access separately where relevant.", "Include accidental deletion and malicious/destructive change alongside hardware failure.", "Identify correlated failures that affect both primary and backup paths.", "Prioritize scenarios by impact and plausible exposure."], steward: ["Useful scenarios include PostgreSQL data loss, complete host loss, corrupted deployment/configuration state and Nexus repository/storage loss.", "A security incident may require recovery from a known-clean point rather than simply restoring the newest copy."], practice: ["Define four distinct Steward disaster scenarios.", "For each, identify lost assets and surviving recovery assets.", "Map detection, decision authority and recovery path.", "Select one scenario for the final restore drill."], reflection: "Why might the newest available backup be the wrong recovery point after a destructive security incident?" },
    { id: "recovery-procedures", title: "Recovery Procedures", intro: "A recovery procedure is an executable sequence with prerequisites, ownership, validation and stop/escalation points. It should reduce cognitive load during disruption while allowing operators to adapt when reality differs from the document.", principles: ["State prerequisites and decision authority before commands.", "Order dependencies so restored components have what they need.", "Include verification and rollback/escalation points.", "Keep procedures maintained through drills, not only document reviews."], steward: ["Steward recovery may require infrastructure/network, database, application configuration, secrets references and supporting platform restoration in a deliberate order.", "Runbooks should distinguish destructive commands and use placeholders/synthetic evidence for sensitive values."], practice: ["Draft a recovery sequence for one Steward disaster scenario.", "Identify prerequisites and owners.", "Add verification gates after major steps.", "Walk the procedure against a clean environment and mark ambiguous instructions."], reflection: "What makes a recovery runbook operationally useful rather than merely a list of commands?" },
    { id: "database-recovery", title: "Database Recovery", intro: "Database recovery must preserve consistency and match the selected recovery point. PostgreSQL supports logical and physical approaches with different capabilities; the right method depends on scale, RPO, RTO and operational maturity.", principles: ["Understand logical dump/restore versus physical/base-backup approaches conceptually.", "Restore roles, extensions and schema dependencies as required.", "Validate constraints and representative data after recovery.", "Point-in-time recovery requires the complete chain of base backup and WAL needed for the target."], steward: ["For the academy environment, a simpler supported PostgreSQL strategy may be more defensible than prematurely operating complex continuous recovery infrastructure.", "The learner must still understand what tighter RPO/RTO would require architecturally."], practice: ["Document Steward's current PostgreSQL backup/recovery method.", "List database-level prerequisites beyond table rows.", "Perform or rehearse a controlled restore.", "Explain when the current method would cease to satisfy future RPO/RTO."], reflection: "Why can selecting a more sophisticated PostgreSQL recovery mechanism increase operational risk if the team cannot reliably operate or test it?" },
    { id: "artifact-repository-recovery", title: "Artifact Repository Backup and Restore", intro: "An internal artifact repository holds reproducible build inputs and release history that can be essential during rollback or rebuild. Its recovery plan must follow the repository platform's supported consistency model rather than treating its storage as an arbitrary folder.", principles: ["Identify repository metadata, blob/artifact storage and configuration required for a consistent restore.", "Use platform-supported backup/restore guidance.", "Protect package integrity and access controls after restoration.", "Verify consumers can resolve known internal packages after recovery."], steward: ["Nexus serves Steward OCI releases and any internal packages whose earlier extraction gates were actually earned; losing it can prevent deterministic builds and emergency rollback even when source code survives. If `steward-common` extraction was deferred, that recorded absence remains valid architecture evidence. `tsa-test-core` is still only a future reuse hypothesis and must not be used as recovery evidence yet.", "Recovery evidence should include a consumer resolving or downloading a known package, not only the Nexus process starting."], practice: ["Map Nexus state required for recovery.", "Define a supported backup and restore sequence for the learner-owned platform.", "Identify a known Steward artifact/version for verification, and include an internal package only if its extraction gate was actually earned.", "Document how storage growth/retention policy affects recovery scope."], reflection: "Why does a running Nexus process after restoration not prove that Steward's artifact ecosystem has recovered?" },
    { id: "configuration-infrastructure-recovery", title: "Configuration and Infrastructure Recovery", intro: "Recovering data without the infrastructure and configuration required to use it leaves the service unavailable. Reproducible infrastructure, versioned configuration and documented external dependencies reduce the amount of unique mutable state that must be protected.", principles: ["Prefer reproducible definitions over undocumented manual state.", "Separate configuration from secrets while preserving recoverable references and procedures.", "Know which external resources cannot be recreated automatically.", "Test bootstrap from a clean environment periodically."], steward: ["Git can preserve application and infrastructure definitions, but DNS, credentials, external identities, certificates or platform state may require separate recovery procedures.", "A clean rebuild is useful evidence that the academy's automation is actually sufficient."], practice: ["Inventory Steward infrastructure/configuration sources of truth.", "Identify mutable or external state not recoverable from Git.", "Recreate one controlled component from versioned definitions.", "Record every manual prerequisite discovered."], reflection: "Why does having Infrastructure as Code not automatically mean the whole Steward environment is recoverable?" },
    { id: "recovery-evidence", title: "Recovery Evidence", intro: "Recovery evidence demonstrates that a stated capability was restored, how much state was lost and how long recovery took. It turns disaster recovery from policy language into an engineering capability that can be reviewed and improved.", principles: ["Timestamp key recovery events and decision points.", "Verify user-visible/application outcomes after infrastructure health checks.", "Compare actual data loss and duration with RPO/RTO targets.", "Record deviations, manual work and residual risk."], steward: ["Evidence can include restore logs, checksums, application requests, package resolution, dashboards and a recovery timeline while excluding secrets and sensitive payloads.", "The final drill should produce a reusable evidence pack for the Reliability Engineer milestone."], practice: ["Define the evidence pack before a drill.", "Include technical and user-visible verification.", "Calculate or bound actual recovery point loss.", "Compare measured recovery duration to target and create follow-up actions."], reflection: "What evidence would convince a skeptical reviewer that Steward was actually restored rather than merely restarted?" },
];

const lab: Lesson = { id: "data-protection-dr-restore-drill", title: "Lab: Run a Steward Restore Drill", activities: [
    { id: "data-protection-dr-restore-drill-001", title: "Plan the Recovery Exercise", estimatedMinutes: 90, content: { type: "practical", objective: "Define a safe, measurable Steward recovery scenario before touching recoverable state.", scenario: "Choose a learner-owned disaster scenario involving critical Steward data and include one supporting platform dependency such as Nexus where practical.", instructions: ["State the scenario, protected assets and assumed failure boundary.", "Declare RPO/RTO targets and current evidence supporting them.", "Select recovery point and define isolation/safety controls.", "Prepare verification checklist, timestamps to capture and abort/escalation conditions."], deliverables: ["Restore drill plan", "RPO/RTO targets", "Verification checklist", "Safety/rollback plan"], completionCriteria: ["No production or third-party data is placed at risk.", "Success means usable capability, not merely completed commands.", "Timing and data-loss measurement are defined before the drill." ] } },
    { id: "data-protection-dr-restore-drill-002", title: "Restore and Verify Steward", estimatedMinutes: 180, content: { type: "practical", objective: "Restore Steward state and prove that recovered capabilities are usable.", scenario: "Execute the documented recovery path into a controlled environment and treat unexpected manual steps as evidence, not something to hide.", instructions: ["Start the recovery timeline and recreate required infrastructure/configuration from OpenTofu, Ansible, GitOps or other versioned definitions in dependency order. Treat this as environment reconstruction, not as restoration of persistent application/platform data.", "Restore PostgreSQL from the selected recovery point.", "Restore or validate the chosen supporting dependency/repository path.", "Start the complete Steward application release and execute representative API verification plus one lifecycle mutation that proves durable outbox intent can resume publication and reach the consumer after recovery.", "Verify known data and, for Nexus, resolve a known internal artifact/version where included.", "Record actual recovery duration, data-loss boundary and every deviation."], deliverables: ["Recovery timeline", "Database restore evidence", "Application verification", "Supporting-platform verification", "Deviation log"], completionCriteria: ["Recovered Steward performs the selected synchronous capability and, where the scenario includes the messaging path, resumes durable asynchronous work without inventing or silently losing committed publication intent.", "Data integrity is checked beyond process health.", "Actual recovery time and point are measurable." ] } },
    { id: "data-protection-dr-restore-drill-003", title: "Publish the Recovery Review", estimatedMinutes: 90, content: { type: "practical", objective: "Turn the drill into durable reliability improvements and milestone evidence.", scenario: "Compare demonstrated recovery capability with the objectives declared before the exercise.", instructions: ["Compare measured RPO/RTO outcomes with targets.", "Classify gaps: backup, tooling, documentation, access, infrastructure, dependency or operator toil.", "Update recovery runbooks from observed reality.", "Create prioritized corrective actions with evidence required for closure.", "Package non-sensitive recovery evidence for the Reliability Engineer milestone."], deliverables: ["Steward recovery review", "Updated runbook", "Corrective-action backlog", "Milestone evidence pack"], completionCriteria: ["Claims are backed by drill evidence.", "Missed objectives are recorded plainly.", "The next drill can start from an improved procedure." ] } },
] };

export const dataProtectionAndDisasterRecoveryDeepLessons: Lesson[] = [...specs.map(lessonFrom), lab];
