import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const prometheus: LearningResource = { title: "Prometheus Documentation", url: "https://prometheus.io/docs/introduction/overview/" };
const promql: LearningResource = { title: "Prometheus Querying Basics", url: "https://prometheus.io/docs/prometheus/latest/querying/basics/" };
const grafana: LearningResource = { title: "Grafana Documentation", url: "https://grafana.com/docs/grafana/latest/" };
const otelMetrics: LearningResource = { title: "OpenTelemetry Metrics", url: "https://opentelemetry.io/docs/concepts/signals/metrics/" };

type Spec = { id: string; title: string; intro: string; principles: string[]; steward: string[]; practice: string[]; reflection: string };

function lessonFrom(spec: Spec): Lesson {
    const blocks: LessonBlock[] = [
        { type: "paragraph", text: spec.intro },
        { type: "heading", id: `${spec.id}-model`, text: "Metrics mental model", level: 2 },
        { type: "list", items: spec.principles },
        { type: "heading", id: `${spec.id}-steward`, text: "Apply it to Steward", level: 2 },
        ...spec.steward.map((text): LessonBlock => ({ type: "paragraph", text })),
        { type: "callout", tone: "steward", title: "Question before chart", body: "A metric is valuable when its meaning, labels and aggregation support a concrete reliability decision. A dashboard full of available numbers is not evidence that Steward is observable." },
        { type: "resources", title: "Continue learning", resources: [prometheus, promql, grafana, otelMetrics] },
    ];
    return { id: `metrics-prometheus-grafana-${spec.id}`, title: spec.title, activities: [
        { id: `metrics-prometheus-grafana-${spec.id}-001`, title: spec.title, estimatedMinutes: 50, content: { type: "reading", body: spec.intro, blocks } },
        { id: `metrics-prometheus-grafana-${spec.id}-002`, title: `Measure: ${spec.title}`, estimatedMinutes: 60, content: { type: "practical", objective: `Apply ${spec.title} to Steward telemetry.`, scenario: "Start from the operational questions and logging model already created. Add or query metrics only when they improve measurement of service behavior, dependency health, resource pressure or delivery reliability.", instructions: spec.practice, deliverables: ["Metric/query/dashboard evidence", "Meaning and label definition", "Operational interpretation"], completionCriteria: ["The signal has defined semantics.", "Labels avoid uncontrolled cardinality.", "The learner can explain what decision the result supports and what it does not prove."] } },
        { id: `metrics-prometheus-grafana-${spec.id}-003`, title: `Knowledge Check: ${spec.title}`, estimatedMinutes: 10, content: { type: "reflection", prompt: spec.reflection, minimumCharacters: 200 } },
    ] };
}

const specs: Spec[] = [
    { id: "mental-models", title: "Metrics Mental Models", intro: "Metrics are numerical observations aggregated across time and dimensions. They are efficient for trends, rates and thresholds, but deliberately discard the event-level detail that logs and traces preserve.", principles: ["Define the phenomenon before the metric name.", "Know whether the value is cumulative, instantaneous or distributed.", "Use dimensions that support useful grouping without exploding cardinality.", "Pair metrics with logs or traces when diagnosis needs individual-event context."], steward: ["Steward needs metrics that describe user-facing API behavior, PostgreSQL/resource pressure, delivery dependencies and internal artifact-platform health.", "Metrics should answer questions from the Reliability Risk Map: traffic, failures, latency, saturation, dependency health and growth."], practice: ["Choose three existing Steward operational questions.", "For each, define a measurable phenomenon and unit.", "Decide whether a metric is actually the best signal.", "Define one metric including name, type, labels and interpretation."], reflection: "Why can a metric show that Steward is degraded without explaining which individual request caused the problem?" },
    { id: "metric-types", title: "Counters, Gauges and Histograms", intro: "Metric types encode how values behave. Counters accumulate events, gauges represent values that can rise and fall, and histograms preserve distributions through buckets so latency and size behavior can be aggregated.", principles: ["Use counters for cumulative events such as requests and failures.", "Use gauges for current state such as queue depth or storage usage.", "Use histograms for distributions such as latency and payload size.", "Do not model a distribution only with an average when tails matter."], steward: ["HTTP request totals and failed publishes fit counters; current Nexus storage consumption fits a gauge; Steward request duration fits a histogram.", "Choosing the wrong type makes later PromQL awkward or semantically misleading."], practice: ["Classify five candidate Steward measurements by type.", "Identify one tempting but incorrect type choice.", "Define histogram observations for one latency path.", "Explain what information an average would hide."], reflection: "Why is a histogram generally more useful than a single average for Steward request latency?" },
    { id: "application-infrastructure", title: "Application and Infrastructure Metrics", intro: "Application metrics describe service semantics while infrastructure metrics describe the resources that support them. Reliability diagnosis usually needs both, but they answer different questions.", principles: ["Measure user/service outcomes at the application boundary.", "Measure CPU, memory, disk, network and database pressure as supporting evidence.", "Do not infer user success solely from host health.", "Connect resource saturation to service symptoms through time and context."], steward: ["Steward API traffic/error/latency can be compared with container, host, PostgreSQL and Nexus resource signals.", "A CPU spike matters operationally when it explains or predicts a service symptom, not simply because the graph is high."], practice: ["Select one Steward failure scenario.", "Identify application and infrastructure signals needed to investigate it.", "Capture or define both layers.", "Explain which signal indicates symptom and which supports causal diagnosis."], reflection: "Why should an operator avoid paging solely because Steward host CPU crosses an arbitrary percentage?" },
    { id: "prometheus-architecture", title: "Prometheus Architecture", intro: "Prometheus collects time-series data primarily by scraping HTTP metric endpoints, stores labeled samples locally and evaluates queries and rules over those series. Understanding the pull model, scrape lifecycle and local storage boundary is essential before operating it.", principles: ["Know what Prometheus scrapes and how targets are discovered.", "Treat scrape success as telemetry health, not service success.", "Understand that labels form time-series identity.", "Plan retention and high availability according to actual operational needs."], steward: ["Prometheus can scrape Steward application metrics plus exporters for hosts, databases and supporting platforms.", "If Prometheus cannot scrape Steward, that may mean target failure, network/configuration failure or telemetry failure; diagnosis must distinguish them."], practice: ["Draw the intended Steward Prometheus topology.", "Identify scrape targets and ownership.", "Define scrape interval/retention assumptions.", "List failure modes that could produce an `up == 0` target."], reflection: "Why does Prometheus reporting a target as down not uniquely prove that the underlying Steward service is unavailable to users?" },
    { id: "exporters", title: "Exporters", intro: "Exporters translate systems that do not expose Prometheus-native metrics into a scrapeable format. They extend visibility but also introduce configuration, permissions and version compatibility concerns.", principles: ["Prefer native instrumentation for application semantics.", "Use exporters for infrastructure or third-party systems where appropriate.", "Grant exporters only the access required to observe.", "Treat exporter health and metric meaning as part of telemetry quality."], steward: ["Node and PostgreSQL exporters can expose host/database behavior while Nexus visibility may combine platform endpoints, JVM/process metrics or other supported integrations.", "An exporter should not receive administrative credentials merely because read-only telemetry is desired."], practice: ["Choose one Steward dependency suited to an exporter.", "Document the data source and required privileges.", "Identify useful metric families and unnecessary ones.", "Define how you would verify the exporter itself is healthy."], reflection: "When should Steward expose an application metric directly instead of relying on an infrastructure exporter?" },
    { id: "service-discovery", title: "Service Discovery Concepts", intro: "Static target lists become fragile as services move or scale. Service discovery lets Prometheus derive scrape targets from infrastructure metadata while relabeling controls which discovered endpoints become meaningful targets.", principles: ["Separate discovering endpoints from deciding which should be scraped.", "Keep target labels stable enough for useful queries.", "Understand how deployment changes alter target identity.", "Avoid hiding failed discovery behind a visually empty dashboard."], steward: ["A small Steward environment may start with static configuration, but the learner should understand how container/orchestrator/cloud discovery changes the model.", "The right choice depends on actual deployment complexity; service discovery is not mandatory ceremony."], practice: ["Document current Steward target discovery.", "Describe how one scaling or redeployment event affects it.", "Propose when static configuration stops being appropriate.", "Define a check that reveals missing expected targets."], reflection: "Why can automatic service discovery create observability gaps if operators do not know which targets should exist?" },
    { id: "promql", title: "PromQL", intro: "PromQL turns labeled time series into rates, aggregations, ratios and distributions. Correct queries depend on understanding metric semantics, counter behavior and label dimensions rather than memorizing syntax.", principles: ["Use rate-like functions for counters over time.", "Aggregate only across dimensions you intentionally discard.", "Protect ratios from mismatched label sets and denominator mistakes.", "Query distributions with the metric's bucket semantics in mind."], steward: ["Useful Steward queries include request rate, error ratio, latency distributions, resource saturation and dependency failure rates.", "Queries should be tested against known traffic/failure events so a plausible graph is not mistaken for a correct calculation."], practice: ["Write a query for Steward request rate.", "Write an error-ratio query with compatible dimensions.", "Query a latency histogram by endpoint or operation at a controlled cardinality.", "Validate one query against a known generated event."], reflection: "Why is dividing two Prometheus counters directly often less meaningful than comparing their rates over the same window?" },
    { id: "recording-rules", title: "Recording Rules Concepts", intro: "Recording rules precompute frequently used or expensive PromQL expressions into new time series. They can improve consistency and query cost, but poor rule design can multiply cardinality and hide the source semantics.", principles: ["Create rules for stable, reused service indicators.", "Keep names and labels traceable to the underlying meaning.", "Do not precompute every dashboard query.", "Review rule cardinality and evaluation health."], steward: ["A stable Steward request error ratio or latency indicator may eventually justify a recording rule, especially when reused for dashboards and SLOs.", "Service Level Engineering comes next, so this lesson prepares reusable indicators without prematurely defining SLO targets."], practice: ["Identify one repeatedly useful Steward PromQL expression.", "Decide whether a recording rule is justified.", "Define rule name and retained labels.", "Explain how you would verify the rule against its source query."], reflection: "What makes a PromQL expression a good recording-rule candidate rather than merely a query that happens to exist?" },
    { id: "grafana", title: "Grafana", intro: "Grafana presents and explores telemetry from data sources such as Prometheus. Its value is not the number of panels it can render but how quickly an engineer can move from service symptom to useful evidence.", principles: ["Treat the data source/query as primary and visualization as representation.", "Use variables only where they support real investigative dimensions.", "Preserve units, thresholds and legends that communicate meaning.", "Link related evidence when possible instead of creating isolated graphs."], steward: ["Grafana should expose Steward service behavior, dependencies and platform health through views derived from the operational questions already defined.", "A beautiful panel backed by a semantically wrong query is an observability defect."], practice: ["Connect or model Prometheus as the Steward Grafana data source.", "Build one panel from a validated PromQL query.", "Set meaningful unit/legend context.", "Use the panel to answer a stated operational question."], reflection: "Why should you validate PromQL independently before trusting the Grafana visualization built on top of it?" },
    { id: "dashboard-design", title: "Dashboard Design", intro: "A useful dashboard organizes signals around a service, audience and decision. It provides a fast view of symptoms and enough context to begin diagnosis without attempting to place every metric on one screen.", principles: ["Design for an audience and operational task.", "Lead with service symptoms and user impact.", "Group supporting dependency/resource evidence coherently.", "Use consistent time windows, units and naming."], steward: ["A Steward service overview can begin with traffic, errors, latency and saturation, then expose PostgreSQL/Nexus/deployment context needed for investigation.", "Specialized capacity or dependency dashboards can exist separately instead of turning the overview into a wall of charts."], practice: ["Define the audience for one Steward dashboard.", "Choose the minimum panels needed for first-pass diagnosis.", "Order panels from service symptoms toward supporting causes.", "Walk through a hypothetical incident using only the dashboard and identify missing context."], reflection: "What should appear near the top of a Steward operational dashboard: host internals or user-visible service symptoms, and why?" },
    { id: "dashboard-antipatterns", title: "Dashboard Anti-patterns", intro: "Dashboards fail when they optimize for visual density, arbitrary thresholds or telemetry availability rather than decisions. Common anti-patterns include wall-of-graphs layouts, unexplained single stats and panels nobody uses during incidents.", principles: ["Remove panels that do not answer a recurring question.", "Avoid traffic-light colors without meaningful objectives.", "Do not hide distributions behind averages.", "Review dashboards after incidents to learn what was actually useful."], steward: ["Steward should not gain a panel for every Prometheus metric simply because it is scrapeable.", "The learner should be able to explain why each primary panel exists and what action or investigation it supports."], practice: ["Review a current or proposed Steward dashboard.", "Identify three low-value or misleading panel patterns.", "Remove, combine or redesign them.", "Document one signal better explored ad hoc than permanently displayed."], reflection: "Why can a dashboard with fewer panels provide better operational visibility than one containing every available metric?" },
    { id: "nexus-platform-metrics", title: "Nexus and Internal Platform Metrics", intro: "Once an internal artifact repository becomes part of build, test and deployment workflows, its reliability becomes part of product delivery reliability. Visibility should cover service availability, storage pressure and publish/download behavior.", principles: ["Measure platform symptoms that affect consumers.", "Track storage growth before exhaustion becomes an incident.", "Separate repository/application availability from host health.", "Observe publish/download failures without exposing credentials or sensitive package metadata unnecessarily."], steward: ["Nexus supports `steward-common`, `tsa-test-core` and other internal dependencies, so repository failure can block CI, QA or deployment even when Steward itself is healthy.", "The reliability program therefore treats the artifact platform as a first-class dependency."], practice: ["Define Nexus consumer-visible reliability questions.", "Identify metrics for availability, resource/storage pressure and operation failures.", "Design a Grafana view that distinguishes platform symptom from host saturation.", "Define one storage-growth signal useful for later capacity planning."], reflection: "Why should Nexus availability be measured from the perspective of package consumers rather than only from process uptime?" },
    { id: "ci-delivery-metrics", title: "CI and Delivery Metrics", intro: "Delivery systems are operational systems. Metrics can reveal pipeline failure, queueing and duration trends, but they should support delivery reliability rather than becoming simplistic productivity scores.", principles: ["Measure pipeline/service behavior, not individual developer worth.", "Distinguish failure by stage or dependency where possible.", "Track duration distributions rather than only averages.", "Connect delivery failures to dependencies such as Nexus, runners and deployment targets."], steward: ["Steward CI depends on tests, internal packages and deployment infrastructure. Metrics can show whether reliability problems originate in application changes or the delivery platform.", "These signals complement, rather than replace, the quality evidence built in earlier schools."], practice: ["Define three delivery-reliability questions for Steward.", "Choose metrics for run outcomes, duration and dependency failures.", "Avoid labels that create per-commit or per-user cardinality explosions.", "Sketch a delivery reliability view and explain what decision it supports."], reflection: "Why is pipeline failure rate a better reliability signal than using raw deployment count as a proxy for engineering performance?" },
];

const instrumentLab: Lesson = { id: "metrics-prometheus-grafana-instrument-steward", title: "Lab: Instrument Steward API", activities: [
    { id: "metrics-prometheus-grafana-instrument-steward-001", title: "Define and Expose Steward Metrics", estimatedMinutes: 120, content: { type: "practical", objective: "Instrument Steward with a small, semantically sound metric set.", scenario: "Use operational questions from Observability and logging evidence to select metrics rather than exposing every internal variable.", instructions: ["Define request traffic, failure and latency metrics with controlled labels.", "Add one meaningful application/domain or dependency metric.", "Expose metrics for Prometheus scraping using the project's appropriate instrumentation path.", "Generate known traffic and verify metric behavior."], deliverables: ["Steward instrumentation", "Metric contract", "Known-event verification"], completionCriteria: ["Metric types and labels match their semantics.", "No unbounded identifiers are used as labels.", "Known events produce explainable samples." ] } },
    { id: "metrics-prometheus-grafana-instrument-steward-002", title: "Scrape, Query and Visualize Steward", estimatedMinutes: 120, content: { type: "practical", objective: "Turn Steward metrics into validated Prometheus queries and useful Grafana views.", scenario: "Operate the telemetry path end to end: target discovery/scraping, PromQL and visualization.", instructions: ["Configure the Steward scrape target and verify target health.", "Build queries for request rate, error ratio and latency distribution.", "Add infrastructure/dependency context where available.", "Build a compact Grafana service view from validated queries.", "Create a controlled failure or error event and confirm the view reflects it."], deliverables: ["Prometheus target/config evidence", "Validated PromQL", "Grafana service dashboard", "Controlled-event evidence"], completionCriteria: ["Queries are validated against known behavior.", "Dashboard panels answer stated operational questions.", "The learner distinguishes telemetry-path failure from service failure." ] } },
] };

const nexusLab: Lesson = { id: "metrics-prometheus-grafana-observe-artifact-platform", title: "Lab: Observe the Internal Artifact Platform", activities: [
    { id: "metrics-prometheus-grafana-observe-artifact-platform-001", title: "Measure Nexus as a Delivery Dependency", estimatedMinutes: 105, content: { type: "practical", objective: "Make the internal artifact platform measurable as a dependency of Steward delivery and testing.", scenario: "Nexus now serves internal packages including steward-common and tsa-test-core. Observe it from both platform and consumer perspectives.", instructions: ["Define consumer-visible availability and operation questions.", "Collect supported process/host/platform metrics without overprivileged telemetry credentials.", "Track storage utilization/growth and representative publish/download failure evidence.", "Build a focused Grafana view for platform health and capacity.", "Document gaps where a desired consumer outcome cannot yet be measured directly."], deliverables: ["Artifact-platform metric inventory", "Prometheus evidence", "Nexus Grafana view", "Measurement-gap note"], completionCriteria: ["The view includes consumer-relevant symptoms and supporting resource signals.", "Storage capacity is observable.", "Missing evidence is explicit rather than inferred from host uptime." ] } },
] };

export const metricsPrometheusGrafanaDeepLessons: Lesson[] = [...specs.map(lessonFrom), instrumentLab, nexusLab];
