import type { Lesson } from "./lesson";

export const internalPkiMachineTrustDeepLessons: Lesson[] = [
    {
        id: "pki-trust-model",
        title: "Model Internal PKI and Machine Trust",
        summary: "Separate public web PKI, internal workload identity, human identity and secret storage before introducing another certificate authority.",
        objectives: ["Explain root, intermediate and leaf certificate responsibilities.", "Distinguish authentication identity from authorization.", "Define boundaries between public ACME, internal PKI, Vault, Keycloak and OS trust stores."],
        activities: [{ type: "exercise", title: "Trust responsibility map", description: "Map Steward public TLS, internal service-to-service TLS, Keycloak/OIDC, Vault secrets and Rocky/Windows trust stores. Design an offline/protected root CA plus an online issuing intermediate for the lab. State explicitly that public Kong certificates remain under the existing ACME lifecycle and that possession of a valid machine certificate does not grant Steward domain authorization." }],
    },
    {
        id: "pki-ca-hierarchy",
        title: "Build a Root and Issuing CA Hierarchy",
        summary: "Implement a bounded CA hierarchy whose root is not used as the routine online signer.",
        objectives: ["Create and protect root/intermediate private keys.", "Apply CA constraints and appropriate validity periods.", "Verify the resulting chain independently."],
        activities: [{ type: "practical", title: "Internal CA hierarchy", objective: "Create a two-tier lab PKI with a protected root and operational issuing CA.", scenario: "Internal workloads need identities that public ACME certificates are not intended to provide.", instructions: ["Use OpenSSL or a justified PKI implementation to create a lab root CA with strong key protection; never commit private keys or passwords to Git/evidence.", "Create an issuing/intermediate CA signed by the root with CA/basic-constraints and key-usage restrictions appropriate to an issuer.", "Store the root offline or otherwise unavailable to routine service issuance after the intermediate is created.", "Define separate directories/permissions for CA private material, issued certificates and public trust material.", "Verify the intermediate chain against the root and inspect constraints, fingerprints and validity.", "Document root/intermediate compromise blast radius and replacement procedure at a high level."], deliverables: ["CA hierarchy diagram", "Sanitized certificate/constraint evidence", "Key-protection model", "Independent chain verification"], completionCriteria: ["Routine leaf issuance does not require the root private key.", "CA constraints are evidenced.", "No private key appears in version control or ordinary evidence."] }],
    },
    {
        id: "pki-workload-certificates",
        title: "Issue Workload Certificates with Explicit Identity",
        summary: "Issue server and client identities with constrained SANs and extended key usage instead of generic certificates used everywhere.",
        objectives: ["Create CSRs and SAN-based workload identities.", "Distinguish serverAuth and clientAuth usage.", "Reject hostname/identity mismatch."],
        activities: [{ type: "practical", title: "Issue Steward service identities", objective: "Issue internal certificates for two representative TSA workloads.", scenario: "A Steward API and one internal client/dependency need encrypted, authenticated communication on the private network.", instructions: ["Choose two existing internal endpoints rather than inventing permanent services solely for PKI.", "Generate workload private keys on or for the intended identity boundary and CSRs containing deliberate DNS SANs from the homelab DNS namespace.", "Issue a server certificate with serverAuth and a separate client certificate with clientAuth or a justified dual-purpose profile.", "Inspect SAN, issuer, EKU, key usage, serial and validity before deployment.", "Validate the server certificate with the correct name and demonstrate a wrong-name or wrong-EKU negative case.", "Record where each private key lives and which workload identity may read it."], deliverables: ["Sanitized CSR/certificate evidence", "Certificate profile record", "Positive/negative identity validation", "Private-key ownership map"], completionCriteria: ["SANs identify real lab names.", "Certificate purpose is constrained.", "A mismatched identity/purpose is rejected."] }],
    },
    {
        id: "pki-trust-distribution",
        title: "Distribute Trust without Disabling Verification",
        summary: "Install only the intended CA trust anchors on selected clients and prove untrusted chains fail before trust is established.",
        objectives: ["Operate Rocky and bounded Windows trust stores.", "Distinguish trust-anchor distribution from leaf-certificate distribution.", "Avoid insecure verification bypasses."],
        activities: [{ type: "practical", title: "Cross-platform trust-store lab", objective: "Make selected Rocky and Windows clients trust the internal CA intentionally.", scenario: "The internal certificate is cryptographically valid but clients must not trust a private CA merely because the server presents it.", instructions: ["From a Rocky client, connect before installing the lab CA and capture the expected trust failure.", "Install only the required public root/intermediate trust material using the OS-supported trust mechanism and verify the connection succeeds.", "Repeat on the bounded Windows lab where available using the appropriate machine trust store and PowerShell/certificate tooling.", "Prove a certificate from an unrelated test CA remains untrusted.", "Search configuration/scripts for insecure shortcuts such as disabled TLS verification and remove/reject them.", "Document how trust anchors would be distributed at scale later rather than copying leaf certificates manually to every client."], deliverables: ["Before/after Rocky trust evidence", "Windows trust evidence where available", "Unrelated-CA negative test", "Trust-distribution record"], completionCriteria: ["Trust failure exists before CA installation.", "Trust succeeds after explicit anchor installation.", "TLS verification is never disabled as the solution."] }],
    },
    {
        id: "pki-mtls",
        title: "Implement Mutual TLS between Workloads",
        summary: "Require both sides of an internal connection to prove machine identity and keep that identity separate from application authorization.",
        objectives: ["Configure server-side client-certificate verification.", "Prove no-certificate, wrong-CA and valid-client outcomes.", "Map certificate identity to a bounded policy without confusing it with user authorization."],
        activities: [{ type: "practical", title: "Internal mTLS path", objective: "Protect one real Steward internal service path with mutual TLS.", scenario: "Network reachability alone must no longer be sufficient for a selected machine-to-machine operation.", instructions: ["Select an existing internal HTTP/API or proxy path appropriate for mTLS and document why this boundary benefits from machine authentication.", "Configure server TLS with the internal server certificate and trusted client-CA verification.", "Call the endpoint without a client certificate and prove rejection.", "Call it with a certificate signed by an untrusted test CA and prove rejection.", "Call it with the intended client identity and prove the TLS handshake plus representative application request succeeds.", "Log/inspect the authenticated certificate subject/SAN or fingerprint at the boundary without logging private material.", "Document which application authorization checks still execute after mTLS succeeds."], deliverables: ["mTLS configuration", "No-cert/wrong-CA/valid-client evidence", "Machine-identity evidence", "TLS-versus-authorization boundary note"], completionCriteria: ["Client identity is cryptographically required.", "At least two negative cases fail closed.", "mTLS is not treated as replacement for Steward domain authorization."] }],
    },
    {
        id: "pki-rotation",
        title: "Rotate Certificates without Changing Identity Semantics",
        summary: "Replace expiring workload certificates and prove consumers trust the identity after key/certificate replacement.",
        objectives: ["Renew/reissue a leaf with a new key.", "Deploy and reload replacement material safely.", "Verify served identity rather than only files on disk."],
        activities: [{ type: "practical", title: "Leaf rotation drill", objective: "Rotate one server and one client certificate with observable continuity.", scenario: "Internal certificates expire and keys must be replaceable without redesigning the application.", instructions: ["Record current serial/fingerprint/expiry for the selected server/client identities.", "Generate replacement key material and issue new certificates preserving intended SAN/profile while changing serial/key.", "Deploy replacements using controlled permissions and reload/restart only the required boundary.", "Verify the certificate actually presented on the network has changed and mTLS still succeeds.", "Prove the old client certificate behavior according to the chosen overlap/revocation policy.", "Record the coexistence window, cutover and cleanup of retired private material."], deliverables: ["Before/after identity evidence", "Replacement deployment evidence", "Post-rotation mTLS proof", "Old-material cleanup record"], completionCriteria: ["Network-served certificate changes are evidenced.", "New keys are used.", "Rotation preserves intended service identity and policy."] }],
    },
    {
        id: "pki-revocation",
        title: "Revocation and Compromised Identity Response",
        summary: "Revoke a compromised workload credential and understand the operational limits of CRLs/OCSP-style status checking.",
        objectives: ["Define certificate status/revocation semantics.", "Publish and consume a revocation mechanism appropriate to the lab.", "Prove a previously valid credential stops authenticating."],
        activities: [{ type: "practical", title: "Compromised client certificate drill", objective: "Invalidate a client identity before natural expiry.", scenario: "A workload private key is assumed compromised; waiting for certificate expiry is unacceptable.", instructions: ["Choose the lab client certificate as compromised and record its serial/fingerprint.", "Revoke it at the issuing CA and generate/publish an updated CRL or configure the chosen status mechanism.", "Configure the mTLS verifier to enforce current revocation status where supported by the selected stack.", "Prove the revoked credential is rejected while a separate valid client remains accepted.", "Issue a replacement identity/key and restore the intended client operation.", "Document propagation/caching/fail-open versus fail-closed risks and the emergency response if status infrastructure is unavailable."], deliverables: ["Revocation record", "Updated status/CRL evidence", "Revoked-client rejection", "Replacement identity evidence", "Revocation availability analysis"], completionCriteria: ["A credential that previously worked is rejected before expiry.", "A non-revoked credential remains valid.", "Replacement uses new key material."] }],
    },
    {
        id: "pki-ca-rotation-failure",
        title: "Trust-Anchor Rotation and Failure Recovery",
        summary: "Change an issuing authority without causing an avoidable trust outage and diagnose failures caused by missing chain or trust distribution.",
        objectives: ["Plan overlapping trust during CA/intermediate replacement.", "Diagnose incomplete-chain and missing-anchor failures.", "Remove retired trust only after migration evidence."],
        activities: [{ type: "practical", title: "Intermediate replacement drill", objective: "Migrate one workload from the old issuing intermediate to a replacement issuer.", scenario: "The issuing CA approaches retirement or is replaced while clients must continue validating internal services.", instructions: ["Create a replacement issuing intermediate under the protected lab root or document a justified root-rotation variant.", "Distribute trust needed for an overlap window before switching the workload certificate.", "Issue/deploy a leaf from the new intermediate and verify old/new intended clients during coexistence.", "Deliberately omit the required intermediate/anchor on one disposable client and diagnose the resulting chain failure from protocol evidence.", "Restore trust, verify service, then remove retired intermediate trust only after no selected workload depends on it.", "Write rollback boundaries and explain when compromise makes rollback to the old issuer unsafe."], deliverables: ["CA migration plan", "Overlap/cutover evidence", "Broken-chain diagnosis", "Retired-trust cleanup", "Rollback/compromise decision record"], completionCriteria: ["Issuer replacement is performed with explicit overlap.", "A chain/trust failure is diagnosed rather than bypassed.", "Retired trust is removed only after dependency verification."] }],
    },
    {
        id: "pki-vault-integration",
        title: "Reassess PKI Ownership with Vault",
        summary: "Move from hand-operated educational issuance toward a managed workload-PKI lifecycle only when the later Vault platform is available.",
        objectives: ["Separate learning CA mechanics from long-term automation.", "Evaluate Vault PKI as an issuing/automation boundary.", "Avoid parallel permanent CAs with ambiguous authority."],
        activities: [{ type: "exercise", title: "PKI ownership ADR", description: "After the Vault path is implemented, compare retaining the lab OpenSSL issuing CA with migrating workload issuance to Vault PKI. Define root/intermediate ownership, authentication for certificate requests, TTLs, renewal, revocation, audit, trust distribution and migration/decommission. Public ACME/Kong certificates remain under the Cloud certificate lifecycle unless a later architecture decision explicitly changes that boundary. End with one authoritative internal workload-PKI design, not two permanent issuers." }],
    },
];