import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const xmlSpec:LearningResource={title:"W3C — Extensible Markup Language (XML) 1.0",url:"https://www.w3.org/TR/xml/",kind:"reference"};
const xmlNamespaces:LearningResource={title:"W3C — Namespaces in XML",url:"https://www.w3.org/TR/xml-names/",kind:"reference"};
const xsdSpec:LearningResource={title:"W3C — XML Schema Definition Language 1.1",url:"https://www.w3.org/TR/xmlschema11-1/",kind:"reference"};
const wsdlSpec:LearningResource={title:"W3C — Web Services Description Language (WSDL) 1.1",url:"https://www.w3.org/TR/2001/NOTE-wsdl-20010315",kind:"reference"};
const soapSpec:LearningResource={title:"W3C — SOAP Version 1.2",url:"https://www.w3.org/TR/soap12-part1/",kind:"reference"};
const owaspXxe:LearningResource={title:"OWASP — XML External Entity Prevention",url:"https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html",kind:"reference"};
const resourcesBySoap:Record<string,LearningResource[]>={
 "soap-xml-document-model":[xmlSpec,xmlNamespaces,owaspXxe],"soap-xml-xsd-contract":[xsdSpec,xmlNamespaces],
 "soap-wsdl-contract":[wsdlSpec,xsdSpec],"soap-envelope-faults":[soapSpec,wsdlSpec],
 "soap-service-implementation":[wsdlSpec,soapSpec],"soap-steward-consumer":[wsdlSpec,soapSpec],
 "soap-contract-testing-failure":[xsdSpec,wsdlSpec],"soap-xml-milestone":[xmlSpec,xsdSpec,wsdlSpec,soapSpec],
};

type TeachingSection = { title: string; paragraphs: string[]; code?: { language: string; code: string; caption?: string } };
const teachingBySoap: Record<string, TeachingSection[]> = {
    "soap-xml-document-model": [
        { title: "XML is a tree with stricter document rules", paragraphs: ["An XML document has one document element, nested elements, attributes, text and escaped characters. Well-formedness is the parser-level requirement that the document obey XML syntax: tags are properly nested/closed, attribute syntax is valid and there is one root document element. A well-formed document can still violate the business or schema contract.", "Unlike a typical JSON object model, XML also has namespaces, attributes versus elements, ordered child content and document-oriented features. Parse it structurally; regular expressions and string slicing cannot reliably preserve those semantics."] },
        { title: "Namespace identity is a URI, not the chosen prefix", paragraphs: ["A namespace qualifies element and attribute names so independently designed vocabularies can coexist. The prefix is only a local alias. <cmdb:Service> and <x:Service> identify the same expanded name when both prefixes map to the same namespace URI.", "Code that depends on the literal prefix can fail on a semantically equivalent document. Query using namespace-aware APIs and the namespace URI."], code: { language: "xml", caption: "Prefixes differ; expanded namespace identity can remain the same", code: "<cmdb:Service xmlns:cmdb=\"urn:example:cmdb:v1\">\n  <cmdb:Name>payments-api</cmdb:Name>\n</cmdb:Service>" } },
        { title: "Parsing and validation are separate stages", paragraphs: ["Parsing turns a well-formed XML byte stream into a structured document/tree or event stream. Schema validation then asks whether that structure satisfies a declared contract. Domain validation still follows: an XSD can prove that ownerId is a string with a required occurrence, but not necessarily that the referenced Steward team exists or may own the service.", "For untrusted XML, parser configuration is a security boundary. Do not casually enable external entity or external resource resolution; Security Steward deepens parser hardening later."] },
    ],
    "soap-xml-xsd-contract": [
        { title: "XSD constrains an XML vocabulary", paragraphs: ["An XML Schema defines elements, attributes, simple/complex types, occurrence constraints and namespace membership. Validation converts 'this sample looks right' into executable structural rules that producer and consumer can test independently.", "The schema targetNamespace states which vocabulary the declarations belong to. Instance documents must use the expected namespace; matching local element text under the wrong namespace is not the same contract."] },
        { title: "Cardinality and types make compatibility visible", paragraphs: ["minOccurs and maxOccurs express whether an element is optional, required or repeated. Simple types constrain lexical/value shape; complex types define structured content. Tightening an optional element into required can break existing producers, while adding an optional element is often easier for tolerant consumers—but actual client behavior must still be tested.", "Schema compatibility is consumer-specific. Generated clients may react differently from generic XML parsers, so predict changes and then verify them with the real toolchain."] },
        { title: "Schema validity is not domain validity", paragraphs: ["Keep cross-record rules, database existence checks, authorization and business lifecycle rules in application/domain validation. XSD should describe the interoperable document structure rather than attempt to become the entire Steward domain model."] },
    ],
    "soap-wsdl-contract": [
        { title: "WSDL connects data contract, operations and wire binding", paragraphs: ["In WSDL 1.1, types normally contain or reference XSD. Messages describe operation data, portType groups abstract operations, binding says how those operations are carried by a concrete protocol such as SOAP, and service/port identifies a reachable endpoint. Read those layers from abstract contract toward concrete endpoint instead of treating WSDL as opaque generated XML."], code: { language: "text", caption: "Trace from schema to reachable service", code: "XSD types\n   ↓\nmessages\n   ↓\nportType / operations\n   ↓\nbinding (SOAP details)\n   ↓\nservice / port / endpoint" } },
        { title: "Operation semantics and transport are different concerns", paragraphs: ["An operation such as GetServiceRecord has request/response meaning independent of the host currently serving it. Binding details connect that abstract operation to SOAP message and transport conventions. Endpoint movement is therefore different from changing the operation's data contract.", "Contract-aware tooling can generate or configure client types from WSDL, but generated code does not remove the need to understand which operation, schema version and binding the client actually uses."] },
    ],
    "soap-envelope-faults": [
        { title: "SOAP wraps the operation payload in a protocol envelope", paragraphs: ["A SOAP message has an Envelope containing an optional Header and a Body. The Body carries the operation payload or a Fault. Headers carry cross-cutting message metadata such as bounded correlation information when the contract/binding supports it; they are not a dumping ground for domain fields.", "HTTP can transport SOAP, but HTTP status and SOAP application/protocol semantics are separate evidence. Diagnose network/HTTP reachability before assuming an XML or business failure."] },
        { title: "A SOAP Fault is structured failure, not an ordinary response object", paragraphs: ["Fault information communicates a protocol/application failure through the SOAP model. Preserve fault category/code, human-readable reason and bounded application detail instead of converting every remote failure into null/empty data.", "Malformed XML, wrong namespace/schema, binding mismatch, SOAP Fault and remote business rejection belong to different diagnostic layers even when a generated client surfaces them through one exception hierarchy."] },
    ],
};

function practical(id: string, title: string, objective: string, scenario: string, instructions: string[], deliverables: string[], completionCriteria: string[], estimatedMinutes = 120): Lesson {
    const resources = resourcesBySoap[id] ?? [soapSpec];
    const sections = teachingBySoap[id] ?? [];
    const blocks: LessonBlock[] = [
        { type: "paragraph", text: objective },
        { type: "heading", id: `${id}-mental-model`, text: "Protocol and contract mental model", level: 2 },
    ];
    for (const section of sections) {
        blocks.push({ type: "heading", id: `${id}-${section.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`, text: section.title, level: 2 });
        for (const paragraph of section.paragraphs) blocks.push({ type: "paragraph", text: paragraph });
        if (section.code) blocks.push(section.code.caption
            ? { type: "code", language: section.code.language, code: section.code.code, caption: section.code.caption }
            : { type: "code", language: section.code.language, code: section.code.code });
    }
    blocks.push({ type: "callout", tone: "steward", title: "Integration boundary", body: "SOAP/XML belongs at the enterprise integration boundary. Steward's domain model remains independent of generated SOAP types and raw XML representation." });
    blocks.push({ type: "resources", title: "Reference specifications", resources });
    const activities: Lesson["activities"] = [];
    if (sections.length) activities.push({ id: `${id}-reading`, title: `${title}: Concepts`, estimatedMinutes: 45, content: { type: "reading", body: objective, blocks } });
    activities.push({ id: `${id}-lab`, title, estimatedMinutes, content: { type: "practical", objective, scenario, instructions, deliverables: [...deliverables, `Reference set: ${resources.map(r => r.title).join("; ")}`], completionCriteria } });
    return { id, title, activities };
}

export const soapXmlEnterpriseIntegrationDeepLessons: Lesson[] = [
    practical("soap-xml-document-model", "XML Documents, Namespaces and Parsing", "Read, create and troubleshoot XML as a structured namespaced document format rather than treating it as verbose JSON.", "A legacy enterprise CMDB will become a Steward integration dependency. Its messages are XML and use multiple namespaces, so string manipulation is not a safe integration strategy.", ["Create representative service, owner and environment XML documents with declarations, attributes, nested elements and escaped content.", "Introduce a namespace for the CMDB contract and a second namespace for shared enterprise identifiers; inspect qualified names and namespace prefixes.", "Parse the documents with a real XML parser and query required values without depending on a particular prefix spelling.", "Compare elements versus attributes and identify where ordering, namespaces and mixed/document semantics make XML different from JSON.", "Create malformed XML and a well-formed document with the wrong namespace; capture and explain the different failures.", "Record safe parser expectations for untrusted XML, including why external-entity behavior must not be enabled casually."], ["Representative XML documents", "Namespace map", "Parser/query implementation", "Malformed-versus-wrong-namespace evidence", "XML safety note"], ["The learner can explain well-formedness independently of schema validity.", "Namespace identity is not confused with prefix text.", "XML is parsed structurally rather than with regex/string slicing.", "Unsafe external-entity assumptions are identified."]),
    practical("soap-xml-xsd-contract", "XSD: Make the XML Contract Executable", "Define and validate an XML Schema that captures the structural contract for the enterprise service messages.", "The CMDB team says a sample XML file is the contract. Steward needs machine-checkable rules for required fields, types, cardinality and namespace membership before integrating.", ["Create an XSD for the selected service-record message and declare its target namespace deliberately.", "Model required/optional elements, suitable simple types and at least one repeating structure or bounded cardinality.", "Validate a correct XML instance against the XSD with a real validator.", "Create invalid instances for a missing required value, wrong type/cardinality and wrong namespace and capture validation diagnostics.", "Change the schema in one backward-compatible and one breaking way and predict the effect on an existing consumer.", "Document what XSD proves and what business semantics still require application/domain validation."], ["Versioned XSD", "Valid instance", "Three invalid-instance results", "Compatibility change note", "Schema-versus-domain-rule boundary"], ["Validation is executed, not merely described.", "Namespace and cardinality failures are demonstrated.", "Schema validation is not presented as complete business validation.", "Compatibility reasoning uses actual consumer impact."]),
    practical("soap-wsdl-contract", "WSDL and the SOAP Service Contract", "Trace how WSDL connects operations, XML messages, bindings and network endpoints before generating or implementing code.", "The CMDB exposes a SOAP service. The integration cannot be understood safely from a URL and one captured envelope alone.", ["Create or inspect a WSDL 1.1 contract for a bounded operation such as GetServiceRecord and one mutation such as UpdateServiceOwner.", "Trace types/schema → messages → portType/operations → binding → service/port endpoint and draw the relationship.", "Identify SOAP action/binding expectations and the request/response XSD types used by each operation.", "Use a WSDL-aware client/tool or library to inspect the published contract and enumerate operations from the contract rather than handwritten notes.", "Change an operation or message contract deliberately and observe how the client/tool exposes the incompatibility.", "Record transport concerns separately from operation/business semantics."], ["Versioned WSDL/XSD contract", "WSDL component map", "Operation inventory from tooling", "Breaking-contract evidence", "Transport-versus-semantic boundary note"], ["The learner can navigate a WSDL without treating it as opaque generated XML.", "Operations resolve to explicit schema types and bindings.", "A contract incompatibility is reproduced.", "WSDL is understood as more than endpoint documentation."]),
    practical("soap-envelope-faults", "SOAP Envelopes, Headers and Faults", "Construct and diagnose SOAP messages at the wire level before hiding them behind generated client abstractions.", "A generated client reports a generic integration error. Operators need to determine whether the wire message, namespace, SOAP header, business request or remote service failed.", ["Send a valid SOAP request and capture the raw HTTP request/response including Content-Type/SOAPAction behavior appropriate to the chosen SOAP version/binding.", "Identify Envelope, Header and Body and map the operation payload to its XSD namespace.", "Add one bounded correlation/request identifier in a SOAP header and verify the service can observe it.", "Trigger a deliberate application rejection represented as a SOAP Fault and distinguish fault code/category, fault reason and application detail.", "Send a wrong operation namespace or malformed envelope and compare protocol/contract failure with the application fault.", "Create a diagnostic checklist from HTTP/network → SOAP envelope/binding → XML/XSD → operation/business fault."], ["Raw successful SOAP exchange", "Header/correlation evidence", "SOAP Fault evidence", "Protocol-versus-application failure comparison", "SOAP diagnostic checklist"], ["The learner can read the raw envelope despite using libraries later.", "SOAP Fault is not treated as an ordinary successful payload.", "At least two different failure layers are distinguished.", "Correlation survives the SOAP boundary."]),
    practical("soap-service-implementation", "Implement a Contract-First SOAP Endpoint", "Build a working SOAP provider from the reviewed WSDL/XSD contract and keep transport mapping outside Steward domain rules.", "To understand the provider side rather than only consuming legacy services, TSA will implement a small enterprise CMDB SOAP service that owns a bounded external service-record capability.", ["Select a maintained SOAP-capable library/runtime suitable for the learner environment and record the choice; do not hand-build an XML-over-HTTP framework.", "Implement the WSDL/XSD operations against a small deterministic data source or bounded service layer.", "Serve/publish the WSDL and prove a fresh client can discover the endpoint from it.", "Validate/map request data at the SOAP boundary and keep the core operation behavior independent of XML element manipulation.", "Return a typed successful response and a deliberate SOAP Fault for a known rejection/not-found case.", "Restart the service and repeat contract discovery and a representative operation from a separate client process."], ["Runnable SOAP provider", "Published WSDL/XSD", "Successful operation evidence", "Typed SOAP Fault evidence", "Transport/domain boundary map", "Restart/reconnect evidence"], ["The endpoint is actually callable through SOAP.", "The published contract describes the implementation used by the client.", "Domain/service behavior is not embedded in raw XML string handling.", "Success and fault paths both work after restart."]),
    practical("soap-steward-consumer", "Integrate Steward with the SOAP Provider", "Consume the SOAP contract from Steward through an explicit adapter that prevents transport-specific XML concerns from leaking into the domain model.", "Steward needs authoritative metadata from the enterprise CMDB, but its core model and REST API should not become SOAP-shaped merely because the external system is SOAP-based.", ["Generate/configure a SOAP client from the WSDL or use a contract-aware library rather than manually concatenating envelopes for application code.", "Create a Steward integration adapter that maps SOAP contract types to a small internal application/domain representation.", "Call the real SOAP provider from a representative Steward workflow and preserve correlation evidence.", "Map a SOAP Fault, timeout/unavailability and invalid response/contract condition into explicit integration outcomes; do not silently convert all failures into empty data.", "Prove one Steward/domain test can run against the adapter boundary without constructing SOAP XML.", "Document timeout, retry/idempotency and source-of-truth assumptions for the integration."], ["Steward SOAP adapter", "End-to-end provider→Steward evidence", "Fault/error mapping", "Domain-level adapter test", "Integration operating contract"], ["Steward consumes the real SOAP endpoint.", "SOAP/XML types stop at the adapter boundary.", "Failure classes remain distinguishable.", "Retry behavior is justified by operation semantics."]),
    practical("soap-contract-testing-failure", "Contract Testing and Compatibility Failure", "Detect SOAP/XML compatibility problems before they become ambiguous production integration failures.", "The CMDB provider evolves independently. Steward must know which WSDL/XSD changes it can tolerate and which require coordinated release work.", ["Automate validation of representative request/response XML against the versioned schema/contract.", "Create a provider/consumer compatibility check around at least one operation used by Steward.", "Inject a breaking XSD/WSDL change such as namespace/type/required-element incompatibility and prove the check fails before accepting the new contract.", "Inject a compatible additive change and determine whether the actual client tolerates it rather than assuming it does.", "Capture raw messages and contract versions in diagnostics without leaking secrets.", "Define contract ownership, version publication and change-notification expectations."], ["Automated contract validation", "Breaking-change failure evidence", "Additive-change evidence", "Diagnostic artifact example", "Contract ownership/versioning policy"], ["Compatibility is tested against the real client/provider boundary.", "Breaking and additive changes are distinguished empirically.", "Diagnostics identify the contract version involved.", "Contract evolution has an owner and coordination rule."]),
    practical("soap-xml-milestone", "Milestone: Build and Integrate a Contract-First SOAP Service", "Prove the complete enterprise SOAP capability by operating both sides of a real contract and recovering from contract and runtime failures.", "An enterprise CMDB exposes SOAP while Steward remains a REST-oriented service registry. Deliver the integration without making SOAP a permanent architectural default or leaking its model throughout Steward.", ["Start both the SOAP provider and Steward integration from versioned configuration/contracts and record the exact WSDL/XSD versions.", "From a separate client, discover the provider contract and execute a successful operation.", "Execute the representative Steward workflow that consumes the SOAP operation through the adapter and prove the mapped result reaches the intended application behavior.", "Trigger and diagnose one SOAP Fault, one namespace/schema incompatibility and one provider-unavailable condition using the layered diagnostic evidence.", "Restore the healthy contract/runtime and prove the end-to-end workflow recovers.", "Produce a concise runbook covering contract location/version, endpoint discovery, raw-message capture, validation, correlation, common faults and escalation ownership."], ["Running contract-first SOAP provider", "Steward SOAP consumer/adapter", "Successful end-to-end evidence", "Three failure/recovery records", "SOAP/XML integration runbook"], ["Both provider and consumer are implemented and operated.", "XML/XSD/WSDL/SOAP evidence is visible end to end.", "Three distinct failure classes are diagnosed from evidence and recovered.", "SOAP remains isolated at an explicit integration boundary."]),
    practical("soap-rest-reassessment", "Reassess SOAP, REST and the Integration Boundary", "Use the implemented integration to decide where SOAP belongs, where REST belongs and when translation should isolate an enterprise contract.", "The SOAP integration now works. The remaining question is architectural ownership, not whether SOAP is 'old' or REST is 'modern'.", ["Compare the implemented SOAP contract with Steward's REST API across contract strictness, tooling, error semantics, evolvability, observability and organizational ownership.", "Identify the concrete reasons the external boundary remains SOAP and whether any justify exposing SOAP inside Steward itself.", "Review the adapter/anti-corruption boundary and list what would leak if SOAP-generated types were allowed into the domain model.", "Define evidence that would justify provider migration or a façade later, including ownership and consumer coordination costs.", "Record the decision without adding a second permanent integration platform merely for technology exposure."], ["SOAP-versus-REST evidence matrix", "Integration-boundary ADR", "Migration/façade trigger criteria"], ["The decision follows observed requirements and evidence.", "SOAP is neither rejected nor selected because of age/fashion.", "The adapter boundary has an explicit purpose.", "No unnecessary middleware/tool zoo is introduced."], 90),
];
