import type { Lesson } from "./lesson";

const scenario = "Treat Steward as a mature organization-owned technology service spanning application code, PostgreSQL, cloud/VPS infrastructure, Nexus, internal packages, CI/CD, security controls, reliability practices and operational ownership. Risk statements must describe uncertain events and consequences, not merely list vulnerabilities, defects or controls.";
const deliverables = ["Risk analysis artifact", "Evidence and rationale", "Owner, treatment or review record"];
const criteria = ["Risk is expressed in terms of cause/event/consequence and linked to evidence.", "Scoring and treatment are proportionate rather than false precision.", "Ownership, acceptance authority and review triggers are explicit."];
function lesson(id: string, title: string, body: string, instructions: string[]): Lesson {
  return { id: `technology-risk-${id}`, title, activities: [
    { id: `technology-risk-${id}-reading`, title: `${title}: concepts`, estimatedMinutes: 60, content: { type: "reading", body } },
    { id: `technology-risk-${id}-practice`, title: `${title}: Steward risk exercise`, estimatedMinutes: 60, content: { type: "practical", objective: `Apply ${title} to a real Steward technology-risk decision.`, scenario, instructions, deliverables, completionCriteria: criteria } },
  ] };
}

export const technologyRiskDeepLessons: Lesson[] = [
  lesson("identification", "Risk Identification", `Technology risk is uncertainty that can affect organizational objectives through technology. A useful risk statement connects a source or condition, an uncertain event and a consequence. "PostgreSQL is a risk" is not useful; "loss of the only recoverable PostgreSQL copy could make Steward data unavailable beyond the agreed recovery objective" is. Sources include architecture, dependencies, security threats, incidents, delivery failures, capacity evidence, lifecycle concerns, people/process concentration and third parties. Reuse evidence from earlier TSA schools instead of inventing risks to populate a register. Distinguish a risk from an issue: an issue already exists; a risk concerns uncertainty about what may happen and its effect.`, ["Review prior Steward architecture, security, reliability, delivery and governance evidence.", "Identify at least eight credible risk scenarios across different technology domains.", "Write each as cause/condition → event → consequence.", "Separate current issues from uncertain future risks and remove duplicate symptoms of the same underlying risk."]),
  lesson("likelihood-impact", "Likelihood and Impact", `Risk assessment helps prioritize attention, not predict the future with fake mathematical certainty. Likelihood estimates how plausible a scenario is over a defined horizon; impact describes consequences such as service disruption, data loss, security exposure, financial cost, compliance impact, delivery delay or loss of stakeholder trust. Define scales before scoring and anchor them to observable criteria. A 1–5 matrix can be useful when its categories mean something; multiplying arbitrary numbers does not make the result scientific. Record uncertainty and evidence quality alongside the score.`, ["Define a practical likelihood scale and multidimensional impact scale for Steward.", "Score five identified scenarios using evidence rather than intuition alone.", "Record confidence and assumptions for each assessment.", "Challenge one score and show how new evidence could change it."]),
  lesson("inherent-residual", "Inherent and Residual Risk", `Inherent risk estimates exposure before the controls being evaluated; residual risk is what remains after considering control design and demonstrated operation. The distinction helps show what controls actually buy. Do not automatically credit a documented control as effective: evidence from tests, monitoring, restore drills, CI enforcement or operational records matters. Residual risk is rarely zero. Be explicit about which controls were assumed in each view so the comparison is reproducible.`, ["Select three Steward risks with existing controls.", "Describe the inherent exposure and the control set applied.", "Assess control evidence before estimating residual exposure.", "Explain what uncertainty or consequence remains after treatment."]),
  lesson("appetite-tolerance", "Risk Appetite and Tolerance", `Risk appetite expresses the broad amount and type of risk an organization is willing to pursue or retain in pursuit of objectives. Tolerance turns that direction into more operational boundaries or thresholds. Engineering teams should not invent enterprise appetite, but they can translate approved direction into decision criteria: maximum recovery objectives, unsupported dependency exposure, release-risk thresholds or security-exception duration. Appetite is not permission to ignore risk; it defines when treatment, escalation or acceptance authority is required.`, ["Draft hypothetical but clearly labelled Steward risk-appetite statements for availability, security, change and dependency risk.", "Translate each into one or more measurable tolerance examples.", "Map which engineering decisions can stay within delegated authority and which require escalation.", "Identify where the organization would need to supply policy direction rather than engineers guessing it."]),
  lesson("treatment", "Risk Treatment", `Common treatment strategies are avoid, reduce/mitigate, transfer/share and accept. Treatment should change likelihood, impact or exposure at a cost justified by the risk. Controls are means, not outcomes: adding another scanner, approval or redundant component is not automatically good treatment. Compare options, secondary risks, implementation cost, operational burden and time to effect. Define the target residual state and evidence that will show whether treatment worked.`, ["Choose four prioritized Steward risks.", "Generate credible avoid/reduce/transfer/accept options where applicable.", "Compare expected risk reduction, cost, complexity and secondary risk.", "Select treatments and define target residual exposure plus validation evidence."]),
  lesson("acceptance", "Risk Acceptance", `Acceptance is an explicit decision to retain known residual exposure, not failure to fix something. A sound acceptance record states the risk, evidence, residual assessment, rationale, accountable authority, duration and review triggers. Temporary exceptions should expire or be reviewed; permanent acceptance should still be reconsidered when assumptions change. The person creating the risk should not silently grant themselves authority the governance model does not delegate.`, ["Create an acceptance case for one realistic Steward residual risk.", "State business/engineering rationale and rejected treatment alternatives.", "Define accountable acceptance authority using the Engineering Governance model.", "Add expiry or review date, triggers and required monitoring evidence."]),
  lesson("registers", "Risk Registers", `A risk register is a decision and follow-up system, not a graveyard of scary sentences. Useful fields include identifier, scenario, category, affected objective/assets, inherent assessment, controls, residual assessment, owner, treatment, due date, acceptance authority, status, evidence links and review trigger. Keep risks at a useful level of abstraction and link related findings or incidents rather than duplicating them as separate risks. A register should support prioritization, ownership and trend review.`, ["Design a lean Steward technology-risk register schema.", "Populate it with the strongest risks identified so far.", "Link controls/evidence and avoid duplicating findings as risks.", "Define lifecycle states and a review cadence that keeps the register alive."]),
  lesson("kri", "Key Risk Indicators", `A KRI is a signal that exposure may be increasing or approaching an unacceptable boundary. It differs from a KPI, which usually tracks performance toward an objective. Useful KRIs are tied to a risk hypothesis and decision threshold: unsupported critical dependencies, backup restore failures, error-budget burn, overdue critical remediation, privileged-access exceptions or concentration in a single failure domain. Avoid dashboards full of metrics with no action. Define source, threshold, owner, cadence and response.`, ["Choose five high-priority Steward risks.", "Propose a KRI for each and explain the causal relationship.", "Define data source, threshold/trend, owner and response action.", "Reject at least one tempting metric that does not actually indicate risk exposure."]),
  lesson("ownership", "Risk Ownership", `Risk ownership means accountability for ensuring a risk is understood, monitored and treated or accepted through the proper authority. It is not necessarily the engineer who discovered it or the person implementing a control. Distinguish risk owner, control owner, action owner and acceptance authority. Ownership should align with the ability to influence the affected objective and make trade-offs. Cross-cutting risks may require escalation rather than assigning them to whoever is closest to the code.`, ["Map owner, control owner, action owner and acceptance authority for six Steward risks.", "Identify ownership mismatches where the named person lacks decision authority.", "Define escalation paths for cross-team or organization-level exposure.", "Connect ownership to the governance structures established in previous modules."]),
  {
    id: "technology-risk-steward-register-lab", title: "Lab: Build the Steward Technology Risk Register", activities: [
      { id: "technology-risk-steward-register-lab-1", title: "Build the risk universe", estimatedMinutes: 120, content: { type: "practical", objective: "Construct an evidence-backed risk universe for the mature Steward ecosystem.", scenario, instructions: ["Collect evidence from architecture, QA, security, reliability, delivery, cloud, Nexus and internal-package work.", "Write credible cause/event/consequence scenarios and distinguish risks from active issues.", "Define likelihood/impact criteria and assess inherent exposure with confidence notes.", "Consolidate duplicates and identify affected organizational/technology objectives."], deliverables: ["Risk universe", "Scoring model", "Evidence map", "Assumption/confidence record"], completionCriteria: criteria } },
      { id: "technology-risk-steward-register-lab-2", title: "Assess controls and treatments", estimatedMinutes: 150, content: { type: "practical", objective: "Turn identified exposure into defensible treatment and residual-risk decisions.", scenario, instructions: ["Map existing controls and operating evidence to each priority risk.", "Estimate residual exposure without assuming undocumented controls work.", "Compare treatment alternatives, cost, complexity and secondary risk.", "Identify risks that require explicit acceptance or escalation."], deliverables: ["Control-to-risk map", "Residual assessments", "Treatment plan", "Acceptance/escalation candidates"], completionCriteria: criteria } },
      { id: "technology-risk-steward-register-lab-3", title: "Operationalize the register", estimatedMinutes: 120, content: { type: "practical", objective: "Make the Steward technology-risk register an operational governance mechanism rather than static documentation.", scenario, instructions: ["Assign risk, control and action ownership plus acceptance authority.", "Define KRIs only for risks where measurable signals improve decisions.", "Set review cadence, due dates, expiry and event-driven reassessment triggers.", "Run a mock risk review and record one treatment, acceptance, escalation or reprioritization decision."], deliverables: ["Final Steward technology-risk register", "KRI set", "Ownership matrix", "Risk-review decision record"], completionCriteria: ["Priority risks trace to real Steward evidence and objectives.", "Residual risk and acceptance decisions are explicit and authorized.", "The register has owners, actions and review triggers that make it maintainable.", "No score or framework label substitutes for engineering reasoning."] } },
    ]
  },
];
