import { engineeringFoundations } from "./engineering-foundations";
import type { LearningJourney } from "./learning-journey";
import { plannedPath } from "./planned-path";

const module = plannedPath;

export const technicalStewardshipJourney: LearningJourney = {
    id: "technical-stewardship-journey",
    title: "Technical Stewardship Journey",
    schools: [
        {
            id: "engineering-apprentice",
            title: "Engineering Apprentice",
            paths: [engineeringFoundations],
        },
        {
            id: "builder",
            title: "Builder",
            paths: [
                module("programming-with-python", "Programming with Python", [
                    "Setting Up a Python Engineering Environment",
                    "Python Syntax, Values and Types",
                    "Control Flow",
                    "Functions and Scope",
                    "Collections and Data Structures",
                    "Modules and Packages",
                    "Errors, Exceptions and Defensive Programming",
                    "Object-Oriented Programming",
                    "Comprehensions, Iterators and Pythonic Tools",
                    "Type Hints and Static Feedback",
                    "Virtual Environments and Dependency Management",
                    "Debugging Python Programs",
                    "Lab: Build a Small Python Service Core",
                ]),
                module("web-and-api-foundations", "Web and API Foundations", [
                    "How the Web Works",
                    "Client-Server Architecture",
                    "HTTP Requests and Responses",
                    "Methods, Headers and Status Codes",
                    "JSON and Content Types",
                    "REST Principles and Trade-offs",
                    "Modeling Resources and API Contracts",
                    "Errors and Status Design",
                    "Lab: Explore APIs with curl and Postman",
                ]),
                module("django-and-api-engineering", "Django and API Engineering", [
                    "Django Fundamentals",
                    "Django Project and Application Structure",
                    "Django REST Framework",
                    "Models and Domain Persistence",
                    "Serializers",
                    "Views, ViewSets and Routing",
                    "Validation",
                    "API Error Handling",
                    "Filtering, Searching and Ordering",
                    "Pagination",
                    "API Versioning",
                    "OpenAPI and Swagger Documentation",
                    "Configuration and Environments",
                    "Application Logging",
                    "Lab: Build Steward API Endpoints",
                ]),
                module("relational-data-and-postgresql", "Relational Data and PostgreSQL", [
                    "The Relational Model",
                    "SQL Fundamentals",
                    "Filtering and Ordering Data",
                    "Aggregations",
                    "GROUP BY and HAVING",
                    "INNER JOIN",
                    "LEFT and RIGHT JOIN",
                    "Subqueries",
                    "Common Table Expressions",
                    "Transactions and ACID",
                    "Keys, Constraints and Relationships",
                    "Schema Design",
                    "Normalization and Denormalization Trade-offs",
                    "Indexes",
                    "Query Plans and EXPLAIN",
                    "Query Performance Fundamentals",
                    "PostgreSQL Administration Basics",
                    "Django ORM",
                    "ORM vs SQL",
                    "The N+1 Query Problem",
                    "Database Migrations",
                    "Concurrency Fundamentals",
                    "Lab: Persist and Query Steward API Data",
                ]),
                module("identity-authentication-authorization", "Identity, Authentication and Authorization", [
                    "Identity Fundamentals",
                    "Authentication vs Authorization",
                    "Passwords, Hashing and Credential Storage",
                    "JWT Structure and Claims",
                    "Access and Refresh Tokens",
                    "Expiration, Rotation and Revocation Concepts",
                    "Authentication Flows",
                    "Roles and Permissions",
                    "Object-Level Authorization",
                    "Ownership and Access Rules",
                    "Common Authentication and Authorization Mistakes",
                    "Lab: Secure Steward API with JWT",
                ]),
                module("software-craft", "Software Craft", [
                    "Git Fundamentals",
                    "Branches, Commits and Collaboration",
                    "Readable Code",
                    "Separation of Concerns",
                    "Refactoring",
                    "Dependency Management",
                    "Configuration as an Engineering Concern",
                    "Designing Useful Application Logs",
                    "API and Code Documentation",
                    "Designing Errors for Humans and Systems",
                    "Performance Awareness",
                    "Milestone: Steward API v1",
                ]),
            ],
        },
        {
            id: "system-thinker",
            title: "System Thinker",
            paths: [
                module("requirements-and-problem-framing", "Requirements and Problem Framing", [
                    "From Requests to Problems",
                    "Stakeholders and Actors",
                    "Functional Requirements",
                    "Quality Requirements",
                    "Constraints and Assumptions",
                    "Acceptance and Evidence",
                ]),
                module("system-boundaries-and-context", "System Boundaries and Context", [
                    "System Context",
                    "Actors and External Systems",
                    "Defining System Boundaries",
                    "Trust and Ownership Boundaries",
                    "Lab: Draw the Steward API Context",
                ]),
                module("modeling-software-systems", "Modeling Software Systems", [
                    "Why We Model Systems",
                    "C4-Style Thinking",
                    "Containers and Components as Models",
                    "State and Lifecycle Modeling",
                    "Communicating Architecture Visually",
                ]),
                module("components-and-dependencies", "Components and Dependencies", [
                    "Components and Responsibilities",
                    "Coupling and Cohesion Foundations",
                    "Dependency Direction",
                    "Internal and External Dependencies",
                    "Lab: Map Steward API Dependencies",
                ]),
                module("data-flow-and-integration", "Data Flow and Integration", [
                    "Following Data Through a System",
                    "Synchronous and Asynchronous Boundaries",
                    "Integration Contracts",
                    "Failure Across Integrations",
                    "Lab: Model Steward API Data Flows",
                ]),
                module("failure-modes", "Failure Modes", [
                    "Thinking in Failure Modes",
                    "Dependency Failure",
                    "Invalid and Partial State",
                    "Resource Exhaustion",
                    "Human and Operational Failure",
                    "Lab: Analyze Steward API Failure Scenarios",
                ]),
                module("architecture-decisions", "Architecture Decisions and Trade-offs", [
                    "Architecture Characteristics Introduction",
                    "Decision Drivers",
                    "Architecture Decision Records",
                    "Evaluating Trade-offs",
                    "Lab: Write Steward API ADRs",
                    "Milestone: Steward API System Design Portfolio",
                ]),
            ],
        },
        {
            id: "platform-builder",
            title: "Platform Builder",
            paths: [
                module("computer-and-os-foundations", "Computer and Operating-System Foundations", [
                    "CPU, Memory, Storage and I/O",
                    "What an Operating System Does",
                    "Kernel Space and User Space",
                    "Processes and Threads",
                    "Filesystems",
                ]),
                module("linux-administration", "Linux Administration", [
                    "Installing Ubuntu Server",
                    "Shell Navigation and Command Fluency",
                    "Files and Directories",
                    "Users and Groups",
                    "Linux Permissions",
                    "Package Management",
                    "Processes and Signals",
                    "systemd and Services",
                    "Environment and Configuration",
                    "Logs and journalctl",
                    "Scheduled Tasks",
                    "Storage and Mounts",
                    "SSH and Key Authentication",
                    "Lab: Operate Steward API as a Linux Service",
                ]),
                module("networking-foundations", "Networking Foundations", [
                    "Networking Mental Models: OSI and TCP/IP",
                    "Ethernet and Switching",
                    "IP Addressing",
                    "Subnetting",
                    "ARP",
                    "TCP and UDP",
                    "Ports and Sockets",
                    "Routing",
                    "DHCP",
                    "DNS",
                    "NAT",
                    "Firewalls",
                    "HTTP and TLS from the Network Perspective",
                    "Network Troubleshooting Tools",
                    "Lab: Diagnose a Broken Service Path",
                ]),
                module("virtualization", "Virtualization", [
                    "Virtual Machines and Hypervisors",
                    "VM CPU, Memory and Storage",
                    "Virtual Networking Modes",
                    "Snapshots and Recovery",
                    "Lab: Build an Ubuntu Server VM",
                ]),
                module("budget-homelab", "Building the Budget Homelab", [
                    "Designing a Learning Homelab",
                    "Choosing Budget Hardware",
                    "CPU, RAM, Storage and NIC Trade-offs",
                    "Power, Noise and Reliability",
                    "Ethernet Switches and Cabling",
                    "Designing the Home Network Topology",
                    "Static Addressing",
                    "Multiple Hosts and VMs",
                    "Remote Administration",
                    "Local Firewalling",
                    "Local DNS Concepts",
                    "Reverse Proxies",
                    "Storage and Backups",
                    "Safe Exposure and Isolation",
                    "VLAN Concepts",
                    "Lab: Move Steward API into the Homelab",
                    "Milestone: Steward Homelab v1",
                ]),
            ],
        },
        {
            id: "delivery-engineer",
            title: "Delivery Engineer",
            paths: [
                module("software-delivery-foundations", "Software Delivery Foundations", [
                    "The Source-to-Production Lifecycle",
                    "Git Workflows",
                    "Pull Requests and Reviews",
                    "Semantic Versioning",
                    "Conventional Commits",
                    "Release Notes and Changelogs",
                    "Build Artifacts",
                    "Environment Promotion",
                ]),
                module("automation-and-shell", "Automation and Shell", [
                    "Shell Scripting for Engineers",
                    "Pipes, Exit Codes and Failure",
                    "Environment Variables",
                    "Repeatable Automation Scripts",
                    "Make and Task Automation",
                    "Idempotency Concepts",
                ]),
                module("containers-and-docker", "Containers and Docker", [
                    "Containers vs Virtual Machines",
                    "Namespaces and cgroups Concepts",
                    "Docker Architecture",
                    "Images and Layers",
                    "Writing Dockerfiles",
                    "Build Context",
                    "Multi-stage Builds",
                    "Volumes",
                    "Container Networking",
                    "Docker Compose",
                    "Health Checks",
                    "Container Registries",
                    "Image Tags and Versioning",
                    "Image Optimization",
                    "Container Debugging",
                    "Lab: Containerize Steward API",
                ]),
                module("continuous-integration", "Continuous Integration", [
                    "CI Pipeline Architecture",
                    "Jobs, Stages and Dependencies",
                    "Runners and Agents",
                    "GitHub Actions and Jenkins",
                    "Self-hosted Runners",
                    "Caching",
                    "Pipeline Artifacts",
                    "Secrets and Variables",
                    "Parallelism",
                    "Automated Checks",
                    "Test Stages",
                    "Quality Gates",
                    "Building Containers in CI",
                    "Lab: Run CI from the Homelab",
                ]),
                module("continuous-delivery-deployment", "Continuous Delivery and Deployment", [
                    "CI vs Continuous Delivery vs Continuous Deployment",
                    "Environment Management",
                    "Deployment Automation",
                    "Release Approvals",
                    "Database Migrations During Deployment",
                    "Rollback",
                    "Rolling Deployments",
                    "Blue-Green Deployments",
                    "Canary Deployment Concepts",
                    "Feature Flag Concepts",
                    "Lab: Automate Steward API Deployment and Rollback",
                ]),
                module("configuration-management", "Configuration Management", [
                    "Configuration Drift",
                    "Desired State and Idempotency",
                    "Ansible Fundamentals",
                    "Inventories",
                    "Playbooks",
                    "Roles Concepts",
                    "Lab: Automate the Steward Servers with Ansible",
                ]),
                module("artifact-and-supply-chain", "Artifact and Supply-Chain Foundations", [
                    "Artifact and Container Registries",
                    "Artifact Retention",
                    "Dependency Provenance Concepts",
                    "SBOM Fundamentals",
                    "Signing and Provenance Concepts",
                    "Dependency and Image Scanning Foundations",
                ]),
                module("release-engineering", "Release Engineering", [
                    "Release Candidates",
                    "Promotion and Gates",
                    "Deployment Evidence",
                    "Release Observability",
                    "Release Failure Handling",
                    "Release Runbooks",
                    "Milestone: Steward Delivery Platform",
                ]),
            ],
        },
        {
            id: "cloud-engineer",
            title: "Cloud Engineer",
            paths: [
                module("cloud-and-hosting-models", "Cloud and Hosting Models", [
                    "On-premises, Colocation, VPS and Cloud",
                    "IaaS, PaaS and SaaS",
                    "Regions and Availability Concepts",
                    "Shared Responsibility",
                    "Cloud Cost Awareness",
                ]),
                module("vps-operations", "VPS Operations", [
                    "Choosing a Budget VPS",
                    "Provisioning a Server",
                    "Public IP Addressing",
                    "Securing SSH Access",
                    "Provider Firewalls and Security Controls",
                    "OS Lifecycle and Patching",
                    "Remote Recovery Concepts",
                    "Lab: Provision the Steward VPS",
                ]),
                module("internet-networking", "Internet Networking", [
                    "Public and Private Addressing",
                    "Internet Routing Concepts",
                    "Domains and DNS Records",
                    "TLS Certificates",
                    "Reverse Proxies",
                    "Ingress Concepts",
                    "Internet-facing Firewalls",
                    "Lab: Publish Steward API with DNS and TLS",
                ]),
                module("cloud-building-blocks", "Cloud Building Blocks", [
                    "Compute",
                    "Object and Block Storage",
                    "Managed Databases",
                    "Virtual Networks",
                    "Load Balancers",
                    "IAM",
                    "Secrets Management",
                    "Cloud Monitoring",
                    "Cloud Backup Services",
                ]),
                module("infrastructure-as-code", "Infrastructure as Code", [
                    "Declarative Infrastructure",
                    "Terraform and OpenTofu Fundamentals",
                    "State",
                    "Variables and Outputs",
                    "Modules Concepts",
                    "Plan and Apply Lifecycle",
                    "Lab: Define Steward Infrastructure as Code",
                ]),
                module("cloud-architecture-and-cost", "Cloud Architecture and Cost", [
                    "Availability in Cloud Environments",
                    "Scalability",
                    "Security Boundaries",
                    "Backup and Recovery",
                    "Cost Estimation",
                    "Cost Controls",
                    "Managed vs Self-managed Trade-offs",
                    "Milestone: Steward Internet Environment",
                ]),
            ],
        },
        {
            id: "quality-steward",
            title: "Quality Steward",
            paths: [
                module("quality-engineering", "Quality Engineering", [
                    "Quality vs Testing",
                    "Quality Risks",
                    "Test Strategy",
                    "Test Levels and Test Types",
                    "Risk-based Testing",
                    "Shift-left and Shift-right",
                    "Testability",
                    "Lab: Write the Steward Quality Strategy",
                ]),
                module("test-analysis-and-design", "Test Analysis and Design", [
                    "Requirements Analysis for Testing",
                    "Equivalence Partitioning",
                    "Boundary Value Analysis",
                    "Decision Tables",
                    "State Transition Testing",
                    "Pairwise and Combinatorial Concepts",
                    "Exploratory Testing",
                    "Negative Testing",
                    "Traceability",
                ]),
                module("unit-and-component-testing", "Unit and Component Testing", [
                    "Designing Unit Tests",
                    "Isolation",
                    "Test Doubles",
                    "Mocks, Stubs and Fakes",
                    "Coverage and Its Limitations",
                ]),
                module("api-and-integration-testing", "API and Integration Testing", [
                    "API Test Design",
                    "Authentication and Authorization Testing",
                    "Schema and Contract Validation",
                    "Database Assertions",
                    "Integration Boundaries",
                    "Contract Testing Concepts",
                    "Mocking and Service Virtualization",
                    "Lab: Test Steward API End-to-End at the Service Layer",
                ]),
                module("automation-framework-engineering", "Automation Framework Engineering", [
                    "What Makes an Automation Framework",
                    "Framework Architecture",
                    "Playwright with Python",
                    "pytest Fundamentals",
                    "Configuration",
                    "Fixtures",
                    "Test Data",
                    "API Clients",
                    "Page Objects and UI Abstractions",
                    "Helpers and Utilities",
                    "Assertions",
                    "Markers and Tags",
                    "Parameterization",
                    "Automation Logging",
                    "Reports",
                    "Screenshots, Traces and Video",
                    "Parallel Execution",
                    "Retries and Flaky-test Risk",
                    "Framework Maintainability",
                    "Lab: Build the Steward Automation Framework",
                ]),
                module("browser-and-environment-testing", "Browser and Environment Testing", [
                    "Browser Differences",
                    "Responsive Testing",
                    "Cross-browser Strategy",
                    "BrowserStack and Cloud Test Infrastructure",
                    "Local vs Remote Execution",
                    "Lab: Execute Steward Tests Remotely",
                ]),
                module("non-functional-quality", "Non-functional Quality", [
                    "Performance Testing Concepts",
                    "Load, Stress, Spike and Endurance Testing",
                    "Accessibility Testing Fundamentals",
                    "Compatibility Testing",
                    "Reliability-oriented Tests",
                ]),
                module("quality-in-ci-cd", "Quality in Containers and CI/CD", [
                    "Testing Dockerized Services",
                    "Ephemeral Test Environments Concepts",
                    "Test Stages in Pipelines",
                    "Parallel Test Execution",
                    "Reports and Artifacts",
                    "Quality Gates",
                    "Test Selection",
                    "Failure Triage",
                    "Milestone: Steward Quality Platform",
                ]),
            ],
        },
        {
            id: "security-steward",
            title: "Security Steward",
            paths: [
                module("security-foundations", "Security Foundations", [
                    "Confidentiality, Integrity and Availability",
                    "Assets, Threats, Vulnerabilities and Risk",
                    "Attack Surface",
                    "Least Privilege",
                    "Defense in Depth",
                    "Trust Boundaries",
                ]),
                module("threat-modeling", "Threat Modeling", [
                    "Assets and Actors",
                    "Security Data Flows",
                    "Trust Boundaries in Threat Models",
                    "STRIDE-style Threat Identification",
                    "Risk Prioritization",
                    "Selecting Mitigations",
                    "Lab: Threat-model Steward API",
                ]),
                module("web-and-api-threats", "Web and API Threats", [
                    "Injection and SQL Injection",
                    "Cross-site Scripting",
                    "Cross-site Request Forgery",
                    "Broken Authentication",
                    "Broken Authorization and IDOR",
                    "Server-side Request Forgery",
                    "Path Traversal",
                    "File Upload Risks",
                    "Command Injection",
                    "Insecure Deserialization Concepts",
                    "Security Misconfiguration",
                    "Secrets and Sensitive Data Exposure",
                    "API Abuse and Rate Limiting",
                    "Session and Token Attacks",
                    "Cryptographic Failures",
                    "Vulnerable Dependencies",
                    "Security Logging and Monitoring Failures",
                ]),
                module("vulnerability-laboratory", "Practical Vulnerability Laboratory", [
                    "Designing an Isolated Security Lab",
                    "Running Deliberately Vulnerable Applications Safely",
                    "Observing Vulnerability Behavior",
                    "Reproducing Representative Attacks",
                    "Gathering Security Evidence",
                    "Implementing Mitigations",
                    "Retesting After Remediation",
                ]),
                module("linux-and-network-security", "Linux and Network Security", [
                    "Linux Users and Permissions for Security",
                    "SSH Hardening",
                    "Firewalling",
                    "Service Exposure",
                    "Patch Management",
                    "Privilege Concepts",
                    "Logging and Auditing",
                    "Network Segmentation Concepts",
                    "Lab: Harden the Steward Ubuntu Host",
                ]),
                module("container-and-delivery-security", "Container and Delivery Security", [
                    "Container Attack Surface",
                    "Image Scanning",
                    "Minimal Images",
                    "Runtime Permissions",
                    "Secrets in Delivery Systems",
                    "CI/CD Permissions",
                    "Dependency Scanning",
                    "SAST and DAST Concepts",
                    "Software Supply-chain Risk",
                    "Security Gates",
                    "Lab: Harden the Steward Delivery Pipeline",
                ]),
                module("application-security-engineering", "Application Security Engineering", [
                    "Secure Authentication",
                    "Authorization Testing",
                    "Input Validation",
                    "Secret Management",
                    "Secure Headers and Configuration",
                    "Security Logging",
                    "Abuse Cases",
                    "Milestone: Steward Security Assessment and Hardening",
                ]),
            ],
        },
        {
            id: "reliability-engineer",
            title: "Reliability Engineer",
            paths: [
                module("reliability-and-sre-foundations", "Reliability and SRE Foundations", [
                    "Reliability as a Quality Attribute",
                    "Availability",
                    "Failure and Recovery",
                    "SRE Principles",
                    "Toil",
                    "Reliability Trade-offs",
                ]),
                module("observability", "Observability", [
                    "Observability vs Monitoring",
                    "Logs, Metrics and Traces",
                    "Telemetry Design",
                    "Correlation and Context",
                    "Instrumentation",
                    "OpenTelemetry Concepts",
                    "Lab: Instrument Steward API",
                ]),
                module("logging", "Logging", [
                    "Structured Logging",
                    "Log Levels",
                    "Correlation IDs",
                    "Log Centralization Concepts",
                    "Useful vs Noisy Logs",
                    "Security and Privacy in Logs",
                ]),
                module("metrics-prometheus-grafana", "Metrics, Prometheus and Grafana", [
                    "Counters, Gauges and Histograms",
                    "Application and Infrastructure Metrics",
                    "Prometheus Architecture",
                    "Exporters",
                    "PromQL Fundamentals",
                    "Grafana Dashboards",
                    "Dashboard Design",
                    "Lab: Monitor Steward with Prometheus and Grafana",
                ]),
                module("service-level-engineering", "Service Level Engineering", [
                    "Service Level Indicators",
                    "Service Level Objectives",
                    "Service Level Agreements",
                    "Error Budgets",
                    "Measuring User-visible Reliability",
                    "Choosing Meaningful Objectives",
                    "Lab: Define Steward SLOs",
                ]),
                module("alerting-and-on-call", "Alerting and On-call Thinking", [
                    "Symptoms vs Causes",
                    "Actionable Alerts",
                    "Alert Fatigue",
                    "Severity",
                    "Escalation",
                    "Runbooks",
                    "Lab: Build Steward Alerts and Runbooks",
                ]),
                module("performance-and-capacity", "Performance and Capacity", [
                    "Latency and Throughput",
                    "Saturation",
                    "Finding Bottlenecks",
                    "Load and Stress Testing",
                    "Capacity Planning",
                    "Resource Utilization",
                    "Database and Application Bottlenecks",
                    "Performance Baselines",
                    "Lab: Establish Steward Performance Baselines",
                ]),
                module("resilience-and-distributed-failure", "Resilience and Distributed Failure", [
                    "Timeouts",
                    "Retries",
                    "Exponential Backoff and Jitter",
                    "Circuit Breakers",
                    "Idempotency",
                    "Partial Failure",
                    "Dependency Failure",
                    "Cascading Failure",
                    "Queues and Backpressure Concepts",
                    "Graceful Degradation",
                ]),
                module("data-protection-and-disaster-recovery", "Data Protection and Disaster Recovery", [
                    "Backup Strategies",
                    "Restore Testing",
                    "RPO and RTO",
                    "Disaster Scenarios",
                    "Recovery Procedures",
                    "Data Durability",
                    "Lab: Perform a Steward Backup and Restore Drill",
                ]),
                module("incident-management", "Incident Management", [
                    "Detection and Triage",
                    "Incident Roles",
                    "Incident Communication",
                    "Mitigation",
                    "Root-cause Analysis",
                    "Blameless Postmortems",
                    "Corrective Actions",
                    "Lab: Run a Steward Incident Simulation",
                ]),
                module("fault-injection", "Fault Injection and Reliability Experiments", [
                    "Hypothesis-driven Reliability Experiments",
                    "Controlled Failure Injection",
                    "Process and Container Failure",
                    "Resource Exhaustion Concepts",
                    "Network and Dependency Failure Simulation",
                    "Recovery Verification",
                    "Chaos Engineering Principles and Safety",
                    "Milestone: Steward Reliability Program",
                ]),
            ],
        },
        {
            id: "architect",
            title: "Architect",
            paths: [
                module("architecture-fundamentals", "Architecture Fundamentals", [
                    "Architecture vs Design",
                    "Architecture Characteristics",
                    "Constraints",
                    "Architecture Trade-offs",
                    "Fitness for Purpose",
                ]),
                module("modularity", "Modularity", [
                    "Coupling and Cohesion",
                    "Components and Modules",
                    "Dependency Direction",
                    "Architectural Boundaries",
                    "Modular Monoliths",
                    "When Distribution Is Justified",
                ]),
                module("architectural-styles", "Architectural Styles", [
                    "Layered Architecture",
                    "Hexagonal and Ports-and-Adapters Concepts",
                    "Event-driven Architecture",
                    "Service-oriented and Microservices Concepts",
                    "Serverless Concepts",
                    "Choosing an Architectural Style",
                ]),
                module("domain-modeling", "Domain Modeling", [
                    "Domain Boundaries",
                    "Domain-Driven Design Fundamentals",
                    "Entities, Value Objects and Aggregates",
                    "Bounded Contexts",
                    "Ubiquitous Language",
                    "When DDD Is Worth the Cost",
                ]),
                module("data-architecture", "Data Architecture", [
                    "Transactional Boundaries",
                    "Consistency",
                    "Caching",
                    "Replication Concepts",
                    "Partitioning Concepts",
                    "Data Ownership",
                    "Eventual Consistency",
                ]),
                module("integration-and-messaging", "Integration and Messaging", [
                    "Synchronous vs Asynchronous Integration",
                    "Messaging Fundamentals",
                    "Queues",
                    "Events",
                    "Delivery Semantics Concepts",
                    "Idempotency in Integrations",
                    "Failure Handling",
                ]),
                module("scalability-and-distributed-systems", "Scalability and Distributed Systems", [
                    "Vertical and Horizontal Scaling",
                    "Load Balancing",
                    "Statelessness",
                    "Caching for Scale",
                    "Distributed-system Constraints",
                    "CAP Theorem as a Reasoning Tool",
                    "Consistency and Availability Trade-offs",
                    "Distributed Failure",
                ]),
                module("resilience-architecture", "Resilience Architecture", [
                    "Redundancy",
                    "Isolation",
                    "Bulkheads",
                    "Timeouts and Retries",
                    "Circuit Breakers",
                    "Graceful Degradation",
                    "Disaster Scenarios",
                ]),
                module("architecture-evaluation-governance", "Architecture Evaluation and Governance", [
                    "Architecture Decision Records Revisited",
                    "Architecture Reviews",
                    "Architecture Fitness Functions",
                    "Evolutionary Architecture",
                    "Technical Debt in Architecture",
                    "Architecture Katas",
                    "Cost, Performance, Security and Reliability Trade-offs",
                    "Lab: Evolve Steward Architecture",
                    "Milestone: Steward Architecture Evolution",
                ]),
            ],
        },
        {
            id: "technical-steward",
            title: "Technical Steward",
            paths: [
                module("technical-leadership", "Technical Leadership", [
                    "Technical Ownership",
                    "Influence Without Authority",
                    "Technical Decision-making",
                    "Technical Communication",
                    "Mentoring",
                    "Technical Reviews",
                ]),
                module("engineering-governance", "Engineering Governance", [
                    "Governance vs Management",
                    "Decision Rights",
                    "Accountability",
                    "Policies, Standards, Procedures and Guidelines",
                    "Exception Processes",
                    "Governance Without Bureaucracy",
                ]),
                module("it-technology-governance", "IT and Technology Governance", [
                    "Business and Technology Alignment",
                    "Value Delivery",
                    "Resource Stewardship",
                    "Performance Oversight",
                    "Governance Structures",
                    "COBIT Concepts",
                    "ITIL and Service Management Concepts",
                    "ISO Management-system Concepts",
                    "NIST Framework Landscape",
                ]),
                module("technology-risk", "Technology Risk", [
                    "Risk Identification",
                    "Likelihood and Impact",
                    "Inherent vs Residual Risk",
                    "Risk Appetite and Tolerance",
                    "Risk Treatment",
                    "Risk Acceptance",
                    "Risk Registers",
                    "Key Risk Indicators",
                ]),
                module("controls-compliance-assurance", "Controls, Compliance and Assurance", [
                    "Preventive, Detective and Corrective Controls",
                    "Control Objectives",
                    "Control Design",
                    "Control Effectiveness",
                    "Evidence",
                    "Testing Controls",
                    "Compliance vs Security",
                    "Audit Fundamentals",
                    "Remediation Tracking",
                ]),
                module("architecture-governance", "Architecture Governance", [
                    "Architecture Principles",
                    "Architecture Standards",
                    "Technology Selection",
                    "Architecture Review",
                    "Architecture Exceptions",
                    "Technology Lifecycle Management",
                ]),
                module("security-and-data-governance", "Security and Data Governance", [
                    "Security Governance",
                    "Security Roles and Accountability",
                    "Policy Hierarchies",
                    "Data Ownership",
                    "Data Classification Concepts",
                    "Retention and Privacy Concepts",
                    "Access Governance",
                ]),
                module("change-and-service-governance", "Change and Service Governance", [
                    "Change Risk",
                    "Change Controls",
                    "Release Governance",
                    "Service Ownership",
                    "Incident, Problem and Change Relationships",
                    "Operational Readiness",
                ]),
                module("third-party-lifecycle-risk", "Third-party and Technology Lifecycle Risk", [
                    "Vendor Assessment",
                    "Dependency Risk",
                    "SaaS and Cloud Governance Considerations",
                    "End-of-life Technology",
                    "Exit and Continuity Planning",
                ]),
                module("technical-debt-engineering-health", "Technical Debt and Engineering Health", [
                    "Identifying Technical Debt",
                    "Measuring and Communicating Debt",
                    "Prioritizing Debt",
                    "Engineering Health Metrics",
                    "KPIs vs KRIs",
                    "Sustainable Remediation",
                ]),
                module("engineering-handbook-standards", "Engineering Handbook and Standards", [
                    "Writing Useful Engineering Standards",
                    "Runbooks and Playbooks",
                    "Decision Records",
                    "Review Checklists",
                    "Knowledge Stewardship",
                    "Lab: Govern the Steward Platform",
                    "Milestone: Technical Stewardship Review",
                ]),
            ],
        },
        {
            id: "professional-engineer",
            title: "Professional Engineer",
            paths: [
                module("problem-discovery", "Problem Discovery", [
                    "Working with Stakeholders",
                    "Discovering Requirements",
                    "Working with Constraints",
                    "Engineering Under Ambiguity",
                    "Identifying Quality Attributes",
                    "Early Risk Analysis",
                ]),
                module("engineering-proposal", "Engineering Proposal", [
                    "Proposing a System Design",
                    "Proposing Architecture Decisions",
                    "Planning Delivery",
                    "Designing a Quality Strategy",
                    "Designing a Security Strategy",
                    "Designing a Reliability Strategy",
                    "Defining the Operational Model",
                    "Building a Cost Model",
                    "Identifying Governance Considerations",
                ]),
                module("independent-build", "Independent Build", [
                    "Capstone Brief: Start from a Blank Repository",
                    "Independent System Modeling",
                    "Independent Implementation",
                    "Independent Infrastructure and Delivery",
                    "Independent Quality Engineering",
                    "Independent Security Engineering",
                    "Independent Operations",
                ]),
                module("production-readiness", "Production Readiness", [
                    "Production Deployment",
                    "Production Observability",
                    "Security Assessment",
                    "Performance Evidence",
                    "Backup and Recovery Evidence",
                    "Runbooks",
                    "Risk and Control Evidence",
                    "Production Readiness Review",
                ]),
                module("engineering-defence", "Engineering Defence", [
                    "Presenting the Architecture",
                    "Explaining Trade-offs",
                    "Demonstrating Evidence",
                    "Defending Engineering Decisions",
                    "Responding to Review Challenges",
                    "Identifying Limitations and Future Evolution",
                    "Final Milestone: Professional Engineering Capstone and Defence",
                ]),
            ],
        },
    ],
};
