import type { Lesson } from "./lesson";

const scenario = "Treat Steward as an organization-owned service whose security and data responsibilities span application code, PostgreSQL, cloud/VPS infrastructure, CI/CD, Nexus, internal packages, operators and business stakeholders. Reuse Security Steward evidence; this module governs accountability and decisions rather than reteaching attack techniques.";
const deliverables = ["Governance artifact", "Evidence and rationale", "Owner, exception or review record"];
const criteria = ["Security or data accountability is explicit.", "Policy intent is separated from implementation detail.", "Exceptions and residual risk follow defined authority and review rules."];
function lesson(id: string, title: string, body: string, instructions: string[]): Lesson {
  return { id: `security-data-governance-${id}`, title, activities: [
    { id: `security-data-governance-${id}-reading`, title: `${title}: concepts`, estimatedMinutes: 60, content: { type: "reading", body } },
    { id: `security-data-governance-${id}-practice`, title: `${title}: Steward exercise`, estimatedMinutes: 60, content: { type: "practical", objective: `Apply ${title} to Steward governance.`, scenario, instructions, deliverables, completionCriteria: criteria } },
  ] };
}

export const securityDataGovernanceDeepLessons: Lesson[] = [
  lesson("security-governance", "Security Governance", `Security governance sets direction, accountability and oversight for security outcomes. Security engineering discovers and reduces threats; governance determines who owns decisions, what minimum expectations apply, which evidence demonstrates operation, how exceptions are handled and when residual risk requires escalation. Reuse threat models, vulnerability evidence, secure-delivery controls and incident lessons from the Security Steward school rather than creating parallel paperwork.`, ["Map Steward security objectives to accountable owners.", "Identify which existing controls need governance oversight versus local engineering ownership.", "Define evidence and review cadence for a small set of material security expectations.", "Separate security policy direction from implementation choices."]),
  lesson("roles", "Roles and Accountability", `Clear security and data governance distinguishes accountable business/data owners, service owners, technical custodians, control owners, approvers and users. RACI-style tools can help, but labels do not replace decision rights. The person operating PostgreSQL or Nexus may be responsible for implementation without owning the business decision about data classification, retention or accepted exposure.`, ["Map owner, custodian, control owner and decision authority for Steward application data, PostgreSQL, secrets, Nexus and internal packages.", "Identify ambiguous or conflicting ownership.", "Assign escalation paths for decisions that exceed technical authority.", "Check that accountability follows the affected objective rather than proximity to the code."]),
  lesson("policy-hierarchy", "Policy Hierarchy", `A usable hierarchy separates policy, standards, procedures and guidelines. Policy states mandatory intent and organizational direction; standards define required rules or baselines; procedures describe how to execute repeatable work; guidelines provide recommended practices. Mixing all four creates brittle documents and makes exceptions difficult to govern. Lower-level artifacts should trace upward to the objective they implement.`, ["Draft a small Steward security/data policy hierarchy.", "Classify existing examples as policy, standard, procedure or guideline.", "Trace each lower-level artifact to a higher-level intent.", "Remove implementation detail that does not belong in policy."]),
  lesson("data-ownership", "Data Ownership", `Data ownership is accountability for acceptable use, quality expectations, access decisions, classification, retention and lifecycle. It is distinct from database administration. The Steward domain and data architecture already identify logical ownership boundaries; governance now assigns authority for decisions about those data sets. Shared infrastructure does not imply shared ownership.`, ["Identify Steward data domains and their accountable owners.", "Distinguish owner from PostgreSQL/platform custodian.", "Define owner decisions for access, quality, retention and change.", "Flag data sets with no credible owner."]),
  lesson("classification", "Data Classification", `Classification groups data by sensitivity and handling need so controls can be proportionate. A simple scheme such as public, internal, confidential and restricted may be enough if each class has concrete handling consequences. Classification should consider confidentiality, integrity, availability, legal/privacy obligations and business impact. Avoid classifying everything at the highest level, which destroys the signal and increases cost without improving control.`, ["Create a lean Steward classification scheme with handling rules.", "Classify representative application, audit, operational, credential and package metadata.", "Justify classifications using impact rather than intuition.", "Identify controls that should vary by class."]),
  lesson("retention-privacy", "Retention and Privacy Concepts", `Retention governs how long information is kept and why; privacy governance addresses lawful, fair and limited processing of personal information. Engineers should not invent legal obligations, but they must translate approved requirements into system behavior. Keep only what has a purpose, distinguish operational logs from audit/history records, define deletion or archival behavior, and account for backups and derived copies.`, ["Inventory Steward data types that may contain personal, operational or historical information.", "Assign a justified retention purpose and owner to each.", "Identify copies in logs, backups, exports or derived views.", "Mark where legal/privacy guidance is required instead of making assumptions."]),
  lesson("access", "Access Governance", `Access governance ensures access is justified, approved by the right authority, provisioned correctly, reviewed and removed when no longer needed. Authentication and authorization mechanisms are technical controls; governance covers entitlement ownership, least privilege, segregation of duties where justified, privileged access, service accounts, review cadence and evidence. Access reviews should target meaningful risk rather than generate giant spreadsheets no one challenges.`, ["Map privileged and normal access paths across Steward, PostgreSQL, cloud/VPS, CI/CD and Nexus.", "Define who approves each access class and why.", "Design joiner/mover/leaver and periodic review evidence.", "Identify one access-review activity that can be automated or risk-scoped."]),
  lesson("exceptions", "Security Exceptions and Risk Acceptance", `Security exceptions are temporary or context-specific departures from an approved requirement. They should state the requirement, rationale, affected assets, threat/risk, compensating controls, residual exposure, accountable acceptance authority, expiry and review triggers. An exception is not a hidden backlog item. Repeated exceptions may show that a standard is unrealistic, a platform capability is missing or investment is required.`, ["Create a realistic Steward security or data exception request.", "Link it to the relevant standard and technology risk.", "Define compensating controls and residual risk.", "Specify authority, expiry and event-driven review triggers."]),
  {
    id: "security-data-governance-steward-accountability-lab", title: "Lab: Define Steward Security and Data Accountability", activities: [
      { id: "security-data-governance-steward-accountability-lab-1", title: "Map accountability and policy", estimatedMinutes: 120, content: { type: "practical", objective: "Create a coherent security and data governance model for Steward.", scenario, instructions: ["Map security, service, data and control ownership across Steward components.", "Create a policy/standard/procedure hierarchy for the highest-value governance needs.", "Classify major data types and define handling consequences.", "Identify missing authority or policy direction that cannot responsibly be invented by engineers."], deliverables: ["Accountability map", "Policy hierarchy", "Data classification register", "Governance gaps"], completionCriteria: criteria } },
      { id: "security-data-governance-steward-accountability-lab-2", title: "Govern access and lifecycle", estimatedMinutes: 120, content: { type: "practical", objective: "Translate accountability into operational access, retention and privacy controls.", scenario, instructions: ["Define access approval, privileged access and review ownership for key systems.", "Define retention purpose, lifecycle and deletion/archive expectations for key data sets.", "Map evidence demonstrating those controls operate.", "Prefer automated guardrails and focused reviews where they reduce friction."], deliverables: ["Access governance matrix", "Retention/lifecycle matrix", "Evidence plan", "Automation opportunities"], completionCriteria: criteria } },
      { id: "security-data-governance-steward-accountability-lab-3", title: "Test an exception and review loop", estimatedMinutes: 90, content: { type: "practical", objective: "Demonstrate that Steward security/data governance can handle legitimate exceptions without hiding risk.", scenario, instructions: ["Submit one credible exception against an approved requirement.", "Assess compensating controls and residual risk using the risk model.", "Record the decision, authority, expiry and review trigger.", "Use the exception to decide whether the standard, platform or roadmap needs improvement."], deliverables: ["Exception record", "Residual-risk decision", "Review trigger", "Governance improvement action"], completionCriteria: ["Ownership and authority are unambiguous.", "Security/Data governance reuses existing technical evidence rather than duplicating it.", "Access, classification and retention requirements are proportionate to risk.", "Exceptions are visible, time-bounded or explicitly reviewed, and connected to residual risk."] } },
    ]
  },
];
