import type { Lesson } from "./lesson";

const scenario = "Steward is a mature organization-owned service whose architecture, delivery, quality, security, reliability, dependency, risk and governance decisions need durable guidance that engineers can find, understand, challenge and maintain. The handbook is an organizational-memory and navigation layer, not a duplicate of every technical artifact.";

function reading(id: string, title: string, body: string, outcomes: string[], example: string, mistakes: string[], practice: string[]): Lesson {
  return {
    id,
    title,
    activities: [{
      id: `${id}-001`,
      title,
      estimatedMinutes: 50,
      content: {
        type: "reading",
        body: `${scenario}\n\nLearning outcomes\n- ${outcomes.join("\n- ")}\n\n${body}\n\nWorked Steward example\n${example}\n\nCommon mistakes\n- ${mistakes.join("\n- ")}\n\nPractice\n- ${practice.join("\n- ")}`,
      },
    }],
  };
}

export const handbookAndStandardsDeepLessons: Lesson[] = [
  reading("handbook-and-standards-writing-usable-standards", "Writing Usable Standards", "A standard converts governance intent into repeatable engineering expectations. A useful standard states scope, requirement, rationale, ownership, verification and the legitimate exception path. Prefer outcome-oriented requirements where implementation flexibility matters, and prescribe a mechanism only when interoperability, risk or organizational consistency justifies it. Every mandatory rule creates maintenance and compliance cost, so do not standardize choices teams can safely make locally.", ["Distinguish standards from policies, procedures and guidelines.", "Write clear, testable and proportionate requirements.", "Avoid encoding personal tool preferences as organization-wide mandates."], "Require internal packages to be published through the approved Nexus repository with traceable provenance, while allowing package-specific implementation choices that do not affect consumers or supply-chain controls.", ["Turning preferences into mandatory standards.", "Writing vague requirements that cannot be verified.", "Copying frameworks without adapting them to Steward.", "Creating requirements without an owner or exception path."], ["Rewrite three vague Steward expectations as testable standards.", "For each, identify scope, rationale, verification evidence and exception authority.", "Remove one proposed rule that does not justify organization-wide standardization."]),
  reading("handbook-and-standards-runbooks-and-playbooks", "Runbooks and Playbooks", "A runbook gives concrete steps for a known operational task or condition; a playbook guides decisions across a class of situations where judgment is still required. Good operational guidance includes prerequisites, safety boundaries, expected observations, verification, rollback or stop conditions, escalation and ownership. A document that has never been exercised is an assumption, so high-consequence procedures must be tested and revised when reality differs.", ["Distinguish runbooks from playbooks.", "Design operational guidance for time-sensitive work.", "Keep procedures aligned with real system behavior."], "A PostgreSQL restore runbook identifies backup source, target, safety checks, commands or automation, validation queries, RTO/RPO evidence and escalation conditions rather than merely saying 'restore the database'.", ["Writing procedures from memory without executing them.", "Omitting stop or rollback conditions.", "Embedding secrets in examples.", "Treating uncertain incidents as deterministic runbooks."], ["Choose one Steward operational capability and classify the needed artifact as runbook or playbook.", "Draft prerequisites, verification and escalation sections.", "Define how it will be exercised and kept current."]),
  reading("handbook-and-standards-decision-records", "Decision Records", "Decision records preserve why consequential choices were made so future engineers can distinguish deliberate trade-offs from accidents. Reuse ADR discipline: context, decision, alternatives, evidence, consequences and status. Historical decisions should normally remain immutable; later decisions supersede them. Do not create ADRs for trivial implementation choices or use them as approval forms.", ["Capture durable decision context without rewriting design documents.", "Record alternatives, evidence and consequences.", "Know when a decision should be superseded rather than silently edited."], "If Steward retains a single PostgreSQL database after evaluating decomposition, preserve the quality-attribute evidence and rejected alternatives so a future team does not split it merely because the rationale disappeared.", ["Recording only the chosen solution.", "Editing away historical rationale.", "Creating records for every code change.", "Using ADRs as substitutes for implementation documentation."], ["Review one Steward architecture or governance decision.", "Identify what a future engineer needs to understand its rationale.", "Draft or supersede the record if the decision changed."]),
  reading("handbook-and-standards-review-checklists", "Review Checklists", "A checklist protects against predictable omissions in repeatable work; it is not evidence that the work is correct. Steward checklists should prompt reviewers to inspect relevant evidence according to change risk. Keep items concrete and short, use conditional sections, and automate machine-verifiable rules. Review escaped failures and ignored prompts to improve or retire checklist items.", ["Use checklists as cognitive aids rather than approval theater.", "Design risk-sensitive review prompts.", "Retire checklist items that no longer improve decisions."], "A low-risk documentation change should not receive the same operational-readiness checklist as a PostgreSQL schema migration; the latter can trigger data-migration, backup, rollback and monitoring prompts.", ["Treating checked boxes as operating evidence.", "Applying one checklist to every change.", "Keeping obsolete prompts forever.", "Using humans for rules CI can enforce reliably."], ["Design a short production-change checklist with conditional prompts.", "Mark which items should be automated.", "Define a signal that would cause a prompt to be revised or retired."]),
  reading("handbook-and-standards-knowledge-stewardship", "Knowledge Stewardship", "Knowledge stewardship makes critical engineering context discoverable, trustworthy and transferable. The goal is not maximum documentation; it is enough maintained knowledge to operate and evolve Steward without depending on one person's memory. Prefer documentation close to the system or decision it describes, stable links, ownership metadata and explicit freshness signals. Treat concentrated undocumented knowledge as an operational risk.", ["Treat technical knowledge as an owned lifecycle asset.", "Reduce dependence on undocumented individual knowledge.", "Choose durable locations and discovery paths."], "The owner and support policy for tsa-test-core belong in discoverable package/handbook metadata, while detailed API documentation remains close to the package rather than being duplicated into a governance manual.", ["Centralizing every detail into one enormous handbook.", "Duplicating documentation until copies disagree.", "Assuming a wiki page transfers operational capability.", "Leaving critical knowledge without a maintainer."], ["Map five critical Steward knowledge assets to authoritative locations and owners.", "Identify one single-person knowledge dependency.", "Design a transfer or validation activity."]),
  reading("handbook-and-standards-standards-ownership-and-versioning", "Standards Ownership and Versioning", "Standards are products with consumers. Owners are accountable for clarity, review, feedback, exceptions and lifecycle decisions, not for personally enforcing every rule. Material changes should be traceable so engineers know which expectation applied when evidence was produced. Define effective dates, migration expectations where needed, review cadence and deprecation or supersession status without overengineering prose versioning.", ["Assign accountable ownership for standards.", "Version material changes without freezing guidance forever.", "Define review and deprecation lifecycles."], "When the internal-package provenance requirement becomes stricter, publish the new effective requirement, define which packages must migrate and by when, and preserve the prior version for historical evidence.", ["Publishing standards with no owner.", "Changing requirements silently.", "Treating wording fixes as major governance events.", "Keeping obsolete standards active indefinitely."], ["Define ownership/lifecycle metadata for three Steward standards.", "Classify sample changes as editorial, material or superseding.", "Specify how consumers discover the effective requirement."]),
  reading("handbook-and-standards-exception-and-waiver-records", "Exception and Waiver Records", "An exception is an explicit, bounded decision not to meet a normally applicable requirement. Record requirement, reason, scope, residual risk, compensating controls, authority, owner, expiry or review trigger and remediation plan where applicable. Repeated exceptions are governance evidence: the standard may be unrealistic, the paved road inadequate or teams insufficiently enabled.", ["Record deviations without normalizing silent non-compliance.", "Connect exceptions to risk acceptance and compensating controls.", "Use recurring exceptions as feedback about standards."], "A package temporarily unable to publish required provenance evidence may receive a time-bound exception only after supply-chain exposure, compensating verification and migration ownership are explicit.", ["Bypassing inconvenient controls silently.", "Approving without expiry or review trigger.", "Treating all deviations as equally risky.", "Renewing the same waiver without challenging the standard or platform."], ["Draft one Steward exception record tied to an existing standard.", "Define acceptance authority and compensating-control evidence.", "State what repeated exceptions would tell you about the standard."]),
  reading("handbook-and-standards-keeping-the-handbook-alive", "Keeping the Handbook Alive", "A handbook is useful only while it reflects how engineering actually works. Make maintenance event-driven as well as periodic: incidents, architecture decisions, control failures, repeated exceptions, new platform capabilities, dependency lifecycle changes and onboarding confusion should trigger review. Use repository ownership, pull-request review and lightweight scheduled checks rather than a parallel documentation bureaucracy. Delete or supersede guidance when it no longer earns its maintenance cost.", ["Design feedback loops that keep guidance current.", "Detect stale or unused documentation.", "Evolve guidance from incidents, reviews, exceptions and engineering-health evidence."], "If repeated exceptions target a manual release-control step after CI gains an equivalent automated guardrail, revise the handbook rather than preserving obsolete ceremony.", ["Annual review as the only freshness mechanism.", "Measuring documentation volume instead of usability.", "Never deleting outdated guidance.", "Updating policy without changing the engineering path it describes."], ["Define event-driven update triggers for the Steward handbook.", "Choose two freshness/usability signals with explicit actions.", "Identify one class of documentation that should stay outside the handbook."]),
  {
    id: "handbook-and-standards-lab-build-the-steward-engineering-handbook",
    title: "Lab: Build the Steward Engineering Handbook",
    activities: [{
      id: "handbook-and-standards-lab-build-the-steward-engineering-handbook-001",
      title: "Lab: Build the Steward Engineering Handbook",
      estimatedMinutes: 390,
      content: {
        type: "practical",
        objective: "Build and exercise a maintainable Steward engineering handbook that consolidates the minimum durable standards, operational guidance, decision records, review aids and exception mechanisms needed to govern the mature service.",
        scenario: "Steward has accumulated evidence across the full TSA journey. Your task is not to copy everything into one document, but to build a trustworthy navigation and standards layer over authoritative sources.",
        instructions: ["Inventory existing Steward governance and engineering artifacts and identify audiences and recurring decisions.", "Design handbook information architecture covering principles/standards, operational guidance, decision records, review aids, ownership/lifecycle metadata and exceptions.", "Write a small set of high-value standards and define scope, rationale, verification and exception path for each mandatory requirement.", "Add or refine at least one exercised runbook/playbook, one decision record and one risk-sensitive review checklist; record evidence of real use.", "Define owners, status/version approach, review triggers, deprecation rules and a discoverable exception record format.", "Run a usability review in which a new engineer must find the applicable standard, evidence expectations, operational guidance and exception path without oral explanation.", "Capture stale, duplicated or bureaucratic guidance, revise it and record follow-up ownership."],
        deliverables: ["Steward engineering handbook structure and navigation", "High-value standards with ownership, verification and exception paths", "Exercised runbook/playbook and evidence", "Decision record and risk-sensitive review checklist", "Standards lifecycle/versioning model", "Exception/waiver record model", "Handbook usability review and improvement record"],
        completionCriteria: ["Another engineer can find authoritative guidance and evidence paths without oral history.", "Mandatory standards are testable, proportionate and owned.", "Operational guidance has been exercised rather than merely written.", "Exceptions are explicit, risk-aware, authorized and time/review bounded.", "The handbook links to authoritative sources instead of duplicating them indiscriminately.", "A usability review produces at least one evidence-backed improvement or justified retain-current-state decision."],
      },
    }],
  },
];
