import type { Lesson } from "./lesson";

const scenario = "Treat Steward as a mature organization-owned technology service with established architecture evidence, ADRs, technical-risk records, control evidence, internal packages, Nexus, cloud/VPS infrastructure, PostgreSQL, delivery pipelines and operational history. Architecture governance must preserve decision quality and lifecycle accountability without becoming a duplicate architecture school or approval bureaucracy.";
const deliverables = ["Architecture-governance artifact", "Evidence and rationale", "Ownership, exception or lifecycle record"];
const criteria = ["The governance mechanism is tied to a real decision or risk.", "Ownership and decision rights are explicit.", "The mechanism is proportionate and avoids unnecessary approval gates."];
function readingPractice(id: string, title: string, body: string, instructions: string[]): Lesson {
  return { id: `architecture-governance-${id}`, title, activities: [
    { id: `architecture-governance-${id}-reading`, title: `${title}: concepts`, estimatedMinutes: 55, content: { type: "reading", body } },
    { id: `architecture-governance-${id}-practice`, title: `${title}: Steward governance exercise`, estimatedMinutes: 55, content: { type: "practical", objective: `Apply ${title} as an architecture-governance capability for Steward.`, scenario, instructions, deliverables, completionCriteria: criteria } },
  ] };
}

export const architectureGovernanceDeepLessons: Lesson[] = [
  readingPractice("principles", "Architecture Principles", `Architecture principles are durable decision guides that express how the organization intends important technology choices to be made. Good principles are few, memorable, linked to business or engineering outcomes, and accompanied by rationale and implications. "Use microservices" is usually a solution preference, not a principle. "Prefer the simplest architecture that satisfies demonstrated quality-attribute needs" is stronger because it guides multiple decisions and can be challenged by evidence. Principles should not override context; they create a default stance and a basis for review.`, ["Review Steward ADRs and earlier architecture lessons for recurring decision themes.", "Draft five architecture principles with statement, rationale and implications.", "Identify one decision each principle would influence and one situation where an exception may be justified.", "Remove any principle that is merely a technology preference disguised as governance."]),
  readingPractice("standards", "Technology Standards", `A technology standard defines an approved default or required constraint for a class of decisions. Standards can reduce fragmentation, support operability, security and supportability, and make expertise reusable. But standards impose opportunity cost and can become stale. A good standard defines scope, rationale, owner, version/status, exceptions and review cadence. Distinguish mandatory controls from preferred defaults. Standardization should be strongest where variance creates real organizational cost: supported runtimes, approved artifact sources, baseline observability, dependency provenance or deployment expectations.`, ["Select four areas in Steward where standardization reduces meaningful risk or support burden.", "For each, define mandatory requirements versus preferred defaults.", "Assign owner, review cadence and exception path.", "Document one area where standardization would currently create more cost than value."]),
  readingPractice("selection", "Technology Selection", `Technology selection is a governed decision process, not a popularity contest. Evaluate a candidate against explicit requirements and constraints: functional fit, operational model, security, reliability, support lifecycle, skills, cost, portability, integration, observability, vendor/dependency risk and reversibility. The default option should often include retaining the current technology. Selection evidence should be proportional to decision consequence; not every library deserves an architecture board.`, ["Choose a realistic Steward technology decision such as adding a cache, broker, SaaS tool or new database capability.", "Define decision drivers and non-negotiable constraints before comparing products or patterns.", "Compare at least three options including retaining the current design where credible.", "Record a decision or rejection with consequences and reconsideration triggers."]),
  readingPractice("reviews", "Architecture Reviews", `An architecture review is structured challenge of significant decisions against drivers, risks, principles and evidence. It is not a ceremony where senior titles approve diagrams. Reviews should be triggered by material consequence: new failure domains, new trust boundaries, irreversible data decisions, major vendor commitments, large cost changes or cross-team coupling. A review can result in approve, approve with conditions, request evidence, defer or reject. The quality of questions matters more than meeting size.`, ["Define risk-based triggers for when a Steward architecture review is required.", "Create a compact review checklist focused on drivers, risks, alternatives, operability and reversibility.", "Run the checklist against one prior Steward architecture decision.", "Identify decisions that should explicitly remain team-local and not require architecture review."]),
  readingPractice("exceptions", "Architecture Exceptions", `An architecture exception is a time-bounded or explicitly reviewed departure from a principle or standard because context justifies it. An exception should state the violated/default expectation, rationale, risks, compensating controls, owner, approval authority, duration and exit or review condition. Exceptions are not failures of governance; hiding deviations is. Repeated exceptions may indicate that the standard is wrong, the implementation ecosystem is weak, or teams need better paved roads.`, ["Choose a plausible Steward exception to an architecture standard.", "Document rationale, affected risks, compensating controls and decision authority.", "Define expiry or review triggers and an exit path.", "Explain what repeated exceptions of this type would tell you about the underlying standard."]),
  readingPractice("lifecycle", "Technology Lifecycle", `Architecture governance continues after adoption. Every significant technology has a lifecycle: evaluate, approve, adopt, maintain, upgrade, deprecate and retire. Lifecycle governance tracks support status, version policy, security maintenance, migration path, data portability, vendor continuity and end-of-life exposure. This applies to runtimes, databases, cloud services, Nexus, internal packages and major frameworks. A technology can still work technically while becoming an unacceptable organizational risk because support or expertise has disappeared.`, ["Create lifecycle states for major Steward technologies and dependencies.", "Identify support/EOL signals and responsible owners.", "Define upgrade, deprecation and retirement expectations.", "Select one technology and produce a lifecycle risk/replacement trigger record."]),
  readingPractice("decision-ownership", "Architecture Decision Ownership", `Decision ownership should sit as close as possible to the relevant knowledge while escalating decisions whose consequences cross boundaries. Separate decision maker, consulted experts, affected owners and governance authority. Centralized architecture teams should not own every decision; teams also should not independently make decisions that impose unbounded cost or risk on others. Clarify thresholds and escalation paths. Durable ADRs allow distributed ownership while preserving organizational memory.`, ["Classify Steward architecture decisions into team-local, cross-service/platform and organization-level categories.", "Assign default decision owners and consultation expectations.", "Define escalation triggers based on blast radius, irreversibility, cost, security and operational impact.", "Check that ownership aligns with accountability established in Engineering Governance."]),
  readingPractice("context", "Standards vs Context-specific Decisions", `A standard exists because repeated consistency has value; a context-specific decision exists because local constraints or evidence justify variation. Mature governance knows the difference. If every decision is standardized, experimentation and fit suffer. If everything is contextual, fragmentation and support burden grow. Use defaults, paved roads and automated checks for common low-variance needs; reserve explicit review for consequential deviations. Measure exception frequency and operational cost to learn whether the balance is right.`, ["List five Steward decisions suited to standards and five that should remain contextual.", "For each standard, identify the organizational cost of variance.", "For each contextual decision, identify why a mandatory standard would be harmful.", "Define one metric or review signal that could reveal over-standardization or excessive fragmentation."]),
  {
    id: "architecture-governance-steward-exception-lab", title: "Lab: Govern a Steward Architecture Exception", activities: [
      { id: "architecture-governance-steward-exception-lab-1", title: "Establish the governing baseline", estimatedMinutes: 120, content: { type: "practical", objective: "Define the principles, standard and decision-right context for a consequential Steward architecture exception.", scenario, instructions: ["Select a credible exception involving data, dependencies, delivery, infrastructure or integration.", "Identify the governing principle/standard, its rationale and the risk it is intended to manage.", "Map affected stakeholders, decision owner and approval/escalation authority.", "Collect architecture, risk, security, reliability and operational evidence relevant to the exception."], deliverables: ["Baseline principle/standard", "Decision-right map", "Evidence pack", "Exception problem statement"], completionCriteria: criteria } },
      { id: "architecture-governance-steward-exception-lab-2", title: "Evaluate the exception", estimatedMinutes: 150, content: { type: "practical", objective: "Determine whether deviation from the default is justified and under what conditions.", scenario, instructions: ["Compare complying with the standard, granting the exception and at least one alternative path.", "Evaluate consequences across security, reliability, delivery, cost, operability, supportability and reversibility.", "Define compensating controls and residual risk if the exception is granted.", "Record the decision with rationale, owner, duration and acceptance/escalation requirements."], deliverables: ["Option analysis", "Exception decision record", "Residual-risk assessment", "Compensating controls"], completionCriteria: criteria } },
      { id: "architecture-governance-steward-exception-lab-3", title: "Operate and learn from the exception", estimatedMinutes: 120, content: { type: "practical", objective: "Make the exception reviewable, temporary where appropriate and useful as governance feedback.", scenario, instructions: ["Define expiry, review cadence and event-driven triggers.", "Define evidence that shows compensating controls are operating.", "Create an exit/remediation plan or explicit long-term acceptance path.", "Explain how repeated similar exceptions would trigger review of the underlying standard or platform capability."], deliverables: ["Review/expiry plan", "Operating-evidence requirements", "Exit or acceptance plan", "Governance feedback note"], completionCriteria: ["The exception is traceable to a real default and its rationale.", "The decision is evidence-based and explicit about residual risk.", "Ownership, authority and review conditions are clear.", "The process does not turn a one-off decision into unnecessary permanent bureaucracy."] } },
    ]
  },
];
