import type { LearningResource, LessonBlock } from "../activities/content";
import type { Lesson } from "./lesson";

const isoGovernance: LearningResource = { title: "ISO/IEC 38500 — Governance of IT overview", url: "https://www.iso.org/standard/62816.html", kind: "reference" };
const cobit: LearningResource = { title: "ISACA — COBIT", url: "https://www.isaca.org/resources/cobit", kind: "reference" };
const techRadar: LearningResource = { title: "Thoughtworks Technology Radar", url: "https://www.thoughtworks.com/radar", kind: "reference" };
const teamTopologies: LearningResource = { title: "Team Topologies — Key Concepts", url: "https://teamtopologies.com/key-concepts", kind: "reference" };

type Spec={id:string;title:string;body:string;practice:string[];resources:LearningResource[]};
function make(s:Spec):Lesson {
  const blocks:LessonBlock[]=[
    {type:"paragraph",text:s.body},
    {type:"callout",tone:"steward",title:"Strategy is a coherent set of choices",body:"A technology strategy is not a wishlist, tool catalogue or multi-year prediction. It connects organizational outcomes to a small set of technology choices, capability investments, deliberate non-investments, sequencing and evidence that would cause the strategy to change."},
    {type:"resources",title:"Continue learning",resources:s.resources},
  ];
  return {id:`technical-strategy-${s.id}`,title:s.title,activities:[
    {id:`technical-strategy-${s.id}-reading`,title:s.title,estimatedMinutes:55,content:{type:"reading",body:s.body,blocks}},
    {id:`technical-strategy-${s.id}-practice`,title:`Practice: ${s.title}`,estimatedMinutes:75,content:{type:"practical",objective:`Apply ${s.title} to Steward's next planning horizon.`,scenario:"Use the accumulated Steward evidence and current organizational assumptions. Make explicit choices about what to strengthen, simplify, defer or stop. Do not invent growth or transformation merely to justify investment.",instructions:s.practice,deliverables:["Strategy/capability decision artifact","Evidence and trade-offs","Owner, horizon and review trigger"],completionCriteria:["Choices trace to organizational outcomes and evidence.","At least one credible non-investment or stop/defer choice is explicit.","Capability and operating consequences are considered, not only technology acquisition."]}},
  ]};
}
const specs:Spec[]=[
{id:"outcomes-horizons",title:"Technology Strategy: Outcomes and Horizons",body:"Technology strategy translates organizational direction into a coherent set of technical choices over a useful horizon. Start from outcomes, constraints and material risks, then identify which technology capabilities matter. Separate committed near-term decisions from directional medium-term bets and conditional longer-term options. Avoid roadmaps that imply certainty where evidence does not exist.",practice:["Define Steward's supplied organizational outcomes and planning horizon.","Identify technology capabilities that materially enable or constrain those outcomes.","Separate committed, directional and conditional choices.","State assumptions and review triggers for each horizon."],resources:[isoGovernance,cobit]},
{id:"strategic-choices",title:"Strategic Choices and Non-choices",body:"Strategy requires choosing what not to do. A list containing cloud migration, microservices, AI, zero trust, observability, developer platform work and modernization is not a strategy unless priorities and exclusions are explicit. Technical Stewardship uses evidence to concentrate scarce attention and accepts that some technically attractive work should be deferred or rejected.",practice:["Build a candidate initiative set from real Steward risks, debt, architecture and service evidence.","Select a small coherent set of priorities.","Explicitly defer, stop or reject at least two credible initiatives.","Explain the opportunity cost and trade-offs."],resources:[cobit,techRadar]},
{id:"capability-map",title:"Technology Capability Mapping",body:"A capability describes an ability the organization needs, not a product it owns. Examples include reliable software delivery, identity lifecycle management, recoverable data, internal artifact distribution, observability and architecture decision-making. Mapping capabilities prevents strategy from becoming vendor-shaped and exposes dependencies among people, process, information and technology.",practice:["Create a Steward technology-capability map.","For each material capability, assess current evidence, ownership and dependency.","Separate capability gaps from product-feature gaps.","Identify capabilities whose weakness blocks multiple outcomes."],resources:[cobit,teamTopologies]},
{id:"investment-prioritization",title:"Technology Investment and Prioritization",body:"Technology investment includes engineering time, operational burden, training, migration risk, licenses/infrastructure and opportunity cost. Prioritization should compare expected value, risk reduction, urgency, reversibility, dependency and evidence confidence without pretending uncertain benefits can be reduced to a perfectly precise score.",practice:["Compare at least five candidate Steward investments or remediation initiatives.","Estimate benefit/risk reduction, cost, dependency and confidence qualitatively or with transparent ranges.","Identify sequencing constraints.","Recommend a portfolio for the current horizon and defend excluded work."],resources:[cobit,isoGovernance]},
{id:"capability-building",title:"Build, Buy, Learn and Retire Capabilities",body:"A gap can be addressed by building software, adopting a service/product, developing people/process capability, simplifying the need or retiring the dependent technology. Sustainable stewardship asks whether the organization can operate and evolve the chosen solution, not only whether it can procure or implement it.",practice:["Select two capability gaps.","Compare build, buy/adopt, learn/process and simplify/retire options.","Include skills, support, exit, security, reliability and lifecycle consequences.","Choose the smallest sustainable response."],resources:[teamTopologies,techRadar]},
{id:"roadmaps-options",title:"Roadmaps, Options and Reconsideration",body:"A technical roadmap should communicate sequence, dependency and decision points without pretending the future is fixed. Commitment should decrease as uncertainty and distance increase: near-term work may have concrete sequencing and ownership, medium-term items should be conditional on evidence, and longer-term items are options rather than promised delivery dates. Record the assumptions that keep an option alive, the evidence gate that permits commitment, and the review or expiry point at which an unsupported option is dropped. Preserve options when uncertainty is high; commit when delay is more costly than uncertainty.",practice:["Create a 12–24 month illustrative Steward technology roadmap from supplied assumptions.","Separate near-term committed work, medium-term conditional decisions and longer-term options/experiments; do not assign false-precision delivery dates to conditional work.","For each conditional item, state the assumption keeping it relevant, evidence needed to commit, decision owner and review/expiry point.","Add dependency and reconsideration triggers, including conditions that stop work rather than only conditions that start it.","Show at least one initiative that disappears if a simplifying assumption holds."],resources:[techRadar,isoGovernance]},
];
export const technicalStrategyCapabilityDeepLessons:Lesson[]=specs.map(make);
