import type { LearningResource } from "../activities/content";
import type { Lesson } from "./lesson";
const fowlerDebt={title:"Martin Fowler — Technical Debt",url:"https://martinfowler.com/bliki/TechnicalDebt.html",kind:"reference"} satisfies LearningResource;
const dora={title:"DORA — Research Program",url:"https://dora.dev/research/",kind:"reference"} satisfies LearningResource;
const sreToil={title:"Google SRE — Eliminating Toil",url:"https://sre.google/sre-book/eliminating-toil/",kind:"reference"} satisfies LearningResource;
const resourcesByHealth:Record<string,LearningResource[]>={
 "technical-debt-health-identifying-technical-debt":[fowlerDebt],"technical-debt-health-measuring-and-communicating-debt":[fowlerDebt,dora],
 "technical-debt-health-prioritization":[fowlerDebt,sreToil],"technical-debt-health-engineering-health-metrics":[dora,sreToil],
 "technical-debt-health-kpi-vs-kri":[dora],"technical-debt-health-sustainable-remediation":[sreToil,fowlerDebt],
 "technical-debt-health-debt-ownership-and-review-cadence":[fowlerDebt],"technical-debt-health-balancing-feature-delivery-and-engineering-health":[dora,sreToil],
};

function reading(id: string, title: string, body: string): Lesson {
  return { id, title, activities: [
    { id: `${id}-001`, title, estimatedMinutes: 35, content: { type: "reading", body, blocks:[{type:"resources",title:"Engineering health reference",resources:resourcesByHealth[id] ?? [fowlerDebt]}] } },
    { id: `${id}-practice`, title: `Practice: ${title}`, estimatedMinutes: 45, content: {
      type: "practical",
      objective: `Apply ${title} to current Steward engineering-health evidence.`,
      scenario,
      instructions: [
        "Select one concrete Steward example supported by an existing artifact, metric, incident, dependency record, exception or delivery observation.",
        "Apply the lesson concept and separate observed evidence from interpretation or assumption.",
        "Make one explicit decision: remediate, contain, schedule, tolerate/monitor, reject the proposed debt label, or escalate where authority is insufficient.",
        "Record the owner, decision consequence and evidence/review trigger that would cause the decision to change."
      ],
      deliverables: ["Focused engineering-health analysis", "Evidence reference", "Decision and rationale", "Owner and reconsideration trigger"],
      completionCriteria: [
        "The example is grounded in current Steward evidence rather than a hypothetical dislike of code.",
        "Debt, defect, risk, maintenance and feature work are not conflated.",
        "The decision has an engineering or organizational consequence rather than ending at classification.",
        "Uncertainty and reconsideration evidence are explicit."
      ]
    } }
  ] };
}

const scenario = "Steward is a mature organization-owned service spanning the final Architect actual application/data estate plus the platform, delivery, security, observability and operational capabilities actually retained. Nexus and `steward-common` are active debt targets only when they remain in that estate and the package extraction gate was earned. Components simplified or retired by Architect remain historical decision evidence rather than active debt targets. `tsa-test-core` does not exist yet; its deferred extraction is not technical debt unless later evidence establishes a real unmet need. Engineering-health decisions must connect debt to delivery, reliability, security, cost or maintainability outcomes rather than treating every imperfection or deferred idea as debt.";

export const technicalDebtHealthDeepLessons: Lesson[] = [
  reading("technical-debt-health-identifying-technical-debt", "Identifying Technical Debt", `${scenario}\n\nTechnical debt is a deliberate or accumulated compromise that creates future cost, risk or constraint. Distinguish debt from defects, feature gaps, ordinary maintenance and architectural preferences. Useful debt records identify the compromise, why it exists, affected assets or teams, current consequence, expected future cost and evidence. Steward examples include unsupported dependencies, duplicated deployment logic, brittle tests, manual release steps, aging PostgreSQL assumptions, weak package boundaries and repeated architecture exceptions.`),
  reading("technical-debt-health-measuring-and-communicating-debt", "Measuring and Communicating Debt", `${scenario}\n\nDebt should be communicated through consequences, not dramatic labels. Use evidence such as change-failure patterns, lead-time drag, flaky-test rates, recurring incidents, dependency age, exception frequency, manual toil, security exposure or developer effort. Avoid pretending that one score precisely measures debt. Combine quantitative indicators with qualitative context, confidence and trend. Translate engineering effects into stakeholder language: slower change, higher outage exposure, harder onboarding, increased cost or reduced ability to meet commitments.`),
  reading("technical-debt-health-prioritization", "Prioritization", `${scenario}\n\nPrioritize debt by expected harm and opportunity cost, not by who complains loudest. Consider risk reduction, frequency of friction, blast radius, strategic dependency, remediation effort, reversibility and whether upcoming work will amplify the problem. Treat "do nothing for now" as a legitimate option when evidence supports it. High-impact debt may deserve immediate remediation; lower-impact debt can be scheduled, tolerated or addressed opportunistically.`),
  reading("technical-debt-health-engineering-health-metrics", "Engineering Health Metrics", `${scenario}\n\nEngineering-health metrics should answer decision questions. Useful measures can include deployment frequency, lead time, change-failure rate, recovery time, flaky-test rate, build duration, dependency freshness, vulnerability aging, restore-test success, toil, review latency and exception volume. Metrics need definitions, owners, data sources and interpretation rules. Once a metric becomes a target, people can optimize the number instead of the underlying outcome: deployment frequency can rise through trivial releases, review latency can fall through shallow review, and vulnerability counts can fall by changing classification or scope. Pair important indicators with counter-metrics and qualitative evidence, watch for denominator/scope changes, and periodically ask whether behavior changed in a way that invalidates the metric. Do not create dashboards that reward gaming or confuse activity with health.`),
  reading("technical-debt-health-kpi-vs-kri", "KPI vs KRI", `${scenario}\n\nA KPI shows progress or performance toward an objective; a KRI signals increasing exposure to risk or proximity to a boundary. The same raw data can serve different purposes depending on the question. Deployment lead time may be a KPI for flow, while growth in unsupported critical dependencies can be a KRI for lifecycle exposure. Define what decision each indicator supports, threshold or target, owner, review cadence and response.`),
  reading("technical-debt-health-sustainable-remediation", "Sustainable Remediation", `${scenario}\n\nRemediation should improve the system without creating a perpetual cleanup programme. Prefer changes that remove recurring causes: paved roads, shared packages, automation, clearer ownership, stronger boundaries, migration plans or better defaults. Validate that remediation actually changes the measured consequence. Large rewrites require especially strong evidence because they can replace known debt with new uncertainty.`),
  reading("technical-debt-health-debt-ownership-and-review-cadence", "Debt Ownership and Review Cadence", `${scenario}\n\nDebt needs an accountable owner who can monitor consequences and drive a decision, but ownership does not imply personally implementing every fix. Record owner, rationale, evidence, treatment, due or review date and escalation trigger. Review cadence should match materiality: critical lifecycle or security debt may need frequent review, while low-impact maintainability debt can be revisited less often. Stale debt records should be closed, reframed or revalidated.`),
  reading("technical-debt-health-balancing-feature-delivery-and-engineering-health", "Balancing Feature Delivery and Engineering Health", `${scenario}\n\nFeature delivery and engineering health are not opposing moral choices. Both consume finite capacity and serve organizational outcomes. Make trade-offs explicit: what feature value is gained, what engineering-health cost is accepted, how long it is tolerable, and what signal forces reconsideration. Reserve capacity where evidence shows recurring health work is necessary, but avoid fixed percentages treated as universal law.`),
  { id: "technical-debt-health-lab-build-the-steward-engineering-health-review", title: "Lab: Build the Steward Engineering Health Review", activities: [{ id: "technical-debt-health-lab-build-the-steward-engineering-health-review-001", title: "Lab: Build the Steward Engineering Health Review", estimatedMinutes: 240, content: { type: "practical", objective: "Build and defend a recurring engineering-health review for Steward that converts evidence about debt, flow, reliability, security, dependencies and toil into prioritized decisions.", scenario, instructions: ["Create a debt inventory from existing Steward evidence and distinguish debt from defects, risks, feature gaps and routine maintenance.", "Select a small set of engineering-health KPIs and KRIs, defining source, meaning, owner, cadence and action thresholds; for each important target, identify a plausible gaming behavior and a counter-metric or review that would expose it." "Prioritize debt using consequence, likelihood, strategic impact, remediation cost and timing rather than a cosmetic score alone.", "Choose treatment for the highest-value items: remediate, contain, schedule, accept temporarily or monitor.", "Define ownership, review cadence, expiry or escalation triggers, and connect material debt to the technology-risk register where appropriate.", "Run a mock engineering-health review and record at least one explicit trade-off between feature delivery and remediation."], deliverables: ["Steward technical-debt register", "Engineering-health KPI/KRI scorecard", "Prioritized remediation and acceptance plan", "Ownership and review-cadence model", "Engineering-health review decision record"], completionCriteria: ["Debt records explain future cost or risk and are not merely lists of disliked code.", "Metrics are tied to decisions and cannot be confused with activity vanity metrics.", "Priorities and treatment choices are evidence-based and proportionate.", "Ownership and review triggers are explicit.", "The review demonstrates a defensible balance between delivery value and engineering sustainability."] } }] }
];
