import type { Lesson } from "./lesson";

const scenario = "Treat Steward as a mature organization-owned technology service that depends on cloud/VPS infrastructure, PostgreSQL, CI/CD tooling, Nexus, third-party libraries and the internal packages steward-common and tsa-test-core. Governance must make ownership, provenance, support boundaries, lifecycle state, continuity and exceptions explicit without blocking ordinary engineering work.";
const criteria = ["The decision is tied to a real dependency, service objective or technology risk.", "Ownership, lifecycle state, evidence and review triggers are explicit.", "Controls are proportionate and avoid unnecessary approval bureaucracy."];
function lesson(id: string, title: string, body: string, instructions: string[]): Lesson { return { id: `third-party-lifecycle-risk-${id}`, title, activities: [
  { id: `third-party-lifecycle-risk-${id}-reading`, title: `${title}: concepts`, estimatedMinutes: 60, content: { type: "reading", body } },
  { id: `third-party-lifecycle-risk-${id}-practice`, title: `${title}: Steward exercise`, estimatedMinutes: 60, content: { type: "practical", objective: `Apply ${title} to Steward's dependency ecosystem.`, scenario, instructions, deliverables: ["Lifecycle/risk decision artifact", "Evidence and rationale", "Ownership or exception record"], completionCriteria: criteria } },
] }; }

export const thirdPartyLifecycleRiskDeepLessons: Lesson[] = [
  lesson("vendor-assessment", "Vendor Assessment", `Vendor assessment asks whether an external provider can support the service outcome and risk posture Steward requires. Evaluate criticality, security and privacy expectations, operational resilience, support model, service levels, financial/organizational dependency, subcontractors where relevant, evidence quality and exit feasibility. Do not treat a questionnaire as proof. Assessment depth should follow criticality: a low-impact developer utility does not need the same review as a provider hosting production data.`, ["Select one critical and one non-critical Steward vendor/provider relationship.", "Define assessment criteria proportional to each dependency's impact.", "Identify evidence that would support or weaken confidence.", "Record decision, owner, unresolved risks and review trigger."]),
  lesson("dependency-risk", "Dependency Risk", `A dependency can fail technically, become vulnerable, change licensing, be abandoned, introduce incompatible releases or create concentration risk. Dependency risk therefore includes more than CVEs. Assess criticality, replaceability, maintenance health, version exposure, transitive dependencies, provenance and blast radius. Reuse SBOM, scanning and architecture evidence from earlier schools, but make a governance decision about what exposure the organization will retain.`, ["Map critical external and internal dependencies used by Steward.", "Assess failure, security, lifecycle and concentration scenarios.", "Identify high-risk transitive or hard-to-replace dependencies.", "Define ownership and monitoring for the most material exposures."]),
  lesson("saas-cloud", "SaaS and Cloud Risk", `SaaS and cloud services shift responsibility; they do not remove it. Governance should identify the shared-responsibility boundary, data/control-plane exposure, availability dependency, identity and access model, portability, contractual/service assumptions, region or residency constraints where applicable, backup/export capabilities and provider concentration. Avoid both extremes: blindly trusting the provider or rebuilding every managed capability yourself.`, ["Create a shared-responsibility map for Steward's cloud/VPS and one SaaS dependency.", "Identify assumptions the organization currently makes about availability, backup, access and portability.", "Define evidence and controls owned by Steward versus the provider.", "Document one concentration or exit risk and its treatment."]),
  lesson("end-of-life", "End-of-life Technology", `Technology becomes lifecycle risk when support, security fixes, compatibility or organizational expertise are no longer dependable. Track runtime versions, operating systems, databases, frameworks, CI tooling, Nexus and significant libraries against support windows and internal capability. End-of-life is not only a calendar date: abandoned projects and unsupported internal packages can create the same exposure. Define states such as strategic, supported, tolerated, deprecated and prohibited, with owners and transition expectations.`, ["Classify major Steward technologies by lifecycle state.", "Identify one approaching or hypothetical end-of-support scenario.", "Define migration lead time, owner, evidence and escalation threshold.", "Explain when temporary tolerance is reasonable and when use should be prohibited."]),
  lesson("exit-continuity", "Exit and Continuity Planning", `A technology decision is incomplete if the service cannot recover from vendor failure, pricing change, acquisition, product retirement or unacceptable degradation. Exit planning does not require maintaining a live replacement for every dependency; it requires knowing what must be portable, what data/configuration must be exportable, realistic replacement lead time, contractual or technical lock-in, and what continuity options exist. Plans should match dependency criticality.`, ["Choose one high-criticality provider or platform dependency.", "Define plausible exit triggers and maximum tolerable transition constraints.", "Inventory data, configuration, artifacts and knowledge needed to leave.", "Create a proportional continuity/exit plan and identify expensive assumptions."]),
  lesson("internal-product-ownership", "Internal Software Product Ownership", `Internal packages are products when multiple systems or teams depend on their behavior. steward-common and tsa-test-core therefore need accountable ownership, purpose, compatibility promises, roadmap/lifecycle decisions, support expectations and consumer communication. Shared code without ownership becomes hidden infrastructure. The owner is accountable for the product boundary and lifecycle, not for manually approving every consumer change.`, ["Define product purpose and accountable owner for steward-common and tsa-test-core.", "Identify consumers and the consequences of breaking changes.", "Define support responsibilities, contribution expectations and escalation paths.", "Separate package-product ownership from Nexus platform ownership."]),
  lesson("approved-sources", "Approved Dependency Sources", `Approved sources reduce supply-chain ambiguity by defining where dependencies and internal artifacts may be obtained. For Steward, Nexus is the controlled package/artifact repository and may proxy or host approved sources; it is not runtime messaging infrastructure. Governance should define source trust, repository configuration, namespace expectations, integrity/provenance evidence and what happens when a required package is unavailable. Prefer automated repository configuration and CI enforcement over manual approval of every install.`, ["Define approved sources for external packages and internal artifacts.", "Describe Nexus's role as repository/proxy and its trust boundary.", "Design an automated guardrail that rejects unapproved sources where practical.", "Define the exception path for a legitimate dependency not available through the approved source."]),
  lesson("version-support", "Internal Package Version and Support Policy", `Internal consumers need to know what versions are safe to adopt and how long they will be supported. Define semantic-versioning expectations where appropriate, compatibility rules, deprecation notice, supported release lines, security-fix policy and breaking-change communication. Avoid promising enterprise-scale support that a small team cannot sustain. A policy should make consumer risk predictable while preserving the ability to evolve the package.`, ["Create a realistic version/support policy for steward-common and tsa-test-core.", "Define what constitutes a breaking change and how it is communicated.", "Choose a sustainable supported-version model.", "Define emergency security-fix and deprecation behavior."]),
  lesson("repository-retention", "Repository Retention and Lifecycle", `Artifact repositories accumulate versions, snapshots, containers and metadata indefinitely unless lifecycle rules exist. Retention should preserve reproducibility, rollback, audit evidence and supported releases while controlling storage and reducing stale exposure. Never delete artifacts solely because they are old if they are required to reproduce supported production builds. Define immutable release expectations, snapshot/temporary retention, deprecation and archival rules, plus ownership for Nexus capacity and integrity.`, ["Define retention classes for release artifacts, snapshots and deprecated package versions.", "Protect artifacts required for production reproducibility and rollback.", "Assign Nexus lifecycle/capacity ownership.", "Define archival/deletion evidence and exceptions."]),
  lesson("dependency-exceptions", "Dependency Exceptions", `Exceptions allow justified use outside an approved dependency rule without silently weakening governance. Record the dependency, unmet standard, business/technical rationale, risk, compensating controls, owner, approver, scope, expiry/review trigger and exit plan. A recurring exception is feedback: the approved catalog, platform capability or standard may need revision.`, ["Draft a dependency exception for a plausible Steward requirement.", "Define compensating controls and residual risk.", "Assign approval authority and expiry/review triggers.", "Explain what repeated exceptions would cause you to change in the standard or platform."]),
  lesson("provenance", "Supply-chain Ownership and Provenance Requirements", `Supply-chain governance needs traceability from source to built artifact and accountable ownership for each stage. Useful evidence includes source repository, reviewed commit, CI run, dependency lockfile, build identity, checksum/signature or attestation where available, SBOM, artifact repository coordinates and promotion history. Provenance should answer: where did this artifact come from, who/what built it, from which inputs, and is this the artifact we intended to deploy? Apply stronger requirements to higher-impact artifacts.`, ["Trace one Steward release and one internal package from source to artifact.", "Identify existing provenance evidence and material gaps.", "Define minimum provenance requirements by artifact criticality.", "Assign ownership across source, CI, Nexus and deployment/promotion stages."]),
  { id: "third-party-lifecycle-risk-package-governance-lab", title: "Lab: Govern steward-common and tsa-test-core", activities: [
    { id: "third-party-lifecycle-risk-package-governance-lab-1", title: "Establish dependency and product governance", estimatedMinutes: 150, content: { type: "practical", objective: "Define accountable lifecycle governance for Steward's internal package ecosystem.", scenario, instructions: ["Inventory steward-common and tsa-test-core consumers, owners, criticality and dependency chains.", "Define purpose, support/version rules, compatibility expectations and contribution boundaries.", "Define approved package sources and Nexus responsibilities without confusing repository infrastructure with runtime services.", "Map material dependency and lifecycle risks into the existing technology-risk register."], deliverables: ["Internal-package ownership model", "Version/support policy", "Approved-source model", "Risk updates"], completionCriteria: criteria } },
    { id: "third-party-lifecycle-risk-package-governance-lab-2", title: "Govern provenance, retention and exceptions", estimatedMinutes: 150, content: { type: "practical", objective: "Make internal artifacts reproducible, traceable and governable through their lifecycle.", scenario, instructions: ["Define source-to-Nexus provenance evidence for package releases.", "Create release/snapshot/deprecation retention rules that preserve reproducibility.", "Design the dependency-exception record with compensating controls and expiry.", "Run one mock breaking-change or unapproved-dependency decision and record the outcome."], deliverables: ["Provenance requirements", "Repository retention/lifecycle policy", "Dependency exception template", "Mock governance decision"], completionCriteria: criteria } },
    { id: "third-party-lifecycle-risk-package-governance-lab-3", title: "Review continuity and ecosystem health", estimatedMinutes: 120, content: { type: "practical", objective: "Demonstrate that Steward can sustain or exit material technology dependencies deliberately.", scenario, instructions: ["Assess one vendor/cloud/SaaS dependency for continuity and exit risk.", "Assess lifecycle state for Nexus, core runtimes and significant package dependencies.", "Define event-driven and periodic review triggers.", "Present a prioritized improvement plan that distinguishes mandatory risk treatment from optional maturity improvements."], deliverables: ["Exit/continuity assessment", "Technology lifecycle register", "Review cadence", "Prioritized improvement plan"], completionCriteria: ["Internal packages are governed as products with clear owners and support boundaries.", "Nexus, sources, provenance and retention rules support reproducibility and supply-chain assurance.", "Exceptions preserve accountability without blocking justified engineering choices.", "Lifecycle and exit decisions are evidence-based and proportionate to criticality."] } },
  ] },
];
