import { engineeringFoundations } from "./engineering-foundations";
import type { LearningJourney } from "./learning-journey";
import { plannedPath } from "./planned-path";

const module = plannedPath;

export const technicalStewardshipJourney: LearningJourney = {
    id: "technical-stewardship-journey",
    title: "Technical Stewardship Journey",
    schools: [
        {
            id: "engineering-apprentice",
            title: "Engineering Apprentice",
            paths: [engineeringFoundations],
        },
        {
            id: "builder",
            title: "Builder",
            paths: [
                module("programming-with-python", "Programming with Python"),
                module("web-and-api-foundations", "Web and API Foundations"),
                module("django-and-api-engineering", "Django and API Engineering"),
                module("relational-data-and-postgresql", "Relational Data and PostgreSQL"),
                module("identity-authentication-authorization", "Identity, Authentication and Authorization"),
                module("software-craft", "Software Craft"),
            ],
        },
        {
            id: "system-thinker",
            title: "System Thinker",
            paths: [
                module("requirements-and-problem-framing", "Requirements and Problem Framing"),
                module("system-boundaries-and-context", "System Boundaries and Context"),
                module("modeling-software-systems", "Modeling Software Systems"),
                module("components-and-dependencies", "Components and Dependencies"),
                module("data-flow-and-integration", "Data Flow and Integration"),
                module("failure-modes", "Failure Modes"),
                module("architecture-decisions", "Architecture Decisions and Trade-offs"),
            ],
        },
        {
            id: "platform-builder",
            title: "Platform Builder",
            paths: [
                module("computer-and-os-foundations", "Computer and Operating-System Foundations"),
                module("linux-administration", "Linux Administration"),
                module("networking-foundations", "Networking Foundations"),
                module("virtualization", "Virtualization"),
                module("budget-homelab", "Building the Budget Homelab"),
            ],
        },
        {
            id: "delivery-engineer",
            title: "Delivery Engineer",
            paths: [
                module("software-delivery-foundations", "Software Delivery Foundations"),
                module("automation-and-shell", "Automation and Shell"),
                module("containers-and-docker", "Containers and Docker"),
                module("continuous-integration", "Continuous Integration"),
                module("continuous-delivery-deployment", "Continuous Delivery and Deployment"),
                module("configuration-management", "Configuration Management"),
                module("artifact-and-supply-chain", "Artifact and Supply-Chain Foundations"),
                module("release-engineering", "Release Engineering"),
            ],
        },
        {
            id: "cloud-engineer",
            title: "Cloud Engineer",
            paths: [
                module("cloud-and-hosting-models", "Cloud and Hosting Models"),
                module("vps-operations", "VPS Operations"),
                module("internet-networking", "Internet Networking"),
                module("cloud-building-blocks", "Cloud Building Blocks"),
                module("infrastructure-as-code", "Infrastructure as Code"),
                module("cloud-architecture-and-cost", "Cloud Architecture and Cost"),
            ],
        },
        {
            id: "quality-steward",
            title: "Quality Steward",
            paths: [
                module("quality-engineering", "Quality Engineering"),
                module("test-analysis-and-design", "Test Analysis and Design"),
                module("unit-and-component-testing", "Unit and Component Testing"),
                module("api-and-integration-testing", "API and Integration Testing"),
                module("automation-framework-engineering", "Automation Framework Engineering"),
                module("browser-and-environment-testing", "Browser and Environment Testing"),
                module("non-functional-quality", "Non-functional Quality"),
                module("quality-in-ci-cd", "Quality in Containers and CI/CD"),
            ],
        },
        {
            id: "security-steward",
            title: "Security Steward",
            paths: [
                module("security-foundations", "Security Foundations"),
                module("threat-modeling", "Threat Modeling"),
                module("web-and-api-threats", "Web and API Threats"),
                module("vulnerability-laboratory", "Practical Vulnerability Laboratory"),
                module("linux-and-network-security", "Linux and Network Security"),
                module("container-and-delivery-security", "Container and Delivery Security"),
                module("application-security-engineering", "Application Security Engineering"),
            ],
        },
        {
            id: "reliability-engineer",
            title: "Reliability Engineer",
            paths: [
                module("reliability-and-sre-foundations", "Reliability and SRE Foundations"),
                module("observability", "Observability"),
                module("logging", "Logging"),
                module("metrics-prometheus-grafana", "Metrics, Prometheus and Grafana"),
                module("service-level-engineering", "Service Level Engineering"),
                module("alerting-and-on-call", "Alerting and On-call Thinking"),
                module("performance-and-capacity", "Performance and Capacity"),
                module("resilience-and-distributed-failure", "Resilience and Distributed Failure"),
                module("data-protection-and-disaster-recovery", "Data Protection and Disaster Recovery"),
                module("incident-management", "Incident Management"),
                module("fault-injection", "Fault Injection and Reliability Experiments"),
            ],
        },
        {
            id: "architect",
            title: "Architect",
            paths: [
                module("architecture-fundamentals", "Architecture Fundamentals"),
                module("modularity", "Modularity"),
                module("architectural-styles", "Architectural Styles"),
                module("domain-modeling", "Domain Modeling"),
                module("data-architecture", "Data Architecture"),
                module("integration-and-messaging", "Integration and Messaging"),
                module("scalability-and-distributed-systems", "Scalability and Distributed Systems"),
                module("resilience-architecture", "Resilience Architecture"),
                module("architecture-evaluation-governance", "Architecture Evaluation and Governance"),
            ],
        },
        {
            id: "technical-steward",
            title: "Technical Steward",
            paths: [
                module("technical-leadership", "Technical Leadership"),
                module("engineering-governance", "Engineering Governance"),
                module("it-technology-governance", "IT and Technology Governance"),
                module("technology-risk", "Technology Risk"),
                module("controls-compliance-assurance", "Controls, Compliance and Assurance"),
                module("architecture-governance", "Architecture Governance"),
                module("security-and-data-governance", "Security and Data Governance"),
                module("change-and-service-governance", "Change and Service Governance"),
                module("third-party-lifecycle-risk", "Third-party and Technology Lifecycle Risk"),
                module("technical-debt-engineering-health", "Technical Debt and Engineering Health"),
                module("engineering-handbook-standards", "Engineering Handbook and Standards"),
            ],
        },
        {
            id: "professional-engineer",
            title: "Professional Engineer",
            paths: [
                module("problem-discovery", "Problem Discovery"),
                module("engineering-proposal", "Engineering Proposal"),
                module("independent-build", "Independent Build"),
                module("production-readiness", "Production Readiness"),
                module("engineering-defence", "Engineering Defence"),
            ],
        },
    ],
};
