import type { Lesson } from "./lesson";

const scenario = "Treat Steward as a mature organization-owned service with production users, releases, incidents, service dependencies, PostgreSQL, cloud/VPS infrastructure, Nexus, internal packages, CI/CD, security controls and reliability evidence. Governance should make risky change accountable without slowing low-risk engineering work unnecessarily.";
const deliverables = ["Governance artifact", "Evidence and rationale", "Owner, approval or follow-up record"];
const completion = ["The governance mechanism is proportionate to change/service risk.", "Ownership and decision authority are explicit.", "Approval depends on evidence, not ceremony alone."];
function moduleLesson(id: string, title: string, body: string, instructions: string[]): Lesson {
  return { id: `change-service-governance-${id}`, title, activities: [
    { id: `change-service-governance-${id}-reading`, title: `${title}: concepts`, estimatedMinutes: 55, content: { type: "reading", body } },
    { id: `change-service-governance-${id}-practice`, title: `${title}: Steward exercise`, estimatedMinutes: 60, content: { type: "practical", objective: `Apply ${title} to Steward.`, scenario, instructions, deliverables, completionCriteria: completion } },
  ]};
}

export const changeServiceGovernanceDeepLessons: Lesson[] = [
  moduleLesson("change-risk", "Change Risk", `Change risk is the possibility that a modification causes unacceptable service, security, data, compliance or operational consequences. Risk depends on blast radius, reversibility, novelty, dependency impact, timing, data migration, privilege changes, observability and recovery readiness—not merely ticket size. Use prior incident and deployment evidence to classify changes.`, ["Define a simple Steward change-risk model.", "Classify five representative changes and justify each rating.", "Identify evidence that would lower or raise the rating.", "Define which risk levels require additional review or approval."]),
  moduleLesson("change-controls", "Change Controls", `Change controls are safeguards around planning, authorization, testing, segregation where needed, deployment, rollback and evidence. Good controls are risk-based and automate repeatable checks. A pull request, test suite or deployment gate can be a control when its objective and operating evidence are clear. Avoid universal manual approval queues that add latency without reducing meaningful risk.`, ["Map current Steward delivery controls to explicit control objectives.", "Separate automated from manual controls.", "Identify one redundant control and one missing high-value control.", "Propose a lower-friction control design where possible."]),
  moduleLesson("release-governance", "Release Governance", `Release governance defines when a version is fit to enter an environment and who can make that decision. It should connect scope, test evidence, security findings, operational impact, known risks, rollback strategy and ownership. Release approval is not the same as executing deployment. Standard low-risk releases may use pre-approved automated paths; material releases may need explicit accountable approval.`, ["Define release evidence required for low, medium and high-risk Steward changes.", "Separate deployment authority from release-risk acceptance.", "Design an approval path that allows standard changes to flow quickly.", "Define conditions that block or defer release."]),
  moduleLesson("service-ownership", "Service Ownership", `A production service needs accountable ownership across its lifecycle. Service ownership includes purpose, stakeholders, technical boundaries, SLOs, support/escalation, data and security responsibilities, dependency ownership, lifecycle status and improvement priorities. It does not mean one person performs every operational task. Ownership gaps become governance and reliability risks.`, ["Create a Steward service ownership record.", "Map application, data, infrastructure, Nexus and internal-package responsibilities.", "Identify ownership gaps or overlaps.", "Define escalation and review cadence."]),
  moduleLesson("incident-problem-change", "Incident, Problem and Change", `Incident management restores service; problem management investigates recurring or systemic causes; change management governs modifications intended to fix or evolve the service. These practices should share evidence instead of becoming disconnected ticket systems. Incidents can trigger problem analysis, risks, controls or architecture changes; changes can close findings only when evidence demonstrates the intended outcome.`, ["Trace one credible Steward incident from detection to restoration, problem analysis and change.", "Identify which records should be linked.", "Define when a recurring incident becomes a problem-management concern.", "Show how closure evidence returns to the risk/control model."]),
  moduleLesson("operational-readiness", "Operational Readiness", `Operational readiness asks whether the organization can safely operate a change, not merely whether the code works. Relevant evidence includes monitoring, logs, alerting, runbooks, capacity, backup/recovery impact, support ownership, dependency behavior, security changes and rollback/recovery procedures. Readiness criteria should scale with risk and reuse Reliability Engineer evidence.`, ["Create an operational-readiness checklist for a significant Steward release.", "Remove checks that do not apply and explain why.", "Link each retained check to a risk or service objective.", "Identify owners and evidence sources for each readiness item."]),
  moduleLesson("emergency-change", "Emergency Change", `Emergency change exists for situations where normal lead time creates greater risk than accelerated execution. It is not a shortcut for poor planning. Emergency paths should preserve minimum safety controls, explicit authority, traceability, rollback thinking and retrospective review. The post-change review should determine whether follow-up remediation, problem analysis or governance improvement is required.`, ["Define criteria for declaring a Steward emergency change.", "Specify minimum controls that cannot be skipped.", "Define emergency authority and communication.", "Design the mandatory post-change review and evidence record."]),
  moduleLesson("evidence-release", "Evidence-based Release Approval", `Approval should answer a decision question: given the change, evidence and residual risk, is release acceptable now? Evidence can include automated tests, security scans, performance results, change diff, observability readiness, incident history and exception records. Absence of evidence should be visible rather than replaced by confidence language. Approvers need authority over the risk being accepted.`, ["Build a concise Steward release decision record.", "Include scope, evidence, known gaps, residual risk and rollback/recovery plan.", "Identify the correct decision owner for each material risk.", "Define what evidence would change a no-go decision to go."]),
  {
    id: "change-service-governance-production-change-lab", title: "Lab: Govern a Steward Production Change", activities: [
      { id: "change-service-governance-production-change-lab-1", title: "Classify and prepare the change", estimatedMinutes: 120, content: { type: "practical", objective: "Prepare a significant Steward production change using risk-based governance.", scenario, instructions: ["Select a credible change involving at least two technical domains.", "Assess change risk, blast radius, reversibility and dependency/data impact.", "Define required testing, security and operational-readiness evidence.", "Identify decision owner, implementers, service owner and escalation path."], deliverables: ["Change record", "Risk classification", "Evidence plan", "Ownership map"], completionCriteria: completion } },
      { id: "change-service-governance-production-change-lab-2", title: "Make the release decision", estimatedMinutes: 120, content: { type: "practical", objective: "Conduct an evidence-based release review.", scenario, instructions: ["Assemble test, security, reliability and operational evidence.", "Record known gaps and residual risks instead of hiding them.", "Decide go, conditional-go or no-go using explicit criteria.", "Record any exception or risk acceptance with correct authority."], deliverables: ["Release evidence pack", "Decision record", "Exception/risk record", "Deployment and rollback plan"], completionCriteria: completion } },
      { id: "change-service-governance-production-change-lab-3", title: "Close the service-governance loop", estimatedMinutes: 105, content: { type: "practical", objective: "Validate the production outcome and feed evidence back into service governance.", scenario, instructions: ["Define post-deployment validation and monitoring.", "Simulate either successful validation or a rollback/incident path.", "Update risks, controls, problem records or runbooks where evidence warrants it.", "Review whether the governance process added useful risk reduction or unnecessary friction."], deliverables: ["Post-release validation record", "Linked incident/problem/change evidence if applicable", "Updated governance artifacts", "Governance retrospective"], completionCriteria: ["The production decision is traceable to evidence and authority.", "Operational ownership and recovery actions are clear.", "Post-change evidence feeds back into risk, controls and service knowledge.", "Governance friction is reviewed as critically as technical risk."] } },
    ]
  },
];
